### ISSUE TITLE
Morph Mod For 1.8?

### ISSUE THREAD

**Issue by Camawama** [iChun/Morph#1007]
I have a serious inquiry, as making a fun modpack relys on this. The Mine & Blade (Battlegear 2) mod supports up to Minecraft 1.8.9 and I had a really fun ModPack I was making. My friends and I were very hyped until we found out that one of our favorite Mods didn't support Minecraft 1.8.9, or any 1.8 version for that matter. Is there a reason behind this or am I missing something somewhere? I really need Morph and Battlegear 2 in the same modpack as it creates such a fun gaming experience but the closest i can get is Minecraft 1.7.10...

**Comment by iChun** [comment]
There was a point in time where I was too busy to port my mods to 1.8. (Sadly I'm still too busy most of the time now). As a result a few of my mods were not available for some modable Minecraft versions and ultimately I decided to skip 1.8 and 1.9 for Morph and I went straight to 1.12.2 altogether. 

If you want you're more than welcome to port the 1.7.10 or 1.12.2 versions to 1.8.9. I, however, will be working forwards and will be updating the mod for 1.12.2 or or 1.13 etc.
