### ISSUE TITLE
Minecraft Crashes because of ForgeOptiFine using Morphing Mod.

### ISSUE THREAD

**Issue by Benny654** [iChun/Morph#1009]
My Minecraft crashes when I kill a new mod when using ForgeOptiFine 1.7.10. When open up minecraft with forge optifine i noticed a .jar file appears in the mods folder. It is a optifine 1.7.10 HD U E7 optifine which is for minecraft 1.7.2. The old optifine might be the problem but I don't know. The morphing mod works fine with normal forge and 1.7.10 optifine and does not crash. I only use forgeoptifine because I can have my custom skin in the game. Is there a way to fix this. If there is not a way to fix this with forge optifine then is there another way to have my custom skin in Minecraft?

**Comment by Benny654** [comment]
I meant to say 1.7.2 for the optifine HD U E7

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878

**Comment by SKILGAMING** [comment]
Use optifine D6 instead of E7
