### ISSUE TITLE
Flying while morphed is very glitched.

### ISSUE THREAD

**Issue by raidenc04** [iChun/Morph#1010]
When morphing to a mob with fly ability I am constantly flying in one direction and glitching through blocks too.

**Comment by iChun** [comment]
What version of Morph?

**Comment by raidenc04** [comment]
0.9.3 Beta

**Comment by iChun** [comment]
Lovely. https://github.com/iChun/Morph/issues/878

**Comment by iChun** [comment]
Your issue is also probably found here https://github.com/iChun/Morph/issues/796 mod conflict.
