### ISSUE TITLE
Fire Immunity bug

### ISSUE THREAD

**Issue by asdfsatfg** [iChun/Morph#1012]
Everytime when i install the mod it crashes here is crash report:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: morph.api.Ability.getNewAbilityFireImmunity()Lmorph/api/Ability; And i got iChunUtil

**Comment by iChun** [comment]
That looks like a 1.7.10 version of Morph. There might be something wrong with your instance or with your Morph jar. Try refreshing your instance or redownloading the mod. Anyhow, https://github.com/iChun/Morph/issues/878
