### ISSUE TITLE
Cant fly/ and goes northwest

### ISSUE THREAD

**Issue by DallenDestroyer** [iChun/Morph#1013]
I'm doing a modded survival and i want to morph for utility but i get stuck on a wall because it just goes northwest and i got trapped in the water but couldn't get out because i couldn't fly. i'm using 1.7.10 and the mod version is morph-beta-0.9.2

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
