### ISSUE TITLE
Constant Client Crash on Server

### ISSUE THREAD

**Issue by thelapisfox** [iChun/Morph#1014]
Not sure if it will occur on SSP, but on the server I was recently walking around morphed as an Animania Angus Bull. While in that form, I ran into an ender lilly plant and instantly crashed. The crash kept occurring on every single relog attempt. Looking at the server logs provided information about 'Colliding with block' and 'BlockEnderLilly.class'. After having someone on the server remove all the ender lillys and the blocks they were on, the crash stopped happening. Not sure if this is an issue with Morph or Animania, but thought I would let you know.

`https://gist.github.com/thelapisfox/136949fc67542e75012e3d6c63f7e3f6`

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
