### ISSUE TITLE
Client Crash killing Thaumcraft Wisps while morphed

### ISSUE THREAD

**Issue by krisjenner** [iChun/Morph#1015]
Player on my server reported a client crash while killing a wisp from TC while morphed.
[Latest.log](https://gist.github.com/krisjenner/811d5df372d106c5c606ab01d1d11fbc)

**Comment by iChun** [comment]
Can I please get the full log rather than a snippet?

**Comment by krisjenner** [comment]
I updated iChunUtil to the latest version seems it still happens - crashes everyone on the server/times them out whenever someone morphs but the morph user stays connected. I am also using Sponge on this server.

Can't provide a full log as the mod is removed now sorry just something to keep in mind
