### ISSUE TITLE
Losing Morphs After I Rejoin Single Player World

### ISSUE THREAD

**Issue by NoobDestroyer2** [iChun/Morph#1017]
When I Leave my world, and rejoin it, i check my morphs and they're all gone. I have tested this many times and the same out put 100% of the time. This also happens with your hat mod. Please help me and please leave instruction (if its possible to fix) to fix it. Thank you!

**Comment by iChun** [comment]
What versions?

**Comment by NoobDestroyer2** [comment]
Version 1.7.10 ---> Beta 0.9.3

**Comment by iChun** [comment]
Sorry, but the 1.7.10 versions of morph are no longer supported.

**Comment by NoobDestroyer2** [comment]
That is unfortunate. Would you know a quick fix though; like a config thing or another mod?

**Comment by iChun** [comment]
I'm not too sure, sorry. But the mod is open source and there is a 1.7.10
legacy branch. If you're able to identify the issue in the source and to
fix it and submit a pull request, I'd be more than happy to release a new
version.

**Comment by NoobDestroyer2** [comment]
I am also using a mod pack. Idk if another mod is interfering with it. The only mods i am not using are the mutant creatures and the telepads.
mod pack:
http://popularmmos.com/challengepackresurrection/
And what is a legacy branch?
Thank you and sorry for the inconvenience

**Comment by NoobDestroyer2** [comment]
iChun, how do i get to the config file... Bc im still having issues and i dont understand this code. I am making a youtube channel and if i cant keep my morphs and hats, i can't use these mods. Sry and thank you.

**Comment by iChun** [comment]
I don't know the cause for this issue and if it's happening with hats as well then it might be an issue with your player character. Are you changing UUID/usernames or something like that? As I mentioned before, 1.7.10 versions of the mod is no longer supported.
