### ISSUE TITLE
[1.7.10] A fatal error has occured...

### ISSUE THREAD

**Issue by Gruntxx** [iChun/Morph#1020]
I tried to add Morph mod to my 1.7.10 modpack, but it seems it doesn't work. I downloaded the latest versions of the mod, and iChunUtil too.
When I kill a mob, the game crashes. Last time when I tried it, I could kill a mob, but when I started morphing, it crashed.

**Comment by iChun** [comment]
What versions?

**Comment by iChun** [comment]
Sorry, I responded via email and didn't see your edits. Morph for 1.7.10 is
no longer supported. Sorry.

**Comment by LukeboticAndDelixto** [comment]
iChun, Can you please fix this problem!
