### ISSUE TITLE
Not getting abilities (flying)

### ISSUE THREAD

**Issue by beefstuw** [iChun/Morph#1021]
Using latest version. I killed a bat but don't have access to the flying ability. any help?

**Comment by Smuffi1738** [comment]
no abilities sadly, ichun said he would try to implement them into the mod back in 2017 but almost 2 years later nothing happened

**Comment by iChun** [comment]
That's cause I've been busy with life and medical school. 🤷‍♂️

**Comment by JFMillerUSA** [comment]
Any updates yet, without this ability the mod is useless

**Comment by loper12** [comment]
There are other mods that do the same thing, such as [metamorph](https://www.curseforge.com/minecraft/mc-mods/metamorph).

**Comment by Anora** [comment]
should update it i know school is important but metamorph is replacing this mod at this time

**Comment by loper12** [comment]
> should update it i know school is important but metamorph is replacing this mod at this time

If you're really tired of the state of this project, you could just fork it and make your own version. I mean, if you know java.
