### ISSUE TITLE
[1.7.10] Crash

### ISSUE THREAD

**Issue by TECHNOCAIN** [iChun/Morph#1023]
Whenever I kill a new mob, I get a fatal error. But when I get back online and kill the same mob, everything is fine. I have the newest version of ichunutil installed (4.2.3)

**Comment by TECHNOCAIN** [comment]
Also when I try to morph, I get another fatal error

**Comment by TECHNOCAIN** [comment]
Now I can't get into that world

**Comment by TECHNOCAIN** [comment]
I have discovered the issue was optifine

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
