### ISSUE TITLE
The game crashes on loading game

### ISSUE THREAD

**Issue by gingerphoenix10** [iChun/Morph#1024]
I load up minecraft and click forge then it dose the forge loading then says The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Show more details
View crash report
please tell me how to fix this
Version 1.12.2
![image](https://user-images.githubusercontent.com/49760080/56373799-ab49c400-61f9-11e9-9767-cf2ae4699172.png)

**Comment by gingerphoenix10** [comment]
[crash-2019-04-18_16.51.52-client.txt](https://github.com/iChun/Morph/files/3095188/crash-2019-04-18_16.51.52-client.txt)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
