### ISSUE TITLE
RENDERER Gui is not open

### ISSUE THREAD

**Issue by MoosetheVast** [iChun/Morph#1025]
I am playing on Stoneblock 2, fully updated. I am having an issue with the Morph GUI in that it does not load fully, and is accompanied with a colorful overlay. This overlay is included in the radial menu as well. The mobs do not render correctly, nor do their names. There is no crash just yet, so I have no crash report to send in. This is also dependent on the direction I am looking. I have included both a screenshot of the "renderer" message from the issue name, and a link to a video of the bug in its entirety. The in-game screenshot does not include the colorful overlay for some reason, but the video shows it.

Picture:
![2019-04-23_21 18 02](https://user-images.githubusercontent.com/49930233/56628104-2baf6100-660e-11e9-9aad-7be0520501e5.png)

Video Link:
[Here is a link to the video](https://youtu.be/o0ayQfgCils)

Video Description:
I open the GUI using one of the 4 keys that open the menu. I look around to demonstrate the bug. I reopen the GUI using the other keys. The video does not show the radial menu, but the bug acts the same as the column menu.

**Comment by iChun** [comment]
@kSunakaer is this a keybind conflict with another mod?

**Comment by Sunekaer** [comment]
idk

**Comment by iChun** [comment]
Well that toast isn't from this mod. I can see that there is some renderring artifacts though. Are you using Optifine?

**Comment by MoosetheVast** [comment]
I don't think it's a keybind, but I can check once I get home. Optifine is installed, yes, the most recent version for this version of FtB.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
