### ISSUE TITLE
Is it possible to disable scaling health?

### ISSUE THREAD

**Issue by Teppynyx** [iChun/Morph#1027]
I always include the morph mod in my personal modpacks because it's such a useful and fun mod. But one thing that always annoyed me was how the health would scale down when morphing. 
This can be a problem with certain mods like more health, where it allows you to change the starting health when you start your world, because it kills me automatically when morphing into something like a chicken.
I was wondering, is there a config option somewhere where it allows me to disable the health changing?

**Comment by iChun** [comment]
Wait, which version of morph is this?
