### ISSUE TITLE
Morph Command 

### ISSUE THREAD

**Issue by RenKyoKrishna** [iChun/Morph#1028]
This is more of a question than an issue. Does the /morph morph command recognize nbt data? I know morphs store nbt data, so does the command to force morph also allow u to force a morph with a particular nbt?

**Comment by iChun** [comment]
No it doesn't, sorry. There's a reason why the command needs the execute to
be looking at an actual mob. Mod mobs are so different that it would be
dangerous to allow the player to make a morph just from NBT data. I might
look into the future if there is a way to allow this properly but for the
moment, no.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
