### ISSUE TITLE
Player skin body parts gltiches

### ISSUE THREAD

**Issue by Minecraftian51** [iChun/Morph#1029]
I love this mod and all but i have 1 problem. Everytime i morph back into my normal skin i lack bodyparts like arms or sometimes when i morph back to my normal skin my skin's texture is scrambled. Is anyone experiencing this problem too?

**Comment by iChun** [comment]
What version of Morph?

**Comment by Minecraftian51** [comment]
7.1.3 for 1.12.2

**Comment by iChun** [comment]
Do you have screenshots? Are you running Optifine? What is your mod list?
Does it happen if you run Morph on its own?

**Comment by Minecraftian51** [comment]
Yes i use optifine and also pixelmon and carry on. i tried it without pixelmon but its still there. Maybe it's the carry on mod that's the problem?


![2019-05-22_17 31 36](https://user-images.githubusercontent.com/50911902/58217535-1898bb00-7cb8-11e9-876e-ee41e9be5da4.png)
![2019-05-22_17 31 39](https://user-images.githubusercontent.com/50911902/58217536-19c9e800-7cb8-11e9-8e26-25bf43df2868.png)

**Comment by iChun** [comment]
If I remember correctly, Optifine causes this issue

**Comment by GarchompGirl** [comment]
Well thank you, this explains what me and my friends where having 
![image](https://user-images.githubusercontent.com/40581633/61260476-03825a80-a744-11e9-90d0-bc2b2a18930e.png)
