### ISSUE TITLE
Morph Mod Not working - Empty Square.

### ISSUE THREAD

**Issue by MaxBurson** [iChun/Morph#1031]
Hey,

I've recently opened a server on port trigger on forge 1.7.10, to my friends so we can all play we have a custom mod pack - Morph mod doesn't seem to work though. It works on single player, but when killing an animal it doesn't show the animation, and when I press [ it only comes up with one blank empty square.

![Mods](https://user-images.githubusercontent.com/51833895/59529079-f15c9480-8ed7-11e9-82e0-2afc81e21ec7.PNG)
 Does anybody know how to fix this?

**Comment by iChun** [comment]
It looks like you didn't get the mod from official sources. Try using the
version on curseforge and report back.

**Comment by MaxBurson** [comment]
Just got the one from CurseForge, reset the server, still, the same issue works on singleplayer, but the empty box occurs on the server!

![UMods](https://user-images.githubusercontent.com/51833895/59551669-db50e180-8f74-11e9-8a38-5a29d884677d.PNG)
Any more suggestion?

**Comment by iChun** [comment]
Is your forge updated?

**Comment by MaxBurson** [comment]
How would I check?

**Comment by iChun** [comment]
Check the version of forge you're running and the latest version for that
Minecraft version?

**Comment by MaxBurson** [comment]
Yes, I have the latest 1.7.10 Forge installed.

**Comment by iChun** [comment]
🤷‍♂️ Then. Mod support for morph 1.7.10 ended ages ago. I don't know how
else to help you, sorry.

**Comment by MaxBurson** [comment]
Okay - Thanks anyway :)
