### ISSUE TITLE
Exception caught during firing RenderPlayerEvent

### ISSUE THREAD

**Issue by nitu2003** [iChun/Morph#1032]
Crash-Report: https://pastebin.com/x2Wt4W8A
The crash usually happened at the end of the morph and usually using the third person perspective.

**Comment by nitu2003** [comment]
The environment is MDK, and just making my mod.
But I think it was not my fault.

**Comment by iChun** [comment]
The deobfuscated mappings to not match your mdk. Nothing I can really do
about it, but you can change the mappings to match morph's, but if you're
in a decompiled environment you could just setup the source and change that
manually too
