### ISSUE TITLE
A fatal eror has occured, this connection is terminated

### ISSUE THREAD

**Issue by YenoQz** [iChun/Morph#1033]
Hi, i really want to play minecraft morph mod but when i kill any mob it kicks me out and says A fatal eror has occured, this connection is terminated but i can get back in but when i try to transform to a mob it kicks me again and says A fatal eror has occured, this connection is terminated but then i cant get back in cuz its going to kick me again and say A fatal eror has occured, this connection is terminated

**Comment by mxnmnm** [comment]
Yea that's what happens when you have too many morphs use an nbt editor and wipe all of your morphs and try to keep a habit of removing morphs you don't use.

**Comment by Jamar1239** [comment]
can you tell me how to tuse the NBT editor because i have the same problem

**Comment by Jamar1239** [comment]
at least how to use it on yourself

**Comment by mxnmnm** [comment]
It was such a long time ago and I can't remember much but what I do remember is if you take your player data from the save file and try to open up all of the things you will definitely be able to tell which one is morph because of how big morph is. Just make backups and experiment.

**Comment by Jamar1239** [comment]
ok thanks
