### ISSUE TITLE
Incompatible with custom mob models for vanilla mobs?

### ISSUE THREAD

**Issue by SuperMario20** [iChun/Morph#1035]
The title says it all. Vanilla mobs with custom models and textures when morphed into have the default model with the custom textures and the textures then don't fit on the model. Is there a way to make it use the models that are custom?

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
