### ISSUE TITLE
Server Morphing issues 

### ISSUE THREAD

**Issue by TylerJBoundy** [iChun/Morph#1036]
When I morph on my server with friends, my friends' bodies also morph but stay the same texture and don't change form. They also see this when pressing F5 and the same happens to me when they morph.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
