### ISSUE TITLE
[Suggestion] Dupe Morphs

### ISSUE THREAD

**Issue by mxnmnm** [iChun/Morph#1037]
As we all know some mobs such as tinker's blue slimes always go into your morph and register as different types of the same morph even if you've already killed them before.  In order to solve any nbt bloat issues you should be able to press a keybind and disable morphing into anymore of that mob subtype.  Shift grave would work perfectly as it would work with the whole favoring system without interfering with other keybinds.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
