### ISSUE TITLE
1 block high issues

### ISSUE THREAD

**Issue by reubenr11** [iChun/Morph#1038]
when i switch to a one block high entity, it drags me south-west while changing to the one block high FOV, but when it stops dragging, it pops back up to a two high FOV. I don think its clashing with mods because my friends are using the exact same custom modpack we made, and they do not have this problem

**Comment by Aerski** [comment]
same issue on my end

**Comment by AntoanBG** [comment]
Same , FIX THIS!

**Comment by AntoanBG** [comment]
It got fixed for me when i removed pymtech and lucraft core mod

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
