### ISSUE TITLE
Config Limit on Morph Subtypes

### ISSUE THREAD

**Issue by mxnmnm** [iChun/Morph#1039]
When you attack certain mobs from certain mods they tend to always give you a subtype even if you already have the exact same morph.  So the config should allow you to limit the amount of subtypes per mob or just overall to help prevent bloating.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
