### ISSUE TITLE
Modpack server crash when morphing

### ISSUE THREAD

**Issue by Dasco** [iChun/Morph#1040]
Morphing into any mob crashes my Direwolf20 1.12.2 V2.5.0 modpack server.
Morph version: Morph-1.12.2-7.1.3.jar

Crash report: https://pastebin.com/7J3R0fzM

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
