### ISSUE TITLE
When player you are morphed into, morphs into something else, the shadow size becomes wrong

### ISSUE THREAD

**Issue by Barteks2x** [iChun/Morph#1041]
I ran into it while trying to reproduce something else (in my dev environment, that's why not logged in). Recording of the issue: https://i.imgur.com/N9sFYzt.mp4

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.

**Comment by iChun** [comment]
Did a double take. Hi @Barteks2x! Sorry I didn't fix this!
