### ISSUE TITLE
abilities still not functional (1.12)

### ISSUE THREAD

**Issue by MASTRAE** [iChun/Morph#1042]
i looked everything in the options menu up, turned abilities on, but still nothing. anyone has a fix?

**Comment by amplified1** [comment]
the dev seems  to of abandoned the mod or gone on a really long hiatus, it isnt programmed in

**Comment by border999** [comment]
can anyone find them and get their permission to take over?

**Comment by WajahBESAR** [comment]
where the ability button? where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?where the ability button?

**Comment by iChun** [comment]
Hang xleh baca ke?

**Comment by WajahBESAR** [comment]
> Hang xleh baca ke?

what is this

**Comment by iChun** [comment]
Also in reference to the previous comments: I'm busy with life. I'll get back to the mod when I can but it won't be soon. The mod is open sourced and licensed, so y'all can extend on that or submit pull requests and I'd review them when I can (easier to review code than to write)

**Comment by iChun** [comment]
> > Hang xleh baca ke?
> 
> what is this

Xkan xleh baca pulak bila namakau pun bahasa melayu/indon doh

**Comment by WajahBESAR** [comment]
![2019-12-13_15 34 27](https://user-images.githubusercontent.com/9049667/72612409-432e3700-395f-11ea-821a-99167f606eb8.png)

cursed minecraft

**Comment by WajahBESAR** [comment]
![2019-12-13_15 32 53](https://user-images.githubusercontent.com/9049667/72612443-61943280-395f-11ea-8d9d-a4edf00d20c7.png)

this to

**Comment by WajahBESAR** [comment]
![2019-12-13_15 24 58](https://user-images.githubusercontent.com/9049667/72612503-8b4d5980-395f-11ea-8bd4-794cf3b7ed84.png)

and this to
:)

**Comment by WajahBESAR** [comment]
![steve-planetminecraft-com-1577781132](https://user-images.githubusercontent.com/9049667/72612578-c3549c80-395f-11ea-9865-e22c25e0d08d.png)


my new skin!

**Comment by WajahBESAR** [comment]
- [ ] wqjekwuhy qeffgf uybfy

**Comment by iChun** [comment]
Ah, you're Indonesian. That's why you don't understand the Malay slang. If you don't have anything constructive to add to the issue please stop commenting.

**Comment by WajahBESAR** [comment]
where the right one

10+9

- [ ] 19

- [ ] 213

- [ ] 979

**Comment by WajahBESAR** [comment]
/give

- [ ] dhanesh

- [ ] pokediger1

- [ ] logdotzip



















































































































































































> dhanesh

**Comment by iChun** [comment]
@WajahBESAR stop spamming. Last warning. I will block you from my repos if you persist.

**Comment by border999** [comment]
looks like someone wasn't happy about something.

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/884
