### ISSUE TITLE
Character model acts like a bayblade when morphed 1.12.2

### ISSUE THREAD

**Issue by tobi-polar** [iChun/Morph#1043]
Don't know how to describe or how to replicate the issue so here's a vid of it happening...

https://youtu.be/fErIaLXnqNQ

**Comment by STOKE-STER** [comment]
Would like to add that while this is happening it makes it extremely hard to move while morphed as certain mobs

**Comment by STOKE-STER** [comment]
found the issue. Some kind of clash between this mod and the betterportals mod.

**Comment by dragon-evol** [comment]
I'm having the same issue but I don't have betterportals installed...

**Comment by dragon-evol** [comment]
It happens when I come back to the Overworld from Nether.

**Comment by iChun** [comment]
Do you all have videos and/or logs I could look through?

**Comment by STOKE-STER** [comment]
There's a vid up the top ^ I found that destroying a better portals mod portal that was nearby instantly fixed it.

**Comment by iChun** [comment]
Oh whoops. I'm totally not just reading this issue because I got a new
email about it, I swear.

**Comment by STOKE-STER** [comment]
All G, I also reported it to what I still think is the conflicting mods git.

**Comment by iChun** [comment]
Though dragon-evol said they didn't have better portals installed. But it
does sound like a mod conflict, which is why I'd like to have a look at the
mods list.

**Comment by STOKE-STER** [comment]
Here's our current mod list:


    Just Enough Resources (JER) (by way2muchnoise)
    Hwyla (by TehNut)
    Schematica (by Lunatrius)
    Bad Wither No Cookie - Reloaded (by Kreezxil)
    Thermal Cultivation (by TeamCoFH)
    LunatriusCore (by Lunatrius)
    Simple Storage Network (by Lothrazar)
    Steve's Carts Reborn (by modmuss50)
    Simply Jetpacks 2 (by Tomson124)
    Shadowfacts' Forgelin (by ShadowfactsDev)
    Actually Additions (by Ellpeck)
    ViesCraft - Airships! (by Vies)
    Morpheus (by Quetzi)
    NotEnoughIDs (by fewizz_)
    SecretRoomsMod (by AbrarSyed)
    Tesla Core Lib (by face_of_cat)
    ZeroCore (by ZeroNoRyouki)
    Botania (by Vazkii_)
    Reborn Core (by modmuss50)
    IvToolkit (by Ivorforce)
    FindMe (by Buuz135)
    Thermal Foundation (by TeamCoFH)
    Mekanism (by bradyaidanc)
    Redstone Flux (by TeamCoFH)
    Mekanism Generators (by bradyaidanc)
    Mekanism Tools (by bradyaidanc)
    CoFH Core (by TeamCoFH)
    Ender Storage 1.8.+ (by covers1624)
    Thermal Expansion (by TeamCoFH)
    Waystones (by BlayTheNinth)
    Ding (by ohaiiChun)
    CoFH World (by TeamCoFH)
    iChunUtil (by ohaiiChun)
    Back Tools (by ohaiiChun)
    Security Craft (by Geforce132)
    Forestry (by _ForgeUser7678633)
    Morph (by ohaiiChun)
    Bookshelf (by DarkhaxDev)
    EnderCore (by tterrag1098)
    SimpleHarvest (by TehNut)
    RFTools (by McJty)
    Pam's HarvestCraft (by pamharvestcraft)
    NetherEx (by LogicTechCorp)
    Bloodmoon (by Lumien231)
    Extreme Reactors (by ZeroNoRyouki)
    Thermal Dynamics (by TeamCoFH)
    MegaLoot (by Winter_Grave)
    Surge (by DarkhaxDev)
    FTB Utilities: Backups (by LatvianModder)
    Nametags Tweaks (by HunterzCZ)
    Morph-o-Tool (by Vazkii_)
    Phosphor (by jellysquid_)
    Refined Storage (by raoulvdberge)
    Chisel (by tterrag1098)
    Immersive Engineering (by BluSunrize)
    ConnectedTexturesMod (by tterrag1098)
    Ore Excavation (by Funwayguy)
    Custom Main Menu (by Lumien231)
    Industrial Foregoing (by Buuz135)
    AutoRegLib (by Vazkii_)
    Too Many Efficiency Losses (by CaffeinatedPinkie)
    Torchmaster (by xalcon)
    McJtyLib (by McJty)
    Mantle (by mDiyo)
    Chance Cubes (by Turkey2349)
    Inventory Tweaks (by Kobata)
    Corail Tombstone (by Corail_31)
    Biomes O' Plenty (by Forstride)
    Controlling (by Jaredlll08)
    Resource Loader (by Lumien231)
    Tinkers' Tool Leveling (by bonusboni)
    Blood Magic (by WayofTime)
    FTB Quests (by LatvianModder)
    Cyclic (by Lothrazar)
    SwingThroughGrass (by exidex)
    Iron Backpacks (by gr8pefish)
    Recurrent Complex (by Ivorforce)
    Prefab (by wuestman)
    FastWorkbench (by Shadows_of_Fire)
    LootBags (by Malorolam)
    Environmental Tech (by ValkyrieofNight)
    FTB Utilities (by LatvianModder)
    Fast Leaf Decay (by olafskiii)
    The Twilight Forest (by Benimatic)
    Just Enough Items (JEI) (by mezz)
    Baubles (by Azanor13)
    Iron Chests (by ProgWML6)
    Chunk-Pregenerator (by Speiger)
    BetterFps (by Guichaguri)
    ValkyrieLib (by ValkyrieofNight)
    Mowzie's Mobs (by bobmowzie)
    Unity (by theCyanideX)
    LibraryEx (by LogicTechCorp)
    Patchouli (by Vazkii_)
    Minecolonies (by H3lay)
    Thermal Innovation (by TeamCoFH)
    Faster Ladder Climbing (by maddachshund)
    Reborn Storage (by modmuss50)
    FTB Library (by LatvianModder)
    BetterPortals (by Johni0702)
    Mystical Agriculture (by BlakeBr0)
    LLibrary (by _ForgeUser11902522)
    FastFlyBlockBreaking (by barteks2x)
    Roguelike Dungeons (by greymerktv)
    Chameleon (by Texelsaur)
    Dark Utilities (by DarkhaxDev)
    Guide-API (by TehNut)
    Akashic Tome (by Vazkii_)
    Mouse Tweaks (by YaLTeR)
    FTB Money (by LatvianModder)
    Storage Drawers (by Texelsaur)
    Clumps (by Jaredlll08)
    Chisels & Bits (by AlgorithmX2)
    [ANGRY PIXEL] The Betweenlands (by oily_oli)
    Cucumber Library (by BlakeBr0)
    CodeChicken Lib 1.8.+ (by covers1624)
    Ender IO (by CrazyPants_MC)
    JourneyMap (by techbrew)
    Lore Expansion (by theCyanideX)
    Bigger Packets Please (by ElNounch)
    Neat (by Vazkii_)
    Extra Utilities (by RWTema)
    MalisisDoors (by Ordinastie)
    MalisisCore (by Ordinastie)
    Item Filters (by LatvianModder)
    Realistic Item Drops (by Funwayguy)
    Tinkers Construct (by mDiyo)
    FoamFix for Minecraft (by asiekierka)

**Comment by STOKE-STER** [comment]
I realise such a massive list probably isn't much help to you :( sorry about that. If there's any other info I could maybe give to help just let me know.

**Comment by dragon-evol** [comment]
Yeah I've tested with only morph and some other basic mods installed and nothing went wrong, so I think there might be a mod conflict. I have a huge mod list as well...(80+?) So I think maybe I should narrow down the list by some bisection first instead of throwing the whole list here.

**Comment by dragon-evol** [comment]
The trigger conditions are really complicated...... Haven't found the real problem yet. Having all the mods installed and going through portals don't necessarily reproduce the bug.

But when the bug comes I do managed to grab some kind of 'another me' in Nether spamming warning like 'Keeping entity xxx that already existed with UUID xxx'. But killing it doesn't help.

Also the glitching happens locally which means if I go to Nether / teleport to a distant position the glitching disappears.

Really strange...

**Comment by dragon-evol** [comment]
Well finally some progression.

Stablized mob spawner from Draconic Evolution and Android station from Matter Overdrive. I broke them and everything fixed. The real problem is still not clear, but the glitching begins exactly when these two kinds of blocks are in my camera.

Don't know what do these two have in common, but maybe they contains some information, like they both mess up with player render or something? At least they both display some model.

Guess the issue is something structrual since the 'antidotes' for me and STOKE-STER are quite different.

I think I'll just build my mob farm elsewhere...

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
