### ISSUE TITLE
Crazy craft 3 killing mobs crashes me

### ISSUE THREAD

**Issue by ItsOnlyBeans** [iChun/Morph#1044]
i hop in for a solid minute look at the world around me. go to kill a bird and i suddenly crash

**Comment by HyperMan19680** [comment]
They will need a crash log. Also, if that mod pack is for 1.7.10 they cannot help you as it is unsupported.

Sent from my iPhone

On Sep 15, 2019, at 1:29 PM, ItsOnlyBeans <notifications@github.com<mailto:notifications@github.com>> wrote:


i hop in for a solid minute look at the world around me. go to kill a bird and i suddenly crash

**Comment by iChun** [comment]
Thanks ^ https://github.com/iChun/Morph/issues/878
