### ISSUE TITLE
Overlord Mod Incompatibility

### ISSUE THREAD

**Issue by MFWalter** [iChun/Morph#1045]
I have the Overlord Mod {https://www.curseforge.com/minecraft/mc-mods/overlord} in an instance of Minecraft which also contains Morph. When I morph into a Skeleton Warrior with a Skin Suit from the overlord mod the server starts throwing a huge fit, https://i.gyazo.com/e8516ed78a0ffcd22ca3d66cd980e056.png .

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
