### ISSUE TITLE
How to setup the development environment?

### ISSUE THREAD

**Issue by mfrischbutter** [iChun/Morph#1046]
I want to work on the abilities for the 1.12 version.
Please add an quick setup guide in the README.md.
And maybe some structural guides or code guides which i need to follow.

**Comment by iChun** [comment]
If you're using IntelliJ IDEA you need to open up Morph and iChunUtil as a separate module in Forge. Add all of Forge's libraries as dependencies for the modules and point idea to the right source and resources folders. iChunUtil and Morph both have circular dependencies (bad, I know) with each other so you're going to need both.

Add the module as a dependency in Forge and you should be able to load the mods when you load up Minecraft in a dev environment.

I should add, I might be changing a bunch of things in 1.14 when I get to it.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
