### ISSUE TITLE
How can I change only OP's (Admin) can morph and users couldn't? 1.12.2

### ISSUE THREAD

**Issue by TheSliman** [iChun/Morph#1049]
I need on my sv 1.12.2 the mod morph it's only can be used by Staff (High ranks) example Admins/Owners (OP).

**Comment by yukinagatosc2** [comment]
The black/white list doesn't work.  There isn't a way to condition it in any case.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
