### ISSUE TITLE
When I kill an animal in my multiplayer game, it says "A fatal error has occured, and something has been terminated?

### ISSUE THREAD

**Issue by SimplyChris0930** [iChun/Morph#1050]
Hello, I just got my new laptop and wanted some make an orespawn server with my friends. I downloaded ironchest, chickenchunks, codechickencore, hats, ichunutils, legends core, morph beta 0.93, NEI 1.7.10, optifine, ore excavation, superheroes unlimited, waila and obviously orespawn. Everytime I kill and animal in my server, it crashes. But this never happens when I'm in singleplayer. Please help, I just want to fly like a bird.

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878

https://github.com/iChun/Morph/issues/941
