### ISSUE TITLE
Edited Crazycraft Crashes at title Screen

### ISSUE THREAD

**Issue by FierceDragon680** [iChun/Morph#1052]
heres the crash note
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 10/19/19 4:52 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.get(Unknown Source)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at lycanite.lycanitesmobs.KeyHandler.onPlayerTick(KeyHandler.java:112)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_214_KeyHandler_onPlayerTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2317355176 bytes (2210 MB) / 5762973696 bytes (5496 MB) up to 15271460864 bytes (14564 MB)
	JVM Flags: 11 total; -Xms1024M -Xmx16384M -XX:MaxPermSize=256M -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:+UseSplitVerifier -XX:+FailOverToOldVerifier -XX:-HeapDumpOnOutOfMemoryError -XX:+UseCompressedOops -XX:+ScavengeBeforeFullGC -XX:+PrintCommandLineFlags
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_D6 107 mods loaded, 106 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (Malisis' Core.jar) 
	UCHIJA	FastCraft{1.25} [FastCraft] (fastcraft.jar) 
	UCHIJA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles.jar) 
	UCHIJA	surpriseeggs{1.0.6} [Surprise Eggs] (Adventure Backpack.jar) 
	UCHIJA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (Adventure Backpack.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI.jar) 
	UCHIJA	armoroverlay{2.0} [Armor Overlay] (Armor-Overlay-1.7.10- 2.0.jar) 
	UCHIJA	armourersWorkshop{1.7.10-0.33.0.84} [Armourer's Workshop] (Armourer's Workshop.jar) 
	UCHIJA	asielib{0.2.7} [asielib] (asielib.jar) 
	UCHIJA	tennox_bacteria{2.3.2} [Bacteria Mod] (Bacteria-Mod-1.7.10.jar) 
	UCHIJA	FLabsBF{4.3} [Better Furnaces] (Better-Furnaces-Mod-1.7.10.jar) 
	UCHIJA	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft.jar) 
	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1548-universal.jar) 
	UCHIJA	BuildCraft|Core{7.1.23} [BuildCraft] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJA	BuildCraft|Transport{7.1.23} [BC Transport] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJA	BuildCraft|Factory{7.1.23} [BC Factory] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJA	BuildCraft|Silicon{7.1.23} [BC Silicon] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJA	BuildCraft|Robotics{7.1.23} [BC Robotics] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJA	BuildCraft|Energy{7.1.23} [BC Energy] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJA	BuildCraft|Builders{7.1.23} [BC Builders] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks.jar) 
	UCHIJA	Railcraft{9.6.1.0} [Railcraft] (Railcraft.jar) 
	UCHIJA	chisel{2.3.10.37} [Chisel 2] (Chisel 2.jar) 
	UCHIJA	cslib{1.7.10-2.7.3} [Clashsoft Lib] (ClashsoftLib-1.7.10-2.7.3.jar) 
	UCHIJA	controlling{1.0.0} [Controlling] (Controlling.jar) 
	UCHIJA	kegare.craftingex{1.0.5.1} [Crafting EX] (CraftingEX_1.7.2-v1.0.5.1.jar) 
	UCHIJA	RDMenuServer{2.0.0.2} [RDMenuServer] (CustomMenu.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNpcs.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.3} [Damage Indicators] (Damage Indicators.jar) 
	UCHIJA	darkcore{0.3} [Dark Core] (Dark Core.jar) 
	UCHIJA	props{2.0.2} [Decocraft] (Decocraft.jar) 
	UCHIJA	dungeonpack{1.7.10-1.0} [Dungeon Pack] (Dungeon-Pack-Mod-1.7.10.jar) 
	UCHIJA	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic-Lights-Mod-1.7.10.jar) 
	UCHIJA	easyconfigbutton{1.7.10-1.0} [EasyConfigButton] (EasyConfigButton-1.0.jar) 
	UCHIJA	EE3{0.3.507} [Equivalent Exchange 3] (Equivalent Exchange 3.jar) 
	UCHIJA	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCHIJA	FoodPlus{3.2rS} [§bFood Plus] (FoodPlus.jar) 
	UCHIJA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun.jar) 
	UCHIJA	Hats{4.0.1} [Hats] (Hats.jar) 
	UCHIJA	HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) 
	UCHIJA	InfernalMobs{1.5.4} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJA	InventoryPets{1.4.3} [Inventory Pets] (inventorypets-1.7.10-1.4.3-universal.jar) 
	UCHIJA	IronChest{6.0.60.741} [Iron Chest] (Iron Chest.jar) 
	UCHIJA	jewelrycraft2{1.1.4} [Jewelrycraft 2] (Jewelrycraft 2.jar) 
	UCHIJA	pacman{1.0.7} [Killer Pacman] (Killer Pacman.jar) 
	UCHIJA	lucky{5.1.0} [Lucky Block] (LuckyBlocks.jar) 
	UCHIJA	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (Malisis' Doors.jar) 
	UCHIJA	mcheli{0.10.6} [MC Helicopter] (MC Helicopter.zip) 
	UCHIJA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (Mine & Blade Battlegear 2 - Bullseye.jar) 
	UCHIJA	mobbattle{2.0.0[1.7.10]-final} [Mob Battle Mod] (Mob+Battle+Mod-2.0.0[1.7.10]final.jar) 
	UCHIJA	morehealth{6.3} [More Health Forge] (More Health Forge.jar) 
	UCHIJA	moretools{1.7.10-1.0.2} [More Tools Mod] (MoreToolsMod-1.7.10-1.0.2.jar) 
	UCHIJA	Morph{0.9.3} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHIJA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfish's Furniture Mod.jar) 
	UCHIJA	MSM3{3.0.0d} [More Swords 3] (MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) 
	UCHIJA	MutantCreatures{1.4.8} [Mutant Creatures] (Mutant Creatures.jar) 
	UCHIJA	NEIAddons{1.12.10.33} [NEI Addons] (NEI Addons.jar) 
	UCHIJA	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (NEI Addons.jar) 
	UCHIJA	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (NEI Addons.jar) 
	UCHIJA	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (NEI Addons.jar) 
	UCHIJA	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (NEI Addons.jar) 
	UCHIJA	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (NEI Addons.jar) 
	UCHIJA	nevermine{1.1.1} [Nevermine] (nevermine-1.1.6H.jar) 
	UCHIJA	newdungeons{0.3} [New Dungeons] (New-Dungeons-Mod-1.7.10.jar) 
	UCHIJA	MapWriter{2.1.2} [MapWriter] (Opis.jar) 
	UCHIJA	Opis{1.2.5} [Opis] (Opis.jar) 
	UCHIJA	origin{3.3.0} [Origin] (Origin.jar) 
	UCHIJA	pandorasbox{2.0.1} [Pandora's Box] (Pandora's Box.jar) 
	UCHIJA	PortalGun{4.0.0-beta-4} [PortalGun] (PortalGun-4.0.0-beta-4.jar) 
	UCHIJA	SaintsCore{0.8} [Saintscore] (Saintscore.jar) 
	UCHIJA	securitycraft{v1.7.4.1} [SecurityCraft] (SecurityCraft.jar) 
	UCHIJA	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (Soul Shards- The Old Ways.jar) 
	UCHIJA	SpecialMobs{3.2.2} [Special Mobs] (Special-Mobs-Mod-1.7.10.jar) 
	UCHIJA	statues{2.1.3} [Statues] (Statues.jar) 
	UCHIJA	sus{4.1.2} [Superheroes Unlimited Mod] (Superheroes Mod.jar) 
	UCHIJA	TardisMod{0.99} [Tardis Mod] (Tardis Mod.jar) 
	UCHIJA	OreSpawn{1.7.10.20.3} [OreSpawn] (The OreSpawn Mod.zip) 
	UCHIJA	secretroomsmod{4.7.1} [The SecretRoomsMod] (The SecretRoomsMod.jar) 
	UCHIJA	TrailMix{4.0.0} [TrailMix] (TrailMix.jar) 
	UCHIJA	transformers{${version}} [Transformers Mod] (Transformers Mod.jar) 
	UCHIJA	weepingangels{3.3.2} [Weeping Angels] (Weeping Angels.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (Witchery.jar) 
	UCHIJA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJA	youtubers{1.7.0} [Youtubers+ Mod] (youtubers-1.7.0.jar) 
	UD	asielibcore{} [AsieLib CoreMod] (minecraft.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.25' Renderer: 'GeForce GTX 745/PCIe/SSE2'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 745/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [§lDefault+3D§r+High+++++++§l16w09c, YoutubersSkin]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.6.0 NVIDIA 391.25
	OpenGlRenderer: GeForce GTX 745/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878

Also this is a lycanite mobs crash, not Morph.

**Comment by FierceDragon680** [comment]
i didnt mean to post it on a morph thread, how do i fix this

**Comment by iChun** [comment]
I've already closed the issue. Nothing else to do here. No worries.
