### ISSUE TITLE
black/whitelist config does not work

### ISSUE THREAD

**Issue by yukinagatosc2** [iChun/Morph#1053]
It appears that the mod ignores the config entry(s) that should set what players can or can't morph.  There is also no way to set this in game despite there being a field that should be selectable for this purpose.

**Comment by LemADEC** [comment]
As of iChunUtil-1.12.2-7.2.2 + Morph-1.12.2-7.2.1, the entity white/black list appears to be completely ignored by the mod.
From a painful check in IdeaJ, the related https://github.com/iChun/Morph/blob/1.12.2/src/main/java/me/ichun/mods/morph/common/core/Config.java#L167
should be called by ConfigBase.setup() from iChunUtils, but that setup() method appears to be never called.

On a side note, please use registry names for entities, those are much easier to dump then class names. By extension, please update the comment in the configuration to say what is expected (I shouldn't have to check the source code to find out fully defined class names are expected).

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
