### ISSUE TITLE
iChun, I ask you for guidance 

### ISSUE THREAD

**Issue by Unknownuserperson** [iChun/Morph#1054]
I play in 1.7.10 forge but wanted to ask if there is a way to enable killing/morphing animation.
I just can't seem to get it to play is there any way to change that in the config?

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
