### ISSUE TITLE
Morph crashes world, can't load save anymore

### ISSUE THREAD

**Issue by Bioniclegenius** [iChun/Morph#1055]
Crash link: https://paste.dimdev.org/rinaduzavu.mccrash

Was in a nested Compact Machine, and morphed. Exited, no problem. Exited again to get back to world, game crashed to title. Loading save just crashes back to title repeatedly.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
