### ISSUE TITLE
Crash or strange copy bug when morphing

### ISSUE THREAD

**Issue by Dimentive** [iChun/Morph#1056]
When I morph, one of two things happen: I crash, or my character is copied.

When I crash by morphing, my screen goes sky blue and properly crashes about a minute later.

Sometimes, I don’t crash, but instead, when I morph, it creates a copy of my player model in the world. It’s completely stuck in the world, with my name tag and everything, and erratically moves slightly in all directions whilst stuck in place. I can’t interact with it, nor can I get rid of it without exiting and re-entering the world. When I look at this strange copy, my gaze quickly _snaps_ onto it, for some reason—until I look away.

![copy morph edited](https://user-images.githubusercontent.com/34230933/71365917-b16e1c80-25a0-11ea-98e9-983546e28185.png)

**Crash log:** https://pastebin.com/raw/4vr7kMjw
**Mod list:** https://pastebin.com/raw/c7W2SP3h

I have been morphing just fine up until now. I did recently add a few mods to my modpack, so it’s almost a guarantee that this is a conflict between one of those mods and Morph. Because of this, I’m not sure if I should even post this issue, but I thought I’d let you know anyway in case this is something that could potentially be fixed, assuming this conflict problem is on Morph’s end.

****

**Minecraft version:** 1.12.2
**Forge version:** 14.23.5.2847 (latest for 1.12.2)
**Morph version:** 7.1.3 (latest)
**iChunUtil version:** 7.2.2 (latest)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
