### ISSUE TITLE
All players start flying after killing Wither (not only who killed)

### ISSUE THREAD

**Issue by Mixm4ster** [iChun/Morph#1057]
In the settings folder there is a command that specifies that only the player who kills Whiter will be able to fly. However, after one player killed Wither, all the others acquired flying as well. So the command is not working, how can I solve?

Info:
- Minecraft 1.7.10
- Morph-Beta-0.9.3
- iChunUtil-4.2.3

Here are their settings:

 # Disable the flight ability until a player...
    # 0 = Enable early game flight
    # 1 = ...has reached the nether
    # 2 = ...has killed the Wither
    # 
    # Min: 0
    # Max: 2
    I:disableEarlyGameFlight=2

    # Disable Early Game Flight Mode
    # 0 = Serverwide toggle
    # 1 = Player specific toggle (Every player has to travel to the nether/kill a wither to get flight for themselves)
    # 
    # Min: 0
    # Max: 1
    I:disableEarlyGameFlightMode=1

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
