### ISSUE TITLE
Can't morph into mods' mobs

### ISSUE THREAD

**Issue by Piipperi** [iChun/Morph#1058]
I keep getting "Unsuccessful on execting command on [ign]" when I try to morph into anything else than Minecraft's own mobs. How do I fix?

**Comment by iChun** [comment]
What version?

**Comment by Piipperi** [comment]
> What version?
> […](#)

1.12.2 Forge w/ichunutil 7.2.2

**Comment by iChun** [comment]
Which command/argument?

**Comment by Piipperi** [comment]
> Which command/argument?

Doing /morph give [ign] and /morph morph [ign] while looking at a mob not from MC (like Pixelmon) results in that error.

**Comment by iChun** [comment]
Have you tried other mod mobs? Pixelmon iirc is a bit..... special, with the way they do their mobs IIRC.

**Comment by iChun** [comment]
Also there might be a print out on the server console/log that tells might say why it failed.

**Comment by Piipperi** [comment]
[15:41:23] [Server thread/INFO] [minecraft/MinecraftServer]: [Piipperi: Unsuccessful in executing command on Piipperi.]
[15:41:23] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] Unsuccessful in executing command on Piipperi.

This is all the info I get from the console from Pixelmon mobs. This error also seems to come up with some other mods but it looks like I just need to do the command a few times on those for morphing to work.

But Pixelmon is still not really working. But I think it could just be Pixelmon being Pixelmon.  Anyways, Idk why couldn't I get any more info from the console but some sort of Pixelmon support would be pretty nice

**Comment by iChun** [comment]
Like I mentioned earlier, Pixelmon does something different with their entities if I remember right. To be real honest with you as well, the morph and give commands weren't really fleshed out properly and was a last minute addition. Morph is still mainly meant to be a "kill a mob to get it" kind of thing. I unfortunately cannot sort out this issue for the time being but I'll make a note to improve it for the later updates.

**Comment by Einsteinlol** [comment]
I have the same problem but a little bit different

I play with dragon mount 2 (in 1.12.2), i kill some dragons and i get their shapes but when i want be one of them i just can be the ender dragon, i don't have the other shape... (but this fonction work with other mod like mo'creature). I have you an idea for fix it or it's impossible?
Thanks for your answer ^^

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
