### ISSUE TITLE
Which is the best and the most used Java Minecraft version of this Mod?

### ISSUE THREAD

**Issue by TamasB14** [iChun/Morph#1059]
I heard that the 1.12 morphs are not reciving their special ability. I just wish to know which version is the best and the smoothest for that mod.

Thank you

**Comment by iChun** [comment]
The latest version on CurseForge

As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier.
