### ISSUE TITLE
When I morph into a flying creature It won't allow me to fly.

### ISSUE THREAD

**Issue by schway-panada** [iChun/Morph#1061]
I killed a butterfly and morphed into it but I couldn't fly. I tried restarting the game but nothing happened.

**Comment by thunderkingytgaming** [comment]
sadly there are still no abillities .

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
