### ISSUE TITLE
Crash on Stoneblock 2 no clue why i crashed

### ISSUE THREAD

**Issue by UnicorNora** [iChun/Morph#1063]
https://pastebin.com/ZA9tWSjB

**Comment by HenoMori** [comment]
The Chisel mod is not compatible with morph.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
