### ISSUE TITLE
Morph mod keeps resetting

### ISSUE THREAD

**Issue by Chuckpopper** [iChun/Morph#1065]
hey ichun im having this issue, whenever i log back in my world all the morph has been reset and all the data, except achievements and inventory. But all my Morphs are gone and i have to kill another one again. I got it working before last 2 months i'm playing on 1.7.10. 2 months ago i got it working no problem i could even play fine on modpack but now i don't know what seems to be the problem i'm playing the same modpack and same version (1.7.10). And other mods that gives you starter items gives you after entering the world. Even though i've been in the same world multiple times. It gives me starter items like Book of Manual. Guide etc etc. i think the mod thinks that it's my first time loading in to the world. Any solution i would get i will happily take it :)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
