### ISSUE TITLE
Morph Mod crashes when loading into a world.

### ISSUE THREAD

**Issue by Magikorp3662** [iChun/Morph#1067]
I've been having troubles with the Morph mod, and here's my latest attempt to fix it. When I try to load into any world, morph will immediately cause a fatal error and boot me out. The mod works on 1.6.4, but not any higher.
I created a superflat world, only bedrock, so my computer didn't have to load much. I enter the world, get 1 frame of my hand and hotbar, and get a fatal error. I'm booted to the multiplayer menu, strangely.

Here's the log: https://gist.github.com/Magikorp3662/4c8be9d3610d815b395a18ed63b865e3

Any help?

I know support for Morph 1.7.10 has been dropped because of the 1.12.2 rewrite, but I don't know anywhere else to ask this.

Edit: I'm using the Mineshafter launcher, on a Mac computer.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
