### ISSUE TITLE
Morph 7.2.0 with Mocreatures crashes

### ISSUE THREAD

**Issue by PlussivePulse** [iChun/Morph#1071]
After installed new Morphs I got crashed after login into my **server** and found that all animals in Mocreautes cause crash for some reason.

There are many error logs report depends on what entity it found first:
Example : Angler

[14:21:29] [Client thread/FATAL]: Reported exception thrown!
[B#534]  net.minecraft.util.ReportedException: Ticking entity
[B#534]  	at net.minecraft.world.World.updateEntities(World.java:1776) ~[amu.class:?]
[B#534]  	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847) ~[bib.class:?]
[B#534]  	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) ~[bib.class:?]
[B#534]  	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
[B#534]  	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[B#534]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
[B#534]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
[B#534]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
[B#534]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
[B#534]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#534]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#534]  Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
[B#534]  	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed(MoCEntityTameableAquatic.java:89) ~[MoCEntityTameableAquatic.class:?]
[B#534]  	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.isEntityInsideOpaqueBlock(MoCEntityTameableAquatic.java:452) ~[MoCEntityTameableAquatic.class:?]
[B#534]  	at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:232) ~[vp.class:?]
[B#534]  	at net.minecraft.entity.EntityLiving.onEntityUpdate(EntityLiving.java:269) ~[vq.class:?]
[B#534]  	at drzhark.mocreatures.entity.MoCEntityAquatic.onEntityUpdate(MoCEntityAquatic.java:914) ~[MoCEntityAquatic.class:?]
[B#534]  	at net.minecraft.entity.Entity.onUpdate(Entity.java:389) ~[vg.class:?]
[B#534]  	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2096) ~[vp.class:?]
[B#534]  	at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377) ~[vq.class:?]
[B#534]  	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
[B#534]  	at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
[B#534]  	at net.minecraft.world.World.redirect$zce000$updateEntity(World.java:5123) ~[amu.class:?]
[B#534]  	at net.minecraft.world.World.updateEntities(World.java:1762) ~[amu.class:?]
[B#534]  	... 10 more
[B#534]  [14:21:29] [Client thread/FATAL]: Minecraft ran into a problem! Report saved to: C:\Users\PlusaiCC-Unit-12C\AppData\Roaming\.technic\modpacks\wildcalling\crash-reports\crash-2020-05-18_14.21.29-client.txt
[B#534]  ---- Minecraft Crash Report ----
[B#534]  // You're mean.
[B#534]  
[B#534]  Time: 2020-05-18 14:21:29 PDT
[B#534]  Description: Ticking entity
[B#534]  
[B#534]  java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
[B#534]      at drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed(MoCEntityTameableAquatic.java:89)
[B#534]      at drzhark.mocreatures.entity.MoCEntityTameableAquatic.isEntityInsideOpaqueBlock(MoCEntityTameableAquatic.java:452)
[B#534]      at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:232)
[B#534]      at net.minecraft.entity.EntityLiving.onEntityUpdate(EntityLiving.java:269)
[B#534]      at drzhark.mocreatures.entity.MoCEntityAquatic.onEntityUpdate(MoCEntityAquatic.java:914)
[B#534]      at net.minecraft.entity.Entity.onUpdate(Entity.java:389)
[B#534]      at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2096)
[B#534]      at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
[B#534]      at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
[B#534]      at net.minecraft.world.World.updateEntity(World.java:1958)
[B#534]      at net.minecraft.world.World.redirect$zce000$updateEntity(World.java:5123)
[B#534]      at net.minecraft.world.World.updateEntities(World.java:1762)
[B#534]      at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
[B#534]      at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
[B#534]      at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
[B#534]      at net.minecraft.client.main.Main.main(SourceFile:123)
[B#534]      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#534]      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#534]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#534]      at java.lang.reflect.Method.invoke(Unknown Source)
[B#534]      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#534]      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#534]  
[B#534]  
[B#534]  A detailed walkthrough of the error, its code path and all known details is as follows:
[B#534]  ---------------------------------------------------------------------------------------
[B#534]  
[B#534]  -- Entity being ticked --
[B#534]    Entity Type: mocreatures:angler (drzhark.mocreatures.entity.aquatic.MoCEntityAngler)
[B#534]    Entity ID: 5302
[B#534]    Entity Name: Angler
[B#534]    Entity's Exact location: 1756.71, 62.00, 3830.85
[B#534]    Entity's Block location: World: (1756,62,3830), Chunk: (at 12,3,6 in 109,239; contains blocks 1744,0,3824 to 1759,255,3839), Region: (3,7; contains chunks 96,224 to 127,255, blocks 1536,0,3584 to 2047,255,4095)
[B#534]    Entity's Momentum: 0.00, -0.01, 0.00
[B#534]    Entity's Passengers: []
[B#534]    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
[B#534]    Entity NBT: ~~ERROR~~ ReportedException: Saving entity NBT
[B#534]  
[B#534]  -- Affected level --
[B#534]    Level name: MpServer
[B#534]    All players: 1 total; [EntityPlayerSP['DeonHNT'/5909, l='MpServer', x=8.50, y=65.00, z=8.50]]
[B#534]    Chunk stats: MultiplayerChunkCache: 122, 122
[B#534]    Level seed: 0
[B#534]    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
[B#534]    Level generator options: 
[B#534]    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[B#534]    Level time: 22 game time, 22 day time
[B#534]    Level dimension: 0
[B#534]    Level storage version: 0x00000 - Unknown?
...
Suspected Mods: DrZhark's Mo'Creatures Mod (mocreatures)
[B#534]    Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
[B#534]    LWJGL: 2.9.4
[B#534]    OpenGL: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7637, Intel
[B#534]    GL Caps: Using GL 1.3 multitexturing.
[B#534]             Using GL 1.3 texture combiners.
[B#534]             Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
[B#534]             Shaders are available because OpenGL 2.1 is supported.
[B#534]             VBOs are available because OpenGL 1.5 is supported.
[B#534]    Using VBOs: Yes
[B#534]    Is Modded: Definitely; Client brand changed to 'fml,forge'
[B#534]    Type: Client (map_client.txt)
[B#534]    Resource Packs: 
[B#534]    Current Language: English (US)
[B#534]    Profiler Position: N/A (disabled)
[B#534]    CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
[B#534]    Client Crashes Since Restart: 9
[B#534]    Integrated Server Crashes Since Restart: 0
[B#534]  
[B#534]  [14:29:16] [Client thread/ERROR]: ########## GL ERROR ##########
[B#534]  [14:29:16] [Client thread/ERROR]: @ VanillaFix GUI Loop
[B#534]  [14:29:16] [Client thread/ERROR]: 1280: Invalid enum

**Comment by valerian2** [comment]
I have the same problem, adjust its in update please ichun

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
