### ISSUE TITLE
Config option "lose morphs on death" issue

### ISSUE THREAD

**Issue by daPWNDAZ** [iChun/Morph#1073]
Hi, just wanted to say that this is a great mod and I was excited to see it up and running in 1.12. I found an issue and confirmed that it isn't caused by a conflict in mods.

The config option
    # Will you lose your morphs on death?
    # 0 = No
    # 1 = Yes, all morphs
    # 2 = Yes, the morph you're currently using [range: 0 ~ 1, default: 0]
when enabled, deletes all known morphs regardless of option 1 or option 2, instead of just deleting the currently equipped morph for option 2. 

Furthermore, it even deletes the player morph of your own model, making it so if you morph after you respawn, you will be stuck in that morph without the option of turning back into a player. Screenshots attached.

forge ver. 14.23.5.2854
ichunutil ver. 12.2-7.2.2
morph ver. 12.2-7.2.0

![2020-05-21_16 14 54](https://user-images.githubusercontent.com/31396601/82607633-c2867e00-9b7e-11ea-8e4c-823429363173.png)
hed. 
![2020-05-21_16 14 26](https://user-images.githubusercontent.com/31396601/82607626-bdc1ca00-9b7e-11ea-8a62-a734a3b276c4.png)

**Comment by iChun** [comment]
I tried to fix this in 7.2.1. Let me know how it goes!

**Comment by iChun** [comment]
Closing in the meantime, feel free to reopen if not resolved.
