### ISSUE TITLE
Morph crashing my game when I go on my server.

### ISSUE THREAD

**Issue by SlenderFinder** [iChun/Morph#1074]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2020-05-22 22:45:52 EDT
Description: Ticking entity

java.lang.ClassCastException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: mocreatures:jellyfish (drzhark.mocreatures.entity.aquatic.MoCEntityJellyFish)
  Entity ID: 5510
  Entity Name: JellyFish
  Entity's Exact location: 965.01, 60.35, 5146.60
  Entity's Block location: World: (965,60,5146), Chunk: (at 5,3,10 in 60,321; contains blocks 960,0,5136 to 975,255,5151), Region: (1,10; contains chunks 32,320 to 63,351, blocks 512,0,5120 to 1023,255,5631)
  Entity's Momentum: 0.00, 0.04, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: ~~ERROR~~ ReportedException: Saving entity NBT

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['SlenderFinder'/5711, l='MpServer', x=1041.87, y=65.00, z=5184.36]]
  Chunk stats: MultiplayerChunkCache: 67, 67
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (875,72,5443), Chunk: (at 11,4,3 in 54,340; contains blocks 864,0,5440 to 879,255,5455), Region: (1,10; contains chunks 32,320 to 63,351, blocks 512,0,5120 to 1023,255,5631)
  Level time: 18383094 game time, 17760711 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 54 total; [EntitySpider['Spider'/5763, l='MpServer', x=965.50, y=31.00, z=5114.50], MoCEntityStingRay['StingRay'/5764, l='MpServer', x=966.81, y=57.81, z=5113.80], MoCEntityAnchovy['Anchovy'/5765, l='MpServer', x=962.00, y=61.06, z=5113.16], MoCEntityJellyFish['JellyFish'/5510, l='MpServer', x=965.01, y=60.35, z=5146.60], MoCEntityManderin['Manderin'/5511, l='MpServer', x=970.19, y=62.07, z=5142.92], MoCEntityCod['Cod'/5767, l='MpServer', x=968.54, y=60.99, z=5113.62], MoCEntityBass['Bass'/5512, l='MpServer', x=966.41, y=62.01, z=5139.26], MoCEntityMantaRay['MantaRay'/5772, l='MpServer', x=969.87, y=57.86, z=5135.59], MoCEntitySalmon['Salmon'/5773, l='MpServer', x=971.93, y=61.98, z=5124.34], MoCEntityMantaRay['MantaRay'/5774, l='MpServer', x=979.21, y=58.50, z=5105.60], MoCEntityPiranha['Piranha'/5519, l='MpServer', x=975.85, y=62.02, z=5175.15], MoCEntitySalmon['Salmon'/5775, l='MpServer', x=988.49, y=59.44, z=5119.99], MoCEntityCrab['Crab'/5520, l='MpServer', x=969.50, y=55.20, z=5176.85], EntityCreeper['Creeper'/5776, l='MpServer', x=986.50, y=14.00, z=5126.50], MoCEntityManderin['Manderin'/5521, l='MpServer', x=973.85, y=62.00, z=5176.92], MoCEntityAnchovy['Anchovy'/5777, l='MpServer', x=981.12, y=62.71, z=5128.30], MoCEntityStingRay['StingRay'/5522, l='MpServer', x=962.68, y=57.50, z=5168.27], MoCEntityBass['Bass'/5778, l='MpServer', x=981.39, y=59.22, z=5127.47], MoCEntityGoat['Goat'/5523, l='MpServer', x=974.76, y=62.58, z=5169.45], MoCEntityMantaRay['MantaRay'/5779, l='MpServer', x=995.02, y=59.44, z=5114.08], MoCEntityJellyFish['JellyFish'/5524, l='MpServer', x=989.46, y=60.19, z=5155.13], MoCEntityAnchovy['Anchovy'/5780, l='MpServer', x=996.68, y=62.43, z=5117.81], MoCEntityCrab['Crab'/5784, l='MpServer', x=984.49, y=47.00, z=5151.45], MoCEntityMantaRay['MantaRay'/5785, l='MpServer', x=991.29, y=60.06, z=5146.40], MoCEntityAngler['Angler'/5787, l='MpServer', x=1004.63, y=61.82, z=5120.10], MoCEntityHippoTang['HippoTang'/5788, l='MpServer', x=997.03, y=61.10, z=5130.37], EntitySkeleton['Skeleton'/5544, l='MpServer', x=970.50, y=9.00, z=5188.50], MoCEntityCrab['Crab'/5545, l='MpServer', x=964.85, y=55.31, z=5185.50], MoCEntityAngler['Angler'/5546, l='MpServer', x=967.85, y=62.06, z=5188.46], MoCEntityClownFish['ClownFish'/5547, l='MpServer', x=968.54, y=62.25, z=5192.84], MoCEntityBlackBear['BlackBear'/5548, l='MpServer', x=972.40, y=73.00, z=5193.40], EntityPlayerSP['SlenderFinder'/5711, l='MpServer', x=1041.87, y=65.00, z=5184.36], MoCEntityAnt['Ant'/5810, l='MpServer', x=976.63, y=87.00, z=5227.47], EntityLatchedRenderer['unknown'/61747, l='MpServer', x=8.50, y=65.00, z=8.50], EntityToad['Toad'/5812, l='MpServer', x=984.82, y=88.00, z=5218.30], MoCEntityBlackBear['BlackBear'/5821, l='MpServer', x=964.87, y=80.00, z=5237.10], MoCEntityGreenOgre['GreenOgre'/5822, l='MpServer', x=974.50, y=88.00, z=5243.50], MoCEntityMaggot['Maggot'/5568, l='MpServer', x=975.24, y=87.00, z=5211.26], EntityItem['item.item.diamond'/5570, l='MpServer', x=989.13, y=4.00, z=5195.13], MoCEntityPandaBear['PandaBear'/5571, l='MpServer', x=977.80, y=80.00, z=5191.40], MoCEntitySnail['Snail'/5572, l='MpServer', x=991.74, y=85.00, z=5199.62], MoCEntitySnail['Snail'/5573, l='MpServer', x=987.58, y=87.00, z=5196.34], MoCEntitySnail['Snail'/5574, l='MpServer', x=986.01, y=87.00, z=5194.63], MoCEntitySnail['Snail'/5575, l='MpServer', x=987.84, y=86.00, z=5199.60], EntitySpider['Spider'/5585, l='MpServer', x=969.92, y=88.25, z=5220.92], EntityTroll['Troll'/5841, l='MpServer', x=988.50, y=12.00, z=5245.50], MoCEntityWraith['Wraith'/5586, l='MpServer', x=967.38, y=91.66, z=5227.35], MoCEntityWerewolf['Werewolf'/5587, l='MpServer', x=976.75, y=87.00, z=5202.40], EntitySkeleton['Skeleton'/5588, l='MpServer', x=999.50, y=90.00, z=5189.50], EntityRoosterWyandotte['Wyandotte Rooster'/5596, l='MpServer', x=1002.45, y=74.00, z=5205.22], EntityDoeKiko['Kiko Doe'/5597, l='MpServer', x=1002.98, y=80.00, z=5209.98], EntityEnderman['Enderman'/5871, l='MpServer', x=983.50, y=21.00, z=5157.50], MoCEntityManderin['Manderin'/5500, l='MpServer', x=971.92, y=62.07, z=5154.75], MoCEntityGoldFish['GoldFish'/5501, l='MpServer', x=967.37, y=61.98, z=5166.82]]
  Retry entities: 1 total; [EntityLatchedRenderer['unknown'/61747, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 344308792 bytes (328 MB) / 3367501824 bytes (3211 MB) up to 3367501824 bytes (3211 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_E3 65 mods loaded, 65 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version                  | Source                                             | Signature                                |
       |:------ |:-------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                  | 9.42                     | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | srm-hooks            | 1.12.2-1.0.0             | minecraft.jar                                      | None                                     |
       | LCHIJA | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | jei                  | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                          | None                                     |
       | LCHIJA | botania              | r1.10-363                | Botania+r1.10-363.jar                              | None                                     |
       | LCHIJA | craftstudioapi       | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHIJA | harvestcraft         | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar                    | None                                     |
       | LCHIJA | ctm                  | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
       | LCHIJA | twilightforest       | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LCHIJA | animania             | 1.7.3                    | animania-1.12.2-1.7.3.jar                          | None                                     |
       | LCHIJA | antiqueatlas         | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
       | LCHIJA | antiqueatlasoverlay  | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
       | LCHIJA | appliedenergistics2  | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | astralsorcery        | 1.10.22                  | astralsorcery-1.12.2-1.10.23.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCHIJA | autoreglib           | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHIJA | backpacks16840       | 3.5.8                    | backpacks+1.12.2+-+3.5.8.jar                       | None                                     |
       | LCHIJA | bibliocraft          | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCHIJA | guideapi             | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
       | LCHIJA | bloodmagic           | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                    | None                                     |
       | LCHIJA | bookshelf            | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | buildcraftlib        | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
       | LCHIJA | buildcraftcore       | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
       | LCHIJA | buildcraftbuilders   | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
       | LCHIJA | buildcrafttransport  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
       | LCHIJA | buildcraftsilicon    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
       | LCHIJA | buildcraftcompat     | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
       | LCHIJA | buildcraftenergy     | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
       | LCHIJA | buildcraftfactory    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
       | LCHIJA | buildcraftrobotics   | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
       | LCHIJA | carrots              | 1.0.0b1                  | carrotslib-mc1.12.2-1.0.0b1.jar                    | None                                     |
       | LCHIJA | chisel               | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
       | LCHIJA | cookingforblockheads | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar              | None                                     |
       | LCHIJA | customspawner        | 3.11.4                   | CustomMobSpawner-3.11.4.jar                        | None                                     |
       | LCHIJA | mocreatures          | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar                | None                                     |
       | LCHIJA | ebwizardry           | 4.2.11                   | ElectroblobsWizardry-4.2.11-MC1.12.2.jar           | None                                     |
       | LCHIJA | eplus                | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | zerocore             | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                        | None                                     |
       | LCHIJA | bigreactors          | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar                | None                                     |
       | LCHIJA | llibrary             | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | fossil               | 8.0.4                    | fossilsarcheology-8.0.4.jar                        | None                                     |
       | LCHIJA | cfm                  | 6.3.1                    | furniture-6.3.1-1.12.2.jar                         | None                                     |
       | LCHIJA | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCHIJA | iceandfire           | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
       | LCHIJA | ichunutil            | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest            | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCHIJA | journeymap           | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                        | None                                     |
       | LCHIJA | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | mca                  | 6.1.0                    | MCA-1.12.2-6.1.0-universal.jar                     | None                                     |
       | LCHIJA | morph                | 7.2.0                    | Morph-1.12.2-7.2.0.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | portalgun            | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | prefab               | 1.3.0.26                 | prefab-1.3.0.26.jar                                | None                                     |
       | LCHIJA | qsilkspawners        | 1.1.3                    | qsilkspawners-1.1.3.jar                            | None                                     |
       | LCHIJA | randomenchantments   | @VERSION@                | randomenchants-0.1.4a.jar                          | None                                     |
       | LCHIJA | roguelike            | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LCHIJA | secretroomsmod       | 5.6.4                    | secretroomsmod-1.12.2-5.6.4.jar                    | None                                     |
       | LCHIJA | tails                | 1.12-1.10.0              | Tails-1.12-1.10.0.jar                              | None                                     |
       | LCHIJA | tconstruct           | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-150               | VanillaFix-1.0.10-150.jar                          | None                                     |
       | LCHIJA | veinminer            | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | LCHIJA | veinminermodsupport  | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | LCHIJA | jurassicraft         | 2.1.23                   | JurassiCraft-1.12.2-2.1.23.jar                     | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      BCModPlugin (backpacks+1.12.2+-+3.5.8.jar)
                                        brad16840.core.ClassTransformer
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      AstralCore (astralsorcery-1.12.2-1.10.23.jar)
                                        
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.75' Renderer: 'GeForce RTX 2080 SUPER/PCIe/SSE2'
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
  Suspected Mods: Unknown
  Launched Version: forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Client Crashes Since Restart: 11
  Integrated Server Crashes Since Restart: 0
-------------------------------------------------------------------------------------------------------------
This is the crash report I get when I try to join my server. It started off saying it was Mo creatures but I knew it is morph because it kept saying...

> Server thread/WARN Keeping entity mca:entityvillagermca that already exists with UUID 5d69dead-edfc-43f1-9c65-ebdfef5cf49e

It keeps saying this everytime I would join the server.

>

**Comment by PlussivePulse** [comment]
Same issue here. I already report this on github also.

**Comment by HenoMori** [comment]
Chisel is the issue mod here. I've tried running morph and chisel alone, not even jei, and it still crashes, compared to my 24-mod server that runs just fine.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
