### ISSUE TITLE
Config Help?

### ISSUE THREAD

**Issue by Psychonator17** [iChun/Morph#1077]
So, this isn't an issue as much as it is a request for help.

I'm in the process of customizing the config mod in my version of morph mod, and I want to include swimming abilities for the Guardian and Elder Guardian mobs. I just have two questions: what to the four variables following the swim function mean (the squid shows false,1.2F,0.4F,true)? And once I successfully input the code, what do I need to do to have it take affect without the original config overriding mine?

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
