### ISSUE TITLE
Option to toggle creative flight?

### ISSUE THREAD

**Issue by Nanorithm** [iChun/Morph#1080]
Is there any way to change flight from the flappy bird style to creative flight? When I used this mod in 1.7 I remember flight was creative style.

**Comment by Absence1** [comment]
I would really appreciate this; the flappy bird flight is useful for verticality but not exactly as useful as creative flight for building, exploring, and all around not spamming my space bar every time I try to cross a ravine.

**Comment by iChun** [comment]
That's unfortunately not possible the way the mod works currently, and I've
dropped support for 1.12.2 unfortunately. I'll keep this in mind for future
updates though!
