### ISSUE TITLE
If in the config I:loseMorphsOnDeath=1 and die, then the morph of itself is also lost

### ISSUE THREAD

**Issue by GeorgePieVG** [iChun/Morph#1082]
After death, the morph menu displays just one empty frame without the player’s model and his nickname, but everything else is working fine so far. If you get a morph of any entity, then in the morph menu the empty frame will be replaced by a frame with this entity and if you use it, you can no longer become yourself, in any way. Only death again.

**Comment by iChun** [comment]
I tried to fix this in 7.2.1. Let me know how it goes! Closing in the meantime, feel free to reopen if not resolved.
