### ISSUE TITLE
I can't morph

### ISSUE THREAD

**Issue by idksdas** [iChun/Morph#1084]
It might be that I'm dumb and didn't do it correctly, but I can't morph into the mobs I kill. Could someone help me

**Comment by thepwrtank18** [comment]
Considering the last commit was in 2017, good luck getting support.

**Comment by iChun** [comment]
Psst, branches are a thing @thepwrtank18. That said, you're not wrong, I'm not currently supporting this mod, heh. @idksdas make sure the mod is installed correctly and is also on the server you're connecting to.

**Comment by thepwrtank18** [comment]
Also, OptiFine does not like the Morph mod and Minecraft crashes if you try to morph into anything. If you need OptiFine, try using version D6.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
