### ISSUE TITLE
Grimoire of Gaia abilities not working 

### ISSUE THREAD

**Issue by teliria** [iChun/Morph#1086]
in 7.2.0, abilities work normally for vanilla mobs when using the local json but when i edit the gaia.entity to gaia.entity.monster the abilities of vanilla mobs disappear

also in 7.2.1 i cant seem to make the local json to work

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
