### ISSUE TITLE
Eye height shifts in multiplayer [1.12.2]

### ISSUE THREAD

**Issue by WarriorsMustang17** [iChun/Morph#1087]
I added this to my multiplayer server and as it is a blast messing with people on there, the eye height resets back to the normal height after moving. If I morph into a smaller mob I go through the animation, my camera goes down, then resets after its done. This also happens with taller mobs.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
