### ISSUE TITLE
Minor incompatibility issue.

### ISSUE THREAD

**Issue by Yenlon** [iChun/Morph#1088]
The following issue doesn't have a very worse impact on the game but nonetheless is it very annoying. If you play the morph mod and the 'Mine Mine No Mi'-mod together in a world, you won't be able to fly with a flying morph, no matter what the configs are set (all other abilities still work fine). I think this happens because the MMNM-mod also adds fruits with which someone can transform into flying beings or their abilities allow to do so. I can fly with the mentioned fruits but not with the morphs. The proof: I played the morph mod in a world without MMNM and I was able to fly in survival. It seems that the fly mechanic from MMNM overrides the one from morph and what I want is a way to change the flying code either from the morph mod or from MMNM so that I'm able to fly with both mods installed or vice versa that the morph mod overrides the fly mechanic from MMNM (morph's fly mechanic appeals more to me). And ye, I know the morph mod isnt supported anymore, so just tell me what and how I have to change in the code exactly.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
