### ISSUE TITLE
Aether's gloves still render while in morph

### ISSUE THREAD

**Issue by auramgold** [iChun/Morph#109]
Pretty self-explanatory by the title, when you are in morph while wearing any kind of aether gloves, the gloves still render. Another thing that I noticed while taking the screenshots: if you are punching a block with the gloves on while in morph, the "hands" of the gloves still move as if they're the arms.
(version beta 0.1.0)

Screenies (taken in creative flight mode while wearing gravitite gloves):

![2013-09-02_19 29 45](https://f.cloud.github.com/assets/5368399/1069654/ca731be0-1427-11e3-981b-2accd1ece719.png)
![2013-09-02_19 30 44](https://f.cloud.github.com/assets/5368399/1069655/d21f9fa8-1427-11e3-92d4-7087551081d1.png)

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
