### ISSUE TITLE
Crash with 7.2.1 for MC 1.12.2 exiting a Nether portal

### ISSUE THREAD

**Issue by xJon** [iChun/Morph#1090]
I was reported this crash: https://pastebin.com/7pYpUTRL after leaving a portal with a bat morph.
I'm not sure whether this is an issue with the mod as I was unable to reproduce it on the first try, but I thought I should forward it nonetheless.
Thank you!

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
