### ISSUE TITLE
Crash with 7.2.1 for MC 1.12.2 looking up a JEI recipe

### ISSUE THREAD

**Issue by xJon** [iChun/Morph#1091]
Hi (again),
I was also reported this crash: https://pastebin.com/7bpKsRbM with a user who's looked up a recipe in JEI.
They also mentioned they were using Optifine. Not sure why but Morph comes up in this crash log, as well as Just Enough Resources. Might be some kind of an incompatibilty?
Thank you!

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
