### ISSUE TITLE
Morph mod causes crash everytime I enter game on TLauncher

### ISSUE THREAD

**Issue by GodDragon121** [iChun/Morph#1095]
lemme send the crash report on gist

**Comment by GodDragon121** [comment]
https://gist.github.com/GodDragon121/526a44dd7f88935b19d755f7d4185536

**Comment by Betelgeusesupergiant** [comment]
Hello. I see you are trying to play a cracked client. Maybe you have too many mods?

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
