### ISSUE TITLE
Add ability modification to config/new config file

### ISSUE THREAD

**Issue by Da-Happy** [iChun/Morph#1097]
It would be really nice to be able to add the appropriate abilities to modded creatures that don't have them, I know you can decompile the code and stuff to find them, but it would be a lot easier if the abilities file was in the config folder. Don't know if that is possible but would be very nice.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
