### ISSUE TITLE
morph mod keeps crashing after pressing [ or ] (brackets)

### ISSUE THREAD

**Issue by JordiH11** [iChun/Morph#1099]
a curious thing is that on a different world it works just fine, but here it crashes instantly when i press the bracket key.
here the full crash report: 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  CreativePatchingLoader (CreativeCore_v1.10.26_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 9/26/20 4:23 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.isChild()Z
	at me.ichun.mods.morph.api.ability.type.AbilitySunburn.entityHasAbility(AbilitySunburn.java:93)
	at me.ichun.mods.morph.client.core.EventHandlerClient.drawEntityOnScreen(EventHandlerClient.java:1903)
	at me.ichun.mods.morph.client.core.EventHandlerClient.drawSelector(EventHandlerClient.java:1610)
	at me.ichun.mods.morph.client.core.EventHandlerClient.onRenderTick(EventHandlerClient.java:1015)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_202_EventHandlerClient_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:360)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1123)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.ichun.mods.morph.api.ability.type.AbilitySunburn.entityHasAbility(AbilitySunburn.java:93)
	at me.ichun.mods.morph.client.core.EventHandlerClient.drawEntityOnScreen(EventHandlerClient.java:1903)
	at me.ichun.mods.morph.client.core.EventHandlerClient.drawSelector(EventHandlerClient.java:1610)
	at me.ichun.mods.morph.client.core.EventHandlerClient.onRenderTick(EventHandlerClient.java:1015)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_202_EventHandlerClient_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Dooki024'/96, l='MpServer', x=-1338.29, y=64.00, z=3685.23]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (44,64,256), Chunk: (at 12,4,0 in 2,16; contains blocks 32,0,256 to 47,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 212287 game time, 243798 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 90 total; [EntitySkeleton['Skeleton'/259, l='MpServer', x=-1318.60, y=11.00, z=3752.70], EntityCreeper['Creeper'/260, l='MpServer', x=-1318.42, y=11.00, z=3752.07], EntityZombie['Zombie'/261, l='MpServer', x=-1319.50, y=22.00, z=3744.50], EntitySkeleton['Skeleton'/262, l='MpServer', x=-1301.50, y=23.00, z=3733.50], EntityZombieVillager['Zombie Villager'/263, l='MpServer', x=-1311.51, y=21.00, z=3739.77], EntitySheep['Sheep'/264, l='MpServer', x=-1298.07, y=65.00, z=3731.50], EntityChicken['Chicken'/265, l='MpServer', x=-1301.53, y=64.00, z=3741.76], EntitySkeleton['Skeleton'/777, l='MpServer', x=-1288.50, y=22.00, z=3689.50], EntityMinecartChest['Minecart with Chest'/266, l='MpServer', x=-1325.89, y=21.00, z=3731.51], EntityMinecartChest['Minecart with Chest'/267, l='MpServer', x=-1322.50, y=17.06, z=3737.11], EntityBat['Bat'/269, l='MpServer', x=-1327.60, y=17.10, z=3728.25], EntityZombie['Zombie'/270, l='MpServer', x=-1312.46, y=21.00, z=3733.73], EntityChicken['Chicken'/271, l='MpServer', x=-1326.14, y=63.00, z=3742.49], EntityItem['item.item.egg'/272, l='MpServer', x=-1325.70, y=63.00, z=3741.59], EntityChicken['Chicken'/273, l='MpServer', x=-1323.13, y=64.00, z=3732.46], EntityMinecartChest['Minecart with Chest'/406, l='MpServer', x=-1290.50, y=26.06, z=3701.50], EntityMinecartChest['Minecart with Chest'/279, l='MpServer', x=-1338.50, y=22.06, z=3747.50], EntitySheep['Sheep'/407, l='MpServer', x=-1291.25, y=64.00, z=3709.64], EntitySpider['Spider'/408, l='MpServer', x=-1274.30, y=21.00, z=3694.30], EntityCreeper['Creeper'/281, l='MpServer', x=-1307.78, y=18.00, z=3682.27], EntityZombieVillager['Zombie Villager'/282, l='MpServer', x=-1328.46, y=22.00, z=3742.73], EntitySheep['Sheep'/283, l='MpServer', x=-1343.58, y=63.00, z=3728.25], EntityMinecartChest['Minecart with Chest'/411, l='MpServer', x=-1282.51, y=20.00, z=3671.50], EntityZombie['Zombie'/284, l='MpServer', x=-1325.50, y=21.00, z=3715.50], EntityMinecartChest['Minecart with Chest'/412, l='MpServer', x=-1293.50, y=25.06, z=3666.51], EntityMinecartChest['Minecart with Chest'/413, l='MpServer', x=-1287.50, y=22.06, z=3684.51], EntityCreeper['Creeper'/286, l='MpServer', x=-1326.30, y=25.00, z=3727.70], EntityChicken['Chicken'/159, l='MpServer', x=-1413.20, y=79.00, z=3627.09], EntityChicken['Chicken'/160, l='MpServer', x=-1419.54, y=85.00, z=3617.87], EntityChicken['Chicken'/161, l='MpServer', x=-1414.87, y=83.00, z=3619.49], EntityChicken['Chicken'/419, l='MpServer', x=-1267.61, y=67.00, z=3743.14], EntityBat['Bat'/547, l='MpServer', x=-1377.85, y=54.03, z=3608.27], EntitySkeleton['Skeleton'/294, l='MpServer', x=-1357.50, y=30.00, z=3744.50], EntityZombie['Zombie'/167, l='MpServer', x=-1409.50, y=26.00, z=3608.50], EntityChicken['Chicken'/169, l='MpServer', x=-1413.86, y=88.00, z=3616.39], EntityMinecartChest['Minecart with Chest'/298, l='MpServer', x=-1315.50, y=30.06, z=3694.50], EntityCaveSpider['Cave Spider'/299, l='MpServer', x=-1304.41, y=21.00, z=3668.93], EntityZombie['Zombie'/301, l='MpServer', x=-1308.36, y=18.00, z=3680.51], EntityBat['Bat'/302, l='MpServer', x=-1288.09, y=21.10, z=3659.82], EntityZombie['Zombie'/175, l='MpServer', x=-1396.70, y=35.00, z=3654.30], EntitySkeleton['Skeleton'/176, l='MpServer', x=-1389.54, y=36.00, z=3646.75], EntitySquid['Squid'/304, l='MpServer', x=-1282.18, y=61.62, z=3655.59], EntityCreeper['Creeper'/305, l='MpServer', x=-1362.50, y=12.00, z=3750.50], EntityPig['Pig'/178, l='MpServer', x=-1415.71, y=76.00, z=3724.74], EntityChicken['Chicken'/306, l='MpServer', x=-1346.10, y=63.00, z=3729.19], EntityItem['item.item.egg'/307, l='MpServer', x=-1345.21, y=63.00, z=3729.88], EntityZombie['Zombie'/180, l='MpServer', x=-1396.50, y=42.00, z=3707.50], EntityMinecartChest['Minecart with Chest'/308, l='MpServer', x=-1323.49, y=20.00, z=3707.11], EntitySpider['Spider'/309, l='MpServer', x=-1326.30, y=26.00, z=3709.30], EntityItem['item.item.egg'/571, l='MpServer', x=-1322.30, y=64.00, z=3731.80], EntityItem['item.item.egg'/573, l='MpServer', x=-1300.94, y=64.00, z=3741.25], EntitySpider['Spider'/832, l='MpServer', x=-1370.50, y=13.00, z=3607.50], EntityBat['Bat'/202, l='MpServer', x=-1371.09, y=14.07, z=3605.26], EntitySkeleton['Skeleton'/218, l='MpServer', x=-1388.76, y=23.00, z=3672.51], EntityZombie['Zombie'/219, l='MpServer', x=-1374.18, y=38.00, z=3659.35], EntityZombie['Zombie'/347, l='MpServer', x=-1311.75, y=21.00, z=3745.44], EntityBat['Bat'/220, l='MpServer', x=-1367.75, y=37.10, z=3658.25], EntitySheep['Sheep'/348, l='MpServer', x=-1292.53, y=65.00, z=3739.36], EntityBat['Bat'/221, l='MpServer', x=-1358.55, y=35.02, z=3644.48], EntityBat['Bat'/222, l='MpServer', x=-1362.67, y=36.20, z=3680.25], EntityItem['item.item.dyePowder.blue'/223, l='MpServer', x=-1351.68, y=14.00, z=3647.88], EntityItem['item.item.dyePowder.blue'/224, l='MpServer', x=-1352.88, y=17.00, z=3647.88], EntityItem['item.item.dyePowder.blue'/225, l='MpServer', x=-1352.78, y=17.00, z=3647.11], EntityItem['item.item.dyePowder.blue'/226, l='MpServer', x=-1352.88, y=17.00, z=3646.13], EntitySkeleton['Skeleton'/228, l='MpServer', x=-1406.29, y=35.00, z=3687.50], EntityCreeper['Creeper'/229, l='MpServer', x=-1392.51, y=24.00, z=3671.23], EntitySkeleton['Skeleton'/230, l='MpServer', x=-1398.50, y=21.00, z=3672.50], EntityZombie['Zombie'/231, l='MpServer', x=-1390.74, y=35.00, z=3658.48], EntityCreeper['Creeper'/232, l='MpServer', x=-1382.20, y=13.00, z=3610.55], EntityBat['Bat'/235, l='MpServer', x=-1363.16, y=55.25, z=3609.05], EntityPlayerSP['Dooki024'/96, l='MpServer', x=-1338.29, y=64.00, z=3685.23], EntityMinecartChest['Minecart with Chest'/238, l='MpServer', x=-1317.50, y=30.06, z=3677.50], EntityZombie['Zombie'/622, l='MpServer', x=-1314.56, y=11.00, z=3752.21], EntityLatchedRenderer['unknown'/367, l='MpServer', x=8.50, y=65.00, z=8.50], EntityMinecartChest['Minecart with Chest'/239, l='MpServer', x=-1315.50, y=30.06, z=3674.50], EntityCreeper['Creeper'/880, l='MpServer', x=-1311.50, y=45.00, z=3632.50], EntitySkeleton['Skeleton'/241, l='MpServer', x=-1363.50, y=28.00, z=3735.50], EntityWitch['Witch'/881, l='MpServer', x=-1312.50, y=45.00, z=3632.50], EntitySkeleton['Skeleton'/242, l='MpServer', x=-1330.71, y=20.00, z=3698.50], EntityWitch['Witch'/882, l='MpServer', x=-1312.50, y=45.00, z=3630.50], EntitySkeleton['Skeleton'/243, l='MpServer', x=-1335.14, y=17.00, z=3705.50], EntityZombie['Zombie'/883, l='MpServer', x=-1310.50, y=45.00, z=3633.50], EntityZombieVillager['Zombie Villager'/244, l='MpServer', x=-1330.49, y=27.00, z=3705.73], EntityZombie['Zombie'/246, l='MpServer', x=-1305.50, y=48.00, z=3647.22], EntityBat['Bat'/247, l='MpServer', x=-1306.77, y=45.00, z=3636.86], EntityItem['item.item.bone'/248, l='MpServer', x=-1307.92, y=63.00, z=3643.81], EntitySquid['Squid'/249, l='MpServer', x=-1337.18, y=56.57, z=3677.19], EntityWitch['Witch'/251, l='MpServer', x=-1368.50, y=36.00, z=3694.70], EntityBat['Bat'/252, l='MpServer', x=-1347.47, y=38.10, z=3651.25], EntityCreeper['Creeper'/253, l='MpServer', x=-1360.50, y=35.00, z=3680.17]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/367, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 781636248 bytes (745 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                    | Signature                                |
	|:------ |:----------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                             | None                                     |
	| LCHIJA | obfuscate         | 0.2.6        | minecraft.jar                             | None                                     |
	| LCHIJA | aether_legacy     | 1.4.4        | aether_legacy-1.12.2-v1.4.4.jar           | None                                     |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.26_mc1.12.2.jar        | None                                     |
	| LCHIJA | ambientsounds     | 3.0          | AmbientSounds_v3.0.14_mc1.12.2.jar        | None                                     |
	| LCHIJA | carryon           | 1.12.3       | CarryOn+MC1.12.2+v1.12.3.jar              | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | cgm               | 0.12.2       | guns-0.12.2-1.12.2.jar                    | None                                     |
	| LCHIJA | ichunutil         | 7.2.1        | iChunUtil-1.12.2-7.2.1.jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | jei               | 4.16.1.302   | jei_1.12.2-4.16.1.302.jar                 | None                                     |
	| LCHIJA | morph             | 7.2.0        | Morph-1.12.2-7.2.1.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | scp               | 2.3.1        | SCP+Lockdown-1.12.2-2.3.1-dev.jar         | None                                     |
	| LCHIJA | sereneseasons     | 1.2.18       | SereneSeasons-1.12.2-1.2.18-universal.jar | None                                     |
	| LCHIJA | xaerominimap      | 1.18.1       | Xaeros_Minimap_1.18.1_Forge_1.12.jar      | None                                     |

	Loaded coremods (and transformers): 
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
CreativePatchingLoader (CreativeCore_v1.10.26_mc1.12.2.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 452.06' Renderer: 'GeForce RTX 2060/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**Comment by minecrafterty1** [comment]
Same issue here and it only started after updating iChunUtils, Morph, and MorphApi to the latest version from, in the same order as before, 7.1.4 to 7.2.2, 7.0.0 to 7.2.1, 7.0 to 7.2.1 on 1.12.2.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
