### ISSUE TITLE
[Compat] [Bug] Astral Sorcery's "Flare" Glitching

### ISSUE THREAD

**Issue by Tomodachi94** [iChun/Morph#1101]
Heyo,
Found a minor bug with Morph and Astral Sorcery installed.
HOW TO REPRODUCE:

1. Load Minecraft with Astral Sorcery, Morph, and related dependancies
2. /summon and kill a Flare.
3. Morph into a Flare, move around a bit, then morph back into a human.

ISSUE ON ASTRAL SORCERY's GITHUB: HellFirePvP/AstralSorcery#1412

**Comment by Tomodachi94** [comment]
Astral Sorcery's dev closed the issue, claiming its 

> Not something we [Astral Sorcery] support

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
