### ISSUE TITLE
Can't swim as Slime

### ISSUE THREAD

**Issue by Vodulm** [iChun/Morph#1102]
When I'm Slime and underwater I'm just going down and cant go up without morphing into something else or flying in creative.

**Comment by Lampent51** [comment]
Slime mobs can't swim, so I'm pretty sure it's intentional that the morph cant either.

**Comment by Vodulm** [comment]
No, vanilla Slime in 1.12 swims on water

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.

Also: Old slimes couldn't swim, only in newer versions are they not even allowed to sink but float on the surface instead.
