### ISSUE TITLE
Multiple morphs of the same mob.

### ISSUE THREAD

**Issue by Lampent51** [iChun/Morph#1103]
I am playing with quite a few mods so there may be some issues, but I'm getting the morph of just about every zombie I find. I have 20+ zombie morphs, and they all look the same.

**Comment by diploscat** [comment]
Hello, I'm also having this issue, if you give me your mod list that would help because then I could compare what mods we have the same of!

**Comment by diploscat** [comment]
My issue was potioncore.

I don't really know a workaround with it's specific data, but I would remove potioncore if you are sick of this morph issue.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
