### ISSUE TITLE
Can't Fly with 7.2.1, and possible whitelisting of other mod entities in config?

### ISSUE THREAD

**Issue by Kwehlani** [iChun/Morph#1105]
Hi, I've been struggling to get flight set up for Morph v.7.2.1.  Every other ability functions as normal outside of flight, but I can't find anything in the config or in my game that would be restricting flight.  I was also wondering if it would be possible to whitelist mobs from other mods to also gain the same abilities as ones that already exist.  Such as getting squid abilities on a hippocampus from fire and ice.  Any help would be greatly appreciated, thanks!

**Comment by kuroodo** [comment]
I am also running Morph v.7.2.1 and cannot fly.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
