### ISSUE TITLE
I cannot morph into Wither or Ender Dragon

### ISSUE THREAD

**Issue by Tyrkys258** [iChun/Morph#1106]
When I will kill one of them, I will dont get the morph. Im using 1.12.2

**Comment by iChun** [comment]
You have to enable it in the config.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
