### ISSUE TITLE
Crashes on my own Multiplayer server with Mocreatures

### ISSUE THREAD

**Issue by Aerski** [iChun/Morph#1107]
**MoCreatures and Morph Mod** (only two mods in my server) crash on start due to ticking an entity that's usually an aquatic creature- in my case, it's a Cod; entity from Mocreatures. I've already contacted the mod author of Mocreatures and I am awaiting a response from them, but I'm also posting an issue here in the meantime.

In MoCreature's **unofficial** Discord, i also asked about it and was told this after they observed the crash report:
_the first cause is a mod conflict in which MoCreatures is expecting the mob entities 16th parameter to be true/false 1/0_, _the second cause is another mod using the 16th entry to store something of it's own._ They said "there is no fix for that right now as it's hard coded into both mods", but I don't know much Java myself, so I don't know if there's some possibility of that being fixed.

They said _another cause is that another mod is spawning creatures using it's own code (bypassing custom mod spawner) which results in that 16th entry being initialized/random (something they're trying to fix in code)._  

I'll also add that this crash doesn't happen in Singleplayer, only when i'm in a Multiplayer server.. don't know the reason.
[crash-2020-11-13_16.58.24-client.txt](https://github.com/iChun/Morph/files/5539583/crash-2020-11-13_16.58.24-client.txt)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
