### ISSUE TITLE
Where is AbilitySupport.txt located?

### ISSUE THREAD

**Issue by AlbY2099** [iChun/Morph#1108]
I wanted to add skills to some mobs present in other mods, but I don't know how to create or find the AbilitySupport.txt file in my local version.
I would kindly need a hand on how to do it. I searched the forum and the internet but couldn't find a guide that could help me.
I am using the mod in 1.12.2.

**Comment by iChun** [comment]
The ability_support.json file can be found here: https://github.com/iChun/Morph/blob/1.12.2/src/main/resources/assets/morph/mod/ability_support.json

That means it will be in the jar file, in the /resources/assests/morph/mod/ directory.

If "useLocalResources" is turned on, the mod will read the ability_support.json file in the configs folder instead. I'll try to remember this issue and hopefully make things clearer/streamlined in the future.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
