### ISSUE TITLE
Morph kicking other Player

### ISSUE THREAD

**Issue by SaschaMkII** [iChun/Morph#1109]
Hi I love the Morph Mod and wanted to play it with my friend in a modpack (1.7.10),

But Everytime I Morph, He gets kicked and the other way arround,
we tested it without the modpack and it worked fine. 
is there a known mod which causes this trouble?
[crash-2020-11-19_16.17.04-client.txt](https://github.com/iChun/Morph/files/5573011/crash-2020-11-19_16.17.04-client.txt)
that is the latest crash log of mine pls I want to know

Thanks already for taking time to read this

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
