### ISSUE TITLE
1.12.2 hitbox error

### ISSUE THREAD

**Issue by WignedGhost6** [iChun/Morph#1110]
when im morphing hitbox shrinks or grows but when morphing is complete hitbox goes to normal 2 block i can walk through 1block and all but i suffocate.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
