### ISSUE TITLE
How to remove all morph data?

### ISSUE THREAD

**Issue by KlikAas** [iChun/Morph#1111]
I morphed into a baby cow from another mod (don't know which one) and then the server crashed. Now when I try to login again the server crashes again. My friends can join just fine but the moment I try to log in it crashes. I can't locate the morph.dat file to remove this issue (I don't even know if morph.dat is still a thing) please help :)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
