### ISSUE TITLE
two bugs

### ISSUE THREAD

**Issue by buzzcola3** [iChun/Morph#1113]
game version 1.12.2

bug: src/main/java/me/ichun/mods/morph/common/thread/ThreadGetResources.java line; 22
-forces to use ability_support.json even if force local is set to 1

also Parrots have no abilities

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
