### ISSUE TITLE
Hitbox and Camera Issue

### ISSUE THREAD

**Issue by rdmchinese** [iChun/Morph#1114]
When you morph into another mob in version 1.12, the camera would be on the smaller one **among the mob you morph into and your original human character** while the hitbox being the larger one.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
