### ISSUE TITLE
Hostile mobs still attacking

### ISSUE THREAD

**Issue by XRedCubeX** [iChun/Morph#1116]
Hi, today I tried the latest version of the Morph mod but the problem is that mobs keep attacking me even when I morph into a zombie or other mob "that shouldn't be attacked" and I also set the setting in the config, so please fix, I was about to smash a keyboard a moment ago.

**Comment by Beany2** [comment]
I had the same issue it made me lose a hardcore world

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
