### ISSUE TITLE
Command "/morph morph (player) (mob)" problem in 1.12.2

### ISSUE THREAD

**Issue by maxoupidou** [iChun/Morph#1117]
Problem when using the command / morph morph "players" "mob": the server crashes and I must delete the info of the player targeted by the command so that he can return to the server without crashing

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
