### ISSUE TITLE
Health bar problem and Hostile mob targeting

### ISSUE THREAD

**Issue by shirofliro** [iChun/Morph#1119]
When i morph into a mob with more than 20hp, the health bar still doesnt up the value, it stays at 20hp, but if i morph into a mob with less than 20hp it desplays correctly,and vanilla mobs dont work either, i killed a 26hp horse wich should be 1 health bar and an extra 4 hearths but it still desplays the original 20hp, and the hostile mob targeting isnt working,in the config i made it to not target if i morph into a hostile mob but hostile mobs still try to kill me.

This is what i put on the hostile ability Modes:

# Hostile Ability Modes
    # 0 = Off, hostile mobs attack you despite being morphed.
    # 1 = Hostile mobs do not attack you if you are a hostile mob.
    # 2 = Hostile mobs of different types do not attack you if you are a hostile mob but hostile mobs of the same kind do.
    # 3 = Hostile mobs of the same type do not attack you but hostile mobs of other types attack you.
    # 4 = Hostile mobs have a decreased detection range around you.
    # 5 = Like 1, but a hostile mob will target you if you attacked them.
    # 
    # Min: 0
    # Max: 5
    I:hostileAbilityMode=5

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
