### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Taknax** [iChun/Morph#1120]
I love your mods and morph is my favorite.
I have one suggestion to make it fully survival.
A moprh skill book. Where you can activte the morh skill?
Its should have cooldown and by upgrading the book (or the skill in the book) it can be reduced.
This would make the survival feeling 100%.
Nice mod. I love your work. Go on!

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
