### ISSUE TITLE
Squid morph bug.

### ISSUE THREAD

**Issue by Niklas2001nh** [iChun/Morph#1121]
If i morph into a Squid, and bag to caracter the Air bar is gone. I still take damage, when i'm under water for to long, but i can't see how much air i got left.

I'm using 1.12.2

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
