### ISSUE TITLE
Bug with Mo'creatures

### ISSUE THREAD

**Issue by TVCJ13** [iChun/Morph#1122]
Everytime when i add morph on my minecraft some Mo'creature mobs are glitched like this. Can you help me ?
![Capture d’écran (53)](https://user-images.githubusercontent.com/77455104/107510931-115cc380-6ba5-11eb-95fa-530d96e6f037.png)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
