### ISSUE TITLE
Something in front of player hand

### ISSUE THREAD

**Issue by chadbrowski** [iChun/Morph#1123]
There are cubes in front of the hands of player. Sometimes happens with mobs with hands: zombie ,pigman, etc.

Here's a screenshot

![2021-02-12_13 55 41](https://user-images.githubusercontent.com/75521463/107736100-333c7e80-6d3c-11eb-8479-50386b94fc23.png)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
