### ISSUE TITLE
Player skins broken on Morph 1.12.2

### ISSUE THREAD

**Issue by RazzletheBazzle** [iChun/Morph#1125]
It appears that (mostly after morphing back from a mob) a third arm is added, sticking out of the neck, and is controlled by looking up or down. My brother's skin Seems to be fine besides the third arm, and sometimes it removes the head completely to replace it with this new limb.
My skin seems to be the most broken, no matter which one I choose-- I either have that new limb and a few extra textures tattooed onto my left hand, or the outer layers completely try recreating themselves around my arms. They don't mold to the size of the 3-pix arms, they stay their original size.
I dunno if this has been fixed already for anyone else, but that's what's goin on

**Comment by Jaspurrb** [comment]
I have the same issue and i think that its probably bc the mod creator is updating the mod

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
