### ISSUE TITLE
Flight for 1.12.2 and modded morphs

### ISSUE THREAD

**Issue by uhhhhhhhidk** [iChun/Morph#1126]
I have found that flight does work in the 1.12.2 version of morph, however differently, instead of double tapping space and being able to fly around you have to constantly spam the space bar, not entirely sure if this is a bug or not. I also found modded mobs dont have abilities, is that something that has yet to be implemented or did I just not see something in the config files? I

**Comment by davedumas0** [comment]
i have found that the firebat does not do this but the normal bat does

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
