### ISSUE TITLE
Too many of the same morph

### ISSUE THREAD

**Issue by diploscat** [iChun/Morph#1128]
As I am aware, I've read through all of my mods and I cannot find out what modifies mob data in a way that presents itself as unique and different.

I don't know what is making it happen, but all vanilla (specifically hostile) creatures are added as a new morph.
My theory is that it was potioncore, I just need to know what mod it is so that I could either toy with the config or remove it entirely.

![image](https://user-images.githubusercontent.com/79271788/108385538-c6acfe00-71d9-11eb-92a5-5bd0492ceb39.png)

**Comment by diploscat** [comment]
My issue was potioncore.

I don't really know a workaround with it's specific data, but I would remove potioncore if you are sick of this morph issue.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
