### ISSUE TITLE
Crashing when you morph in morphing mod.

### ISSUE THREAD

**Issue by Taruska** [iChun/Morph#1130]
So i have my big modpack on 1.7.10 and i have morphing mod in it too so when i use morph to something minecraft crashes here is crash log or what is it called:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 19.2.2021 15:35
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access method jp.mc.ancientred.starminer.core.entity.EntityLivingGravitized.func_70105_a(FF)V from class morph.common.core.TickHandlerServer
	at morph.common.core.TickHandlerServer.serverTick(TickHandlerServer.java:189)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_662_TickHandlerServer_serverTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 779137944 bytes (743 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 2, allocated: 15, tallocated: 93
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 93 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	modJ_StarMinerCore{0.9.9} [StarMinerCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (Not-Enough-Items-1.7.10-Latest.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (Gilded-Games-Util-1.7.10.jar) 
	UCHIJAAAA	securitycraft{v1.8.13} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.13.jar) 
	UCHIJAAAA	aether{1.7.10-1.6} [Aether II] (Aether-2-1.7.10.jar) 
	UCHIJAAAA	modJ_StarMiner{0.9.9} [Starminer Mod] (Anti-Gravity-Mod-1.7.10.jar) 
	UCHIJAAAA	ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
	UCHIJAAAA	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (Thermal-Foundation-Mod-1.7.10.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (Thermal-Expansion-Mod-1.7.10.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (Big-Reactors-Mod-1.7.10.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.23} [BuildCraft] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.23} [BC Transport] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.23} [BC Factory] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.23} [BC Silicon] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.23} [BC Robotics] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.23} [BC Energy] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.23} [BC Builders] (BuildCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenters-Blocks-Mod-1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-Mod-1.7.10-Recommended.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (CoroUtil-1.7.10.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (CoroUtil-1.7.10.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (CoroUtil-1.7.10.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.7.10.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.7.10.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.1_1.7.10.jar) 
	UCHIJAAAA	props{2.4.1} [Decocraft] (Decocraft-2.4.1_1.7.10.jar) 
	UCHIJAAAA	doggystyle{1.1.3.99} [Doggy Style] (DoggyStyle-Mod-1.7.10.jar) 
	UCHIJAAAA	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (Galacticraft-Mod-1.7.10.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-Mod-1.7.10.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (Gravity-Gun-Mod-1.7.10.jar) 
	UCHIJAAAA	SGCraft{1.13.3} [Greg's SG Craft] (Gregs-SG-Craft-Mod-1.7.10.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-Mod-1.7.10.jar) 
	UCHIJAAAA	HatStand{4.0.0} [HatStand] (Hat-Stand-Mod-1.7.10.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (Immersive-Engineering-Mod-1.7.10.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-Mod-1.7.10.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Just-Another-Better-Barrel-Attempt-Mod-1.7.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-Mod-1.7.10.jar) 
	UCHIJAAAA	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UCHIJAAAA	mdxlib{1.0.0.74} [mdxlib] (MDXLib-1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	Mekanism{9.1.1} [Mekanism] (Mekanism-Mod-Core-1.7.10.jar) 
	UCHIJAAAA	MekanismGenerators{9.1.1} [MekanismGenerators] (Mekanism-Mod-Generators-1.7.10.jar) 
	UCHIJAAAA	MekanismTools{9.1.1} [MekanismTools] (Mekanism-Mod-Tools-1.7.10.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.2B1} [MineFactory Reloaded] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.2B1} [MFR Compat: BuildCraft] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.2B1} [MFR Compat: ForgeMicroblock] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.2B1} [MFR Compat: IC2] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.2B1} [MFR Compat: Thermal Expansion] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UCHIJAAAA	tc{4.3.1_008} [Traincraft] (Traincraft-Mod-1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-Mod-1.7.10.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.2B1} [MFR Compat: Tinkers' Construct] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (Twilight-Forest-Mod-1.7.10.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.2B1} [MFR Compat: TwilightForest] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.2B1} [MFR Compat: Vanilla] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UCHIJAAAA	numina{1.7.10} [Numina] (Numina-Mod-1.7.10.jar) 
	UCHIJAAAA	powersuits{@VERSION@} [MachineMuse's Modular Powersuits] (Modular-Powersuits-Mod-1.7.10.jar) 
	UCHIJAAAA	Morph{0.9.3} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat-Mod-1.7.10.jar) 
	UCHIJAAAA	shit{1.3} [Poop Mod] (Poop-Mod-1.7.10.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (Portal-Gun-Mod-1.7.10.jar) 
	UCHIJAAAA	rivalrebels{1.7.10Y} [Rival Rebels] (Rival-Rebels-Mod-1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (Thermal-Dynamics-Mod-1.7.10.jar) 
	UCHIJAAAA	Torched{4.0.0} [Torched] (Torched-Mod-1.7.10.jar) 
	UCHIJAAAA	tts{0.6} [Tube Transport System] (Tube-Transport-System-Mod-1.7.10.jar) 
	UCHIJAAAA	xaerominimap{1.17.2} [Xaero's Minimap] (Xaeros-Minimap-Mod-1.7.10.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.2B1} [MFR Compat: Applied Energistics] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.2B1} [MFR Compat: Atum] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.2B1} [MFR Compat: BackTools] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.2B1} [MFR Compat: Chococraft] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.2B1} [MFR Compat: ExtraBiomes] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.2B1} [MFR Compat: Forestry] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.2B1} [MFR Compat ProjectRed] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.2B1} [MFR Compat: Railcraft] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.2B1} [MFR Compat: Sufficient Biomes] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.2B1} [MFR Compat: Thaumcraft] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.2B1-201
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['Taruska'/250, l='New Worldttttreereest', x=-52,80, y=77,00, z=-65,49]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
