### ISSUE TITLE
When will version 1.15.2 be released?

### ISSUE THREAD

**Issue by Micoumi** [iChun/Morph#1131]
Hi ! I really love the morph mod but unfortunately all the mods I play are in 1.15.2 ... but I miss this mod I wanted to know when it will be in this version? thank you and sorry for the spelling i'm french

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. Hope this helps!
