### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by mbm101** [iChun/Morph#1132]
Hello, I was just wondering if anyone could tell me how I would go about doing the permissions to allow other players in my server to use the morph mod? As you know it doesn’t use commands it uses the brackets…. I’m new to this server stuff and would appreciate any help!

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
