### ISSUE TITLE
flying

### ISSUE THREAD

**Issue by kripotker** [iChun/Morph#1137]
Hello!
In the morph mod, i can fly, BUT I need to spam the space bar, not just double tap the spacebar, how can I fix this?

**Comment by iChun** [comment]
That's how flight works for winged mobs now. If you want creativelike
flight you should kill a blaze or something. I didn't make the abilities
for 1.12.2 but I think that's how it works?

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
