### ISSUE TITLE
game crashes when i colide with a mob from primative mobs

### ISSUE THREAD

**Issue by Dracotyoshi** [iChun/Morph#1138]
so basicaly i got a ticking player error when a brain slime attacked me
then a combat skeleton attacked me in a seprate workd and crashed the game
whats going on

**Comment by Dracotyoshi** [comment]
i had more player modles on that can and seems to cause those errors
removing to test now (these errors stil need to be fixed tho)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
