### ISSUE TITLE
Rendering Glitch

### ISSUE THREAD

**Issue by Jaspurrb** [iChun/Morph#1141]
Sometimes when i morph into mobs and back into player my player renders a second set of arms under the normal ones, this also sometimes happens when i switch back to a mob for example a bat. the bat has a really weird render like he misses a wing or sometimes misses a head. its really annoying bc i want to morph normally. this happens to all morphs, even the ones from other mods like ancient warfare 2. thank you for reading!

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
