### ISSUE TITLE
hostile mob dedect not work

### ISSUE THREAD

**Issue by Beany2** [iChun/Morph#1143]
The hostile mod prevension thingy doesn't work even though I turned it on in config.

I legiteraly made a githuib account just to comment this so please do not ignore it.

**Comment by Betelgeusesupergiant** [comment]
Grammar

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
