### ISSUE TITLE
Health does not change to 4 hearts morphing as an untamed wolf.

### ISSUE THREAD

**Issue by Betelgeusesupergiant** [iChun/Morph#1145]
![2021-05-20_19 29 47](https://user-images.githubusercontent.com/84168091/119064807-d1765b00-b9a1-11eb-933c-a9ddd9a48e33.png)
Hello.
I am using this mod but now the hearts don't change amount anymore. Someone help!

**Comment by DamienOlcikas** [comment]
UGH flip this creator

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
