### ISSUE TITLE
I dont know what to call this bug

### ISSUE THREAD

**Issue by Connorray1234** [iChun/Morph#1148]
Well theres this bug in thew 1.12.2 version of the mod where if you die as the bird from mo creature when you hit a block it dosent kill you it show the screen but wqhen you morph back into the player it loops the diening animation.
![Screenshot (1024)](https://user-images.githubusercontent.com/85777151/121765003-d50e8500-cafc-11eb-9109-746f9b037d1d.png)
![Screenshot_70](https://user-images.githubusercontent.com/85777151/121765031-fec7ac00-cafc-11eb-9c1b-c8a222f122b0.jpg)

The first ss is the bug
the 2nd issue is what creates the bug its when you fly into 
Its when you first morph into the bird from mo creatures and fly into something

**Comment by iChun** [comment]
Sorry, but 1.12.2 is no longer supported.
