### ISSUE TITLE
"Minecraft ran into a problem and crashed"

### ISSUE THREAD

**Issue by LunarSoul7** [iChun/Morph#1149]
I am completely unknown to what exactly has happened or as to how to solve the problem. To my knowledge, I was morphed as a bat in the Stoneblock 2 modpack, and was killed by a baby skeleton. Upon respawn, my death location was incorrectly marked but I headed towards where I knew I died anyway and as I was 'flying' with the bat up some stairs towards my body, I crashed. I cannot login to the server as it tells me that "Minecraft ran into a problem and crashed" when I try. Here is the crash report I was given, https://paste.dimdev.org/kaloqurezi.mccrash I don't know what it means but I imagine it is useful. Any help is appreciated.
![crash](https://user-images.githubusercontent.com/86033809/122324867-89424e00-cef7-11eb-8cfa-c205858ceb4b.PNG)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
