### ISSUE TITLE
File Error

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [iChun/Morph#1150]
My Morph Mod is a file instead of an Executable Jar File
![image](https://user-images.githubusercontent.com/58344347/122481047-9d3b8d80-cf93-11eb-8be9-5c6895627745.png)

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
