### ISSUE TITLE
Drifting When Morphing

### ISSUE THREAD

**Issue by bencfun** [iChun/Morph#1152]
Whenever I morph into 1-block mobs, I drift, and cannot stop it until I am done morphing and my pov is 2blocks tall (makes me see through blocks) Is there any fix? all other posts about it were filled with "same issue" or "what version?"

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
