### ISSUE TITLE
Hostile Mob Ability doesn't work

### ISSUE THREAD

**Issue by Friskipoo** [iChun/Morph#1153]
I turn into a hostile mob, but they still come after me

**Comment by DamienOlcikas** [comment]
cause the creator didn't add it in the code

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
