### ISSUE TITLE
Cant morph into any boss

### ISSUE THREAD

**Issue by BENDY7160** [iChun/Morph#1154]
I watched some youtube videos and one of them can morph into a minecraft boss tried it myself it didnt work any solutions

**Comment by iChun** [comment]
Have you looked into the config files for the mod?

**Comment by BENDY7160** [comment]
Sorry for the long response can you tell where the cfg file is located?

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
