### ISSUE TITLE
Morph 1.12.2+

### ISSUE THREAD

**Issue by EvilNapkin0** [iChun/Morph#1156]
Hello,

I like morph so much its the first mod I ever installed and since 1.12.2 it isn't getting any updates anymore. So my question is, is morph gonna be updated to 1.13 and higher?

**Comment by iChun** [comment]
https://github.com/iChun/Morph/tree/1.16

**Comment by iChun** [comment]
That said, I'm taking a break from dev, lil burnt out from working on the mod, there is **a lot** to do.
