### ISSUE TITLE
can I still morph without sleeping?

### ISSUE THREAD

**Issue by AryIsNotHere** [iChun/Morph#1157]
I want to morph in different mobs but the problem is that if i kill them it doesn't work, the only way it does work is if I sleep/kill myself. I found the mob menu but every time I click on of them it works just for a few seconds. Is there a way to change this?
Thank you.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
