### ISSUE TITLE
Morph config, not remembering/applying my preferences

### ISSUE THREAD

**Issue by PurpleFox32** [iChun/Morph#1161]
There is an issue with the config. I have it set to where hostile mobs don't attack if I am morphed as a hostile mob but I am still being attacked by hostile mobs while being a hostile mob.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
