### ISSUE TITLE
1.12.2 Morph Mod crashes when morphing

### ISSUE THREAD

**Issue by vialucid** [iChun/Morph#1163]
The morph mod still shows me acquiring a morph (the animation of the mob deforming and becoming gray), but anytime I try morphing to a mob (For example, a Chicken), it straight up crashes the game and leaves me this crash log :

https://pastebin.com/CHDkC3c2

Also, it also crashes when I press the select "UP" or "DOWN" keybind when I don't actually have the menu open. I did download the API, and I'm not sure if it's just other mods counteracting with the morph mod.

(Download from Curseforge)

**Comment by iChun** [comment]
You're not supposed to have the API installed, that's for developers to
build their mod against. It might be why you are crashing if you have that
in your mods folder

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
