### ISSUE TITLE
You get kicked for flapping flying in survival in a server

### ISSUE THREAD

**Issue by Ch1216** [iChun/Morph#1168]
due to "allow-flight=true" in server.properties

**Comment by CmdrFigrow** [comment]
Not a dev but I've found that this isn't necessarily a Morph issue. Bukkit/Spigot server-side plugins that do similar things also have this issue. The best solution I've found is, as you mentioned, to set `allow-flight=false` to `allow-flight=true` in the server.properties file. Hope this helps :)

**Comment by iChun** [comment]
Fixed for next update.
