### ISSUE TITLE
[Crash] When i click morph button

### ISSUE THREAD

**Issue by DonSimeone** [iChun/Morph#1171]
Game has crashed. Multiplayer in mc 1.16.5 Forge

Raport: https://pastebin.com/aQXBPgsq

Ideas?

**Comment by iChun** [comment]
Noted, I'll have to fix it on the mod end I think. In the meantime you
might have to delete your player save data, it's in the world folder called
morph_save.dat. If on multiplayer you might need to get an NBT editor to
remove specifically your save data in the file as to not affect others.

I don't know if there is a /morph morph clear command but if there is you
can use that, it'll clear your morphs. If it doesn't, then, uh I should
probably add that.

**Comment by iChun** [comment]
Fixed for the next update.
