### ISSUE TITLE
Minecraft crashes whenever I am trying to open morph menu in multiplayer

### ISSUE THREAD

**Issue by ltoko** [iChun/Morph#1177]
When I try to open any morph menu while playing with my friend on local network, minecraft crashes.
[crash-2022-01-26_00.11.08-client.txt](https://github.com/iChun/Morph/files/7958406/crash-2022-01-26_00.11.08-client.txt)
.

**Comment by Shr1mps** [comment]
same thing here, ill leave my crash report as wel
[crash-2022-01-30_01.02.11-client.txt](https://github.com/iChun/Morph/files/7966109/crash-2022-01-30_01.02.11-client.txt)

**Comment by Seastrom2022** [comment]
are u guys using aternos by any chance?

**Comment by ltoko** [comment]
> are u guys using aternos by any chance?

I am not using aternos

**Comment by iChun** [comment]
Only took me a couple of hours trying to figure it out, but it should be fixed in the next update of Morph.
