### ISSUE TITLE
Morph Mod Is crashing minecraft in Multiplayer

### ISSUE THREAD

**Issue by Seastrom2022** [iChun/Morph#1179]
Its crashing the game in multiplayer but not in single player as soon as we try to change in a other animal it crashes instantly please fix it

**Comment by iChun** [comment]
I'm going to need a crash log before I can assist with this issue

**Comment by Seastrom2022** [comment]
[crash-2022-01-26_00.11.08-client.txt](https://github.com/iChun/Morph/files/7986877/crash-2022-01-26_00.11.08-client.txt)

**Comment by Seastrom2022** [comment]
I Dont know how to get crash log so i asked one of my frnd to give the crash log after the game crashed on his computer

**Comment by iChun** [comment]
Only took me a couple of hours trying to figure it out, but it should be fixed in the next update of Morph.
