### ISSUE TITLE
Morph mod crashes on dedicated server when opening morph menu

### ISSUE THREAD

**Issue by lewapro** [iChun/Morph#1180]
It crashes when you try opening the menu. You can see it for a second. It will crash even if you remove hud.
It works completely fine in singleplayer.
Crash report: [crash-2022-02-05_12.41.34-client.txt](https://github.com/iChun/Morph/files/8007732/crash-2022-02-05_12.41.34-client.txt)
The only mods installed are Morph and iChunUtil.

**Comment by Yao0oooo** [comment]
same issues

**Comment by iChun** [comment]
Only took me a couple of hours trying to figure it out, but it should be fixed in the next update of Morph.
