### ISSUE TITLE
opening mod menu crashes minecraft, also trying to transform crashing 

### ISSUE THREAD

**Issue by lizpp** [iChun/Morph#1183]
as in topic https://pastebin.com/NUgxhAUg

**Comment by iChun** [comment]
I'm very perplexed as to why you can get a null String there, as I've never encountered that before. Did this start happening after you killed a specific mob (and acquired it)? 

Can you also try to remove Optifine to see if that solves this issue?

**Comment by iChun** [comment]
Only took me a couple of hours trying to figure it out, but it should be fixed in the next update of Morph.
