### ISSUE TITLE
When morphed mobs still attack me

### ISSUE THREAD

**Issue by ghost** [iChun/Morph#1188]
Title, I wanna make it so when I am morphed mobs wont attack me when I am a hostile mob myself.
https://pastebin.com/TfBkwbp7
Config file in pastebin.

**Comment by iChun** [comment]
I no longer support Morph for versions 1.12.2 and older, sorry.

Abilities were ported over by a third party and unfortunately the event
that the hostile ability uses wasn't ported over, so the hostile ability
doesn't work.
