### ISSUE TITLE
Crashes after hitting morph 

### ISSUE THREAD

**Issue by EternalStorm944** [iChun/Morph#1189]
The game crashes when morphing into mobs 
Error code: The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Ticking entity
Exit Code: -1
crash report
[Morph mod -2022-03-04_12.40.59-client.txt](https://github.com/iChun/Morph/files/8187853/Morph.mod.-2022-03-04_12.40.59-client.txt)

**Comment by iChun** [comment]
I checked with Mowzie's Mobs, it'll be fixed on their end.
