### ISSUE TITLE
crashes whenever kill a mob

### ISSUE THREAD

**Issue by syamrz227** [iChun/Morph#1195]
Im using morph mod in version 1.7.10 for a modpack called orespawn adventure and ill get a fatal error whenever i kill a mob. The log shows as this;
[New Text Document.txt](https://github.com/iChun/Morph/files/8223680/New.Text.Document.txt)

**Comment by iChun** [comment]
I no longer support Morph for 1.12.2 and older. You're asking for support
on a version of Minecraft that could be in elementary school at this point.
Obligatory: https://howoldisminecraft1710.today/

Try removing Optifine, Morph has a history of not working well with it
installed.
