### ISSUE TITLE
My server doesn't launch because morph mod

### ISSUE THREAD

**Issue by martiiic** [iChun/Morph#1199]
WHEN IT'S ALREADY DONE MORPH SENDS A MESSAGE THAT SAYS "[Morph Resource Thread/INFO] [Morph]: Found and mapped ability mappings for 24 presumably Minecraft mobs]" I'm in minecraft 1.12.2 14.23.5.2860

[https://pastebin.com/zfPbMdsr]

**Comment by iChun** [comment]
That's a line morph logs just for info to whoever reads it. It's not indicative that it's causing your server to be unable to launch just cause it was the last line on the log.

Also your paste is marked private so I can't view it. I also no longer support Morph for 1.12.2 and older.
