### ISSUE TITLE
Crash on Morph in pack Crazy Craft Updated

### ISSUE THREAD

**Issue by hahasel** [iChun/Morph#1201]
Heyho,
For some reason the newest version (10.1.1) crashes for me and my friends. It happens with basically any morph, even with the demorph command. Crash log here: https://pastebin.com/0pKpZ08E
The crash seems to be client side only.

Upon further testing, with just Morph and IchunUtils installed it does not happen, hence I assume its because of some interaction weirdness. 

Playing on a server, optifine is not installed. It also happens on Singleplayer on any morph, crash log for executing a demorph command as a player here: https://pastebin.com/cpwUGx0u

I'll be happy to provide any other information you need!

**Comment by iChun** [comment]
Update Mowzie's Mobs to 1.5.23, its been fixed on their end.

**Comment by iChun** [comment]
If you'd like, report the issue to the mod pack creator so they can update the pack as well.

Also: Thanks for the way you've made your issue report, detailing what causes the crash and including the crash log goes a long way for us devs to figure out what's going on. Bit refreshing to see!
