### ISSUE TITLE
Crashes when i open menu

### ISSUE THREAD

**Issue by HunterTubeGaming** [iChun/Morph#1202]
so when i click the [ ] buttons to open the morph menu i crash dont know why if anyone knows how to fix please reply to this with the answer

**Comment by iChun** [comment]
Basic information such as the version of Morph you are using and the crash log does wonders in terms of getting people to assist you

**Comment by HunterTubeGaming** [comment]
> Basic information such as the version of Morph you are using and the crash log does wonders in terms of getting people to assist you

sorry i dont know anything about modding what do you mean?


> https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report
> 
> I just need the crash report, attach the file here.

ok gimme a sec

**Comment by iChun** [comment]
https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report

I just need the crash report, attach the file here.

**Comment by HunterTubeGaming** [comment]
> https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report
> 
> I just need the crash report, attach the file here.
[crash-2022-04-22_20.44.02-client.txt](https://github.com/iChun/Morph/files/8545969/crash-2022-04-22_20.44.02-client.txt)

i hope that the right one

**Comment by HunterTubeGaming** [comment]
> > https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report
> > I just need the crash report, attach the file here.
> > [crash-2022-04-22_20.44.02-client.txt](https://github.com/iChun/Morph/files/8545969/crash-2022-04-22_20.44.02-client.txt)
> 
> i hope thats the right one

**Comment by iChun** [comment]
Minecraft is crashing due to an error in the Chocolate Quest Repoured mod. You should send this crash report to them. 

I would like to note that you're also playing a version of Minecraft that not many mod devs will support any more due to it's age. 

I personally am no longer supporting any of my mods for 1.12.2 and older.

**Comment by HunterTubeGaming** [comment]
> Minecraft is crashing due to an error in the Chocolate Quest Repoured mod. You should send this crash report to them.
> 
> I would like to note that you're also playing a version of Minecraft that not many mod devs will support any more due to it's age.
> 
> I personally am no longer supporting any of my mods for 1.12.2 and older.

ok
