### ISSUE TITLE
Creative Fly

### ISSUE THREAD

**Issue by ghost** [iChun/Morph#1205]
Hello IChun can you please readd creative fly to all morphs that can fly? or make an option for that in the config file in Morph 1.16.5

**Comment by iChun** [comment]
It's in the mod already, you have to change the mappings for those mob's
abilities and make sure those mappings are synced on the client and server.
Eg the blaze has creative-like flight

**Comment by iChun** [comment]
For your reference:

Blazes: https://github.com/iChun/Morph/blob/1.16/morph/mob/Blaze.json

Bats: https://github.com/iChun/Morph/blob/1.16/morph/mob/Bat.json
