### ISSUE TITLE
For some reason I don't have a .cfg file to change anything about the mod

### ISSUE THREAD

**Issue by J7901Io** [iChun/Morph#1206]
![Screenshot (143)](https://user-images.githubusercontent.com/105252673/167516659-13efce05-aaca-4403-a8ab-3fcc253ecceb.png)

**Comment by iChun** [comment]
That toml file is the config file. Open it with a text editor. There will be another config file in the world save folder. Most mods' config files are toml files from MC 1.13 onwards
