### ISSUE TITLE
Morph mod crash lockout after travelling through the nether as a bat.

### ISSUE THREAD

**Issue by MagnesiumSail** [iChun/Morph#1213]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-05-19 12:54:06 MDT
Description: Unexpected error

java.lang.NullPointerException
    at net.minecraft.client.model.ModelBiped.setRotationAngles(SourceFile:123)
    at net.minecraft.client.model.ModelPlayer.setRotationAngles(SourceFile:117)
    at me.ichun.mods.morph.client.render.RenderPlayerHand.renderRightArm(RenderPlayerHand.java:106)
    at net.minecraft.client.renderer.ItemRenderer.renderArmFirstPerson(ItemRenderer.java:255)
    at net.minecraft.client.renderer.ItemRenderer.renderItemInFirstPerson(ItemRenderer.java:358)
    at net.minecraft.client.renderer.ItemRenderer.renderItemInFirstPerson(ItemRenderer.java:333)
    at me.ichun.mods.morph.client.core.EventHandlerClient.onRenderHand(EventHandlerClient.java:797)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1276_EventHandlerClient_onRenderHand_RenderHandEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:201)
    at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:772)
    at thebetweenlands.client.handler.ShaderHandler.updateShaders(ShaderHandler.java:103)
    at thebetweenlands.client.handler.ShaderHandler.onRenderWorldLastLowest(ShaderHandler.java:89)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1766_ShaderHandler_onRenderWorldLastLowest_RenderWorldLastEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1432)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['MagnesiumSail'/2589228, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Chunk stats: MultiplayerChunkCache: 0, 0
  Level seed: 0
  Level generator: ID 29 - BIOMESOP, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 0 game time, 0 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 2 total; [EntityPlayerSP['MagnesiumSail'/2589228, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/100558, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Retry entities: 1 total; [EntityLatchedRenderer['unknown'/100558, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1828020064 bytes (1743 MB) / 7382499328 bytes (7040 MB) up to 9902751744 bytes (9444 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10624m -Xms256m
  IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 118 mods loaded, 118 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                    | Version                  | Source                                         | Signature                                |
       |:------ |:--------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                  | None                                     |
       | LCHIJA | mcp                   | 9.42                     | minecraft.jar                                  | None                                     |
       | LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                 | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | ivtoolkit             | 1.3.3-1.12               | minecraft.jar                                  | None                                     |
       | LCHIJA | otgcore               | 1.12.2-v9.3              | minecraft.jar                                  | None                                     |
       | LCHIJA | reachfix              | 1.0.1                    | minecraft.jar                                  | None                                     |
       | LCHIJA | smoothfontcore        | mc1.12.2-2.1.2           | minecraft.jar                                  | None                                     |
       | LCHIJA | foamfixcore           | 7.7.4                    | minecraft.jar                                  | None                                     |
       | LCHIJA | srm-hooks             | 1.12.2-1.0.0             | minecraft.jar                                  | None                                     |
       | LCHIJA | randompatches         | 1.12.2-1.22.1.10         | randompatches-1.12.2-1.22.1.10.jar             | None                                     |
       | LCHIJA | smoothfont            | mc1.12.2-2.1.2           | SmoothFont-mc1.12.2-2.1.2.jar                  | None                                     |
       | LCHIJA | jei                   | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                      | None                                     |
       | LCHIJA | abyssalcraft          | 1.10.4                   | AbyssalCraft-1.12.2-1.10.4.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | ctm                   | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
       | LCHIJA | mysticalworld         | 1.12.2-1.9.8             | mysticalworld-1.12.2-1.9.8.jar                 | None                                     |
       | LCHIJA | chisel                | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                   | None                                     |
       | LCHIJA | mantle                | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                       | None                                     |
       | LCHIJA | quark                 | r1.6-179                 | Quark-r1.6-179.jar                             | None                                     |
       | LCHIJA | twilightforest        | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar  | None                                     |
       | LCHIJA | tconstruct            | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
       | LCHIJA | acintegration         | 1.11.3                   | AbyssalCraft Integration-1.12.2-1.11.3.jar     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | aether_legacy         | 1.5.3.2                  | aether-1.12.2-v1.5.3.2.jar                     | None                                     |
       | LCHIJA | aether_legacy_addon   | 1.12.2-v1.3.0            | Aether Continuation v1.3.0.jar                 | None                                     |
       | LCHIJA | antiqueatlas          | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
       | LCHIJA | antiqueatlasoverlay   | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
       | LCHIJA | aoa3                  | 3.3.6                    | AoA3-3.3.6.jar                                 | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCHIJA | appleskin             | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                    | None                                     |
       | LCHIJA | attributefix          | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                         | None                                     |
       | LCHIJA | atum                  | 2.0.20                   | Atum-1.12.2-2.0.20.jar                         | None                                     |
       | LCHIJA | autoreglib            | 1.3-32                   | AutoRegLib-1.3-32.jar                          | None                                     |
       | LCHIJA | battletowers          | 1.6.5                    | BattleTowers-1.12.2.jar                        | None                                     |
       | LCHIJA | betteradvancements    | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar         | None                                     |
       | LCHIJA | bettercaves           | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                   | None                                     |
       | LCHIJA | bibliocraft           | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
       | LCHIJA | biggerpacketsplz      | 1.2                      | biggerpacketsplz-since1.8-1.2.jar              | 266588b191a3e2974a4a577f282858a3bc07da42 |
       | LCHIJA | biomesoplenty         | 7.0.1.2445               | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar  | None                                     |
       | LCHIJA | bookshelf             | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | forgelin              | 1.8.3                    | Forgelin-1.8.3.jar                             | None                                     |
       | LCHIJA | bountiful             | 2.2.2                    | Bountiful-2.2.2.jar                            | None                                     |
       | LCHIJA | brokenwings           | 2.0.0                    | brokenwings-3.0.0.jar                          | None                                     |
       | LCHIJA | chameleon             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                       | None                                     |
       | LCHIJA | chiselsandbits        | 14.33                    | chiselsandbits-14.33.jar                       | None                                     |
       | LCHIJA | chococraft            | 0.9.9.0                  | chococraft_1.12.2-0.9.9.0.jar                  | None                                     |
       | LCHIJA | phosphor-lighting     | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar    | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | cqrepoured            | 2.6.6B                   | Chocolate_Quest_Repoured-1.12.2-2.6.6B.jar     | None                                     |
       | LCHIJA | conarm                | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                     | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
       | LCHIJA | cookingforblockheads  | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar          | None                                     |
       | LCHIJA | cosmeticarmorreworked | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | dimdoors              | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                 | None                                     |
       | LCHIJA | dldungeonsjbg         | 1.14.10                  | DoomlikeDungeons-1.14.10-MC1.12.2.jar          | None                                     |
       | LCHIJA | dungeonsmod           | @VERSION@                | DungeonsMod-1.12.2-1.0.8.jar                   | None                                     |
       | LCHIJA | dungeontactics        | DT-0.16.9                | DungeonTactics-1.12.2-0.16.9.jar               | None                                     |
       | LCHIJA | eplus                 | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | erebus                | 1.0.32                   | Erebus-1.0.32.jar                              | None                                     |
       | LCHIJA | exoticbirds           | 1.0                      | Exotic+Birds+1.12.2-3.2.0.jar                  | None                                     |
       | LCHIJA | fastfurnace           | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                   | None                                     |
       | LCHIJA | fastbench             | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                 | None                                     |
       | LCHIJA | featuredservers       | 1.12-1.0.6               | FeaturedServers-1.12-1.0.6.jar                 | None                                     |
       | LCHIJA | foamfix               | 0.10.14-1.12.2           | foamfix-0.10.14-1.12.2.jar                     | None                                     |
       | LCHIJA | cfm                   | 6.3.1                    | furniture-6.3.1-1.12.2.jar                     | None                                     |
       | LCHIJA | futureminecraf        | 1.3.1                    | FutureVersions v1.3.1.jar                      | None                                     |
       | LCHIJA | geckolib3             | 3.0.13                   | geckolib-forge-1.12.2-3.0.18.jar               | None                                     |
       | LCHIJA | gottschcore           | 1.14.1                   | GottschCore-mc1.12.2-f14.23.5.2854-v1.14.1.jar | None                                     |
       | LCHIJA | heroicarmory          | 1.1.3                    | heroicarmory-1.2.0.jar                         | None                                     |
       | LCHIJA | placebo               | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                       | None                                     |
       | LCHIJA | hexxitgear            | 2.8.0                    | Hexxit Gear-1.12.2-2.8.0.jar                   | None                                     |
       | LCHIJA | librarianlib          | 4.22                     | librarianlib-1.12.2-4.22.jar                   | None                                     |
       | LCHIJA | hooked                | %VERSION%                | hooked-1.0.3.jar                               | None                                     |
       | LCHIJA | ichunutil             | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | infernalmobs          | 1.7.6                    | InfernalMobs-1.12.2.jar                        | None                                     |
       | LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest             | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
       | LCHIJA | jrftl                 | 1.1                      | JRFTL[1.12.2]-1.1.jar                          | None                                     |
       | LCHIJA | jeid                  | 1.0.4-SNAPSHOT           | JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar          | None                                     |
       | LCHIJA | llibrary              | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | lepidodendron         | 50.2                     | lepidodendron-1.12.2-50.2.jar                  | None                                     |
       | LCHIJA | login_shield          | 1.12.2-6-g5654706        | Login_Shield-1.12.2-6-g5654706.jar             | None                                     |
       | LCHIJA | lootbags              | 2.5.8.7                  | lootbags-2.5.8.7.jar                           | None                                     |
       | LCHIJA | lost_aether           | 1.0.2                    | lost-aether-content-1.12.2-1.0.2.jar           | None                                     |
       | LCHIJA | megaloot              | 0.2.40                   | megaloot-1.12.2-0.2.40.jar                     | None                                     |
       | LCHIJA | morebeautifulplates   | 1.12.2-1.1.4             | morebeautifulplates-1.12.2-1.1.4.jar           | None                                     |
       | LCHIJA | morph                 | 7.2.0                    | Morph-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | natura                | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                     | None                                     |
       | LCHIJA | netherportalfix       | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar              | None                                     |
       | LCHIJA | oretweaker            | 1.0.2-1.12.0             | Ore Tweaker-1.0.2-1.12.0.jar                   | None                                     |
       | LCHIJA | patchouli             | 1.0-23.6                 | Patchouli-1.0-23.6.jar                         | None                                     |
       | LCHIJA | performant            | 1.12.2-1.5               | performant-1.11.jar                            | None                                     |
       | LCHIJA | railcraft             | 12.0.0                   | railcraft-12.0.0.jar                           | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | reccomplex            | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                   | None                                     |
       | LCHIJA | xreliquary            | 1.12.2-1.3.4.796         | Reliquary-1.12.2-1.3.4.796.jar                 | None                                     |
       | LCHIJA | additionalstructures  | 2.5.0                    | Rex's-AdditionalStructures-1.12.x(v.2.5.0).jar | None                                     |
       | LCHIJA | roguelike             | 2.4.1                    | RoguelikeDungeonsFnarEdition-1.12.2-2.4.1.jar  | None                                     |
       | LCHIJA | roughmobsrevamped     | 2.3.22                   | roughmobsrevamped-1.12.2-2.3.22.jar            | None                                     |
       | LCHIJA | secretroomsmod        | 5.6.4                    | secretroomsmod-1.12.2-5.6.4.jar                | None                                     |
       | LCHIJA | soulshardsrespawn     | 1.12.2-1.1.1-13          | SoulShardsRespawn-1.12.2-1.1.1-13.jar          | None                                     |
       | LCHIJA | spartanshields        | 1.5.5                    | SpartanShields-1.12.2-1.5.5.jar                | None                                     |
       | LCHIJA | storagedrawers        | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                | None                                     |
       | LCHIJA | surge                 | 2.0.77                   | Surge-1.12.2-2.0.77.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | theoneprobe           | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                    | None                                     |
       | LCHIJA | tcomplement           | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar             | None                                     |
       | LCHIJA | toastcontrol          | 1.8.1                    | Toast Control-1.12.2-1.8.1.jar                 | None                                     |
       | LCHIJA | tombmanygraves        | 1.12-4.2.0               | TombManyGraves-1.12-4.2.0.jar                  | None                                     |
       | LCHIJA | treechopper           | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                   | None                                     |
       | LCHIJA | tropicraft            | 7.1.9.115                | tropicraft-MC1.12.2-7.1.9.115.jar              | None                                     |
       | LCHIJA | unloader              | 1.2.0                    | unloader-1.2.0.jar                             | None                                     |
       | LCHIJA | vanillafix            | 1.0.10-150               | VanillaFix-1.0.10-150.jar                      | None                                     |
       | LCHIJA | waddles               | 0.6.0                    | Waddles-1.12.2-0.6.0.jar                       | None                                     |
       | LCHIJA | wearablebackpacks     | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar             | None                                     |
       | LCHIJA | worleycaves           | 1.5.2                    | worleycaves-1.12.2-1.5.2.jar                   | None                                     |
       | LCHIJA | recipehandler         | 0.14                     | YARCF-0.14(1.12.2).jar                         | None                                     |
       | LCHIJA | zoocraftdiscoveries   | 1.0                      | Zoocraft+Discoveries+1.12.2-1.3.0.jar          | None                                     |
       | LCHIJA | jurassicraft          | 2.1.21                   | JurassiCraft-1.12.2-2.1.21 (1).jar             | None                                     |
       | LCHIJA | orelib                | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | thebetweenlands       | 3.8.1                    | TheBetweenlands-3.8.1-universal.jar            | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCHIJA | librarianliblate      | 4.22                     | librarianlib-1.12.2-4.22.jar                   | None                                     |
       | LCHIJA | mysticallib           | 1.12.2-1.13.0            | mysticallib-1.12.2-1.13.0.jar                  | None                                     |
  Loaded coremods (and transformers): RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      ReachFixPlugin (ReachFix-1.12.2-1.0.1.jar)
                                        meldexun.reachfix.asm.ReachFixClassTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.6B.jar)
                                        team.cqr.cqrepoured.asm.CQRClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.8.1-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
                                        net.elnounch.mc.biggerpacketsplz.BiggerPacketsPlzClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.79' Renderer: 'NVIDIA GeForce GTX 1070/PCIe/SSE2'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleMelter (Enabled/Not Forced)
                                    - ModuleArmor (Enabled/Not Forced)
                                    - ModuleSteelworks (Enabled/Not Forced)
                                    - ChiselPlugin (Enabled/Not Forced)
                                    - Oredict (Enabled/Forced)
  Patchouli open book context: n/a
  Suspected Mods: Morph (morph), The Betweenlands (thebetweenlands)
  Launched Version: forge-14.23.5.2860
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.79, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 1700 Eight-Core Processor
  Client Crashes Since Restart: 20
  Integrated Server Crashes Since Restart: 0

**Comment by iChun** [comment]
Going through your crash log, I realise this is a crash for 1.12.2. I'm sorry but I no longer support Morph for 1.12.2 and older https://github.com/iChun/Morph/issues/878

**Comment by Kurtoid** [comment]
Any advice for recovering from this?

**Comment by Natedogwoooof** [comment]
its chocolate quest try deleting it it crashed me when opening morph menu
