### ISSUE TITLE
Cannot find the bossMorphs option inside of the config file.

### ISSUE THREAD

**Issue by Kbm003** [iChun/Morph#1214]
This issue is for the serverconfig, not the morphclient

**Comment by iChun** [comment]
If this is regarding the 1.16.5 version of Morph, this config doesn't exist
anymore. You will acquire boss morphs by default when you kill them.

**Comment by Kbm003** [comment]
This is with the 1.16.4 version and when i kill a boss (including endermen; iron golems and bees) it says "invalid morph pig.

**Comment by iChun** [comment]
Then something is causing the morphs to error out. I need to look at the log file to see what's causing it. 


Wait, what version is this?

**Comment by Kbm003** [comment]
Of Minecraft or morph mod?

**Comment by iChun** [comment]
Morph

**Comment by iChun** [comment]
Is there any particular reason you're on 1.16.4 and not 1.16.5?

**Comment by iChun** [comment]
The issue you are having with those mobs showing as invalid was fixed by Minecraft Forge for 1.16.5.

**Comment by Kbm003** [comment]
I'm using mods and rps that are only on 1.16.4
The version of morph I'm using is 1.16.5-10.1.1

**Comment by Kbm003** [comment]
NVM I found the solution. I just needed yo update my game. Sorry but how do you enable abilities in this version?

**Comment by iChun** [comment]
Active Abilities are not a thing that exist, that keybind is just there for
a future introduction.

Passive abilities and traits, which is what existed in the 1.12.2 version
of Morph, already exist as part of the mod.

**Comment by iChun** [comment]
Then something is causing the morphs to error out. I need to look at the
log file to see what's causing it.
