### ISSUE TITLE
abilities not enabled / not working 

### ISSUE THREAD

**Issue by Allmanolis** [iChun/Morph#1223]
Hello my abilities are not working in the in the control tab it says disabled and I don't know what to do and please help me so I can enable them.

Some info
Minecraft server: 1.16.5 mohist
Mohist have forge and plugins
Hosting: aternos.org

22 mods with morph

**Comment by iChun** [comment]
![image](https://user-images.githubusercontent.com/2298444/219121567-98b6d6d3-002a-44c7-a7ef-c31932806a35.png)
