### ISSUE TITLE
Morphs retain armor and weapon traits

### ISSUE THREAD

**Issue by Catlord-3** [iChun/Morph#1224]
Basically, if a mob has armor or weapons equipped, if you obtain their morph and morph into them, you will have the traits they had when they had the armor and or weapon. This stacks with currently equipped armor and weapons. This can allow for the creation of broken morphs, as all you need to do is find a zombie or husk which can pick up items, give it your best armor and highest damaging weapon, and then kill it. you then get those buffs in morph. this allows for example +20 armor and +13 damage to all attacks with only vanilla items. it is also pretty easy to get +9 damage to all attacks, as that only needs a stone axe. Morph should probably take the base damage and armor instead of total.

**Comment by iChun** [comment]
Heh, didn't realise items would have modified those attributes. I have it so that the mobs' items are stripped from them before copying over the attributes now. Should fix this. Thanks for the report! Will be in the next update.
