### ISSUE TITLE
1.16.5 Version Lags/Freezes

### ISSUE THREAD

**Issue by RConTRS** [iChun/Morph#1225]
The 1.16.5 version seems to have a massive amount of performance issues, (using latest version)
pressing the ` key will freeze the game for 5-20 seconds, especially first time pressing when playing in server, or even single player
however, it's not the case, i have tested my modpack without morph and performance somehow improved, which means it might have other performance issues as well, at least i think it does
so maybe you can check it out whenever you want to. thanks

**Comment by iChun** [comment]
Is there anything popping up in the console during the freezes? It could be
lag due to render errors.

**Comment by RConTRS** [comment]
can't tell, i launched latest forge 1.16.5 with only morph and ichunutil, played for sometime and tested performance in certain conditions. completely no lag.
i think it happens when using it with other mods, i had another modpack with 60 mods and it still freeze the game for 5-20 secs when pressing ` for example, it might be another mod having issues with morph.
morph 1.16.5 can be unstable and might have entity rendering issues with other mods, i remember when it used to crash with mowzie's mobs but fixed later.
the best solution is to not use it in modpacks anyway, at least for now

**Comment by iChun** [comment]
Can I have a look at the logs where this is happening? Again, render issues might be causing that and it would show an error in the console which gets logged.

**Comment by Natedogwoooof** [comment]
> can't tell, i launched latest forge 1.16.5 with only morph and ichunutil, played for sometime and tested performance in certain conditions. completely no lag. i think it happens when using it with other mods, i had another modpack with 60 mods and it still freeze the game for 5-20 secs when pressing ` for example, it might be another mod having issues with morph. morph 1.16.5 can be unstable and might have entity rendering issues with other mods, i remember when it used to crash with mowzie's mobs but fixed later. the best solution is to not use it in modpacks anyway, at least for now

I have been using it in all the mods 6 and I haven't seen that much of a performance dip only a little

**Comment by iChun** [comment]
Was awaiting logs to see if anything was in the console when these lag spikes happen. Going to close. Feel free to reopen if still an issue.
