### ISSUE TITLE
Chickens Variations dont count as Diffrent variations

### ISSUE THREAD

**Issue by Natedogwoooof** [iChun/Morph#1228]
So i was playing all the mods 6 with morphThere where more then one variation for Chickens in the modpack and when I killed a black one after a brown one it didn't count as a 2ed variation

**Comment by iChun** [comment]
Morph strips all NBT data and mappings need to be made to tell morph which NBT data needs to be kept to maintain their appearance. You can read details on how to create these mappings on the CurseForge page for Morph
