### ISSUE TITLE
Bug With Ice and Fire

### ISSUE THREAD

**Issue by Natedogwoooof** [iChun/Morph#1229]
In 1.16.5 when i kill them it dosent do the correct morph
![2022-11-28_13 41 50](https://user-images.githubusercontent.com/109338104/204366640-16929027-6977-47c6-a0c5-228919b352e0.png)

and the myrmax worker and the rest are supost to show up like thta not white in the morph menu, like they did in 1.12.2.

**Comment by iChun** [comment]
As I mentioned in the other issue you opened 9 days ago. Morph strips all NBT data and mappings need to be made to tell morph which NBT data needs to be kept to maintain their appearance. You can read details on how to create these mappings on the CurseForge page for Morph
