### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by KordaWolf** [iChun/Morph#1248]
Every time I try to transform my game just freezes it doesn't crash though I am using the Mod pack Regrowth for 1.7.10 with 122 mods so I don't know if its a compatibility issue or what which I don't think it is because wouldn't it crash the game not freeze it? I don't know how to create JSON files for overrides or whatever I don't know if it's because I'm trying to turn into a modded mob like a Black Widow spider from Erebus or what but even vanilla mobs cause my game to freeze  any help to fix this would greatly help and be appreciated

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878

**Comment by Natedogwoooof** [comment]
ichun im big fan
