### ISSUE TITLE
1.16.5 "crazy craft updated" Cant fly?

### ISSUE THREAD

**Issue by Alaybaba2468** [iChun/Morph#1253]
Hi hows it going, I've been playing crazy craft updated on curseforge and I cant fly at all or anything. No icons whatsoever show up next to any mobs. plus as a dragon im tiny. Is there any way to fix these issues? 
help much appreciated thanks

**Comment by Natedogwoooof** [comment]
Do /generate morph resources mob to add the fly Trate and then look at the dragon and say /morph resources  generate not and move data from export folder to the mob and not folder.

**Comment by Natedogwoooof** [comment]
Nbt

**Comment by iChun** [comment]
Please read the Curseforge page for Morph to its completion, there's a specific section on "Adding compatibility with mods" that you might also want to pay closer attention to. 

There are no ability icons for Morph 1.16.5 yet as there will be a different way to identify what mobs have what traits in the future
