### ISSUE TITLE
Blacklist 1.12.2

### ISSUE THREAD

**Issue by D4njek** [iChun/Morph#1255]
Hello everyone, i can't add mobs to blacklist. What am I doing wrong?
[morph.txt](https://github.com/iChun/Morph/files/13225626/morph.txt)

**Comment by Natedogwoooof** [comment]
1.12.2 isnt supported

**Comment by D4njek** [comment]
> 1.12.2 isnt supported

not supported blacklist?

**Comment by iChun** [comment]
I don't know if the blacklist was working on 1.12.2 although it should and I see no reason from your config that you've input it incorrectly, though is the ice and fire mod domain spelled correctly? You have it as "iceadnfire". 

The blacklist only disables acquiring new mobs, if you already have it as a morph you'll still have it and will be able to use it.

I no longer officially provide support for 1.16.5 mods and older so I'm afraid that's really the most I'm willing to offer
