### ISSUE TITLE
Need help with config

### ISSUE THREAD

**Issue by TheDemonLordXXX** [iChun/Morph#1258]
Hi it says to open abilities menu and biomass menu I have to change the config in game in a single player world. But there is no config or mod window in the world I only see mods menu on the title screen. This is really irritating

**Comment by Natedogwoooof** [comment]
its not implaiminted yet

**Comment by iChun** [comment]
> Hi it says to open abilities menu and biomass menu I have to change the config in game in a single player world. But there is no config or mod window in the world I only see mods menu on the title screen. This is really irritating

Where are you reading this information from? There isn't anywhere on my project page do I speak about setting those buttons, since those menus haven't been implemented.
