### ISSUE TITLE
Morphs do not save when leaving and rejoining my modded server

### ISSUE THREAD

**Issue by TheFunsizedGuy** [iChun/Morph#1259]
any morphs i have on my server are randomly wiped whenever I leave the server.

**Comment by iChun** [comment]
Version???

**Comment by TheFunsizedGuy** [comment]
1.7.10. it used to always work but now it doesn't. Last time i used it was last year

**Comment by TheFunsizedGuy** [comment]
i had my server up in october 2021 and it worked fine so it was after you stopped support

**Comment by TheFunsizedGuy** [comment]
hey I figured it out. Advent of Ascension was messing with it some how so I had to delete it.
