### ISSUE TITLE
I cannot use mob abilities in crazy craft [updated[ 1.16

### ISSUE THREAD

**Issue by larrylemoncakes** [iChun/Morph#1261]
me and my friend downloaded crazy craft yesterday because we both recently got pcs that can run it when i killed mobs typically able to fly they could not for example i killed a fly and it simply turned me into a walk.

i checked the config and most of it was greyed out and then checked it in file explorer but i didnt understand one bit of code

i also tried to go to the nether to be able to fly and that didnt work

{no icon was visible next to any mobs in the morph menu}

**Comment by Natedogwoooof** [comment]
Morph resources generate mob or download configuration I can give u alexes mobs ones

**Comment by iChun** [comment]
Please read the Curseforge page for Morph to its completion, there's a specific section on "Adding compatibility with mods" that you might also want to pay closer attention to.
