### ISSUE TITLE
Bug - collision with my other mod

### ISSUE THREAD

**Issue by ShinJoy991** [iChun/Morph#1263]
I found a bug when you from sunburn mob (skeleton), while burning, then change to pumkin spirit, it create infinity Seared Spirit mobs (many many...)
Version minecraft 1.16.5.  mod 10.2.1 Forge

**Comment by Natedogwoooof** [comment]
First thing is spell pumpkin right 2ed is list your mods and post crash report if u crashed and post a log

**Comment by ShinJoy991** [comment]
Oh I forgot, its modded mob called Born in Chaos, the mob (name Pumpkin Spirit) that will change to other mob (Seared Spirit) when on fire, and the morphing stage treate player as Pumpkin Spirit so it constantly spawn Seared, yeah I think it just a mod behavior, it was not crashed, I will restrict player morph to it. Thanks

**Comment by iChun** [comment]
> Oh I forgot, its modded mob called Born in Chaos, the mob (name Pumpkin Spirit) that will change to other mob (Seared Spirit) when on fire, and the morphing stage treate player as Pumpkin Spirit so it constantly spawn Seared, yeah I think it just a mod behavior, it was not crashed, I will restrict player morph to it. Thanks

Likely a mod conflict, yeah. Morph does have to simulate an entity at the player's position, but if the Pumpkin Spirit is created in a manner that it'll combust right away then I'm curious if it's something that can be sorted through mod compatibility support.

@Natedogwoooof please watch your tone, that was not appropriate.
