### ISSUE TITLE
It's possible to make a own morph from .json model? 

### ISSUE THREAD

**Issue by ElgerElg** [iChun/Morph#1267]
Hello! I don't understand about models and how they made, but maybe somebody know how to make morph to .json model?

**Comment by ElgerElg** [comment]
Maybe where has a tutorial?

**Comment by iChun** [comment]
Unfortunately not. Morph works by using entity instances to render them as morphs. To have a morph using a custom model would require coding that in using the model system that doesn't use JSON at this point in time, I'm afraid.
