### ISSUE TITLE
Abilities MC 1.6.4

### ISSUE THREAD

**Issue by Kiddabob** [iChun/Morph#1268]
Hi, I have recently started using my old MC 1.6.4 (Tekkit) server
I added the Morph mod ages ago. It was working fine until today. I had to try and fix the server since something I changed was causing issues and stopping it from loading. I ended up deleting the config folders and mods folders from both the client-side and server-side and starting fresh. After doing that I can't figure out how to enable the abilities. All of the other settings can work. I have been able to enable and disable the ability to bring up my GUI but the abilities just don't work. I have tried to link to the file using the custom path.

It is currently set to:
    # Redirect the mod to a different JSON patch location rather then the default patch hosted on GitHub.
    # If you would like to use the default, leave this blank.
    # This also affects NBTStripper.json.
    # If the link to your file is "https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/AbilitySupport.json", put "https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/", you cannot change the file name (eg: AbilitySupport.json) part of the link.
    S:customPatchLink=AbilitySupport.json

I have downloaded the .json file into both Client-side & Server-side config folders and the main Morph.cfg is an exact copy in each

**Comment by Kiddabob** [comment]
[Morph.txt](https://github.com/user-attachments/files/15942380/Morph.txt)
This is the whole file

**Comment by iChun** [comment]
![image](https://github.com/iChun/Morph/assets/2298444/4a972854-1f3d-4c1e-8122-4740fe7a786d)

Also you realise how old this version of the mod is, yes?

**Comment by Kiddabob** [comment]
do i add the "" around the link?

**Comment by Kiddabob** [comment]
I have it set like this now:

gameplay {
    # Enable mod mob NBT Stripping?
    # This support is mostly provided by the community and is not officially supported by the mod
    # The stripper was added to remove non-essential information from the Entity NBT to remove duplicate morphs.
    # 0 = No
    # 1 = Yes
    I:NBTStripper=1

    # Enable abilities?
    # 0 = No
    # 1 = Yes
    I:abilities=1

    # Requested by SoundLogic
    # Can you open the morph GUI?
    # 0 = No
    # 1 = Yes
    I:allowMorphSelection=1

    # Prevent players from acquiring these mobs as a morph.
    # Leave blank to allow acquisition of all compatible mobs.
    # Formatting is as follows: <class>, <class>, <class>
    # Example: am2.entities.EntityBattleChicken, biomesoplenty.entities.EntityJungleSpider, thaumcraft.common.entities.monster.EntityWisp
    S:blacklistedMobs=

    # Can you acquire boss morphs?
    # This is disabled by default due to morphing issues with mobs like the EnderDragon, Twilight Forest's Hydra and Naga, etc.
    # 0 = No
    # 1 = Yes
    I:bossMorphs=1

    # Can you sleep while morphed?
    # 0 = No
    # 1 = Yes
    I:canSleepMorphed=1

    # Can you acquire child mob morphs?
    # Disabled by default due to improper morph transitions
    # 0 = No
    # 1 = Yes
    I:childMorphs=1

    # Redirect the mod to a different JSON patch location rather then the default patch hosted on GitHub.
    # If you would like to use the default, leave this blank.
    # This also affects NBTStripper.json.
    # If the link to your file is "https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/AbilitySupport.json", put "https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/", you cannot change the file name (eg: AbilitySupport.json) part of the link.
    S:customPatchLink="https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/"

    # Disable the flight ability until a player...
    # 0 = Enable early game flight
    # 1 = ...has reached the nether
    # 2 = ...has killed the Wither
    I:disableEarlyGameFlight=0

    # Hostile Ability Distance Check for Hostile Ability Mode 4
    # You have to be *this* close before hostile mobs know you are not one of them.
    # Default: 6
    I:hostileAbilityDistanceCheck=6

    # Hostile Ability Modes
    # 0 = Off, hostile mobs attack you despite being morphed.
    # 1 = Hostile mobs do not attack you if you are a hostile mob.
    # 2 = Hostile mobs of different types do not attack you if you are a hostile mob but hostile mobs of the same kind do.
    # 3 = Hostile mobs of the same type do not attack you but hostile mobs of other types attack you.
    # 4 = Hostile mobs have a decreased detection range around you.
    # If you'd like to turn on Hostile Ability, I'd recommend Mode 2 (personal preference)
    I:hostileAbilityMode=1

    # Will you insta-morph into a new morph acquired?
    # 0 = No
    # 1 = Yes
    I:instaMorph=0

    # Will you lose your morphs on death?
    # 0 = No
    # 1 = Yes, all morphs
    # 2 = Yes, the morph you're currently using
    I:loseMorphsOnDeath=0

    # Can you acquire player morphs?
    # 0 = No
    # 1 = Yes
    I:playerMorphs=1

    # Force the mod to use the local copy of resources in the config folder?
    # This is meant for debugging purposes and for modified local mod mob abilities mappings/NBT stripper.
    # Do take note that mappings server and clientside are not synched so both ends will require the same mappings.
    # 0 = No
    # 1 = Yes
    I:useLocalResources=0

and it still doesn't have the abilities

**Comment by iChun** [comment]
If I remember right - the old config files didn't need quotes around strings, but you're missing the point - you're asking for help/support for a version of Minecraft that came out >10 years ago. I no longer provide support for versions of mods that old.

**Comment by iChun** [comment]
Have a read of the log files, tinker with the config, etc but please don't ask for any further help here - this version of the mod is over a decade old

**Comment by Kiddabob** [comment]
It was having "" around the URL causing the issue. I know I was asking a lot but the config didn't say to use them or not XD
