### ISSUE TITLE
Morph Mod Config 

### ISSUE THREAD

**Issue by RolloHB99185** [iChun/Morph#128]
First, I do not really understand why those keys must be so weird-placed :P
whatever, I want to change the key:
"Key Code to go down on the selector"
But the default is   [   and there's no list of the numbers that I could put instead of that..
and I don't know what numbers I can put to change the keybind.
can you put a list on the config of every keybind "ID" or tell me directly here?

**Comment by hron84** [comment]
@iChun I have same issue, however 0.9.1 does not generate default keybindings in the morph.cfg. How can I specify keybinding now?

**Comment by iChun** [comment]
Keybindings are in iChunUtil-keybinds.cfg

**Comment by hron84** [comment]
@iChun is there a chance this mod will get a section under MC Controls setting?

**Comment by iChun** [comment]
Most unlikely. Last time I added a hook in there I had some people complain
about it.

**Comment by Kender6000** [comment]
Hey, i don't play minecraft anymore and i don't remember how to stop
getting these emails.Could you work some magic and get me off the list so i
don't recieve these anymore? Pretty please?

**Comment by iChun** [comment]
Click the unfollow button on the page of the issue.

**Comment by Kender6000** [comment]
And, uh where could i do that? As I said, i don't play minecraft and have
not for over half a year now. So if you could send me a link or something,
i would love you

**Comment by iChun** [comment]
Go to the issues page. It's linked on every email you get. -_-

**Comment by Kender6000** [comment]
Alright, thanks for helping. And sorry for being a hassle

**Comment by itzKailo** [comment]
@iChun Theres an issue with my Server... Everytime youre leaving the Server and then rejoining it, you lose every Morph you had... It is the same in singleplayer. sry for bad english, help me pls

**Comment by iChun** [comment]
What version of Morph?

**Comment by itzKailo** [comment]
its a beta but dont know exactly

**Comment by iChun** [comment]
I stopped marking Morph as a beta after 1.7.10, sorry but your MC 1.7.10 is
no longer supported.

**Comment by itzKailo** [comment]
@iChun would it work with a newer version of Morph or is it all of 1.7.10 which isnt supported

**Comment by iChun** [comment]
All of 1.7.10 isn't supported. The newer versions of morph use a different
system and do not encounter this issue.

**Comment by hron84** [comment]
@itzKailo 1.7.10 lost support from large part of modding scene since it came out at 2014 (5 years old!). 

If you encounter this issue in a prebuilt modpack, try to disable Morph mod if this issue is so annoying, if not, consider upgrading to 1.12 where a lot of issues are fixed not only in Morph but in other mods.
