### ISSUE TITLE
I can't open the GUI, nor can I find the Config file. 

### ISSUE THREAD

**Issue by TineCroi** [iChun/Morph#131]
I am insanely confuzzeled

**Comment by KitKatPanda** [comment]
> I just figured it out, nothing was wrong with the mod.

Could you by chance let us know what was wrong? I'm using an updated version, for 1.7.10, and I'm unable to open the gui with the [ ] buttons. I can open the favorites wheel, so Ik it's installed, but Idk how to open the gui to view my morphs..
