### ISSUE TITLE
Not able to morph to enderdragon

### ISSUE THREAD

**Issue by mcqwertycreeper** [iChun/Morph#169]
I killed the enderdragon to morph into it, but it didn't work. i don't know if I had an older version or something, but it didin't work. I used Beta 0.3.0 of the mod in minecraft 1.6.2. I hope you can do something with it

**Comment by Kbm003** [comment]
I can't find the Morph.cfg file in config. I can only find it in the server config section and that doesn't have the bossMorphs option. also does this apply to endermen?

**Comment by iChun** [comment]
This issue is almost 9 years old. Please don't nerf old and closed issues, if you're having a problem make a new issue.
