### ISSUE TITLE
i can not fly at all by morphing into mobs!

### ISSUE THREAD

**Issue by NightHound12** [iChun/Morph#349]
hey iChun, you done an incrdible mod but i have this problem with it in which i can not fly with any mob. for example , i aquired a butterfky morph from mo creatures mod and it has the flight ability and i press space like in creative buy i cant fly . ive tried multipule times with other mobs and i cant fly with every single one of them . i cant fly at all. 
can you help me cuz i want to be able to fly again.

**Comment by waterghosteus** [comment]
So my problem is the same but i can't see any icons not the walk up blocks not the fly not the burn in day you failed with this mod I checked the configs turned abilities off then on and that didn't fix it either so you failed at making a mod you are famous for me and my brother are raging as NONE of the abilities work

**Comment by Jen7NZ** [comment]
I solved my problem by getting rid of a mod that also enabled flight...might want to remove any mods that give flight and see if that works?

**Comment by jarmi24** [comment]
My problem is that some mobs are able to fly, but some aren't. It's really weird. Some flying mobs have the flying icon and some don't. All things in the Config are on. Plz help!

**Comment by mineyea** [comment]
So I have the mod and the abilities don't show up when I look through my morphs (basically they don't work) and I saw you said something about a config folder and I'd like to know exactly how to fix this.

**Comment by raidenc04** [comment]
I have an urgent question. I can morph into a mob and fly but it is constantly flying in one direction and is impossible to stop it, and when you come into contact with a block you start glitching into it. I REALLY need help on this, so people can fly on my server.

**Comment by larrylemoncakes** [comment]
i cant fly either i know its ten years later and i may not get a response but i went into the config and it is all jibberish i dont know if its because i opened it in note pad to try fix this problem but could i get some help please.

**Comment by iChun** [comment]
If you have to necro a 10 year old issue you're better off making a new issue. Be wary of https://github.com/iChun/Morph/issues/878
