### ISSUE TITLE
When Morphing to an animal, Set Smart Moving to disabled

### ISSUE THREAD

**Issue by Razorskills** [iChun/Morph#362]
Basically if someone has smart moving installed, it messes with the animals swimming and crouching and such. When laying down as a chicken, it puts you in the block bellow you.

When Changing gamemode (survival,creative) it is able to change the smart moving settings. So Why not morphing? This would be an awesome feature and would be a great mod to help support!

Heres a link to smart moving if you haven't used it before: http://www.minecraftforum.net/topic/361430-164smp-smart-moving/

edit:

I also made a post on the smart moving page and you can read it here http://www.minecraftforum.net/topic/361430-164smp-smart-moving/page__st__7400#entry28394342

I really hope this can be fixed easily!

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
