### ISSUE TITLE
Some weird glitches when using Noppes' mods

### ISSUE THREAD

**Issue by CliffracerX** [iChun/Morph#405]
1: Super incompatible with More Player Models, morph's rendering takes a higher priority maybe?  Kinda a bummer, can't even use sitting/laying down and stuff (although that might be a weird glitch with some other mod, no idea).  Also noticed today that MPM takes a higher item rendering priority, causing held items to glitch out.  This may be an issue on Noppes' part and therefor only Noppes can fix it.
2: You can morph into Custom NPCs (yay), but on your client most NPC models will be moved down so it looks like you're a head sticking out of the ground.  -_-  Works fine for other players though.
3: Custom NPC issues again, a great deal of the NPC settings are not noticed by Morph.  For instance, my dragon NPC named Cliffie (Dragon) has fire resistance turned on, but it doesn't show up as a morph.

Ah well.  BTW, Morph is super-amazing.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
