### ISSUE TITLE
List of mods conflicting with Morph's flight ability.

### ISSUE THREAD

**Issue by iChun** [iChun/Morph#457]
By Conflicting.. I mean prevents the flight ability from working, NOT a mob that should fly but doesn't.

These are the few known mods that had, at one point, conflicted with Morph's flight. They may have been fixed since.

Rareores - http://www.minecraftforum.net/topic/1711724-164-forge-universal-rareores-version-17/
Superheros Unlimited
Divine Rpg
Iron Man Armors Mod
Mario Mod

It CANNOT be fixed Morph's side as Morph only sets flight when it needs to. You need to tell the conflicting mod not to set flight when they're not supposed to (like on every tick or something). If they have issues still you can ask them to contact me here or on IRC.

**Comment by blanas** [comment]
i have found that the survival wings mod won't let you fly.

**Comment by koaps** [comment]
SmartMoving

It overrides how flying works, I tested if setting:

# To switch on/off smart flying
move.fly:false

in smart_moving_options.txt fixed it and it didn't. 
I had to disable to disable the mod for now.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
