### ISSUE TITLE
Bugging with lights and etc.

### ISSUE THREAD

**Issue by vavraCZe** [iChun/Morph#473]
Bug with lights from redlogic mod. (sometimes)

Player bug (after 2x - 3x change morph (1 player on server) then other player have this glitch or bug):
https://dl.dropboxusercontent.com/u/8167722/2014-04-12_18.59.18.png

https://dl.dropboxusercontent.com/u/8167722/2014-04-13_12.20.40.png

Version: 0.7.1
Server based on MCPC+

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
