### ISSUE TITLE
Hotbar GUI issue when morphing.

### ISSUE THREAD

**Issue by Crafter102012** [iChun/Morph#479]
I have had a few problems with the morph mod. Before I installed it, my gui would look like this: 
![2014-04-23_17 26 16](https://cloud.githubusercontent.com/assets/7381225/2774256/e86e7698-cab2-11e3-9754-958cbd146e6b.png)
But when I installed it, every 10 seconds it goes like this: 
![2014-04-23_17 26 34](https://cloud.githubusercontent.com/assets/7381225/2774259/f8921e9e-cab2-11e3-8396-ec798784c16d.png)
And sometimes fluids like lava and water will disappear too. Is this a bug with the morph mod? Or a conflict? Or from another mod? Please help!

P.S. The mods I have installed: 

Zan's minimap 1.6.4
Morph-beta-0.1.0 
Not Enough Items 1.6.4
Optifine 1.6.4
iChun Util 2.4.0
Damage Indicators 1.6.4
EnchantView 1.6.4
Enchantments Plus 1.6.4

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
