### ISSUE TITLE
Mob Models Misshapen after Morph 0.7.1 

### ISSUE THREAD

**Issue by Techition** [iChun/Morph#496]
So many M's, anyways! I am using Morph Beta 0.7.1 and I have noticed that many of the mob models will end up with their polygons in a twist. This also occurs at times with the player model (An occurrence I have nicknamed "Legs") where the arms, head and torso all use the same texture as the legs of the avatar skin. I have seen everything from repeated textures, polygonal chaos and invisible mobs after morphing into them. 

This first happened in a heavily modded world. I thought "Maybe the mods are conflicting." so I started up a new world with only the morph mod installed and, while it took a bit longer to happen, sure enough, I morphed into a cat at one point and ended up as just a floating tail. As funny as this may be (Trust me, I've had a few good laughs about this) it can become an issue when hostile mobs end up invisible due to it since it doesn't affect just the model in use by the player but all models of that type. Morphing into something else sadly doesn't fix the messed up models, they remain disfigured and morphing more just worsens it. If it just effected the player it would be tolerable because the functionality would still be there but, since it effects all mobs using that model, well, being attacked by a horde of invisible zombies/spiders/etc is a bit less tolerable.

When this occurred I had not messed with the config file or the coding of the mod itself. It was tested in both heavily modded and exclusively morph modded environments. It is less likely to occur on the first few morphs however morphing back and forth makes the issue show up. It has occurred both in single player and multiplayer for me. When in multiplayer even the other people morphing will cause this issue on my end.

Technical Info:
Forge version: 9.11.1.965
Morph Version: Beta 0.7.1

So far I've not found anyone else having this issue so I'm really trying to figure out what's causing it and how to fix it. When it came to install I just dropped the morph mod zip folder right in the mod folder the way you normally install mods so this has me a bit stumped.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
