### ISSUE TITLE
Seeding Thermal Expansion Blizz

### ISSUE THREAD

**Issue by bufothetoad1** [iChun/Morph#519]
Ok so I took a shot at seeding the blizz. This is what I got and it did not work:

```
"thermalexpansion.entity.Blizz.name": [
  "hostile",
  "fly|true",
  "swim",
  "fallNegate"
],
```

alternately I am going to try these 3 things and see if any fixes it:

```
"entity.Blizz.name": [
  "hostile",
  "fly|true",
  "swim",
  "fallNegate"
],


"entity.Blizz.class": [
  "hostile",
  "fly|true",
  "swim",
  "fallNegate"
],


"thermalexpansion.entity.Blizz.class": [
  "hostile",
  "fly|true",
  "swim",
  "fallNegate"
],
```

if you know that any of these will work let me know.

**Comment by RikuSS4** [comment]
If anyone is still looking for this. In 1.7.10. It is actually "cofh.thermalfoundation.entity.monster.EntityBlizz"
So it would look something like this in AbilitySupport.json:
  "cofh.thermalfoundation.entity.monster.EntityBlizz": [
    "hostile",
    "fly|false"
  ],
You can add it to a custom AbilitySupport.json file. Then change S:customPatchLink= in Morph.cfg to point to where it is. EntityBasalz and EntityBlitz are the other 2.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
