### ISSUE TITLE
Morphing into the TC Pech causes it to render in the ground.

### ISSUE THREAD

**Issue by iChun** [iChun/Morph#521]
http://i.imgur.com/qERYhg7.png

**Comment by KingR17** [comment]
The morph animation shows the proper height, but when the textures are loaded to the model, it appears in the ground (it jumps from proper height with the gray particles of morphing to in the ground with proper texture).

**Comment by jadejutsu07** [comment]
It only happens with custom npc or other non native minecraft mods.
I did so badly want to be a baby enderman.....Dont ask! lol

**Comment by KILLER-CHIEF** [comment]
![mod mob model offset bug](https://dl.dropboxusercontent.com/u/51958998/Halocraft/morph%20mob%20model%20bug.png)
There are no issues in first person, only 3rd.
It seems I'm still getting this issue in my mod also (Halocraft). Is there something i should change to fix it? The mobs model/render code is heavily based off the player's fyi. I briefly tinkered around with the mobs getYOffset function but makes no difference, and setting yOffset in constructor causes client side mob to glitch up and down (but didn't get the chance to test with morph as having trouble setting up morph workspace).

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Comment by iChun** [comment]
i think this was fixed anyways with the abolishment of the ySize factor in MC, and it was probably addressed in the newer Morph versions for 1.7.10 but this issue was never closed
