### ISSUE TITLE
Screen goes dark...

### ISSUE THREAD

**Issue by 1iamtheone1** [iChun/Morph#525]
So when i morph back to my player my screen goes darker than it usually is. I tried everything and only goes back to normal if im in morph. It also haves my player hand if i morph into anything.

Please help,
iamtheone

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
