### ISSUE TITLE
Health Is Acting Odd With Other Mods Mobs

### ISSUE THREAD

**Issue by Dakotsie** [iChun/Morph#575]
Health of other mods mobs tends to act odd. On a mob that had 10 health points or 5 hearts, when morphing to that mob I only get 2 and 1/2 hearts. On a very rare occasion after taking damage, the health will heal back to a total of 5 hearts but only 3 hearts will show because the health was originally 2 and 1/2. If the health does go back to 5 hearts, if you take damage, the health bar will flicker as if healing but the extra hearts don't appear. Other mobs from mods will have reduced health. One for example, has 36 health points, but I only get a total of 5 hearts. I have only gotten the correct amount of health but with missing hearts once, so I don't know if this happens with other mobs. Just for reference the only other mod I have installed Fossils And Archeology Revival. I have the latest version of Morph, Util, and the recommended forge. It is kinda hard for a screen shot to show this, but if you need one, let me know.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
