### ISSUE TITLE
Suffocation under 1 block high mobs is back.

### ISSUE THREAD

**Issue by JohnFreemason** [iChun/Morph#583]
This is for morph beta 0.7.2 in minecraft 1.6.4.  Any morph that is 1 block high still suffocates under walls with 1 block above you.

Previous issue: #168

**Comment by SportsFan10** [comment]
I can confirm, that after removing ars magica and animation api the morphs worked correctly.  Tinkers Construct was installed when it was working.

**Comment by stephenmc608** [comment]
Geez, talk about Necro-post.
Anyway, Mithion released a new version of AM2 that fixed the issue.
https://twitter.com/Mithion13/status/563764652413173760
