### ISSUE TITLE
removeAllPlayerMorphsExcludingCurrentMorph doesnt work

### ISSUE THREAD

**Issue by Cestis** [iChun/Morph#595]
Hi. This method is doing totaly nothing. I tried to cast this in my child mod, but with no result. When you die, Morphs are not removed (option set to true in config). Same with /morph clear command. It doesn't work it's just demorphing!
Please fix this as soon as you can, or at least give me the method to cast (I want to delete all player's Morphs).

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
