### ISSUE TITLE
If you absorb CustomNPC, it's invisible after respawn.

### ISSUE THREAD

**Issue by Cestis** [iChun/Morph#598]
...and still able to kill you if aggresive.

I dont want my players to absorb them at all (i disabled Morph GUI), so could you please add absorbing morphs configurable?

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
