### ISSUE TITLE
Almost invincible while morphing, 1.7.10

### ISSUE THREAD

**Issue by HerrFolgreich** [iChun/Morph#607]
While morphing to a creature with different max hp than the one currently in, taken damage is not accounted for when the transformation is complete. I did not test this with damage higher than the current hp (creeper explosions etc.) though.

**Comment by iChun** [comment]
I'm gonna leave this open as a reminder for when I reimplement Morph's Health Balancing for 1.12.2

**Comment by iChun** [comment]
Not an issue anymore since Morph is using the attributes system for this.
