### ISSUE TITLE
Horse Morph Always Looks Down

### ISSUE THREAD

**Issue by ghost** [iChun/Morph#61]
When you morph into a horse, no matter what, the horse head will always look down.
![2013-08-18_22 28 33](https://f.cloud.github.com/assets/4017447/984243/aaa1c9e4-0890-11e3-86b2-935a3141f50e.png)

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
