### ISSUE TITLE
Issues when used with Ars Magica 2

### ISSUE THREAD

**Issue by zloebl777** [iChun/Morph#618]
When Morph and AM2 are installed together, there is an issue with player modeling and the player hitbox.  When Morphed into a form of a different size than the player form, the game still sees you as being two blocks tall.  This means that smaller forms (like bats) can fit into one block spaces, but will take suffocation damage.  This also means that the game thinks the player is looking somewhere they are not because it is assuming the player is two blocks tall.

This bug can be replicated with just AM2, iChunUtil, and Morph present in a world.  Removing AM2 fixes the issue with Morph.

This is reported on Mithion's bug tracker here: https://github.com/Mithion/ArsMagica2/issues/927

**Comment by iChun** [comment]
There is nothing I can do about this since Ars Magica forces the setSize all the time therefore it's the one overriding Morph's setSize. I'm afraid you're pretty much out of luck unless someone releases an unofficial fixed version of AM2.
