### ISSUE TITLE
[Feature] Invert Hostile Mob overrides

### ISSUE THREAD

**Issue by TeamSpen210** [iChun/Morph#622]
Currently, hostile mobs can be set to ignore the player if they are hostile, but what about the reverse? Snow / Iron Golems should aggro on you if you are a hostile mob (using the same rules that regular encounters provide). If you are a sheep or skeleton wild wolves should attack you.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
