### ISSUE TITLE
unintended movement while morphing to/from sheep [1.7.10] [morph 0.9.1]

### ISSUE THREAD

**Issue by Vritra22189** [iChun/Morph#625]
whenever i morph to/from sheep, my character won't standstill, 
sliding towards the northwest direction horizontally, and is very possible to stuck and suffocate myself into hills, walls, caves.
i figure out that when i morph other>sheep or sheep>other, i am displaced -6 blocks in x and -6 blocks in z direction.
and if i morph between different color sheep, i am displaced -12 blocks in x and -12 blocks in z direction.

so i guess it is the sheep morphing that cause the problem, and morphing within sheep is doubling the problem (demorph from sheep + morph to sheep)

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
