### ISSUE TITLE
One Block High Mobs suffocate in one block high spaces [MC 1.7.10, Morph 0.9.1]

### ISSUE THREAD

**Issue by andy1922** [iChun/Morph#627]
As a bat, I suffocate in one block high spaces even though I am one block high. Also, the aim is off. If i aim at a block in front of me, it mines the one above it.

**Comment by Gunner76th** [comment]
This issue has been all but 100% confirmed to be a mod conflict with Ars Magica 2. My server has morph and prior to adding AM2, we did not have this issue. After having added AM2, using morphs has become basically unusable between the fact that no matter what morph you are in you suffocate if your head touches a block, and the fact that you have to look 1-1.5 blocks below the block you want to interact with. I have posted a bug report about this issue on both this github as well as the one for Ars Magica 2. With Mithion having announced that the update/release on Dec 24 will be the last one he does, as he plans to stop doing mods, it is unlikely that AM2 will be updated anytime in the near future to address this issue. 

https://github.com/Mithion/ArsMagica2/issues/988

https://github.com/iChun/Morph/issues/662

**Comment by iChun** [comment]
There is nothing I can do about this since Ars Magica forces the setSize all the time therefore it's the one overriding Morph's setSize. I'm afraid you're pretty much out of luck unless someone releases an unofficial fixed version of AM2.

**Comment by Gunner76th** [comment]
Mithion commented 12 hours ago
"The shrink spell now properly tracks your height in 1.4.0.007 (dev).
As a workaround (or if for some reason it still doesn't work), disabling the shrink spell via config will also prevent AM2's size modifying code from running."
