### ISSUE TITLE
Player specific wither kill config for flight not working

### ISSUE THREAD

**Issue by tterrag1098** [iChun/Morph#628]
```
# Disable the flight ability until a player...
    #0 = Enable early game flight
    #1 = ...has reached the nether
    #2 = ...has killed the Wither
    # 
    # Min: 0
    # Max: 2
    I:disableEarlyGameFlight=2

    # Disable Early Game Flight Mode
    #0 = Serverwide toggle
    #1 = Player specific toggle (Every player has to travel to the nether/kill a wither to get flight for themselves)
    # 
    # Min: 0
    # Max: 1
    I:disableEarlyGameFlightMode=1
```

Running forge 1231 on a cauldron server.

Modlist: https://github.com/TPPI-Dev/TestPackPleaseIgnore2/blob/Development/ModVersions.txt

**Comment by Grovert11** [comment]
Have you ever looked into this again, it isn't working for me either...

**Comment by micle546** [comment]
still broken as of  0.9.2-beta on forgecraft modpack

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
