### ISSUE TITLE
Too many morphs leads to playerdata bloating, causing other crashes

### ISSUE THREAD

**Issue by WesCook** [iChun/Morph#629]
There's an issue right now where if you have Father Toast's Special Mobs installed, all mobs are randomized (height, health, etc).  This means every kill results in a unique morph.  I assume the same is true of similar mods so I won't single them out, but it leads to very large morph lists.  This isn't the bug I'm reporting though.

Having very large morph lists means large player files.  Once a player file reaches a certain size, other mods (such as Sync) will crash catastrophically when they try and send the player file.

![minecraft 1 7 10-000112](https://cloud.githubusercontent.com/assets/792101/4782118/3b6ab46c-5cdd-11e4-8ac0-0e6aa4444cff.png)

There's a packet limit in Forge and it will crash the client, and in the case of Sync prevents anyone from connecting to the server.  It seems the only fix is to delete the region file and playerdata when using a dedicated server.  With a SSP world (singleplayer), I found there was no fix - the problem seemed rooted in the level.dat file.  Perhaps that's where Morphs are saved in SP?

After I trimmed my player.dat file of Morph data, it was reduced from 36KB > 15KB and I could use Sync shells again.

I know the solution in this case is to simply disable Morph or Special Mobs (or add a blacklist) and that's fine.  This bug was extremely difficult to track down though, and can lead to serious server crashes if one is not careful.  My suggestion would be to add some sort of additional check in Morph where if the player file is above a certain size (32K I believe), stop saving new morphs and alert the player or console that they need to trim their morphs.

Thank you.

**Comment by dpsman917** [comment]
i can confirm this as an issue still in april 2015 but instead of crashes the server started tick lagging whenever a player with over 500 morphs droped items(im assuming the larger player files means larger load fir the server whenever a player does somthing) using nbt explorer i deledeted every players morph and each of the player dat file sizes went from 100kb - 8kb and fixed my tick lag i am black listing the special mobs morphs THANK YOU SquareWheel i did a NEI dump and could not find father toasts entities they were not there :C only run in to this with special mobs

**Comment by iChun** [comment]
I'll be working on fixing this with a variants system in 1.8

**Comment by dpsman917** [comment]
Awesome thank you for your fast reply!!

**Comment by Defiancey** [comment]
Hey dpsman917 can you explain how you blacklisted special mobs? I want to use that and Lycanite's Mobs but its giving me too many mobs.

**Comment by iChun** [comment]
It only took 3 years but it's done now. I can finally close this! :)

**Comment by dpsman917** [comment]
Woooooo thank you ichun!!!!!
