### ISSUE TITLE
black/white list is not working

### ISSUE THREAD

**Issue by eoistana** [iChun/Morph#639]
I have added a list of players to the 
S:blackwhitelistedPlayer=xxxx, yyyy
-setting in the config, and set
I:listIsBlacklist=1

But, everyone can still morph and gain new forms.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
