### ISSUE TITLE
WAILA problem with small mobs

### ISSUE THREAD

**Issue by Chubbychunks01** [iChun/Morph#646]
Version 0.9.1 for 1.7.10.
When morphing into mobs with the same height as the player, WAILA works fine, but when turning into a smaller mob, like a bat, the WAILA only shows the block you are standing on. It's not game-breaking or anything, but really annoying.

**Comment by iChun** [comment]
Didn't WAILA already fix this a while ago?

**Comment by iChun** [comment]
Pretty sure Waila has fixed this ages ago, since prof has been talking to me about it too.
