### ISSUE TITLE
Perspective issue with 1block high mobs

### ISSUE THREAD

**Issue by Lankoran** [iChun/Morph#656]
I've recently changes packs from DNSTech Pack to the TolkienCraft 2 pack, and copied my Morph settings over, but for some reason in TC2, whenever i use a small mob the perspective of my cross hair is off. Not only for WALIA as in other posts here. but also for block breaking, its as though my headheight remains the same regardless of the morph. 

Is this a config thing or a version change thing? is there anyway i can fix this?

**Comment by GameSlayar** [comment]
It's usually a problem with Ars Magica 2. Until they get updated, I'm afraid it's a problem.

**Comment by iChun** [comment]
I'm not sure about this but I have a feeling there's a mod overriding the eyeHeight of the player. There's not really much I can do about it unless you identify the mod that's doing this

**Comment by iceking1200** [comment]
Just tested the tolkiencraft pack without Ars Magica 2 and that fixed the perspective and the suffocating  
in a block above you problems.

**Comment by iChun** [comment]
Use Morph 0.9.2, it has a config that constantly forces the size and height of the player as a workaround for this issue.
