### ISSUE TITLE
Conflict with Transformers Mod by Fiskfile (MC 1.7.10)

### ISSUE THREAD

**Issue by Nuaman** [iChun/Morph#658]
As the name says, there is a believed conflict with the Transformers Mod. What I think was going on is the game was trying to transform (Transformers Mod) a sheep (Morph), but the armor wasn't displayed, so it couldn't transform and the game was confused.

Edit: 
Looking at this now, the assigned render is... Galacticraft? 
Edit 2: Don't click the links, because the don't do anything.
Crash Report:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/31/14 3:19 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
    at fiskfille.tf.render.entity.EntityRendererAlt.getOffsetY(EntityRendererAlt.java:105)
    at fiskfille.tf.main.ClientEventHandler.onRenderPlayerPre(ClientEventHandler.java:91)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_192_ClientEventHandler_onRenderPlayerPre_Pre.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
    at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
    at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1008)
    at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:351)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_294_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:992)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at fiskfille.tf.render.entity.EntityRendererAlt.getOffsetY(EntityRendererAlt.java:105)
    at fiskfille.tf.main.ClientEventHandler.onRenderPlayerPre(ClientEventHandler.java:91)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_192_ClientEventHandler_onRenderPlayerPre_Pre.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)

-- Entity being rendered --
Details:
    Entity Type: OtherPlayers (net.minecraft.client.entity.EntityOtherPlayerMP)
    Entity ID: 516
    Entity Name: Nickobug
    Entity's Exact location: 160.50, 66.62, 252.50
    Entity's Block location: World: (160,66,252), Chunk: (at 0,4,12 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0.00, 0.00, 0.00

-- Renderer details --
Details:
    Assigned renderer: micdoodle8.mods.galacticraft.core.client.render.entities.RenderPlayerGC@1bea0814
    Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Rotation: 0.0
    Delta: 1.0
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
    at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
    at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1008)
    at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:351)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_294_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCEntityClientPlayerMP['Nickobug'/424, l='MpServer', x=163.92, y=83.62, z=306.62]]
    Chunk stats: MultiplayerChunkCache: 49, 49
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (160,64,252), Chunk: (at 0,4,12 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 10540 game time, 10540 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 51 total; [EntityZombie['Zombie'/4365, l='MpServer', x=-19.70, y=-3.62, z=-53.53], EntityZombie['Zombie'/3752, l='MpServer', x=3.61, y=-28.09, z=-52.23], EntityItem['item.item.egg'/6459, l='MpServer', x=154.00, y=73.13, z=316.25], EntitySheep['Sheep'/175, l='MpServer', x=115.50, y=82.35, z=235.50], EntitySheep['Sheep'/174, l='MpServer', x=115.50, y=83.35, z=232.50], EntitySheep['Sheep'/173, l='MpServer', x=112.19, y=83.35, z=233.50], EntitySheep['Sheep'/172, l='MpServer', x=113.78, y=83.35, z=233.50], EntitySheep['Sheep'/184, l='MpServer', x=146.50, y=68.00, z=365.50], EntitySheep['Sheep'/182, l='MpServer', x=117.50, y=73.00, z=265.50], EntitySheep['Sheep'/183, l='MpServer', x=119.50, y=73.00, z=266.47], EntitySheep['Sheep'/180, l='MpServer', x=112.38, y=72.00, z=267.53], EntitySheep['Sheep'/181, l='MpServer', x=119.50, y=73.00, z=267.78], EntitySheep['Sheep'/197, l='MpServer', x=118.81, y=70.35, z=254.50], EntitySheep['Sheep'/196, l='MpServer', x=118.78, y=70.35, z=253.31], EntitySheep['Sheep'/195, l='MpServer', x=118.53, y=70.35, z=251.47], EntitySheep['Sheep'/194, l='MpServer', x=117.22, y=70.35, z=254.50], EntitySheep['Sheep'/220, l='MpServer', x=197.66, y=85.00, z=269.53], EntitySheep['Sheep'/221, l='MpServer', x=149.16, y=80.00, z=272.06], EntitySheep['Sheep'/223, l='MpServer', x=165.22, y=76.00, z=308.59], EntitySheep['Sheep'/218, l='MpServer', x=173.81, y=81.00, z=261.78], EntitySheep['Sheep'/219, l='MpServer', x=184.19, y=78.00, z=257.50], EntityChicken['Chicken'/234, l='MpServer', x=154.49, y=74.00, z=314.72], EntityChicken['Chicken'/233, l='MpServer', x=159.56, y=74.00, z=315.61], EntityChicken['Chicken'/232, l='MpServer', x=160.47, y=76.00, z=310.53], EntityChicken['Chicken'/231, l='MpServer', x=153.53, y=78.00, z=305.59], EntitySheep['Sheep'/230, l='MpServer', x=161.47, y=72.00, z=330.27], EntitySheep['Sheep'/229, l='MpServer', x=154.63, y=70.00, z=327.97], EntitySheep['Sheep'/228, l='MpServer', x=155.47, y=70.00, z=326.47], EntitySheep['Sheep'/227, l='MpServer', x=152.38, y=71.00, z=327.63], EntitySheep['Sheep'/226, l='MpServer', x=162.45, y=81.00, z=312.72], EntitySheep['Sheep'/225, l='MpServer', x=151.88, y=79.00, z=301.91], EntitySheep['Sheep'/246, l='MpServer', x=186.13, y=77.00, z=360.78], EntitySheep['Sheep'/247, l='MpServer', x=196.09, y=79.00, z=366.22], EntitySheep['Sheep'/244, l='MpServer', x=194.38, y=77.00, z=362.88], EntitySheep['Sheep'/245, l='MpServer', x=192.50, y=77.00, z=361.50], EntityZombie['Zombie'/5724, l='MpServer', x=33.74, y=-53.88, z=-8.29], EntitySheep['Sheep'/305, l='MpServer', x=224.50, y=72.35, z=302.75], EntitySheep['Sheep'/304, l='MpServer', x=221.13, y=72.00, z=306.13], EntityChicken['Chicken'/307, l='MpServer', x=209.56, y=76.00, z=315.53], EntitySheep['Sheep'/306, l='MpServer', x=217.66, y=73.00, z=307.47], EntityChicken['Chicken'/309, l='MpServer', x=220.50, y=72.00, z=307.50], EntityChicken['Chicken'/308, l='MpServer', x=223.50, y=70.00, z=310.50], EntityChicken['Chicken'/310, l='MpServer', x=221.50, y=72.00, z=307.50], EntitySheep['Sheep'/303, l='MpServer', x=218.66, y=74.00, z=303.53], EntityTrail['unknown'/3053, l='MpServer', x=163.92, y=83.62, z=306.62], EntityZombie['Zombie'/3058, l='MpServer', x=-12.24, y=-15.62, z=-45.08], EntityZombie['Zombie'/4701, l='MpServer', x=-15.95, y=-12.52, z=-40.91], EntityItem['item.item.egg'/7317, l='MpServer', x=219.41, y=72.13, z=307.75], EntityItem['item.item.egg'/7291, l='MpServer', x=156.00, y=76.13, z=311.25], GCEntityClientPlayerMP['Nickobug'/424, l='MpServer', x=163.92, y=83.62, z=306.62], EntityItem['item.item.egg'/6724, l='MpServer', x=225.00, y=-39.93, z=309.91]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 264306328 bytes (252 MB) / 657215488 bytes (626 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:PermSize=512M -XX:MaxPermSize=768M -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 52 mods loaded, 52 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1277} [Forge Mod Loader](forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1277} [Minecraft Forge](forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    deconstruction{2.2.5} [The Deconstruction Mod]([MC1.7.10]deconstruction[v2.2.5].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core](CoFHCore-[1.7.10]3.0.0B9-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildMod{v1.0} [Build Mod](CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoroAI{v1.0} [CoroAI](CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtendedRenderer{v1.0} [Extended Renderer](CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ConfigMod{v1.0} [Extended Mod Config](CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.2.658-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.658-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftCore{3.0.6} [Galacticraft Core](GalacticraftCore-1.7-3.0.6.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftMars{3.0.6} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.6.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    planetguyLib{1.3} [planetguyLib](PlanetguyLib-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    planetguy_Gizmos{3.0} [Gizmos](Gizmos-3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraviSuite{1.7.10-2.0.3} [Graviation Suite](GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{4.1.2} [iChunUtil](iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Kenshiro{1.2.1} [Kenshiro Mod](KenshiroMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    KoadPirates{For minecraft 1.7.10} [Koadmaster's Pirates](KoadmastersPirates-0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.7.10R2.8.0RC6} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC6} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC6} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC6} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC6} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC6} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC6} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC6} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC6} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC6} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC6} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC6} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC6} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC6} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC6} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC6} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Minions{1.9.4} [Minions](Minions-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Paintball{1.7.10v1} [Paintball](Paintball-1.7.10v1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Torched{4.0.0} [Torched](Torched-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    transformers{0.4} [Transformers Mod](Transformers-1.7.10-0.4.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.7} [Waila](Waila-1.5.7a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.2.1277
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 8550G GL version 4.3.12618 Compatibility Profile Context 13.251.0.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
