### ISSUE TITLE
No permission whilst Trying to use /morph demorph @p in cmd block. (No Permission)

### ISSUE THREAD

**Issue by orangebeak** [iChun/Morph#660]
@iChun  It wont let me use "/morph demorph @p" in a command block. it says no permission, yet i'm on creative, with cheats. how do i fix it? I want the command block so when it activates, the nearest player is demorphed. Is there some workaround?

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
