### ISSUE TITLE
Bungeecord vanilla lobby in combination with ichun morph mod players stay morphed

### ISSUE THREAD

**Issue by Superjo149** [iChun/Morph#661]
https://github.com/SpigotMC/BungeeCord/issues/1323

Like seen on the issue above, my players are still in morph if they were on the modded server and kicked to the lobby. (in a bungeecord configuration) Is there a way for me to unmorph them when switching servers?

**Comment by Superjo149** [comment]
is there a possibility for someone to help me out?

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
