### ISSUE TITLE
Morph Emty List Server

### ISSUE THREAD

**Issue by AxelRod21** [iChun/Morph#664]
Hiya as another post I host a server with forge 1.7.10-10.13.2.1277. One of my friends had her Morph forms removed twice. I have the "Lose morph on death to false" I believe that the mod had trouble reading the morph data from server according to the error logs. I am reluctant to remove her player data.

The issue comes up around 20:41:30 mark from her client:
http://pastebin.com/embed_js.php?i=reR1Rtsv

Game logs from client and server
https://dl.dropboxusercontent.com/u/281028554/Server%20and%20client%20logs.zip

Also any help with other errors from the server and client would be appreciated. 

Thank you for your time. :)
Alex

**Comment by iChun** [comment]
Are you still experiencing this issue?
