### ISSUE TITLE
(0.9.1) Taking damage when morphed plays the player taking damage sound.

### ISSUE THREAD

**Issue by ariosos** [iChun/Morph#666]
Issue: Taking damage when morphed no longer plays the damage sound of that morph.

Steps to Reproduce:
1 - Morph into any mod. 
2 - Take damage.

Result: The player damage sound file is played.

Expected: The damage sound of that mob should play, not the player's damage sound.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
