### ISSUE TITLE
When i morph i don't keep it

### ISSUE THREAD

**Issue by MistyCoop24** [iChun/Morph#667]
i have the thing that you open that stores all your morphs in it but when i go to choose one of the morphs i have killed it dosen't work, i have the mo'creatures mod and the MCA mod  do they affect it?, i can turn into my siblings that have played my game in a diffrent minecraft accountbut that is about it.

**Comment by iChun** [comment]
Are you opening your Favourites menu (round gui) or the proper selector (squareish gui on the left side of the screen)
