### ISSUE TITLE
Morph closes when I open the Gui

### ISSUE THREAD

**Issue by vitorMg** [iChun/Morph#670]
When I try to open the Gui it says shutting down internal server andgives me this crash report:

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 20/01/15 18:44
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at fiskfille.tf.render.entity.EntityRendererAlt.getOffsetY(EntityRendererAlt.java:105)
	at fiskfille.tf.main.ClientEventHandler.onRenderPlayerPre(ClientEventHandler.java:91)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_51_ClientEventHandler_onRenderPlayerPre_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1008)
	at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:351)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_59_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:992)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fiskfille.tf.render.entity.EntityRendererAlt.getOffsetY(EntityRendererAlt.java:105)
	at fiskfille.tf.main.ClientEventHandler.onRenderPlayerPre(ClientEventHandler.java:91)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_51_ClientEventHandler_onRenderPlayerPre_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityOtherPlayerMP)
	Entity ID: 427
	Entity Name: Vitoray
	Entity's Exact location: 156,50, 66,62, 204,50
	Entity's Block location: World: (156,66,204), Chunk: (at 12,4,12 in 9,12; contains blocks 144,0,192 to 159,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0,00, 0,00, 0,00

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@12aad4c
	Location: 0,00,0,00,0,00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1008)
	at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:351)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_59_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Vitoray'/394, l='MpServer', x=80,70, y=67,62, z=307,65]]
	Chunk stats: MultiplayerChunkCache: 624, 624
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (156,64,204), Chunk: (at 12,4,12 in 9,12; contains blocks 144,0,192 to 159,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 20146 game time, 7540 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 120 total; [EntityCreeper['Creeper'/257, l='MpServer', x=145,50, y=25,00, z=366,50], EntityZombie['Zumbi'/260, l='MpServer', x=145,50, y=27,00, z=375,06], EntityCreeper['Creeper'/261, l='MpServer', x=158,50, y=31,00, z=381,50], EntityCreeper['Creeper'/262, l='MpServer', x=152,53, y=25,00, z=375,31], EntitySquid['Lula'/266, l='MpServer', x=142,66, y=47,00, z=367,41], EntityEnderman['Enderman'/23, l='MpServer', x=2,94, y=51,00, z=353,25], EntityTrail['desconhecido'/537, l='MpServer', x=80,70, y=67,62, z=307,65], EntityPig['Porco'/33, l='MpServer', x=16,88, y=63,00, z=249,97], EntitySkeleton['Esqueleto'/37, l='MpServer', x=10,50, y=44,00, z=350,50], EntityCreeper['Creeper'/38, l='MpServer', x=12,47, y=22,00, z=360,69], EntityEnderman['Enderman'/39, l='MpServer', x=27,91, y=23,00, z=337,50], EntityEnderman['Enderman'/40, l='MpServer', x=11,13, y=39,00, z=353,50], EntityCreeper['Creeper'/42, l='MpServer', x=7,34, y=50,00, z=365,91], EntityCreeper['Creeper'/43, l='MpServer', x=4,50, y=50,00, z=370,50], EntityPig['Porco'/48, l='MpServer', x=21,84, y=64,00, z=241,94], EntityItem['item.item.beefRaw'/816, l='MpServer', x=78,06, y=66,13, z=309,59], EntityPig['Porco'/49, l='MpServer', x=22,50, y=65,00, z=258,69], EntityPig['Porco'/50, l='MpServer', x=25,78, y=64,00, z=240,22], EntityCreeper['Creeper'/51, l='MpServer', x=28,70, y=32,92, z=349,69], EntityBat['Morcego'/52, l='MpServer', x=20,56, y=37,10, z=340,75], EntityBat['Morcego'/53, l='MpServer', x=30,31, y=40,10, z=337,25], EntityZombie['Zumbi'/54, l='MpServer', x=29,03, y=47,00, z=350,72], EntityCreeper['Creeper'/55, l='MpServer', x=27,89, y=33,15, z=349,70], EntityCreeper['Creeper'/56, l='MpServer', x=31,06, y=40,00, z=376,34], EntitySpider['Aranha'/57, l='MpServer', x=22,13, y=41,00, z=359,78], EntitySkeleton['Esqueleto'/569, l='MpServer', x=73,50, y=39,00, z=329,50], EntitySkeleton['Esqueleto'/58, l='MpServer', x=21,50, y=41,00, z=362,50], EntitySpider['Aranha'/59, l='MpServer', x=25,59, y=33,00, z=365,66], EntityCreeper['Creeper'/571, l='MpServer', x=74,50, y=39,00, z=329,50], EntitySpider['Aranha'/60, l='MpServer', x=27,47, y=33,00, z=362,72], EntityCreeper['Creeper'/572, l='MpServer', x=74,50, y=39,00, z=328,50], EntitySkeleton['Esqueleto'/61, l='MpServer', x=30,16, y=33,00, z=359,69], EntityBat['Morcego'/62, l='MpServer', x=39,88, y=39,07, z=367,56], EntityPig['Porco'/70, l='MpServer', x=42,53, y=68,00, z=230,34], EntityPig['Porco'/71, l='MpServer', x=38,44, y=66,00, z=234,69], EntityPig['Porco'/72, l='MpServer', x=42,50, y=64,00, z=232,50], EntityPig['Porco'/73, l='MpServer', x=46,81, y=63,00, z=249,50], EntityPig['Porco'/74, l='MpServer', x=33,88, y=63,00, z=241,06], EntityPig['Porco'/75, l='MpServer', x=40,84, y=64,00, z=251,44], EntityPig['Porco'/76, l='MpServer', x=34,47, y=65,00, z=257,50], EntityMinecartChest['entity.MinecartChest.name'/77, l='MpServer', x=46,50, y=39,50, z=329,50], EntityCreeper['Creeper'/78, l='MpServer', x=39,25, y=38,00, z=321,38], EntityCreeper['Creeper'/79, l='MpServer', x=44,00, y=39,00, z=327,34], EntityZombie['Zumbi'/80, l='MpServer', x=45,50, y=42,00, z=343,50], EntityBat['Morcego'/81, l='MpServer', x=44,25, y=42,10, z=338,59], EntityBat['Morcego'/82, l='MpServer', x=38,31, y=38,10, z=351,56], EntityZombie['Zumbi'/83, l='MpServer', x=43,59, y=38,00, z=353,13], EntityMinecartChest['entity.MinecartChest.name'/84, l='MpServer', x=40,50, y=39,50, z=368,50], EntitySlime['Slime'/85, l='MpServer', x=42,69, y=39,00, z=378,69], EntitySkeleton['Esqueleto'/86, l='MpServer', x=37,59, y=49,00, z=383,69], EntitySkeleton['Esqueleto'/87, l='MpServer', x=32,97, y=50,00, z=380,69], EntitySkeleton['Esqueleto'/88, l='MpServer', x=34,50, y=49,00, z=383,50], EntityCreeper['Creeper'/89, l='MpServer', x=32,03, y=50,00, z=379,72], EntityCreeper['Creeper'/90, l='MpServer', x=34,50, y=49,00, z=384,50], EntityPig['Porco'/94, l='MpServer', x=48,50, y=78,00, z=234,50], EntityCreeper['Creeper'/95, l='MpServer', x=50,06, y=35,00, z=287,84], EntityMinecartChest['entity.MinecartChest.name'/96, l='MpServer', x=63,50, y=40,50, z=334,50], EntityCreeper['Creeper'/97, l='MpServer', x=61,50, y=18,00, z=341,50], EntityMinecartChest['entity.MinecartChest.name'/98, l='MpServer', x=55,50, y=39,50, z=346,50], EntityMinecartChest['entity.MinecartChest.name'/99, l='MpServer', x=63,50, y=44,50, z=359,50], EntityMinecartChest['entity.MinecartChest.name'/100, l='MpServer', x=61,50, y=44,50, z=357,50], EntityMinecartChest['entity.MinecartChest.name'/101, l='MpServer', x=57,50, y=35,50, z=361,50], EntitySkeleton['Esqueleto'/102, l='MpServer', x=62,50, y=40,00, z=366,50], EntityZombie['Zumbi'/104, l='MpServer', x=59,06, y=14,00, z=381,50], EntitySkeleton['Esqueleto'/105, l='MpServer', x=58,41, y=13,00, z=386,63], EntitySpider['Aranha'/883, l='MpServer', x=33,50, y=34,00, z=356,50], EntitySkeleton['Esqueleto'/122, l='MpServer', x=78,34, y=41,00, z=334,97], EntitySpider['Aranha'/123, l='MpServer', x=69,50, y=39,00, z=334,50], EntityBat['Morcego'/124, l='MpServer', x=72,63, y=48,22, z=322,01], EntityZombie['Zumbi'/125, l='MpServer', x=70,50, y=13,00, z=350,50], EntitySkeleton['Esqueleto'/126, l='MpServer', x=79,16, y=41,00, z=351,63], EntityCreeper['Creeper'/127, l='MpServer', x=66,06, y=44,00, z=339,66], EntityCreeper['Creeper'/129, l='MpServer', x=66,50, y=19,00, z=364,50], EntityZombie['Zumbi'/130, l='MpServer', x=67,50, y=37,00, z=352,50], EntityZombie['Zumbi'/131, l='MpServer', x=42,31, y=38,00, z=354,69], EntityBat['Morcego'/132, l='MpServer', x=70,88, y=39,00, z=370,25], EntitySkeleton['Esqueleto'/133, l='MpServer', x=78,75, y=41,00, z=353,16], EntityBat['Morcego'/134, l='MpServer', x=48,44, y=41,05, z=356,78], EntityZombie['Zumbi'/135, l='MpServer', x=75,91, y=40,00, z=362,38], EntitySquid['Lula'/157, l='MpServer', x=99,55, y=47,00, z=284,56], EntityBat['Morcego'/158, l='MpServer', x=78,09, y=13,00, z=328,25], EntitySkeleton['Esqueleto'/159, l='MpServer', x=81,50, y=22,00, z=334,50], EntityCreeper['Creeper'/160, l='MpServer', x=87,00, y=36,00, z=364,56], EntityCreeper['Creeper'/161, l='MpServer', x=95,00, y=42,00, z=359,41], EntityMinecartChest['entity.MinecartChest.name'/162, l='MpServer', x=90,50, y=36,50, z=373,50], EntityCreeper['Creeper'/163, l='MpServer', x=91,38, y=36,00, z=369,72], EntitySquid['Lula'/168, l='MpServer', x=108,59, y=46,38, z=299,50], EntitySkeleton['Esqueleto'/169, l='MpServer', x=96,22, y=46,00, z=328,50], EntityClientPlayerMP['Vitoray'/394, l='MpServer', x=80,70, y=67,62, z=307,65], EntityZombie['Zumbi'/171, l='MpServer', x=105,28, y=50,00, z=344,16], EntityMinecartChest['entity.MinecartChest.name'/172, l='MpServer', x=97,50, y=29,50, z=365,50], EntityMinecartChest['entity.MinecartChest.name'/173, l='MpServer', x=96,50, y=42,50, z=369,50], EntityCreeper['Creeper'/182, l='MpServer', x=124,50, y=19,00, z=234,50], EntitySquid['Lula'/183, l='MpServer', x=119,56, y=47,00, z=302,50], EntityBat['Morcego'/184, l='MpServer', x=124,53, y=50,45, z=357,00], EntitySkeleton['Esqueleto'/185, l='MpServer', x=114,13, y=51,00, z=345,44], Entitychica['Chica the Chicken'/186, l='MpServer', x=113,88, y=18,00, z=363,00], EntityCreeper['Creeper'/187, l='MpServer', x=118,70, y=34,08, z=387,30], EntitySquid['Lula'/210, l='MpServer', x=137,03, y=57,34, z=267,31], EntitySquid['Lula'/211, l='MpServer', x=140,56, y=48,00, z=297,50], EntitySquid['Lula'/212, l='MpServer', x=135,50, y=48,00, z=305,50], EntitySquid['Lula'/213, l='MpServer', x=137,22, y=50,28, z=311,19], EntitySquid['Lula'/216, l='MpServer', x=137,81, y=50,38, z=315,28], EntitySquid['Lula'/217, l='MpServer', x=137,63, y=47,00, z=345,50], EntitySquid['Lula'/218, l='MpServer', x=141,41, y=47,34, z=342,69], EntitySquid['Lula'/219, l='MpServer', x=138,81, y=47,00, z=345,31], EntitySquid['Lula'/220, l='MpServer', x=143,41, y=47,34, z=337,56], EntitySquid['Lula'/221, l='MpServer', x=137,16, y=47,00, z=336,75], EntitySquid['Lula'/222, l='MpServer', x=136,50, y=47,22, z=344,44], EntitySquid['Lula'/223, l='MpServer', x=142,41, y=48,34, z=347,50], Entityfoxy['Foxy the Pirate Fox'/224, l='MpServer', x=138,22, y=31,00, z=366,69], EntityBat['Morcego'/225, l='MpServer', x=149,91, y=28,07, z=374,88], EntitySkeleton['Esqueleto'/226, l='MpServer', x=143,59, y=27,00, z=379,06], EntitySquid['Lula'/238, l='MpServer', x=141,97, y=55,00, z=265,50], EntitySquid['Lula'/240, l='MpServer', x=145,56, y=57,38, z=268,19], EntitySquid['Lula'/244, l='MpServer', x=144,53, y=53,34, z=297,66], EntityBat['Morcego'/247, l='MpServer', x=158,25, y=25,10, z=326,66], EntityBat['Morcego'/250, l='MpServer', x=141,94, y=27,89, z=352,44], EntityZombie['Zumbi'/253, l='MpServer', x=157,50, y=35,00, z=349,50], EntityZombie['Zumbi'/254, l='MpServer', x=156,63, y=36,00, z=347,88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 204773528 bytes (195 MB) / 408621056 bytes (389 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx512M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 8 mods loaded, 8 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod.ymt.air.HariboteAirCraft{172v3 hiten} [HariboteAirCraft] (AirCraft-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FNAFMod{1.2} [FNAFMod] (Five-Nights-at-Freddys-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	iChunUtil{4.1.2} [iChunUtil] (iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	transformers{0.4.4} [Transformers Mod] (Transformers-1.7.10-0.4.4 (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: GeForce 8400 GS/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Levare 1.7.x (1.8).zip]
	Current Language: Português (Brasil)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by gegy1000** [comment]
Uninstall the Transformers Mod

**Comment by vitorMg** [comment]
thanks!

**Comment by gegy1000** [comment]
This is fixed in 0.5.0 (Not released yet)!
