### ISSUE TITLE
Flying mobs still taking fall damage on landing

### ISSUE THREAD

**Issue by droppies** [iChun/Morph#671]
This issue started today after a reboot of the server. Whenever I am morphed to a flying mob (like a bat or a blaze) I still take fall damage when landing. The damage seems to be a total of all the blocks I have fallen in that flying 'session'

I.e. If I fly 50 blocks up, then fall 10 blocks down, then I fly a few blocks up again and fall another 10 blocks, If I then go and land (using the shift key) I will take the damage those 20 blocks would've given me (Which would be 16 hp or 8 hearts if I remember correctly)

edit:
Okay, I have been looking through the config to find if there maybe was an option for this, there was not. I added the support for boss mob morphs and rebooted the server, and now it seems to be working again. (I have not tested every mob yet, but thus far this bug has not happened again)

Here is the current config: http://pastebin.com/p4evu8Sg (The only thing I added between the bug happening and it being fixed was the ability to morph into boss mobs. Other than that nothing has changed on the server)

**Comment by droppies** [comment]
Okay, I have been looking through the config to find if there was an option for this maybe, there was not. I added the support for boss mob morphs and rebooted the server, and now it seems to be working again. (I have not tested every mob yet, but thus far this bug has not happened again)

Here is the current config: http://pastebin.com/p4evu8Sg (The only thing I added between the bug happening and it being fixed was the ability to morph into boss mobs. Other than that nothing has changed on the server)

**Comment by Slender2112** [comment]
I do not have this problem. I play Minecraft 1.7.10, so this issue might already be fixed.

**Comment by droppies** [comment]
I am playing on 1.7.10, and it seems to be a rare bug, since it was fixed with a server restart.

**Comment by iChun** [comment]
It's a mod conflict.

**Comment by droppies** [comment]
Okay, report closed.
