### ISSUE TITLE
Bad mod mob compatibility

### ISSUE THREAD

**Issue by Slender2112** [iChun/Morph#672]
The morphs for some mobs from other mods is a bit glitchy. This is really trivial, and I honestly don't expect this to be fixed, so take it with a grain of redstone I guess.

The first is a Mist wolf from Twilight forest. The mist wolf has 15 hearts of health, but morphing into a mist wolf changes your health to 4 hearts.

The second are the Ice cores from Twilight Forest, if you morph into one while wearing armor, it shows the armor even though the entity is not human. (not sure you can even do anything about this)

The third one is the Eldritch Guardian from the Thaumcraft mod. Along with the lack of extra health, morphing into one will phase your body into the ground, with only the head partly showing.

I am running Minecraft 1.7.10 in Kovacic's Mod Pack, and I will provide screenshots if you need them.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
