### ISSUE TITLE
Flight Inoperable

### ISSUE THREAD

**Issue by aravol** [iChun/Morph#673]
Playing in single player, kill a bat in survival, turn into bat, unable to fly.

Configurations set to enable early-game flight, remained inoperable after visiting the nether, killing a wither, and deleting and reacquiring the bat morph.

Using versions:
Morph: 0.9.1
iChunUtil: 4.0.0
Forge: 10.13.2.1230
Minecraft: 1.7.10

**Comment by iChun** [comment]
Mod conflict.

**Comment by iChun** [comment]
I have a list somewhere but it's probably buried in all the other issues by
now

**Comment by aravol** [comment]
Negative, not using any of the mods presented in Issue #457.
Will fetch the list of currently implemented mods

**Comment by aravol** [comment]
Using the following mods, as they appear in the main menu:

Mod|Version
---|---
Minecraft Coder Pack|9.05
Forge Mod Loader|7.10.85.1230
Minecraft Forge|10.12.2.1230
CodeChickenCore|1.0.4.29
Not Enough Items|1.0.3.74
SpaceCore|0.7.12
Survival Wings|1.2.6
bspkrsCore|6.15
StartingInventory|1.7.10.r03
The Twilight Forest|2.3.2
Forge Multipart|1.1.0.314
Chisel 2|2.3.3.28
GraveStone|2.11.1
IndustrialCraft 2|2.2.663-experimental
Nuclear Control 2|@VERSION@
iChunUtil|4.0.0
Mantle|0.3.2..jenkins184
Morph|0.9.1
Multi World|1.2.7
Natura|1.7.10-92.8a1150f
MrTJPCoreMod|1.0
ProjectRed (3 child mods)|4.5.8.59
Roguelike Dungeons|1.3.5
Greg's SG Craft|1.9.0-mc1.7.10
Torch Levers|1.4.1
Balkon's WeaponMod|1.14.3
Minecraft Multipart Plugin|1.1.0.314
Forge Microblocks|1.1.0.314

**Comment by iChun** [comment]
Any of those mods provide creative-like flight?

**Comment by aravol** [comment]
Survival Wings is nothing but craftable wings from feathers, and IC2 does
add jetpacks

**Comment by iChun** [comment]
IC2 doesn't conflict AFAIK, you can try removing survival wings and see if
the conflict is resolved.

**Comment by aravol** [comment]
Conflict is confirmed for Survival Wings. Have not confirmed for the given version of IC2 (but would be relatively surprised if it did)

However, attempting to resolve the conflict via key bindings does not seem viable - despite documentation in the configs for iChunUtil, there does not seem to be a keybinding option in the options Menui. Will double check that.

Notably the psuedoflight given to Squid forms works fine.

**Comment by aravol** [comment]
On wrong click and it's "closed" - reoslved, I guess, but will open a bug about the keybinding configuration if we can't get it working
