### ISSUE TITLE
Most morph not in prober hit box (Morph-Beta-0.9.1) I found it, it's am2 making the conflicts

### ISSUE THREAD

**Issue by Gamingdaredevil** [iChun/Morph#674]
when I'm morph my hit box for breaking blocks is wrong its one above where the black square is. and I take damage when in air block which is one below a solid block.
I have now done some testing and it an2 making this hotbox conflict, so a new version on am2 needs to come out to fix this!! Sorry to annoy you Ichun in your stream 
Morph-Beta-0.9.1

**Comment by ignisthedragon** [comment]
here is the link to the bugreport on github at mithons project page for thoose of you who are interessted: https://github.com/Mithion/ArsMagica2/issues/1140
