### ISSUE TITLE
Ability strength

### ISSUE THREAD

**Issue by heldplayer** [iChun/Morph#676]
&lt;pig&gt; Also while you're at it can you make an issue on github for ability strength?

Ok

**Comment by iChun** [comment]
I forget what this was for but I have other plans now so that's fine.

**Comment by heldplayer** [comment]
Training abilities probably, like climb x meters to level up your wall climbing skill.

**Comment by iChun** [comment]
Oh GOD no.

**Comment by heldplayer** [comment]
Only making guesses :P
