### ISSUE TITLE
 "I:disableEarlyGameFlightMode" config option not working properly

### ISSUE THREAD

**Issue by BBoldt** [iChun/Morph#677]
Using Morph-Beta-0.9.1, but this problem has existed since 1.7.2.

So, I want morph set up so every player has to kill a wither themselves to unlock the flight ability. Problem is, when the config is set up how it is below, every player has the fly ability as soon as anyone kills a wither. 

It seems like the "I:disableEarlyGameFlightMode" config option isn't working correctly. 

I'm not sure if it's only players who are online while the wither is being killed, or just everyone after a wither is killed.

```
    # Disable the flight ability until a player...
    #0 = Enable early game flight
    #1 = ...has reached the nether
    #2 = ...has killed the Wither
    # 
    # Min: 0
    # Max: 2
    I:disableEarlyGameFlight=2

    # Disable Early Game Flight Mode
    #0 = Serverwide toggle
    #1 = Player specific toggle (Every player has to travel to the nether/kill a wither to get flight for themselves)
    # 
    # Min: 0
    # Max: 1
    I:disableEarlyGameFlightMode=1
```

Not using cauldron or anything crazy like that. Just regular forge.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
