### ISSUE TITLE
Mo' Creatures morphed Wyvern landing animation

### ISSUE THREAD

**Issue by Kanadris** [iChun/Morph#678]
Hey i got a problem and I couldn't find a topic for this: I use the Morph mod and Mo' Creatures. Everything works fine, but the Wyvern transformation. When I morph into a Wyvern, no matter which size, i float slightly over the ground. Its the same animation as flying. Might not be a problem for some, but it really annoys me. The only way to get the normal standing animation is to have something like snow or grass on the block you are standing on. Would be amazing if that could be fixed. I already tried to reinstall both mods and I have no other mods installed.

Thank you :)

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
