### ISSUE TITLE
My Skin and model haggard itself after morphing

### ISSUE THREAD

**Issue by Jefftekila1904** [iChun/Morph#684]
I'm using the 0.9.1 version, to 1.7.10 minecraft, and after i morph into any mob, my skin and player model turns into a haggard version of itself, but all the other morphs keep normal.I'm not good at config so I really don't know what to do.
can anyone help me?

Before Morph:
![image](https://cloud.githubusercontent.com/assets/11062277/6251073/e8f9f962-b778-11e4-9ac9-3735686ab9ee.png)

After Morph:
![image](https://cloud.githubusercontent.com/assets/11062277/6251142/5c834dca-b779-11e4-8e89-ebbe85518ef1.png)

**Comment by Jefftekila1904** [comment]
I just discovered that this is a conflict with the smart moving, can i somehow config the smart moving to accept the morph?

**Comment by Tamaized** [comment]
Smartmoving has issues with a ton of mods.

**Comment by Jefftekila1904** [comment]
no way to keep with smart moving and morph together?

**Comment by Tamaized** [comment]
Not that I know of.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
