### ISSUE TITLE
NEI won't search whilst using this mod.

### ISSUE THREAD

**Issue by TheSSVids** [iChun/Morph#685]
When I use this mod, NEI won't search. The search bar can be written in, but no results will show up. NEI will be in the state you left it in. The version I used was beta 0.9.2 1.7.10, all though it seems like the same issue is there with other versions, according to the FTB subreddit.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
