### ISSUE TITLE
Crash Upon Pressing Grave Key

### ISSUE THREAD

**Issue by stephenmc608** [iChun/Morph#687]
Hey there!

Whenever I press the Grave key, (Which is the key I have bound to opening the morph menu), I get a crash. I was playing in a Creative Test World.

I am using Morph Beta 0.9.1 and iChunUtil 4.1.3.
I am using Forge 10.13.2.1307.

Here is the crash report:
https://gist.github.com/stephenmc608/2b4a88202136f615e670

Edit: I accidentally pressed the Grave key in a survival world and it didn't crash...
Edit2: I pressed it again in survival and it crashed

**Comment by blanas** [comment]
i fix that problem by removing one other mod i had but i can not remember what mod. Sory :(

**Comment by iChun** [comment]
I may have tried to fix this in 0.9.2 by slapping a null check but it still needs a proper full fix in the future. We'll have to see how it goes in the 1.8 version
