### ISSUE TITLE
Lava resistance not working properly

### ISSUE THREAD

**Issue by LMAOisbeast** [iChun/Morph#688]
When i was using a zombie pigman morph i had read on the abilities page that they can swim in lava and are impervious to its damage. I went into a pool of lava to look for ores and immediately started taking lava damage but not fire damage. Im not sure if this is a normal glitch or caused by some other factor but i assume im not the only person experiencing this. P.S. This affects all mobs with "fire immunity."

**Comment by cheatscom** [comment]
This seems to still be an open issue, so I hope I'm not wrong in thinking I can add to this. After doing some various testing with mod-conflicts, it appears that if you have ProjectE or EE2 installed in a modpack, then using morph to become a mob with fire immunity will mean that you will not set on fire, but still take damage. Possibly their mod will update in the future that will fix this, but it seems to be a conflict of some kind.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
