### ISSUE TITLE
I find height bug.(with ars magica2)

### ISSUE THREAD

**Issue by pitaya0835** [iChun/Morph#689]
[Mobs look in the wrong spot when trying to look at you when you’re morphed as something that’s differently sized/Arrows and buckets don’t work right from different heights.]

i found this bug with ars magica2.(I feel height is default after morph)

PC
windows vista 32bit
1.7.10-Forge10.13.2.1291(latest?)

Other mods
IC2-experimental(many addon)
Buildcraft(many addon)
Thaumcraft4(many addon)
Mystcraft
twilightForest

every mod is latest.

**Comment by iChun** [comment]
Update ars magica

**Comment by iChun** [comment]
Use Morph 0.9.2, it has a config that constantly forces the size and height of the player as a workaround for this issue.
