### ISSUE TITLE
Bug with bats?

### ISSUE THREAD

**Issue by destroyahx2** [iChun/Morph#691]
I'm playing the Joe Gaming Mod Pack on the ATLauncher and when i transform into a bat and touch a block that is higher than me i start taking damage and this will some times  happen with walls too. So is this a bug or intentional?

**Comment by iChun** [comment]
Ars Magica?

**Comment by destroyahx2** [comment]
It does have it so mabey I was just wondering that because I watch Direwolf20 he does it he doesn't take dmg just wondering

**Comment by destroyahx2** [comment]
Also just as a comment I will take damage when I also go through one block spaces

**Comment by iChun** [comment]
Ars Magica.

**Comment by iChun** [comment]
Use Morph 0.9.2, it has a config that constantly forces the size and height of the player as a workaround for this issue.
