### ISSUE TITLE
When morphed into a bat or sheep, deathscreen

### ISSUE THREAD

**Issue by ekrej** [iChun/Morph#692]
when I morph into a bat or sheep I get the deathscreen and i just keep on dieing, i have some other mods installed like buildcraft, ic 2, tinkersconstruct (all with some addons) and zelda swordskills, and morph is V 0.9.1

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
