### ISSUE TITLE
While Being morphed Into something not two blocks tall it changes the hitbox but not the eyes position

### ISSUE THREAD

**Issue by creeperbrinemob** [iChun/Morph#693]
while i trie to morph into smaller or bigger mobs hitbox does change like i can get trough 1x1 space but i cant mine anythin because it will always mine the block above me.
CAN PLEASE SOMEONE TELL ME HOW TO FIX IT.

also ars magica is fully updated

or is it Animation API?

**Comment by creeperbrinemob** [comment]
checked animation API is also up to date

**Comment by iChun** [comment]
It could be both of them, do you have Smart Moving? Is your Ars Magica the dev version?

**Comment by creeperbrinemob** [comment]
I don't have Smart moving mod.(because it restricts you) adon't know about ars magica it hasn't have .dev at the file name.

Also I watched some youtubers.
Direwolf20 doesnt have that problem but he also doesn't have AM2,
Captain Sparklez has the same problem but he has AM2.
 so that is probably it.

Oh i ment in title like if i'm morphed in to a bat i am as big as bat and i see as bat but it's hard to place and break blocks

**Comment by iChun** [comment]
It's AM2. Update to the dev version (at your own risk) to fix.

**Comment by creeperbrinemob** [comment]
I may be expecting too much from you but how do i get dev version on the forums there is only download witch is direct link and api witch is link for animation API

Otherwise Thank You For Help very much appreciated.

**Comment by iChun** [comment]
I'm not really sure, sorry. I was just told that it's fixed in the dev
version. I don't play with AM2 myself so I've never seeked to find out
where it is.

**Comment by creeperbrinemob** [comment]
ok I will look around if i can find it

Thanks Again!

**Comment by iChun** [comment]
Use Morph 0.9.2, it has a config that constantly forces the size and height of the player as a workaround for this issue.
