### ISSUE TITLE
Aether II - Morph Crash

### ISSUE THREAD

**Issue by piano1997** [iChun/Morph#694]
When i morph into something the game crashes and when I load the profile again I'm morphed but if i try to morph into something else the game will crash again

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 14/03/15 19.09
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.aetherteam.aether.player.PlayerAether.onUpdate(PlayerAether.java:262)
    at com.gildedgames.util.player.common.PlayerEventHandler.onLivingUpdate(PlayerEventHandler.java:70)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_49_PlayerEventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:59)
    at morph.client.core.TickHandlerClient.worldTick(TickHandlerClient.java:826)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_75_TickHandlerClient_worldTick_ClientTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2052)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.aetherteam.aether.player.PlayerAether.onUpdate(PlayerAether.java:262)
    at com.gildedgames.util.player.common.PlayerEventHandler.onLivingUpdate(PlayerEventHandler.java:70)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_49_PlayerEventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:59)
    at morph.client.core.TickHandlerClient.worldTick(TickHandlerClient.java:826)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_75_TickHandlerClient_worldTick_ClientTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Pio'/173, l='MpServer', x=184,88, y=72,62, z=201,38]]
    Chunk stats: MultiplayerChunkCache: 601, 601
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (168,64,252), Chunk: (at 8,4,12 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 2087 game time, 2087 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 103 total; [EntityZombie['Zombie'/9216, l='MpServer', x=162,25, y=55,00, z=161,78], EntityZombie['Zombie'/9217, l='MpServer', x=158,97, y=55,00, z=164,66], EntityBat['Bat'/10246, l='MpServer', x=243,56, y=56,10, z=127,44], EntityBat['Bat'/10247, l='MpServer', x=237,29, y=49,10, z=139,44], EntityBat['Bat'/7191, l='MpServer', x=157,75, y=49,57, z=148,38], EntityBat['Bat'/7197, l='MpServer', x=158,00, y=48,00, z=141,44], EntityCreeper['Creeper'/10285, l='MpServer', x=231,50, y=49,00, z=133,50], EntitySkeleton['Skeleton'/10292, l='MpServer', x=236,50, y=56,00, z=237,50], EntityZombie['Zombie'/8247, l='MpServer', x=213,46, y=54,00, z=218,75], EntityCreeper['Creeper'/7229, l='MpServer', x=205,50, y=53,00, z=246,50], EntityCreeper['Creeper'/7231, l='MpServer', x=205,50, y=53,00, z=245,50], EntitySkeleton['Skeleton'/10307, l='MpServer', x=198,03, y=48,00, z=220,53], EntityCreeper['Creeper'/10308, l='MpServer', x=197,38, y=48,00, z=219,69], EntityCow['Cow'/73, l='MpServer', x=131,50, y=67,00, z=214,50], EntityCow['Cow'/74, l='MpServer', x=130,50, y=69,00, z=210,50], EntityCow['Cow'/75, l='MpServer', x=126,50, y=67,00, z=211,50], EntityCow['Cow'/76, l='MpServer', x=130,50, y=73,00, z=207,50], EntityCow['Cow'/93, l='MpServer', x=165,47, y=83,00, z=149,53], EntityCow['Cow'/94, l='MpServer', x=160,69, y=77,00, z=141,53], EntityCow['Cow'/95, l='MpServer', x=162,50, y=82,00, z=149,50], EntityCow['Cow'/96, l='MpServer', x=163,50, y=82,00, z=147,50], EntityCow['Cow'/97, l='MpServer', x=164,56, y=88,00, z=185,06], EntityCow['Cow'/98, l='MpServer', x=165,41, y=88,00, z=186,28], EntityCow['Cow'/99, l='MpServer', x=166,03, y=88,00, z=187,44], EntityCow['Cow'/100, l='MpServer', x=164,53, y=88,00, z=183,47], EntityCow['Cow'/105, l='MpServer', x=165,94, y=91,00, z=184,06], EntityCow['Cow'/106, l='MpServer', x=177,53, y=88,00, z=185,16], EntityCow['Cow'/107, l='MpServer', x=174,50, y=90,00, z=177,38], EntityCow['Cow'/108, l='MpServer', x=178,50, y=89,00, z=179,31], EntityCow['Cow'/113, l='MpServer', x=233,78, y=64,00, z=194,78], EntityCow['Cow'/114, l='MpServer', x=232,47, y=64,00, z=193,19], EntityCow['Cow'/115, l='MpServer', x=233,50, y=69,00, z=190,50], EntityCow['Cow'/116, l='MpServer', x=235,50, y=64,00, z=196,50], EntityWolf['Wolf'/117, l='MpServer', x=238,28, y=64,00, z=190,31], EntityBat['Bat'/7286, l='MpServer', x=180,33, y=34,49, z=270,20], EntityWolf['Wolf'/118, l='MpServer', x=234,50, y=64,00, z=189,00], EntityWolf['Wolf'/119, l='MpServer', x=242,56, y=69,00, z=184,13], EntityWolf['Wolf'/120, l='MpServer', x=235,44, y=64,00, z=189,75], EntityCreeper['Creeper'/10365, l='MpServer', x=255,50, y=42,00, z=178,50], EntityCow['Cow'/129, l='MpServer', x=259,50, y=66,00, z=122,50], EntityCow['Cow'/131, l='MpServer', x=255,50, y=67,00, z=122,50], EntityCow['Cow'/132, l='MpServer', x=260,50, y=65,00, z=125,50], EntityCow['Cow'/133, l='MpServer', x=254,22, y=63,00, z=261,41], EntityCow['Cow'/134, l='MpServer', x=256,41, y=65,00, z=258,38], EntityCow['Cow'/135, l='MpServer', x=254,50, y=63,00, z=262,97], EntitySheep['Sheep'/141, l='MpServer', x=261,38, y=64,00, z=182,47], EntitySheep['Sheep'/143, l='MpServer', x=262,47, y=64,00, z=178,59], EntitySkeleton['Skeleton'/9374, l='MpServer', x=175,50, y=68,00, z=141,50], EntitySkeleton['Skeleton'/9378, l='MpServer', x=175,50, y=68,00, z=138,50], EntityZombie['Zombie'/9380, l='MpServer', x=212,50, y=34,00, z=136,50], EntityClientPlayerMP['Pio'/173, l='MpServer', x=184,88, y=72,62, z=201,38], EntitySkeleton['Skeleton'/9463, l='MpServer', x=215,50, y=55,00, z=249,50], EntitySpider['Spider'/1284, l='MpServer', x=178,50, y=35,00, z=271,50], EntityBat['Bat'/12551, l='MpServer', x=223,50, y=43,10, z=128,25], EntityCreeper['Creeper'/9486, l='MpServer', x=110,00, y=24,00, z=144,44], EntityCreeper['Creeper'/1303, l='MpServer', x=177,69, y=71,00, z=165,94], EntityBat['Bat'/12573, l='MpServer', x=185,48, y=30,47, z=127,58], EntityBat['Bat'/12575, l='MpServer', x=192,25, y=30,10, z=123,75], EntityBat['Bat'/12576, l='MpServer', x=193,45, y=26,00, z=124,20], EntityBat['Bat'/12577, l='MpServer', x=197,80, y=25,05, z=121,77], EntityTrail['unknown'/1337, l='MpServer', x=184,88, y=72,62, z=201,38], EntityCreeper['Creeper'/4443, l='MpServer', x=197,50, y=57,00, z=263,50], EntityZombie['Zombie'/10596, l='MpServer', x=120,50, y=56,00, z=130,50], EntityZombie['Zombie'/10597, l='MpServer', x=118,50, y=56,00, z=130,50], EntityBat['Bat'/358, l='MpServer', x=122,78, y=13,10, z=258,72], EntitySkeleton['Skeleton'/11623, l='MpServer', x=161,94, y=56,00, z=159,44], EntitySkeleton['Skeleton'/11624, l='MpServer', x=166,50, y=61,00, z=143,50], EntityCreeper['Creeper'/11625, l='MpServer', x=165,50, y=62,00, z=149,00], EntityZombie['Zombie'/10635, l='MpServer', x=196,50, y=56,00, z=252,50], EntityZombie['Zombie'/10637, l='MpServer', x=199,50, y=56,00, z=256,50], EntitySkeleton['Skeleton'/10638, l='MpServer', x=200,50, y=56,00, z=253,50], EntityCreeper['Creeper'/1429, l='MpServer', x=186,50, y=52,00, z=264,50], EntityCreeper['Creeper'/1430, l='MpServer', x=190,44, y=52,00, z=267,50], EntityBat['Bat'/11685, l='MpServer', x=198,41, y=58,04, z=269,24], EntityBat['Bat'/11686, l='MpServer', x=195,41, y=56,24, z=253,16], EntitySkeleton['Skeleton'/10687, l='MpServer', x=169,50, y=58,00, z=125,50], EntitySkeleton['Skeleton'/485, l='MpServer', x=196,50, y=56,00, z=265,50], EntitySpider['Spider'/12779, l='MpServer', x=178,50, y=77,00, z=169,50], EntityZombie['Zombie'/10747, l='MpServer', x=206,50, y=72,00, z=156,50], EntityBat['Bat'/7695, l='MpServer', x=158,66, y=62,04, z=179,34], EntitySkeleton['Skeleton'/11803, l='MpServer', x=111,50, y=46,00, z=141,50], EntitySkeleton['Skeleton'/1586, l='MpServer', x=142,16, y=40,00, z=250,50], EntityWitch['Witch'/10817, l='MpServer', x=174,50, y=78,00, z=170,50], EntityZombie['Zombie'/11857, l='MpServer', x=121,50, y=14,00, z=273,50], EntityZombie['Zombie'/11858, l='MpServer', x=121,50, y=14,00, z=271,50], EntitySkeleton['Skeleton'/12882, l='MpServer', x=214,50, y=54,00, z=220,50], EntitySkeleton['Skeleton'/12883, l='MpServer', x=215,50, y=54,00, z=220,50], EntityCreeper['Creeper'/8790, l='MpServer', x=112,50, y=46,00, z=141,50], EntityCreeper['Creeper'/10846, l='MpServer', x=239,50, y=57,00, z=232,50], EntitySkeleton['Skeleton'/11881, l='MpServer', x=200,50, y=54,00, z=240,50], EntitySkeleton['Skeleton'/11882, l='MpServer', x=197,50, y=54,00, z=240,50], EntitySkeleton['Skeleton'/11883, l='MpServer', x=200,13, y=58,00, z=243,69], EntityXPOrb['Experience Orb'/12976, l='MpServer', x=187,62, y=71,25, z=199,51], EntityCreeper['Creeper'/10944, l='MpServer', x=129,50, y=47,00, z=126,50], EntityCreeper['Creeper'/10945, l='MpServer', x=132,56, y=50,00, z=132,03], EntityWitch['Witch'/13011, l='MpServer', x=154,50, y=58,00, z=275,50], EntitySkeleton['Skeleton'/8950, l='MpServer', x=201,50, y=31,00, z=127,50], EntitySkeleton['Skeleton'/13079, l='MpServer', x=228,50, y=50,00, z=138,50], EntitySkeleton['Skeleton'/13080, l='MpServer', x=229,50, y=50,00, z=138,50], EntityCreeper['Creeper'/13081, l='MpServer', x=227,57, y=50,00, z=141,43], EntityZombie['Zombie'/889, l='MpServer', x=189,47, y=65,00, z=157,44], EntityBat['Bat'/10173, l='MpServer', x=148,22, y=48,12, z=140,59], EntityZombie['Zombie'/12248, l='MpServer', x=189,50, y=33,00, z=122,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.8.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3325934576 bytes (3171 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 8 mods loaded, 8 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    gilded-games-util{1.7.10-1.0} [Gilded Games Utility](gilded-games-util.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    aether{Alpha 1.7.10-1.1} [Aether II](aether.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{4.1.3} [iChunUtil](iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.2.1291
    LWJGL: 2.9.1
    OpenGL: GeForce GT 640/PCIe/SSE2 GL version 4.2.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by TheTemportalist** [comment]
Looks like the AetherII crew is assuming that something isnt null in the PlayerAether class! :P

**Comment by iChun** [comment]
Yeah can you drop this error by the aether team?

**Comment by piano1997** [comment]
Yes , sure !

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
