### ISSUE TITLE
Morphing into Pixelmon

### ISSUE THREAD

**Issue by Santvarg** [iChun/Morph#695]
I checked in several places, including here, just as a note.

I changed into my chosen pixelmon (about four blocks high), yet when I morph into (apparently) any Pixelmon, my eye height is set to a block high ( or so )

( Attempted with Charmander and Ginormous level 100 Lucario (heheh). They produce the similar results,  Charmander's view is actually about half a block, Lucario's seems to be just over one block high.

**Comment by iChun** [comment]
Report it to pixelmon. Morph uses the eye height provided by other mods.

**Comment by MoeBoy76** [comment]
Pixelmon hitboxes are highly inaccurate, i will discuss changing the obj models over to be more accurate with the dev team

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
