### ISSUE TITLE
Config wont work with Hostile ability Mode

### ISSUE THREAD

**Issue by Allensfish** [iChun/Morph#696]
Hi. I am trying to set the hostile ability mode to 5 so the mods wont attack me if im morphed into a hostile mob and if I attack them then they will attack me.  but everytime I set it to 5 it resets to down to 4

can u help with this?

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
