### ISSUE TITLE
Can't fly in multiplayer, but friends can.

### ISSUE THREAD

**Issue by AceTheGmodGeek** [iChun/Morph#697]
Every time I try and fly, It only lets me Glide, for the bat, blaze, blizz, everything I try only glides, My friend got the bat and he could fly perfectly, btw, This is MULTIPLAYER Version 1.6.4.

**Comment by iChun** [comment]
Why are you still using Minecraft 1.6.4 anyways?

**Comment by AceTheGmodGeek** [comment]
Its Tekkit Attack of the B Team

**Comment by iChun** [comment]
Well all I can really say is that there might be a mod conflict which you
might have but the others don't. Can you ask the pack team if they know of
any? They would know better than I would.

**Comment by eoistana** [comment]
Ooh... Just a thought, you might have been cursed by a player witch.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
