### ISSUE TITLE
my health goes down when i morph into small things

### ISSUE THREAD

**Issue by pbrocks798** [iChun/Morph#699]
its bugging me when im fighting something with 100 health and when i morph into a butterfly I only have one heart. is that part of the mod or is it a bug. plzz help!!!!

**Comment by Tamaized** [comment]
Part of the mod.

**Comment by 61352151511** [comment]
How can you think something like this is a bug? You take on the health of the mob you morph into, apart from certain mobs that have extreme amounts of health.

**Comment by taj1994** [comment]
Like 61352151511 said, it's supposed to do that. You get the health of anything with the same amount of health as a player or less (maximum 20 health/10 hearts). If you need more health, install Tinkers' Construct if you don't already have it. You can get hearts to make into heart canisters that each increase your health by one heart, up to a max of 10 per level. There are currently two levels (red and yellow) with a third (green) coming at some point in the future
