### ISSUE TITLE
Hostile Ability Mode config Problem

### ISSUE THREAD

**Issue by Z2589** [iChun/Morph#704]
The morph.cfg file had the acceptable input range for Hostile Ability Mode set to Min: 0, Max: 4, which prevented me from setting Hostile Ability Mode to 5. Is this a bug?

**Comment by iChun** [comment]
Uhhh... that probably is indeed a bug. :/ I don't really maintain/look at
Hostile Mode much, honestly, though.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
