### ISSUE TITLE
[1.7.10] Morph conflicting with Ars Magica

### ISSUE THREAD

**Issue by Xtronius** [iChun/Morph#705]
Hey this is Xtronius, also known as Mecblader, and I found a bug with the hitbox of the player. I don't think this bug is your fault because, the ars magica creator said somthing about hitboxes and an issue with them on his mod page, but I thought that I should bring it to your attention anyway. So basically when ars magica is installed and you morph into a creature that is smaller than a player, the hitbox is not correctly adjusted, meaning that when I look at the block in front of me, and start breaking it, the block above it starts breaking.

Morph Version: Morph-Beta-0.9.1
IChun Util Version: iChunUtil-4.2.2
(Even though I don't think it makes a difference, I tried using different versions of IChun Util, but the bug still exists)

Ars Magica Version: 1.7.10_AM2-1.4.0.008
Animation API Version: AnimationAPI-1.7.10-1.2.4

**Comment by iChun** [comment]
Update to the dev build of ars Magica, that fixes it last I heard.

**Comment by taj1994** [comment]
>Update to the dev build of ars Magica, that fixes it last I heard.

Where is this available for download? All I can find is the "1.7.10_AM2-1.4.0.008" version...

**Comment by iChun** [comment]
Sorry, you'll have to go figure that out yourself, I'm just passing along
what I'm told by others :/

**Comment by iChun** [comment]
Use Morph 0.9.2, it has a config that constantly forces the size and height of the player as a workaround for this issue.
