### ISSUE TITLE
[1.7.10] Morph conflicting with Smart Moving Mod Dependency(SmartRender-1.7.10-2.1)

### ISSUE THREAD

**Issue by Xtronius** [iChun/Morph#706]
Hey this is Xtronius, also know as Mecblader. I found a bug with the rendering of a player model when the mod dependency, Smart Render, of the mod Smart Moving Mod is installed. The description of the Smart Render mod is Replaces the vanilla render model for the player with a much more useable one:
- implement better animations with less code
- attach additional renderers wherever you want
  *only worry about the animations of your own renderers
  Given that the description states that it changes the player model, it explains the issue I have found.
  The issue is that when you morph into a creature and then back into the player, the player model kind of changes to be like the model of the creature that you morphed into, but really messed up, and remains like this for the rest of the session, the model will not change once you have morphed the initial time.

![2015-04-12_12 03 56](https://cloud.githubusercontent.com/assets/5482218/7106372/229fa47a-e10c-11e4-9481-879efe591f9b.png)

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
