### ISSUE TITLE
Morph Bug

### ISSUE THREAD

**Issue by DrayMan13** [iChun/Morph#708]
When I morph into a shorter mob my characters look height is at what it would be if I was still my player and not in morph.
ie: as a bat when I break a block it is breaking the block above the one I'm looking at.

**Comment by taj1994** [comment]
Not sure what version you were using when you posted this, but this is still a problem in 0.9.1... Plus, whenever I'm a one-block tall mob (a bat and Thaumcraft Wisp are a couple examples) and go into a one-block high space, I start suffocating

**Comment by iChun** [comment]
If I got a dollar for every time I had to say this... :/

Anyways, it's a mod conflict. Known conflicts are AM2 and TC2 amongst a few
others.

**Comment by iChun** [comment]
Use Morph 0.9.2, it has a config that constantly forces the size and height of the player as a workaround for this issue.
