### ISSUE TITLE
Flying Morphs conflicting with the chunks.

### ISSUE THREAD

**Issue by Verzachi** [iChun/Morph#710]
So anytime I'm in my game, and using any flying mob, like a Firefly, Bee, or Dragon Fly, if I go ahead enough, chunks will not load while in that morph while flying, and even when I'm on the ground with that morph, still won't load. I did try reloading the chunks while in the morph, but the chunks were still missing. So I decided to go in my Minecraft Skin morph and the chunks reloaded and were there.

**Comment by iChun** [comment]
Have you tried rejoining hte server to see where you are while morphed?

**Comment by Verzachi** [comment]
What do you mean, to see where I am?

**Comment by Tamaized** [comment]
I'm assuming to see if your position in the world is the same when you log out and rejoin while the chunks were not visible.

**Comment by Verzachi** [comment]
Nah, if I rejoin as an flying mob, the chunks would reload around me, therefore affecting the chunk that wasn't there, but if on go on, sometimes a lot of chunks won't load, like I'm stuck in a giant box with land, like trees and stuff in it.

**Comment by iChun** [comment]
what version of forge is on the server?

**Comment by Verzachi** [comment]
Minecraft 1.7.10-Forge10.13.2.1291 sir.

**Comment by iChun** [comment]
What about your other mods? Do you know of anyone else experiencing the
issue?

**Comment by Verzachi** [comment]
The other mods that I have are working fine, unless it is Biomes A Plenty or something like that. 
 And no sir.

**Comment by iChun** [comment]
Hmm, could you possibly try a full reinstall of MC and forge? I can't
really track down the issue at the moment as I'm currently on hiatus and
it's not exactly something I can identify a fix for. :/

To the server you're still a player and stuff, it's just the client
changing how you look so I don't know what could be causing this. Plus no
one else you know has this issue.

**Comment by Verzachi** [comment]
Does a full reinstall mean deleting the programs I have of MC and Forge and just re-downloading them? Or getting the same version of MC while getting an more updated version of Forge?

**Comment by iChun** [comment]
both works either way, I guess. Like I said, this is a unique issue, I
don't know what to do about it.

**Comment by Verzachi** [comment]
Ok so I reinstall the same version of MC and installed a new version of Forge for 1.7.10, but the game crashed while loading in so I decided to use the recommended again.
My world didn't get deleted, and my mods didn't also. Is that supposed to go away when I uninstall and reinstall MC or not?

**Comment by iChun** [comment]
It probably won't cause the files are still there. Anyways, for some reason
I suspect a mod conflict... But as I said before, I really can't help you
debug this right now. It might be better if you ask over on the FTB forums
or IRC, someone might know something.

**Comment by Verzachi** [comment]
Alright then, thanks for your help.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
