### ISSUE TITLE
Morph Mod Incompatible With Kuda Shaders?

### ISSUE THREAD

**Issue by Ashleyosity** [iChun/Morph#713]
Hello,

I've found an issue whenever I morph into anything other than myself, a large white line appears in the middle of my screen, but disappears when I morph back into myself. It looks like it could be a shader issue, however I do have other mods installed. Anything similar like this happened to anyone else?

EDIT: The whole screen also goes opaque when this happens.

**Comment by iChun** [comment]
Screenshot?

**Comment by iChun** [comment]
Unfortunately I don't know how much I can help with this issue as I'm
currently on modding hiatus until my exams get settled with, though.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
