### ISSUE TITLE
Too many morphs for a packet?

### ISSUE THREAD

**Issue by Robijnvogel** [iChun/Morph#717]
So I have not been able to connect to my server for a while. It kept throwing this exception whenever I tried to connect.
java.lang.IllegalArgumentException: Payload may not be larger than 2097050 bytes

I read that this was a Hats problem once. Too many hats or something? But that should be solved, right?

As I am playing with SpecialMobs, every zombie, skeleton or creeper is unique. This causes a lot of entries in Morph.

After I deleted all Hats NBT entries from my <playername>.dat (using NBT Explorer) I still wasn't able to connect.
After this I proceeded to delete my Morph entries, which solved the problem. (I also changed my max health and health from 4096 to 50, but I do not think that these two integer and double values could have been the issue)

I have killed a ridiculous number of mobs before this happened, which gave me around a thousand different morphs, so I can not really reproduce this problem for you :) (Unless I get to that point again in a few months)

**Comment by iChun** [comment]
Yeah that would the reason for the bloating. I will be working on a
"variants" morph system to address this in the future. It's a long known
issue but I've not had the time to work on this

**Comment by Robijnvogel** [comment]
Would it be possible for you to write a temporary "rule" that doesn't allow you to have more than a specific number of Morphs? By overwriting the least recently obtained Morph that is not in your favourites with the new one when the limit is reached perhaps?

**Comment by iChun** [comment]
That's uh... Well it's possible, but unfortunately I won't be doing this as
I'm focusing on other projects for the time being.

**Comment by iChun** [comment]
This has been fixed in 1.12.2's version. Yay!

This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Comment by Robijnvogel** [comment]
Good to know! O_o you release PiP for 1.12.2? Awesome, man!
I can't wait to test if it still conflicts with Botania. :D
