### ISSUE TITLE
Morph Hand Not Overriding

### ISSUE THREAD

**Issue by LilyToon** [iChun/Morph#718]
When I morph into another mob using that Morph Mod, my hand always stays the same. I have hand overriding enabled in the config, and have the latest version of iChun Util that I could get.  Is there anything else I can do to try fixing the problem?

**Comment by iChun** [comment]
What version of Morph?

**Comment by LilyToon** [comment]
I'm using Morph Beta 0.9.1

**Comment by iChun** [comment]
It would be possible somehting's catching the render hand event and
preventing Morph from catching it later on, do you happen to know of any
mods which could do that?

**Comment by LilyToon** [comment]
I'm not sure if any other mods that I have could be catching the render hand event, but if I have a mod that has me holding things a certain way (Galacticraft while holding a spaceship is different from holding any other item), could that potentially be the problem?

**Comment by iChun** [comment]
Well the hand renderer would only be when there is no item in hand though.
The option is enabled in the config, yes?

**Comment by LilyToon** [comment]
Yes, it is enabled in the config. And just to clarify, it says this in the config for hand rendering:
clientonly {
    # Allow the mod to override player hand rendering?
    # 
    # Min: 0
    # Max: 1
    I:handRenderOverride=1

**Comment by iChun** [comment]
Alright :/ does the hand override work if it's just morph running?

**Comment by LilyToon** [comment]
It does work if I'm only running morph. Since this must be a mod conflic, is there any way I can fix it without having to remove the certain mod? (in the meantime, I'll be adding mods back 1 by 1 to see which one causes a problem).

**Comment by iChun** [comment]
Well we can't really know till we identify the mod unfortunately... Let me
know which mod it is.

**Comment by LilyToon** [comment]
Sorry I couldn't reply earlier, I finished going through them in a short amount of time but my internet went out DX anyways, the mod that was causing the hand not to be overridden was the shaders mod core. To be more specific, it was ShadersModCore-v2.3.18 for 1.7.10

**Comment by iChun** [comment]
Shaders Mod? Yeah I've never heard of that issue before, though. Have you
tried raising an issue with them to see if they know about it?

**Comment by LilyToon** [comment]
I'll bring up the issue as soon as I make sure I have the latest version, in case it was fixed in a newer version.

**Comment by iChun** [comment]
Alright grand. Thanks!

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
