### ISSUE TITLE
screen turns red whenever i fly in morph mod

### ISSUE THREAD

**Issue by eforme123** [iChun/Morph#721]
the title pretty much says it all but here is a list of other mods i have installed jic ones that say used with morph before means ive used them and hadnt had this red screen
rougelike dungeons(havent used before)
backpacks(used with morph before)
buildcraft(used with morph before)
codechickenlib(havent used before)
deconstruction table(havent used before)
emerald mod(used with morph before)
enchanting plus(used with morph brfore)
ichun util(used with morph before)
iron chest(used with morph before)
ivtoolkit(havent used before)
lovely robot(havent used before)
lucky block(used with morph before)
msm snap(used with morph before)
optifine(not sure)
orespawn(used with morph before
psychedelicraft(havent used before)
tree capitator(used with morph before)
twilight forest(havent used before)
waila(used with morph before)
zelda sword skills(used with morph before)
wow that list was tedious to type

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Comment by eforme123** [comment]
Yeah np I filed this a long time ago bud
