### ISSUE TITLE
Some suggestions for morph mod

### ISSUE THREAD

**Issue by AshkoreDracson** [iChun/Morph#722]
Hello.

I know this isn't a suggestion place probably, but there was not any other place I could have shared this, I have a few suggestions for morph mod:

Night Vision Ability (For mobs like spiders, enderman & others, maybe ocelots and cats too ?)
Speed Ability (Depending on the mob, you will be able to either go faster, or slower, for example, the horse should be able to go quite faster, zombie would make you slower)

Last suggestion that probably will be a bit much to do:
Get the sounds from the mob to inherit from them, for example, when you are walking, or when you get hurt, the sounds are different, like if you are a pig, you have hooves footsteps sounds, if no sounds are avaliable for the mob, use the default player sounds.

**Comment by iChun** [comment]
Night Vision is very much a possibility.

Sounds from the mob when you're attacked has long been done. If the mob has no sounds then no sound is played.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
