### ISSUE TITLE
Morph and witchery

### ISSUE THREAD

**Issue by Gamingdaredevil** [iChun/Morph#723]
I have done meany test with only Morph and witchery and the hit box for most of the morph are wrong after you die in game so correct this you have to demorph and then remorph, after some meany time this gets rather annoying. Say you are a bat then try and go in to a 1 bock high space after you die you will not fit until you remorph.

Mods 

witchery-1.7.10-0.24.1
Morph-Beta-0.9.1
iChunUtil-4.2.2

Mod loader

forge-1.7.10-10.13.3.1428-1.7.10

Help would be greatly appreciated.

**Comment by iChun** [comment]
Does this still happen without witchery installed?

**Comment by Gamingdaredevil** [comment]
no

**Comment by Gamingdaredevil** [comment]
and i have sent a message to Emoniph no had no reply

**Comment by iChun** [comment]
Is there anything that witchery uses that changes the player size?

**Comment by Gamingdaredevil** [comment]
I:"witchery:potion.sinking"=51 there is no config to turnif off and on

**Comment by iChun** [comment]
Use Morph 0.9.2, it has a config that constantly forces the size and height of the player as a workaround for this issue.
