### ISSUE TITLE
Morph AnimationAPI

### ISSUE THREAD

**Issue by Yorn** [iChun/Morph#724]
Morph and AnimationAPI aren't friends. That problem makes for example bats hurting while in 1 high hole.

**Comment by Gamingdaredevil** [comment]
Do you have ars magica installed. If so go in to the config and look for am folder then in there SkillConf and in there do down until you find  B:Shrink=true and set it to  B:Shrink=false this should fix this.

**Comment by Gamingdaredevil** [comment]
There is also currently a bug with morph and witchery like you have said about but there is no way of solving this yet.

**Comment by Yorn** [comment]
Thank you. That totally helped and resolved my problem.
