### ISSUE TITLE
[0.9.1] Bat morphs take up 2 blocks in height

### ISSUE THREAD

**Issue by Novocastrian** [iChun/Morph#725]
Hi!

I noticed that bat mode (not sure of others - haven't killed or seen any other 1-block high mobs yet in my world) requires normal player height. In the attached image, I am holding down spacebar to ascend. I can dig down and fill 1x1x1 holes though.

Thanks for your time!
![2015-06-17_20 50 53](https://cloud.githubusercontent.com/assets/4601813/8205379/82c0a31c-1533-11e5-9aaf-0b51f79e3646.png)

**Comment by Gamingdaredevil** [comment]
#723

**Comment by iChun** [comment]
Use Morph 0.9.2, it has a config that constantly forces the size and height of the player as a workaround for this issue.
