### ISSUE TITLE
Memory leak after world unloads due to world field in MorphState's entInstance

### ISSUE THREAD

**Issue by nallar** [iChun/Morph#726]
Morph is causing a memory leak when worlds unload.

The entInstance field of MorphState is [set here](https://github.com/iChun/Morph/blob/7bfa22db8daa0930477768499d4fd194962c9985/src/main/java/morph/common/morph/MorphState.java#L52-56).

    entInstance = isRemote ? createPlayer(world, player) : new FakePlayer((WorldServer)world, EntityHelperBase.getSimpleGameProfileFromName(player));
    // OR
    entInstance = (EntityLivingBase)EntityList.createEntityFromNBT(tag, world);

When worlds unload, the MorphState's entity still has the old world object.

**Comment by nallar** [comment]
Made a temporary due to getting annoyed needing to restart my client constantly when changing between ages and running out of RAM.

[Patch to keep track of MorphStates](https://github.com/nallar/nTweaks/blob/aca422495d853604155d5c04a5d8df83d776e744/src/main/resources/cleanUnloadedWorlds.xml#L7-21)
[Code which cleans up those morph states on world change](https://github.com/nallar/nTweaks/blob/aca422495d853604155d5c04a5d8df83d776e744/src/main/java/me/nallar/ntweaks/NTweaks.java#L50-88)

**Comment by iChun** [comment]
Hold on, where are the references still being stored after change of dimension?

**Comment by nallar** [comment]
MorphState instances are created, these MorphStates have an entInstance field, the entity has a worldObj field -> worlds are leaked, as MorphStates are not cleaned up/changed when you change dimension.

For example, if you connect to a server in the overworld and bring up the morph menu, MorphState instances are created. The entInstance field is created then, with an entity which has a reference to the current world. If you then go through a nether portal, the old MorphState instances aren't cleaned up in any way, and still hold entities which have a reference to the overworld.

**Comment by iChun** [comment]
That wouldn't be a horribly large Mem leak now would it? It's only caching one world unless you constantly gain new morphs in various dimensions. (although bad, still. I've fixed this in the 1.8 rewrite).

Would you like me to try and make a quick fix for this?

**Comment by nallar** [comment]
It's quite a bad memory leak - I'm seeing about 400MB :(

If it's already fixed in the 1.8 rewrite, nevermind. 1.7 isn't important.
