### ISSUE TITLE
 Suffocation Bug

### ISSUE THREAD

**Issue by ignisthedragon** [iChun/Morph#727]
Its pretty much the same bug like in 1.6.4 with TiC. Everytime I morph into a 1 block high entity and go directly under a solid block, I start suffocating. When I switch to 3rd person view I dont even fit into a 1 block high gap. Also my headhigh seems to be wrong. if im mining a block i will mine the block over the one im aming on.
I think its a thing between morph and another mod but I cant figure out which one.
Ive already tried without TiC, special mobs and withery but it wasnt one of them.

Here is a list of mod I use:

Morph-Beta-0.9.1 for 1.7.10
Forge 10.13.3.1403

bspkrsCore-universal-6.15.jar
commons-codec-1.9.jar
FoxLib-1.7.10-0.7.0.jar
MrTJPCore-1.0.8.16-universal.jar
Baubles-1.7.10-1.0.1.10.jar
commons-compress-1.8.1.jar
CodeChickenLib-1.7.10-1.1.3.138-universal.jar 
ForgeMultipart-1.7.10-1.2.0.344-universal.jar  
LibSandstone-1.0.0.jar

AM2-1.4.0.008.jar
AnimationAPI-1.7.10-1.2.4.jar
AOBD-2.6.2.jar
AppleCore-mc1.7.10-1.1.0.jar
appliedenergistics2-rv2-stable-8.jar
ArmorStatusHUD-client-1.28.jar
ATG-1.7.2-0.10.0.jar
Automagy-1.7.10-0.24.2.jar
bdlib-mc1710-1.7.1.71.jar
BetterStorage-1.7.10-0.13.1.126.jar
BiblioCraft[v1.10.4][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[Forestry][v1.7].jar
BiblioWoods[Highlands][v1.4].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.3A2+3.jar
BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
BloodMagic-1.7.10-1.3.2-1.jar.old
BloodMagic-1.7.10-1.3.3-4.jar
Botania r1.6-191.jar
buildcraft-6.4.15.jar
carpentersblocks
Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel2-2.3.10.37.jar
CodeChickenCore-1.7.10-1.0.7.46-universal.jar
CoFHCore-[1.7.10]3.0.2-262.jar
CoFHLib-[1.7.10]1.0.2-160.jar
CompactSolars-1.7.10-4.4.39.315-universal.jar
ComputerCraft1.73.jar
CookieCore-1.7.10-1.3.1-5.jar
CoroUtil-1.1.1.jar
CreeperCollateral-[1.7.10]1.0.0B3-6.jar
DamageIndicatorsMod-3.2.3.jar
DirectionHUD-client-1.24.jar
Draconic-Evolution-1.7.10-1.0.1c.jar
DragonMounts-r41-9-g0119bf0-1.7.10.jar
dynamictanks-1.1.04.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
Enchiridion-1.7.X-1.2.jar
EnderIO-1.7.10-2.3.0.0_beta.jar
EnderStorage-1.7.10-1.4.7.36-universal.jar
EquivalentExchange3-1.7.10-0.3.507.jar
ExtraCells-1.7.10-2.2.69bNIGHTLY.jar
extrautilities-1.2.6.jar
Factorization-1.7.10-0.8.92.jar
fastcraft-1.21.jar
FlatSigns-1.7.10-universal-2.1.0.19.jar
Forbidden Magic-1.7.10-0.562.jar
forestry_1.7.10-3.5.6.15.jar
funky-locomotion-1.7.10-beta-5c.jar
gendustry-mc1710-1.4.10.77.jar
GravityGun-4.0.0-beta.jar
Guide-API-1.7.10-1.0.1-20.jar
GUILib.jar
Hats-4.0.1.jar
HungerOverhaul-1.7.10-1.0.0.jar
iChunUtil-4.2.2.jar
IGW-Mod-1.7.10-1.1.1-17-universal.jar
industrialcraft-2-2.2.720-experimental.jar
InfiniBows-1.7.10-universal-coremod-1.3.0.20.jar
INpureCore-[1.7.10]1.0.0B9-60.jar
InventoryTweaks-1.59-dev-152.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.1a_1.7.10.jar
logisticspipes-0.8.3.ayron+4.jar
magicbees-1.7.10-2.3.1.jar
Mariculture-API-1.7.10.jar
Mariculture-Deluxe-1.7.10-1.2.4d-11.jar
Mekanism-1.7.10-8.1.5.237.jar
MekanismGenerators-1.7.10-8.1.5.237.jar
MekanismTools-1.7.10-8.1.5.237.jar
Metallurgy-1.7.10-4.0.8.97.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
mffs-4.1.0.31-core.jar
Mimicry-1.7.10_1286_1.0.9.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
MineTweaker3-1.7.10-3.0.9C.jar
MobiusCore-1.2.5_1.7.10.jar
ModTweaker 2-0.8.1.jar
ModularPowersuits-0.11.0.181.jar
Morph-Beta-0.9.1.jar
Morpheus-1.7.10-1.5.22.jar
MSC2.jar
mystcraft-1.7.10-0.11.12.00.jar
neiaddons-1.12.8.29-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.0.9.jar
NotEnoughItems-1.7.10-1.0.5.110-universal.jar
Numina-0.4.0.99.jar
ObsidiPlates-1.7.10-universal-3.0.0.18.jar
OpenBlocks-1.7.10-1.4.3-snapshot-628.jar
OpenModsLib-1.7.10-0.7.3-snapshot-359.jar
OpenPeripheralAddons-1.7.10-0.3.1-snapshot-197.jar
OpenPeripheralCore-1.7.10-1.1.1-snapshot-227.jar
OpenPeripheralIntegration-1.7.10-0.2.2-snapshot-67.jar
Opis-1.2.5_1.7.10.jar
OptiFine_1.7.10_HD_U_B7.jar
Pam's HarvestCraft 1.7.10h.jar
PneumaticCraft-1.7.10-1.4.2-39-universal.jar
PortalGun-4.0.0-beta-4.jar
pressure-1.2.0.101-mc1.7.10.jar
pressure-mc1710-1.0.1.48.jar.defunct
pressure-mc1710-1.1.1.89.jar.old
ProjectRed-1.7.10-4.6.2.82-Base.jar
ProjectRed-1.7.10-4.6.2.82-Compat.jar
ProjectRed-1.7.10-4.6.2.82-Integration.jar
ProjectRed-1.7.10-4.6.2.82-Lighting.jar
ProjectRed-1.7.10-4.6.2.82-Mechanical_beta.jar
ProjectRed-1.7.10-4.6.2.82-World.jar
QuarryPlus-1.7.10-2.1.0.jar
Railcraft_1.7.10-9.6.1.0-unofficial.jar
RandomThings-2.2.4.jar
RedstoneArsenal-[1.7.10]1.1.0-80.jar
Reliquary-1.2.jar
RemoteIO-1.7.10-2.3.B0-universal.jar
RemoteIO-1.7.10-2.3.B0-universal.jar.old
resonant-engine-2.0.0.118-core.jar
rftools-2.50.jar
roguelike-1.7.10-1.3.6.3.jar
SGCraft-1.9.0-mc1.7.10.jar
SolarFlux-1.7.10-0.5b.jar
SpiceOfLife-mc1.7.10-1.2.3.jar
Springboards-1.7.10-0.1.jar
SSR-rc3.jar
StatusEffectHUD-client-1.27.jar
StevesCarts2.0.0.b18.jar
StevesFactoryManagerA93.jar
StevesWorkshop-0.5.1.jar
symcalc-0.13.5.jar
Sync-4.0.0.jar
Tails-1.7.10-1.3.1.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThaumcraftMobAspects-1.7.2-2A.jar
ThaumicExploration-1.7.10-1.1-37.jar
ThaumicTinkerer-2.5-1.7.10-164.jar
ThermalDynamics-[1.7.10]1.0.0-122.jar
ThermalExpansion-[1.7.10]4.0.1-182.jar
ThermalFoundation-[1.7.10]1.0.0-81.jar
TorchLeversV1.4.1.jar
Translocator-1.7.10-1.1.2.15-universal.jar
TravellersGear-1.7.10-1.14.6.jar
twilightforest-1.7.10-2.3.7.jar
universal-electricity-4.0.0.78-core.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.0.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
ZombieAwareness-1.9.6.jar
Ztones-1.7.10-2.2.1.jar

**Comment by Gamingdaredevil** [comment]
#674

**Comment by Gamingdaredevil** [comment]
#1053

**Comment by Gamingdaredevil** [comment]
Morph conflict - Player hitbox issue #1053
