### ISSUE TITLE
my hitbox is staying at two block high

### ISSUE THREAD

**Issue by Nexus625** [iChun/Morph#729]
No matter I change to enderman or bat,my block will place/break like two block high tall.
This make me take damage when I get into one block hole in bat form.
P.S.Notice me If you need my mod list because I install over 100 mod

**Comment by iChun** [comment]
Use Morph 0.9.2, it has a config that constantly forces the size and height of the player as a workaround for this issue.

**Comment by TheTrueForce** [comment]
Sorry to necropost, but I'm using 0.9.2, and I'm still getting killed trying to fly right below blocks.
It's probably worth noting that I'm using single-player (local server).

**Comment by iChun** [comment]
Is the setting to force the size/eye height on? What other mods do you have?

**Comment by TheTrueForce** [comment]
The force-size setting is set to 1(I tried 0, just in case. Made no difference.), and my mod list is here: http://pastebin.com/Fzp9zFje.

**Comment by iChun** [comment]
can you try renaming the zip of morph to start with a lowercase z? I'm not
sure if this works yet but it's worth a shot. I'm not sure which mod is
conflicting.

**Comment by TheTrueForce** [comment]
I renamed the Morph jar to 'zMorph-0.9.2-beta.jar' and it didn't do anything.
What mod(s) do you suspect to be conflicting?

**Comment by luchokoldo** [comment]
I have the same problem.. I will try to find what mod make this problem..

**Comment by luchokoldo** [comment]
https://github.com/iChun/Morph/issues/724 here is the solution
