### ISSUE TITLE
Morph/java IllegalAccessError Crashing! (crash report included)

### ISSUE THREAD

**Issue by Jury76** [iChun/Morph#730]
There are two different error reports and I've tried everything! Can you help me?

Error Report 1:

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 7/8/15 3:07 PM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagCompound.field_74784_a from class morph.common.morph.MorphState
	at morph.common.morph.MorphState.parseTag(MorphState.java:221)
	at morph.common.morph.MorphState.<init>(MorphState.java:66)
	at morph.common.core.EntityHelper.morphPlayer(EntityHelper.java:85)
	at morph.common.core.EntityHelper.morphPlayer(EntityHelper.java:25)
	at morph.common.core.EventHandler.onLivingDeath(EventHandler.java:1490)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_113_EventHandler_onLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:891)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:145)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 165766976 bytes (158 MB) / 1033895936 bytes (986 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal (2).jar) 
	UCHIJAAAA	FamiliarsAPI{1.7.10} [Familiars API] (FamiliarsAPI-1.7.10 (2).jar) 
	UCHIJAAAA	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar (2).zip) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3 (2).jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJAAAA	IMSM{100.0.2} [IMSM] ([1.7.10]InstantMassiveStructuresMod.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4 (2).jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) 
	UCHIJAAAA	animalbikes{1.7.10} [Animal Bikes] (AnimalBikes_1.7.10 (2).jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	AnyDimensionMod{beta2} [AnyDimensionMod] (AnyDimensionModbeta2 (2).zip) 
	UCHIJAAAA	B0bGrowsOre{2.3.0} [B0bGary's Growable Ores] (B0bGary's Growable Ores-2.3.0 for 1.7.10 (2).jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x (2).jar) 
	UCHIJAAAA	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
	UCHIJAAAA	CakeIsALie{4.04} [CakeIsALie] (CakeIsALie-1.7.10-4.04.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0 (2).jar) 
	UCHIJAAAA	colourfulportalsmod{1.4.3} [Colourful Portals] (ColourfulPortals-1.4.3.jar) 
	UCHIJAAAA	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c (2).jar) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7 (2).jar) 
	UCHIJAAAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0 (2).jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d (2).jar) 
	UCHIJAAAA	explosives_pp{1.7b} [§6Explosives§4++] (ExplosivesPP-1.7.10-1.7b (2).jar) 
	UCHIJAAAA	DefaultMobPack{1.7.10} [DefaultMobPack] (FamiliarsDefaultMobPack-1.7.10 (2).jar) 
	UCHIJAAAA	ExtendedFamPack{1.7.10} [ExtendedFamPack] (FamiliarsExtendedFamPack-1.7.10 (2).jar) 
	UCHIJAAAA	flowercraftmod{1.9} [Flowercraft] (Flowercraftmod 1.8 - 1.7.10 Forge.jar) 
	UCHIJAAAA	cm{1} [More Grenades Mod] (Grenades_Mod (2).jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (Grenades_Mod (2).jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2 (3).jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1 (2).jar) 
	UCHIJAAAA	instahouse{7.5} [Insta House] (InstaHousev7.5 (2).jar) 
	UCHIJAAAA	instantblocks{1.5.4} [Instant Blocks] (InstantBlocks_v1.5.4 (2).jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal (2).jar) 
	UCHIJAAAA	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) 
	UCHIJAAAA	movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1 (1).jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10) (2).jar) 
	UCHIJAAAA	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) 
	UCHIJAAAA	mwaw{1.7.10-0.0.5} [Elemental Witch Mod] (mwaw-1.7.10-0.0.5.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3 (2).zip) 
	UCHIJAAAA	pennyarcade{Alpha 1.2} [Penny Arcade Mod] (Penny Arcade Mod Alpha 1.2.jar) 
	UCHIJAAAA	pvzmcw{Alpha 1.4.2} [Plants vs Zombies: Minecraft Warfare] (PvZ Minecraft Warfare Alpha 1.4.2.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2 (2).jar) 
	UCHIJAAAA	rivalrebels{1.7.10G} [Rival Rebels] (rivalrebels-1.7.10G (2).jar) 
	UCHIJAAAA	AS_Ruins{14.7} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413 (2).jar) 
	UCHIJAAAA	shinyfood{1.5} [ShinyFood] (shinyfood-1.7.10-v1.5 (2).jar) 
	UCHIJAAAA	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2 (2).jar) 
	UCHIJAAAA	voxelmap{1.7.10} [VoxelMap No Radar] (VoxelMap-No-Radar-Mod-1.7.10 (2).jar) 
	UCHIJAAAA	nolpfij_wildycraft{1.7.3} [Wildycraft] (wildycraft-1.7.10-1.7.3 (2).jar) 
	UCHIJAAAA	youtubers{1.7.0} [Youtubers+ Mod] (youtubers-1.7.0 (2).jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Jury76'/177, l='New World', x=-68.09, y=68.00, z=179.06]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
-------------------------------------------------------------------------------------------------------------------------------###############################################################################
Error Report 2: 

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 7/8/15 3:28 PM
Description: Rendering entity in world

java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.entity.Render.field_76989_e from class morph.common.core.EventHandler
	at morph.common.core.EventHandler.onRenderPlayer(EventHandler.java:296)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_123_EventHandler_onRenderPlayer_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1008)
	at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:351)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_235_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at morph.common.core.EventHandler.onRenderPlayer(EventHandler.java:296)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_123_EventHandler_onRenderPlayer_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)

-- Entity being rendered --
Details:
	Entity Type: OtherPlayers (net.minecraft.client.entity.EntityOtherPlayerMP)
	Entity ID: 782
	Entity Name: Jury76
	Entity's Exact location: -104.50, 65.62, 382.50
	Entity's Block location: World: (-105,65,382), Chunk: (at 7,4,14 in -7,23; contains blocks -112,0,368 to -97,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00

-- Renderer details --
Details:
	Assigned renderer: RenderPlayerOF@126353d0
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1008)
	at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:351)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_235_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Jury76'/497, l='MpServer', x=-105.33, y=64.62, z=380.28]]
	Chunk stats: MultiplayerChunkCache: 441, 450
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-105,63,382), Chunk: (at 7,3,14 in -7,23; contains blocks -112,0,368 to -97,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1861075 game time, 249631 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 45 total; [EntityChicken['Chicken'/128, l='MpServer', x=-137.44, y=71.00, z=311.44], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/131, l='MpServer', x=-128.53, y=63.16, z=365.63], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/144, l='MpServer', x=-115.41, y=60.16, z=350.47], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/145, l='MpServer', x=-113.38, y=60.16, z=349.56], EntityTrail['unknown'/530, l='MpServer', x=-105.33, y=64.62, z=380.28], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/146, l='MpServer', x=-120.63, y=60.16, z=352.63], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/147, l='MpServer', x=-120.63, y=61.16, z=354.22], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/148, l='MpServer', x=-120.63, y=62.16, z=358.22], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/149, l='MpServer', x=-120.63, y=62.16, z=358.63], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/150, l='MpServer', x=-118.38, y=60.16, z=352.56], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/151, l='MpServer', x=-120.63, y=60.16, z=353.66], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/152, l='MpServer', x=-117.28, y=63.16, z=364.63], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/153, l='MpServer', x=-116.00, y=63.16, z=364.63], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/154, l='MpServer', x=-120.63, y=61.16, z=362.41], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/155, l='MpServer', x=-126.25, y=64.16, z=362.97], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/156, l='MpServer', x=-122.03, y=64.16, z=365.22], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/157, l='MpServer', x=-118.78, y=64.16, z=363.91], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/158, l='MpServer', x=-121.47, y=64.16, z=360.44], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/159, l='MpServer', x=-122.53, y=64.16, z=363.56], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/160, l='MpServer', x=-117.66, y=64.16, z=361.34], Cassowary['Cassowary'/61, l='MpServer', x=-166.50, y=22.00, z=434.50], EntityWolf['Wolf'/190, l='MpServer', x=-100.31, y=63.00, z=382.47], Cassowary['Cassowary'/62, l='MpServer', x=-166.50, y=22.00, z=438.50], EntityItemFrame['entity.ItemFrame.name'/191, l='MpServer', x=-100.06, y=65.50, z=374.50], Cassowary['Cassowary'/63, l='MpServer', x=-165.50, y=22.00, z=436.50], EntityItemFrame['entity.ItemFrame.name'/192, l='MpServer', x=-100.06, y=65.50, z=373.50], EntitySheep['Sheep'/67, l='MpServer', x=-165.75, y=72.00, z=450.41], EntityHat['unknown'/2642, l='MpServer', x=-158.71, y=63.00, z=325.77], EntityTFBoar['Wild Boar'/92, l='MpServer', x=-159.53, y=63.00, z=318.47], EntityTFPenguin['Penguin'/93, l='MpServer', x=-159.75, y=63.00, z=319.94], EntityChicken['Chicken'/94, l='MpServer', x=-147.44, y=65.00, z=310.16], RedCow['Apple Cow'/100, l='MpServer', x=-155.31, y=63.00, z=325.72], EntitySheep['jeb_'/101, l='MpServer', x=-159.45, y=63.00, z=327.55], Lizard['Lizard'/230, l='MpServer', x=-48.48, y=61.70, z=338.16], EntityCamel['Ugthanki Camel'/102, l='MpServer', x=-150.47, y=63.00, z=327.53], EntityVillager['Villager'/103, l='MpServer', x=-159.70, y=63.00, z=326.65], EntityTFBighorn['popo the great'/104, l='MpServer', x=-158.71, y=63.00, z=325.77], EntityTFDeer['Wild Deer'/105, l='MpServer', x=-156.00, y=63.00, z=327.41], FamiliarCompanionCube['entity.ExtendedFamPack.Familiar Cube.name'/747, l='MpServer', x=-105.28, y=64.62, z=379.28], EntityWaypointContainer['unknown'/749, l='MpServer', x=0.00, y=0.00, z=0.00], EntityItem['item.item.apple'/110, l='MpServer', x=-151.56, y=64.13, z=367.72], EntityItem['item.item.apple'/111, l='MpServer', x=-146.09, y=65.13, z=374.53], EntityClientPlayerMP['Jury76'/497, l='MpServer', x=-105.33, y=64.62, z=380.28], EntityHat['unknown'/499, l='MpServer', x=-105.33, y=64.62, z=380.28], Cassowary['Cassowary'/252, l='MpServer', x=-45.50, y=64.00, z=421.59]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 517701808 bytes (493 MB) / 1008730112 bytes (962 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal (2).jar) 
	UCHIJAAAA	FamiliarsAPI{1.7.10} [Familiars API] (FamiliarsAPI-1.7.10 (2).jar) 
	UCHIJAAAA	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar (2).zip) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3 (2).jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJAAAA	IMSM{100.0.2} [IMSM] ([1.7.10]InstantMassiveStructuresMod.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4 (2).jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) 
	UCHIJAAAA	animalbikes{1.7.10} [Animal Bikes] (AnimalBikes_1.7.10 (2).jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	AnyDimensionMod{beta2} [AnyDimensionMod] (AnyDimensionModbeta2 (2).zip) 
	UCHIJAAAA	B0bGrowsOre{2.3.0} [B0bGary's Growable Ores] (B0bGary's Growable Ores-2.3.0 for 1.7.10 (2).jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x (2).jar) 
	UCHIJAAAA	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
	UCHIJAAAA	CakeIsALie{4.04} [CakeIsALie] (CakeIsALie-1.7.10-4.04.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0 (2).jar) 
	UCHIJAAAA	colourfulportalsmod{1.4.3} [Colourful Portals] (ColourfulPortals-1.4.3.jar) 
	UCHIJAAAA	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c (2).jar) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7 (2).jar) 
	UCHIJAAAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0 (2).jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d (2).jar) 
	UCHIJAAAA	explosives_pp{1.7b} [§6Explosives§4++] (ExplosivesPP-1.7.10-1.7b (2).jar) 
	UCHIJAAAA	DefaultMobPack{1.7.10} [DefaultMobPack] (FamiliarsDefaultMobPack-1.7.10 (2).jar) 
	UCHIJAAAA	ExtendedFamPack{1.7.10} [ExtendedFamPack] (FamiliarsExtendedFamPack-1.7.10 (2).jar) 
	UCHIJAAAA	flowercraftmod{1.9} [Flowercraft] (Flowercraftmod 1.8 - 1.7.10 Forge.jar) 
	UCHIJAAAA	cm{1} [More Grenades Mod] (Grenades_Mod (2).jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (Grenades_Mod (2).jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2 (3).jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1 (2).jar) 
	UCHIJAAAA	instahouse{7.5} [Insta House] (InstaHousev7.5 (2).jar) 
	UCHIJAAAA	instantblocks{1.5.4} [Instant Blocks] (InstantBlocks_v1.5.4 (2).jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal (2).jar) 
	UCHIJAAAA	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) 
	UCHIJAAAA	movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1 (1).jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10) (2).jar) 
	UCHIJAAAA	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) 
	UCHIJAAAA	mwaw{1.7.10-0.0.5} [Elemental Witch Mod] (mwaw-1.7.10-0.0.5.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3 (2).zip) 
	UCHIJAAAA	pennyarcade{Alpha 1.2} [Penny Arcade Mod] (Penny Arcade Mod Alpha 1.2.jar) 
	UCHIJAAAA	pvzmcw{Alpha 1.4.2} [Plants vs Zombies: Minecraft Warfare] (PvZ Minecraft Warfare Alpha 1.4.2.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2 (2).jar) 
	UCHIJAAAA	rivalrebels{1.7.10G} [Rival Rebels] (rivalrebels-1.7.10G (2).jar) 
	UCHIJAAAA	AS_Ruins{14.7} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413 (2).jar) 
	UCHIJAAAA	shinyfood{1.5} [ShinyFood] (shinyfood-1.7.10-v1.5 (2).jar) 
	UCHIJAAAA	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2 (2).jar) 
	UCHIJAAAA	voxelmap{1.7.10} [VoxelMap No Radar] (VoxelMap-No-Radar-Mod-1.7.10 (2).jar) 
	UCHIJAAAA	nolpfij_wildycraft{1.7.3} [Wildycraft] (wildycraft-1.7.10-1.7.3 (2).jar) 
	UCHIJAAAA	youtubers{1.7.0} [Youtubers+ Mod] (youtubers-1.7.0 (2).jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by iChun** [comment]
Could you try updating Forge and reporting back?
Make sure the iChunUtil you have is from my site or CurseForge and not from
some random site rehosting it.
