### ISSUE TITLE
Morph/java IllegalAccessError Crashing! pt 2 (the crashing is real!)

### ISSUE THREAD

**Issue by Jury76** [iChun/Morph#731]
Hello, iChun!
Here is the crash repost you requested.
and both the mod and the Utility are from your website.

(java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagCompound.field_74784_a from class morph.common.morph.MorphState)
This part keeps erroring! ^---
---- Minecraft Crash Report ----
// Oops.

Time: 7/13/15 4:00 PM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagCompound.field_74784_a from class morph.common.morph.MorphState
	at morph.common.morph.MorphState.parseTag(MorphState.java:221)
	at morph.common.morph.MorphState.<init>(MorphState.java:66)
	at morph.common.core.EntityHelper.morphPlayer(EntityHelper.java:85)
	at morph.common.core.EntityHelper.morphPlayer(EntityHelper.java:25)
	at morph.common.core.EventHandler.onLivingDeath(EventHandler.java:1490)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_85_EventHandler_onLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:891)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:335)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 383942496 bytes (366 MB) / 910688256 bytes (868 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1490 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1490-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1490} [Minecraft Forge] (forge-1.7.10-10.13.4.1490-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal (2).jar) 
	UCHIJAAAA	FamiliarsAPI{1.7.10} [Familiars API] (FamiliarsAPI-1.7.10 (2).jar) 
	UCHIJAAAA	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar (2).zip) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3 (2).jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJAAAA	IMSM{100.0.2} [IMSM] ([1.7.10]InstantMassiveStructuresMod.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4 (2).jar) 
	UCHIJAAAA	animalbikes{1.7.10} [Animal Bikes] (AnimalBikes_1.7.10 (2).jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	AnyDimensionMod{beta2} [AnyDimensionMod] (AnyDimensionModbeta2 (2).zip) 
	UCHIJAAAA	B0bGrowsOre{2.3.0} [B0bGary's Growable Ores] (B0bGary's Growable Ores-2.3.0 for 1.7.10 (2).jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x (2).jar) 
	UCHIJAAAA	CakeIsALie{4.04} [CakeIsALie] (CakeIsALie-1.7.10-4.04.jar) 
	UCHIJAAAA	carsanddrives{1.0.9.1} [Cars and Drives] (Cars_and_Drives_Mod_V-1.0.9.1.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0 (2).jar) 
	UCHIJAAAA	colourfulportalsmod{1.4.3} [Colourful Portals] (ColourfulPortals-1.4.3.jar) 
	UCHIJAAAA	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c (2).jar) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7 (2).jar) 
	UCHIJAAAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0 (2).jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d (2).jar) 
	UCHIJAAAA	explosives_pp{1.7b} [§6Explosives§4++] (ExplosivesPP-1.7.10-1.7b (2).jar) 
	UCHIJAAAA	DefaultMobPack{1.7.10} [DefaultMobPack] (FamiliarsDefaultMobPack-1.7.10 (2).jar) 
	UCHIJAAAA	ExtendedFamPack{1.7.10} [ExtendedFamPack] (FamiliarsExtendedFamPack-1.7.10 (2).jar) 
	UCHIJAAAA	flowercraftmod{1.9} [Flowercraft] (Flowercraftmod 1.8 - 1.7.10 Forge.jar) 
	UCHIJAAAA	cm{1} [More Grenades Mod] (Grenades_Mod (2).jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (Grenades_Mod (2).jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2 (3).jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1 (2).jar) 
	UCHIJAAAA	instahouse{7.5} [Insta House] (InstaHousev7.5 (2).jar) 
	UCHIJAAAA	instantblocks{1.5.4} [Instant Blocks] (InstantBlocks_v1.5.4 (2).jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal (2).jar) 
	UCHIJAAAA	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1 (3).jar) 
	UCHIJAAAA	movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1 (1).jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10) (2).jar) 
	UCHIJAAAA	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) 
	UCHIJAAAA	mwaw{1.7.10-0.0.5} [Elemental Witch Mod] (mwaw-1.7.10-0.0.5.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3 (2).zip) 
	UCHIJAAAA	pennyarcade{Alpha 1.2} [Penny Arcade Mod] (Penny Arcade Mod Alpha 1.2.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2 (2).jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413 (2).jar) 
	UCHIJAAAA	shinyfood{1.5} [ShinyFood] (shinyfood-1.7.10-v1.5 (2).jar) 
	UCHIJAAAA	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2 (2).jar) 
	UCHIJAAAA	voxelmap{1.7.10} [VoxelMap No Radar] (VoxelMap-No-Radar-Mod-1.7.10 (2).jar) 
	UCHIJAAAA	youtubers{1.7.0} [Youtubers+ Mod] (youtubers-1.7.0 (2).jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Jury76'/611, l='SO MANY CRASHES!', x=3.44, y=69.00, z=244.75]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by iChun** [comment]
Lex said to blame chickenbones. Can you try the mod without the other mods?
