### ISSUE TITLE
[Suggestion] Ability Fuel

### ISSUE THREAD

**Issue by power-spike** [iChun/Morph#733]
Hi, 

i love the morph mod, how ever in some ways it can be a bit OP 

could we have the ability to add fuels (turn on and off as a config option).  and fuel time.

An example would be - feathers for flying, inksac's for wather breathing. and you could set it so 1 feather for 30 seconds , or 1 inksav for 60 seconds.

**Comment by iChun** [comment]
Already have plans on balancing Morph in regards to this in terms of time limits. Thanks though.
