### ISSUE TITLE
Morph/java IllegalAccessError Finale (resolved) (no crash report)

### ISSUE THREAD

**Issue by Jury76** [iChun/Morph#734]
Hello, iChun!
I no longer have any more crash reports.
Thanks for your help!

**Comment by iChun** [comment]
Why are you still making new issues?!?!?!

**Comment by iChun** [comment]
Would also be nice is you stated what fixed it

**Comment by Jury76** [comment]
what fixed it is that i didnt open the archive.
also sorry that i am making new issues, (this one is not an issue)
