### ISSUE TITLE
I found answer to the problem with the "Morph Hand Not Overriding"

### ISSUE THREAD

**Issue by PalomaAguirre** [iChun/Morph#735]
I have read the issues about this and I understand why the hand do not changes when I Morph, this happens beacause we can have others mods installed. The Shaders mod specifically.
I tried with a lot of mods and the only one mod that caused problems, was The Shaders.
I wrote this to help, if you still don't know why this happens, I don't know :smile:
Excuse me the orthography, I do not speak english really hehe.
Greetings :smile:

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
