### ISSUE TITLE
I:handRenderOverride=1 breaks shaders mod

### ISSUE THREAD

**Issue by Kronnn** [iChun/Morph#736]
I noticed that whenever I was morphed most shader packs I tried would have something broken with them, usually either a strong blue tint / horrible persistent glare / totally broken water texture. I played around with the configs and noticed that when I:handRenderOverride=1 weas changed to disable it, I could morph without the shaders breaking (albeit at the expense of showing my skins hand while holding nothing)

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
