### ISSUE TITLE
[Ability Suggestion]Block Breaking

### ISSUE THREAD

**Issue by Alex-the-666** [iChun/Morph#738]
The wither can break blocks, along with many mobs from the fossils and archeology.(code they use here: https://github.com/FossilsArcheologyRevival/FossilArcheology1.7/blob/master/src/main/java/com/github/revival/common/entity/mob/EntityDinosaur.java)

**Comment by iChun** [comment]
Too overpowered for player use. Trying to keep balance in the game isn't easy guys!
