### ISSUE TITLE
Get morphed entity inventory size to see if the entity can keep items or not, if not, drop items.

### ISSUE THREAD

**Issue by iChun** [iChun/Morph#745]
Configurable

**Comment by Virtheon** [comment]
Has this feature been implemented? Sorry, I don't have Minecraft installed at the moment, so I can't check.

**Comment by iChun** [comment]
I thought about it for the 1.16.5 rewrite, but I decided against it as
there would be no easy way to handle modded inventories (unless they add
support for Morph themselves), so I opted not to do it.
