### ISSUE TITLE
lastest version of iChunUtil doesn't work with latest morph

### ISSUE THREAD

**Issue by dmodoomsirius** [iChun/Morph#749]
using version 5.4.0 of iChunUtil and version 0.9.2 of Morph and it requires iChunUtil 4.0.0.
any chance of changing it so it works with the latest iChunUtil?

**Comment by Leviathan143** [comment]
iChunUtil 5.4.0 is for MC1.8, Morph 0.9.2 is for MC1.7.10.
iChun's version numbering is explained here:
http://ichun.us/what-version-of-minecraft-is-this-mod-version-for/

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/796
