### ISSUE TITLE
Custom Npc Morphs Still Glitching Out? Personally Curious Why.

### ISSUE THREAD

**Issue by Purecreationer** [iChun/Morph#753]
Good morning, afternoon, or evening, reader hopefully iChun is reading this. But my question here today is the issues of when killing a "custom npcs" and morphing into it the 1st person perspective is correct as stated by previous posters, but like said by others the 3rd person is not. This issues is of course the one causing the mob to morph into the group only being able to see the head and shoulders of the npcs. I've also heard that it appears fine to other players' perspective when they are looking at you as well. 

So I'll just get to the point now, why is it still an issue with it not showing up properly in 3rd person, quite literally nearly a year later on the mod and we usually don't get some sort of reply on what's wrong, how to even fix this issue, or even an update that would come with a patch to fix this issue and add additional content?

Thank you for reading who ever made it this far, I just hope this slight problem could be fixed eventually.

~Have a nice day

P.S
Also iChun I read your future plans for this mod and I gotta admit, that seems pretty damn awesome if pulled off the way you want it to be.

**Comment by iChun** [comment]
Sorry, only just getting to this issue now, I don't quite understand what your issue is with Custom NPCs. Could a screenshot possibly help explain this?

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
