### ISSUE TITLE
Why do you ignore loading of abilities

### ISSUE THREAD

**Issue by TheTemportalist** [iChun/Morph#755]
Why are abilities prevented from being loaded if a mob already has abilities?
See: https://github.com/iChun/Morph/blob/master/src/main/java/morph/common/thread/ThreadGetOnlineResources.java#L160

What if a mod happens to add abilities to a mob in their postInit and your thread isnt finished. This is occurring in MorphAdditions and is causing issues. Why not use the method at https://github.com/iChun/Morph/blob/master/src/main/java/morph/common/ability/AbilityHandler.java#L41 which allows you to just append more abilities?

**Comment by iChun** [comment]
Abilities are under revision at the moment for 1.8, the current system is
obviously flawed and I'm not sure why I made it so you cannot override
abilities.

I made this choice ages ago but I just can't remember why now. I'll look
into it for the 1.8 revision

**Comment by TheTemportalist** [comment]
Is there anyway you could allow morph to add abilities even when other kids have also? Like just by commenting out a few of those lines in AbiltiyHandler? Just so that I can keep MorphAddtions running in 1.7.10. Would be super helpful.

**Comment by iChun** [comment]
Well, it's not of a hiiiigh priority, so for the moment I probably won't be
doing that and pushing an update just for that... I'd recommend that you
just reflect into Morph if you have to, to work around this.

Like I said, I'll rethink/handle this with the ability revamp in MC 1.8

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
