### ISSUE TITLE
Spawn Into World as A Different Mob

### ISSUE THREAD

**Issue by sui-0** [iChun/Morph#757]
Hi there. Hopefully you can help me with this. 
I'm using the morph mod, as well as the YarrCuteMobModels mod. 
I morphed into the ghast girl and (for totally different reasons) my game crashed.
Now everytime I enter a TOTALLY DIFFERENT WORLD I will spawn in
as the ghast girl.
Please help!
![2015-09-20_20 25 00](https://cloud.githubusercontent.com/assets/14497748/9984045/c4e4270e-5fd5-11e5-869a-03cd66716a3f.png)

**Comment by iChun** [comment]
Have you tried demorphing?

**Comment by iChun** [comment]
There should also be an admin command to demorph

**Comment by iChun** [comment]
No response, closing.
