### ISSUE TITLE
Morh abilities

### ISSUE THREAD

**Issue by Joshmja91** [iChun/Morph#758]
I love your morph mod but when I kill a creature that has abilities like the bat having flight I don't get that ability. I have already checked the config file to see if the issue was with the config file but it isn't i don't know if it is a bug or you have removed the abilities from the mobs.

**Comment by iChun** [comment]
Can you show me your FML log?

**Comment by Joshmja91** [comment]
Sorry it has taken so long to respond but I was having issues with my internet. Github isn't letting me attach the log file to this comment even when I saved the log file as a .txt. It says "Attaching documents requires write permission to this repository.

**Comment by iChun** [comment]
Put it on pastebin

**Comment by Joshmja91** [comment]
i'm unable to paste it to pastebin the log file is too large. And I am not skilled enough to read the FML log files to get the correct info for you.

**Comment by iChun** [comment]
Gist.github.com then

**Comment by CyberCelestial** [comment]
It's because of Chance Cubes. I recently opened an issue addressing specifically that. I'm not sure WHY, exactly, but nevertheless, it is.

**Comment by iChun** [comment]
Huh. Okay. Do you have logs for this then?

**Comment by Joshmja91** [comment]
Thank you. I wonder why chance cubes is causing the issue. I was wanting to do something that wasn't lucky blocks but still had the same type of random things but I guess that I will have to stick with lucky blocks.
