### ISSUE TITLE
Internal Server Error when collecting Mo' Creature Morphs

### ISSUE THREAD

**Issue by ShadeyWolf294** [iChun/Morph#771]
Hi,
I have no idea what's going on. But whenever I kill a Mo' Creature, I'm disconnected from the server and get a message saying "Internal Server Error". If I kill a vanilla creature, this error doesn't occur. Here's the crash report:

http://pastebin.com/VzRvGH7G

Any help? Thanks! :D

**Comment by iChun** [comment]
Not morph. Send this log to ivorius. It's his mod doing it.

**Comment by ShadeyWolf294** [comment]
Oh, Okay.
