### ISSUE TITLE
Duplicate Morphs

### ISSUE THREAD

**Issue by Zsashas** [iChun/Morph#772]
I have the NBT stripper enabled, which says it is supposed to remove duplicate morphs. However, some mobs give a new morph EVERY single time, despite being identical in every way.

Examples: 

Mowzie's Mobs: Barakoa (even taking into account the various mask/weapon combinations, there are still way too many)

Exotic Birds: Magpie

![2015-11-16_01 11 14](https://cloud.githubusercontent.com/assets/6917535/11198647/47571012-8c7b-11e5-91e1-3ef5bd79a639.png)

**Comment by iChun** [comment]
That's cause they don't have any stripper mappings

**Comment by Zsashas** [comment]
I honestly don't know quite what that means. How can mappings be made/added?

**Comment by iChun** [comment]
The mappings are added by the community (as I clearly can't do that myself
for every mod out there by myself). The mappings are of the names of the
NBT tags that are meant to be removed from the entity save. This changes in
1.8 but aren't applicable here clearly.

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/796
