### ISSUE TITLE
[Doors] Mobs can be pushed through doors?

### ISSUE THREAD

**Issue by Zsashas** [iChun/Morph#775]
I was fighting several Barakoa, using the door to attack and retreat, and it seems that if a mob is in the same space as the door, a player can push them through, despite them otherwise being unable to enter the doors.

I was under the impression that the doors were treated as solid by everything except players, including items, is this not true?

There is no possible way for them to have entered this room otherwise, yet this is the first time they have done so.

Another odd bit is that they seemed to not notice me whatsoever, as if they still thought they were at the other end of the door link.
![2015-11-28_20 46 03](https://cloud.githubusercontent.com/assets/6917535/11455377/6ca495c0-9611-11e5-9788-8988867a5db0.png)

**Comment by iChun** [comment]
This is intended behaviour. Anything can pass through if the doors are
linked. Mobs just don't know that they can path through doors to get to the
other side. Also why is this posted on this repo?

**Comment by Zsashas** [comment]
Mistake. Meant to post on the other one.
