### ISSUE TITLE
Unable to Morph into any mob

### ISSUE THREAD

**Issue by ZaneGlitch** [iChun/Morph#776]
When i kill a mob i don't turn into anything but i do see the limbs coming after me when i just killed someone.
![giphy](https://cloud.githubusercontent.com/assets/9377968/11458357/84ef8c22-96be-11e5-8ebf-81abce98f334.gif)

**Comment by iChun** [comment]
Have you tried actually opening the gui and selecting a morph to morph into?

**Comment by ZaneGlitch** [comment]
Nope i can't.

**Comment by iChun** [comment]
Which keys are you hitting?

**Comment by iChun** [comment]
You can't what?

**Comment by iChun** [comment]
You can't open the GUI?

**Comment by iChun** [comment]
You can't morph?

**Comment by 66hami66** [comment]
i did downloaded this mod 1 hour ago and same problem like this guy cant morhp into any mob that i killed and after i killed some mobs i opened the gui and there is no mobs to select to morhp into it

**Comment by iChun** [comment]
Is it installed on the server?

**Comment by 66hami66** [comment]
no singleplayer

**Comment by iChun** [comment]
What buttons are you hitting to open the GUI?

**Comment by ZaneGlitch** [comment]
I finally fixed it. It turns out that the mod was working all the time. It's just that the instaMorph was set to 0 at the config but now im facing an another problem. The mod doesn't store mobs acquired by killing.

**Comment by ZaneGlitch** [comment]
Also i had to change the key to open the GUI to "M" because my keyboard is danish.

**Comment by iChun** [comment]
Which GUIs are you opening?

**Comment by ZaneGlitch** [comment]
The Morph Menu

**Comment by ZaneGlitch** [comment]
I just noticed that not only can't i acquire mobs but the only thing that makes me morph is when i enable instaMorph and morph back to myself

**Comment by iChun** [comment]
That's cause you're opening the favourites menu (one key). By default
demorphing will be in the favourites list. The selection menu uses two
keys. Figure out which those two keys are.

**Comment by ZaneGlitch** [comment]
OMG IT WORKS NOW.
