### ISSUE TITLE
Morph Crashes When I attempt to use it.

### ISSUE THREAD

**Issue by MinerManKCMB** [iChun/Morph#777]
As soon as I press the key that opens the morph GUI, my game freezes and crashes. It only happens in one world though. I have the same mods installed in every other world though. Is it just my computer, or what? Any suggestions?

**Comment by iChun** [comment]
I need the crash report if you could

**Comment by MinerManKCMB** [comment]
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 11/30/15 2:51 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at com.webs.arkif.models.ModelHoverboard_Rocket.setRotationAngles(ModelHoverboard_Rocket.java:215)
	at com.webs.arkif.models.ModelHoverboard_Rocket.func_78088_a(ModelHoverboard_Rocket.java:159)
	at com.webs.arkif.render.RenderHoverboardRockets.renderHoverboard(RenderHoverboardRockets.java:60)
	at com.webs.arkif.render.RenderHoverboardRockets.func_76986_a(RenderHoverboardRockets.java:70)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1014)
	at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:365)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_430_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.webs.arkif.models.ModelHoverboard_Rocket.setRotationAngles(ModelHoverboard_Rocket.java:215)
	at com.webs.arkif.models.ModelHoverboard_Rocket.func_78088_a(ModelHoverboard_Rocket.java:159)
	at com.webs.arkif.render.RenderHoverboardRockets.renderHoverboard(RenderHoverboardRockets.java:60)
	at com.webs.arkif.render.RenderHoverboardRockets.func_76986_a(RenderHoverboardRockets.java:70)

-- Entity being rendered --
Details:
	Entity Type: hoverboard.EntityHoverboardRocket (com.webs.arkif.entities.EntityHoverboardRockets)
	Entity ID: 485
	Entity Name: entity.hoverboard.EntityHoverboardRocket.name
	Entity's Exact location: 232.90, 69.60, 110.36
	Entity's Block location: World: (232,69,110), Chunk: (at 8,4,14 in 14,6; contains blocks 224,0,96 to 239,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.35, 0.40, -0.19

-- Renderer details --
Details:
	Assigned renderer: com.webs.arkif.render.RenderHoverboardRockets@2773c24
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1014)
	at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:365)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_430_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['MinerManKCMB'/331, l='MpServer', x=403.99, y=74.12, z=202.14]]
	Chunk stats: MultiplayerChunkCache: 37, 46
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (244,64,240), Chunk: (at 4,4,0 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3422997 game time, 554692 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 97 total; [EntitySittableBlock['entity.cfm.MountableBlock.name'/188455, l='MpServer', x=405.50, y=73.60, z=200.50], EntitySilverfish['Silverfish'/796970, l='MpServer', x=-9.83, y=-0.06, z=-30.61], EntitySittableBlock['entity.cfm.MountableBlock.name'/202034, l='MpServer', x=405.50, y=73.60, z=200.50], EntityTrail['unknown'/1083, l='MpServer', x=403.99, y=74.12, z=202.14], EntityTrite['Trite'/771392, l='MpServer', x=26.56, y=-27.62, z=-16.09], EntityClientPlayerMP['MinerManKCMB'/331, l='MpServer', x=403.99, y=74.12, z=202.14], EntityHat['unknown'/350, l='MpServer', x=403.99, y=74.12, z=202.14], EntityItem['item.tile.woodSlab.oak'/892540, l='MpServer', x=398.34, y=67.13, z=203.69], EntityCaveSpider['Cave Spider'/772238, l='MpServer', x=16.40, y=-28.62, z=-15.86], EntityHat['unknown'/798340, l='MpServer', x=395.72, y=67.00, z=205.75], EntityHat['unknown'/798341, l='MpServer', x=378.41, y=67.00, z=183.28], EntityHat['unknown'/798337, l='MpServer', x=380.22, y=67.00, z=177.47], EntityHat['unknown'/798338, l='MpServer', x=412.78, y=67.00, z=205.56], EntityHat['unknown'/798339, l='MpServer', x=406.50, y=68.00, z=205.61], EntityHat['unknown'/800412, l='MpServer', x=399.94, y=67.00, z=163.94], EntityHat['unknown'/800410, l='MpServer', x=399.94, y=67.00, z=175.06], EntityHat['unknown'/800411, l='MpServer', x=400.69, y=67.00, z=166.66], EntitySilverfish['Silverfish'/780945, l='MpServer', x=-0.31, y=-0.03, z=-62.66], EntityHorse['Horse'/798124, l='MpServer', x=392.09, y=67.00, z=196.34], EntityHorse['Horse'/798125, l='MpServer', x=391.91, y=67.00, z=198.06], EntityHuman['Leven the Mason'/798126, l='MpServer', x=388.44, y=67.00, z=193.72], EntityHuman['Piers the Librarian'/798127, l='MpServer', x=415.31, y=71.00, z=205.31], EntityCandyWolf['Choco-dog'/798121, l='MpServer', x=380.50, y=67.00, z=215.50], EntityHuman['Drake the Toolsmith'/798122, l='MpServer', x=407.75, y=67.00, z=213.34], EntityHuman['Enzo the Farmer'/798123, l='MpServer', x=382.41, y=67.00, z=177.50], EntityHuman['Moemi the Weaponsmith'/798140, l='MpServer', x=393.00, y=67.00, z=204.94], EntityHuman['Norman the Guard'/798141, l='MpServer', x=411.69, y=67.00, z=190.50], EntityHuman['Lexie the Guard'/798142, l='MpServer', x=403.03, y=67.00, z=176.31], EntityHuman['Caiden the Guard'/798143, l='MpServer', x=403.03, y=67.00, z=176.31], EntityHuman['Xena the Miner'/798136, l='MpServer', x=412.78, y=67.00, z=205.56], EntityHuman['Noelle the Shepherd'/798137, l='MpServer', x=385.50, y=67.00, z=199.84], EntityHuman['Erin the Fletcher'/798139, l='MpServer', x=406.50, y=68.00, z=205.61], EntityHuman['Yvette the Miner'/798132, l='MpServer', x=401.75, y=67.00, z=192.56], EntityHuman['Coby the Miner'/798133, l='MpServer', x=387.50, y=67.00, z=190.78], EntityHuman['Ira the Fisherman'/798134, l='MpServer', x=378.41, y=67.00, z=183.28], EntityHuman['Elijah the Guard'/798135, l='MpServer', x=398.23, y=67.00, z=213.26], EntityHuman['Lea the Shepherd'/798129, l='MpServer', x=382.50, y=67.00, z=184.50], EntityHuman['Katherine the Librarian'/798130, l='MpServer', x=391.31, y=67.00, z=185.69], EntityHuman['Turner the Mason'/798131, l='MpServer', x=391.41, y=67.00, z=184.66], EntityHuman['Jakob the Shepherd'/798156, l='MpServer', x=380.22, y=67.00, z=177.47], EntityHuman['Archer the Toolsmith'/798157, l='MpServer', x=386.25, y=67.00, z=210.50], EntityHuman['Jane the Butcher'/798158, l='MpServer', x=374.69, y=67.00, z=192.50], EntityHuman['Forest the Mason'/798159, l='MpServer', x=399.94, y=67.00, z=175.06], EntityHuman['Preston the Baker'/798152, l='MpServer', x=403.03, y=67.00, z=176.69], EntityHuman['Nico the Leatherworker'/798153, l='MpServer', x=407.76, y=67.00, z=206.41], EntityHuman['Alec the Leatherworker'/798155, l='MpServer', x=409.28, y=67.00, z=210.69], EntityHuman['Beccy the Guard'/798148, l='MpServer', x=403.69, y=67.00, z=176.31], EntityHuman['Aaliyah the Guard'/798149, l='MpServer', x=403.03, y=67.00, z=176.31], EntityHuman['Rain the Guard'/798150, l='MpServer', x=403.69, y=67.00, z=176.97], EntityHuman['Evan the Archer'/798151, l='MpServer', x=403.03, y=67.00, z=176.69], EntityHuman['Honor the Guard'/798144, l='MpServer', x=403.69, y=67.00, z=176.97], EntityHuman['Petrie the Child'/798145, l='MpServer', x=403.03, y=67.00, z=176.31], EntityHuman['Demi the Guard'/798146, l='MpServer', x=403.69, y=67.00, z=176.97], EntityHuman['Claris the Guard'/798147, l='MpServer', x=403.03, y=67.00, z=176.31], EntityHorse['Horse'/207, l='MpServer', x=349.03, y=63.75, z=244.19], EntityHuman['Fawn the Guard'/798172, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Alec the Guard'/798173, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Elisa the Guard'/798174, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Tala the Toolsmith'/798175, l='MpServer', x=387.34, y=67.00, z=177.41], EntityHuman['Clare the Guard'/798168, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHorse['Horse'/213, l='MpServer', x=359.03, y=66.00, z=248.97], EntityHuman['Joel the Guard'/798169, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Toby the Shepherd'/798170, l='MpServer', x=399.94, y=67.00, z=175.06], EntityHuman['Owen the Guard'/798171, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Fabio the Guard'/798164, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Ira the Guard'/798165, l='MpServer', x=399.94, y=67.00, z=175.06], EntityHuman['Delany the Toolsmith'/798166, l='MpServer', x=399.94, y=67.00, z=175.06], EntityHuman['Montana the Guard'/798167, l='MpServer', x=399.94, y=67.00, z=163.94], EntityHuman['Fabio the Guard'/798160, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Zora the Butcher'/798161, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Sean the Guard'/798162, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Becca the Farmer'/798163, l='MpServer', x=399.94, y=67.00, z=175.06], EntityHuman['Layne the Weaponsmith'/798188, l='MpServer', x=400.69, y=67.00, z=175.06], EntityHuman['Mavis the Armorer'/798189, l='MpServer', x=400.69, y=67.00, z=175.06], EntityHuman['Cleo the Weaponsmith'/798190, l='MpServer', x=400.69, y=67.00, z=175.06], EntityHuman['Saira the Leatherworker'/798191, l='MpServer', x=400.69, y=67.00, z=175.06], EntitySkeleton['Skeleton'/772079, l='MpServer', x=-13.47, y=-39.62, z=4.89], EntityHuman['Lyric the Guard'/798184, l='MpServer', x=400.69, y=67.00, z=174.16], EntityHuman['Raquel the Fletcher'/798185, l='MpServer', x=400.69, y=67.00, z=175.06], EntityHuman['Tess the Archer'/798186, l='MpServer', x=400.69, y=67.00, z=175.06], EntityHuman['Vlad the Cleric'/798187, l='MpServer', x=400.69, y=67.00, z=175.06], EntityHuman['Elijah the Guard'/798180, l='MpServer', x=400.69, y=67.00, z=166.66], EntityHuman['Erin the Guard'/798181, l='MpServer', x=400.69, y=67.00, z=167.28], EntityHuman['Aleah the Guard'/798182, l='MpServer', x=399.94, y=67.00, z=165.97], EntityHuman['Paul the Toolsmith'/798183, l='MpServer', x=395.72, y=67.00, z=205.75], EntityHuman['Cedric the Guard'/798176, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Arran the Guard'/798177, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Keeley the Butcher'/798178, l='MpServer', x=399.94, y=67.00, z=172.94], EntityHuman['Tess the Guard'/798179, l='MpServer', x=399.94, y=67.00, z=163.94], EntityHuman['Evan the Archer'/798196, l='MpServer', x=400.69, y=67.00, z=172.94], EntityHuman['Jamie the Guard'/798197, l='MpServer', x=400.69, y=67.00, z=168.06], EntityHuman['Forest the Weaponsmith'/798198, l='MpServer', x=406.59, y=67.00, z=210.00], EntityHuman['Carol the Guard'/798199, l='MpServer', x=399.94, y=67.00, z=165.16], EntityHuman['Aaliyah the Guard'/798192, l='MpServer', x=400.69, y=67.00, z=175.06], EntityHuman['Kaden the Fletcher'/798193, l='MpServer', x=400.69, y=67.00, z=175.06], EntityHuman['Dena the Baker'/798194, l='MpServer', x=400.69, y=67.00, z=172.94], EntityHuman['Acacia the Armorer'/798195, l='MpServer', x=400.69, y=67.00, z=172.94]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 56741432 bytes (54 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: XRay v2.14.2 MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1541 Optifine OptiFine_1.7.10_HD_U_C1 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1541-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1541} [Minecraft Forge] (forge-1.7.10-10.13.4.1541-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
	UCHIJAAAA	RenderPlayerAPI{1.3} [Render Player API] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) 
	UCHIJAAAA	SC0_SpaceCore{0.7.14} [SpaceCore] (SpaceCore-1.7.10.jar) 
	UCHIJAAAA	SC0_Wings{1.2.6} [Survival Wings] (1.7.10-Survival-Wings-1.2.6.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHIJAAAA	aether{Alpha 1.7.10-1.2} [Aether II] (Aether-2-1.7.10.jar) 
	UCHIJAAAA	animatedplayer{1.5.1} [Animated Player Mod] (Animated-Player-Mod-1.7.10.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.26.1.55} [Armourer's Workshop] (Armourers-Workshop-Mod-1.7.10.jar) 
	UCHIJAAAA	asielib{0.2.7} [asielib] (AsieLib-1.7.10.zip) 
	UCHIJAAAA	battlemusic{1.5} [Battle Music] (Battle-Music-Mod-1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-Mod-1.7.10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	SC0_BiomeWand{1.1.9} [Biome Wand] (Biome-Wand-Mod-1.7.10.jar) 
	UCHIJAAAA	speedytoolsmod{2.1.0} [Build Faster Mod] (Build-Faster-Mod-1.7.10.zip) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.13} [BuildCraft] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.13} [BC Builders] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.13} [BC Transport] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.13} [BC Energy] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.13} [BC Silicon] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.13} [BC Robotics] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.13} [BC Factory] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	candycraftmod{Beta 1.3} [CandyCraft] (CandyCraft-1.3.jar) 
	UCHIJAAAA	CarpentersBlocks{3.2.5} [Carpenter's Blocks] (Carpenters-Blocks-Mod-1.7.10.zip) 
	UCHIJAAAA	ClothingCraft{1.1.1} [ClothingCraft] (ClothingCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	crystalcraft{0.1} [CrystalCraft] (CrystalCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10} [CustomNpcs] (CustomNPCs_1.7.10.jar) 
	UCHIJAAAA	wonderfulwands{1.4.2} [Cyano's Wonderful Wands] (CyanosWonderfulWands-1.4.2.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	dinodim{1.1} [Dinosaur Dimensions] (DinoDimension-1.01.jar) 
	UCHIJAAAA	diversity{ALPHA 1.6.1} [Diversity] (Diversity-Mod-1.7.10.jar) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimeVoid-Library-1.7.10.jar) 
	UCHIJAAAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (Dynamic-Transport-Mod-1.7.10.jar) 
	UCHIJAAAA	ElementalItems{4.0.0} [Elemental Items mod] (Elemental-Items-Mod-1.7.10.zip) 
	UCHIJAAAA	emeraldmod{3.5.1} [EmeraldMod] (Emerald-Mod-1.7.10.jar) 
	UCHIJAAAA	etfuturum{1.2.1} [Et Futurum] (Et-Futurum-Mod-1.7.10.jar) 
	UCHIJAAAA	golems{1.15} [Extra Golems] (Extra-Golems[1.7.10]-1.15b.jar) 
	UCHIJAAAA	fairylights{0.6} [Fairy Lights] (Fairy-Lights-Mod-1.7.10.jar) 
	UCHIJAAAA	pixelmoncore{1.7.2} [FandomCraft] (FandomCraft-Mod-1.7.10.zip) 
	UCHIJAAAA	MinecraftDonaldsMod{v2.0} [MinecraftDonaldsMod] (Fast-Food-Mod-1.7.10.zip) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (Gravity-Gun-Mod-1.7.10.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-Mod-1.7.10.jar) 
	UCHIJAAAA	hoverboard{Pre-Alpha} [Hoverboard Mod by Arkif] (Hoverboard-Mod-1.7.10.jar) 
	UCHIJAAAA	InventoryPets{1.3.2} [Inventory Pets] (Inventory-Pets-Mod-1.7.10.jar) 
	UCHIJAAAA	ism{8.0.0} [MaggiCraft's Instant Structures Mod] (ism-8.0.0.jar) 
	UCHIJAAAA	LotsOfFood{1.7.10} [Lots of Food] (Lots of Food-1.7.10.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) 
	UCHIJAAAA	lycanitesmobs{1.7.0 - MC 1.7.10} [Lycanites Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	arcticmobs{1.7.0 - MC 1.7.10} [Lycanites Arctic Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	demonmobs{1.7.0 - MC 1.7.10} [Lycanites Demon Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	desertmobs{1.7.0 - MC 1.7.10} [Lycanites Desert Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	forestmobs{1.7.0 - MC 1.7.10} [Lycanites Forest Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	infernomobs{1.7.0 - MC 1.7.10} [Lycanites Inferno Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	junglemobs{1.7.0 - MC 1.7.10} [Lycanites Jungle Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	mountainmobs{1.7.0 - MC 1.7.10} [Lycanites Mountain Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	plainsmobs{1.7.0 - MC 1.7.10} [Lycanites Plains Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	saltwatermobs{1.7.0 - MC 1.7.10} [Lycanites Saltwater Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	swampmobs{1.7.0 - MC 1.7.10} [Lycanites Swamp Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.12.10} [MalisisCore] (malisiscore-1.7.10-0.12.10.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.10.1} [Malisis' Doors] (malisisdoors-1.7.10-1.10.1.jar) 
	UCHIJAAAA	majora{1.0.0 Alpha} [Majora's MaskCraft] (Maskcraft-Mod-1.7.10.jar) 
	UCHIJAAAA	RadixCore{2.0.2} [RadixCore] (RadixCore-2.0.2-1.7.10-universal.jar) 
	UCHIJAAAA	MCA{5.0.6} [Minecraft Comes Alive] (MCA-5.0.6-1.7.10-universal.jar) 
	UCHIJAAAA	mythril{1.6} [Mythril mod] (Mithril-mod-by-dawars-1.7.2.jar) 
	UCHIJAAAA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJAAAA	MSM3{3.0.0d} [More Swords 3] (MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) 
	UCHIJAAAA	musiccraft{2.9.8.3} [MusicCraft] (musiccraft-2.9.8.3.jar) 
	UCHIJAAAA	MutantCreatures{1.4.9} [Mutant Creatures] (Mutant-Creatures-Mod-1.7.10.jar) 
	UCHIJAAAA	Mystcraft{0.11.0.00} [Mystcraft] (Mystcraft-Mod-1.7.10.jar) 
	UCHIJAAAA	necromancy{1.7.0} [Necromancy] (Necromancy-Mod-1.7.10.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-5} [PortalGun] (Portal-Gun-Mod-1.7.10.jar) 
	UCHIJAAAA	cuchaz.powerTools{1.7.10-1.3} [Power Tools] (powerTools-v1.7.10-1.3.jar) 
	UCHIJAAAA	Real Kether{1.2.5alpha} [The Real Kether] (Real-Kether-Dimension-Mod-1.7.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	rfguns{0.0.1} [RF Guns] (rfguns-0.0.1.jar) 
	UCHIJAAAA	soulforest{1.9.3} [Soul Forest Mod] (Soul-Forest-Mod-1.7.10.jar) 
	UCHIJAAAA	statues{2.1.3} [Statues] (Statues-Mod-1.7.10.zip) 
	UCHIJAAAA	steveuniverse{1.0.2} [Steve's Universe] (Steves-Universe-Mod-1.7.10.jar) 
	UCHIJAAAA	tamedmobs{???} [§cTamed Mobs] (Tamed-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	kitchen{1.2.2} [The Kitchen Mod] (The-Kitchen-Mod-1.7.10.jar) 
	UCHIJAAAA	toolsdoneright{1.1.3} [Tools Done Right] (Tools Done Right by NukeDuck [1.7.10][1.1.3].zip) 
	UCHIJAAAA	WirelessRedstoneCore{1.8.0.0} [Wireless Redstone] (Wireless-Redstone-Mod-1.7.2.jar) 
	UCHIJAAAA	worldtools{1.1.1} [World Tools] (World-Tools-Mod-1.7.10.jar) 
	UCHIJAAAA	XaeroMinimap{1.6.1.2} [Xaero's Minimap] (xaeros_minimap_v1.6.1.2_Forge_1.7.10.jar) 
	UCHIJAAAA	YAFM{1.0.3} [Yet Another Food Mod] (Yet-Another-Food-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4256' Renderer: 'Intel(R) HD Graphics'
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	rfguns: Lacking version information.
	Launched Version: 1.7.10-Forge10.13.4.1541-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Tamaized** [comment]
whatever mod "com.webs.arkif.models" is whats causing the issue. Looks like ModelHoverboard_Rocket fails to render while in the Morph GUI.

**Comment by MinerManKCMB** [comment]
@Tamaized Oh. Thanks. I'll try uninstalling it.

**Comment by MinerManKCMB** [comment]
@Tamaized It worked! Thanks! XD!
