### ISSUE TITLE
Glitch morphing into one-block high entities

### ISSUE THREAD

**Issue by PurpleRavenX11** [iChun/Morph#778]
I'm running a custom modpack with the latest Morph and Util installed. Whenever I morph into a mob that is one block tall, my character gets sucked into the ground diagonally, eventually being pulled into blocks and suffocating. I've played with it extensively and it seems to happen with only one-block tall entities and only those that are one block tall, other morphs (even giant ones) work fine. It is the same in Survival and Creative and no amount of flying, moving, or sneaking makes any difference. I've got a short video clip of this happening if it's helpful (screenshot doesn't exactly work here). Thanks.

**Comment by PurpleRavenX11** [comment]
Sorry meant *all* one-block tall entities and only those.

**Comment by iChun** [comment]
Is there another mod trying very hard to set the mob size?

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/796
