### ISSUE TITLE
How do I add flight to custom mobs?

### ISSUE THREAD

**Issue by Tokoshoran** [iChun/Morph#780]
I'm playing with a modpack that makes use of the questbook, and requires you to be able to fly pretty early. Normally, this would be done by finding a bat and visiting the nether, but I've only been able to encounter mobs known as "Rabid bat," which, despite their ability to fly, don't have that morph ability.

The config offers a link to https://raw.githubusercontent.com/iChun/Morph/master/src/main/resources/assets/morph/mod/AbilitySupport.json, do we have to make our own file on github with additional mobs, and link to that in our server config file?

**Comment by iChun** [comment]
Make a pull request to add the abilities to that file, I'll go through them when I can and if appropriate, I'll pull the abilities to the main repo. https://github.com/iChun/Morph/issues/796
