### ISSUE TITLE
Adding abilities to currently unsupported mob entities

### ISSUE THREAD

**Issue by Ally1177** [iChun/Morph#781]
Hello. Recently I've installed the exotic birds mod for mine craft (it's a very new mod) and I've edited the .json for ModMobAbility support (its uploaded as a txt here) and added flight to the birds (under avocado). However, when I entered the game the abilities still do not render. Is it now impossibe to add mod supported abilities, since the mod mob mapping has been removed?
[AbilitySupport.txt](https://github.com/iChun/Morph/files/67613/AbilitySupport.txt)

**Comment by Ally1177** [comment]
Correction: pavocado, not avocado

**Comment by iChun** [comment]
You need to tell Morph to load the local version of the mod mob abilities. I would however have appreciated if you submitted a pull request to add those abilities to morph's mappings though! https://github.com/iChun/Morph/issues/796
