### ISSUE TITLE
When morphing into anything not vanilla, i start moving in a direction, with no stop.

### ISSUE THREAD

**Issue by Froosty11** [iChun/Morph#784]
I have no idea what is causing this, tried it with alot of morphs, seems to only happen with stuff that has small/big models, like Rat from MoCreatures and Irongolem. This can even make u go through walls, or suffocate u. Does not happen with all the stuff that is 2 blocks or so...

Theres no log or anything...

**Comment by Froosty11** [comment]
I could get a log, for the mods, if u need it.

**Comment by pchard** [comment]
I have this exact same problem...

**Comment by RadioactiveStud** [comment]
I did some testing and it seems to be a conflict with the core mod LLibrary.

**Comment by pchard** [comment]
Yes, I did this too.. And figured out, the LLibrary version 0.3.2 works fine with Morph.

**Comment by Froosty11** [comment]
Thx :3

**Comment by Froosty11** [comment]
Gonna try it

**Comment by iChun** [comment]
Is this still an issue? It normally happens when there's a mod trying to set the size of the player constantly when the player is morphing.

**Comment by Froosty11** [comment]
Yes kinda cause u need an old version of LLibrary which means u can only use old mods...

**Comment by iChun** [comment]
Has the author of LLibrary responded to this issue?

**Comment by pchard** [comment]
No, but I can bring it up to iLexiconn.
2. feb. 2016 15:57 skrev "iChun" <notifications@github.com>:

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
