### ISSUE TITLE
Shutting down internet server on startup

### ISSUE THREAD

**Issue by oks1998** [iChun/Morph#786]
when i start singleplayer map, it is running but after i can see the gui interface in game, it just suddenly show shutting down server and show 
a fatal error occur something like that, and just quit the game and back to multiplayer server page?!

(later i will post full log and photo as reference)

**Comment by oks1998** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9070825/12225460/fbaeba88-b845-11e5-8819-e7ecf1889feb.png)
![asd](https://cloud.githubusercontent.com/assets/9070825/12225461/fbb5ccd8-b845-11e5-867c-d4b39f7202fd.png)
![asdd](https://cloud.githubusercontent.com/assets/9070825/12225462/fbb7b138-b845-11e5-86ad-dada8be8bb78.png)

**Comment by oks1998** [comment]
http://4gp.tw/ba3s/1452476411565.txt

sorry for big log file and i only found this website can upload large log file

**Comment by iChun** [comment]
I think you'll have to try a clean install. It looks like your authlib is outdated/modified or something. I don't think there's much I can do in Morph's code.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
