### ISSUE TITLE
Game Crashes when I hit the access key

### ISSUE THREAD

**Issue by Shashikur** [iChun/Morph#787]
Hey dude, every time I try to use the access key for the GUI, the whole game crashes and I gotta restart it. I'll post the file so you can see it. Could ya lend me a hand? :)

UPDATE: Also, just found out, it ALSO crashes when I try to open my survival inv. when in GM1.

**Comment by Shashikur** [comment]
---- Minecraft Crash Report ----
// You're mean.

Time: 1/13/16 1:20 AM
Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.client.model.ModelBiped cannot be cast to noppes.mpm.client.model.ModelMPM
	at noppes.mpm.client.RenderMPM.setEntity(RenderMPM.java:420)
	at noppes.mpm.client.RenderEvent.pre(RenderEvent.java:78)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_113_RenderEvent_pre_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:804)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at noppes.mpm.client.RenderMPM.setEntity(RenderMPM.java:420)
	at noppes.mpm.client.RenderEvent.pre(RenderEvent.java:78)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_113_RenderEvent_pre_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
	Entity ID: 293
	Entity Name: Shashik
	Entity's Exact location: -29.50, 71.62, 201.50
	Entity's Block location: World: (-30,71,201), Chunk: (at 2,4,9 in -2,12; contains blocks -32,0,192 to -17,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00

-- Renderer details --
Details:
	Assigned renderer: RenderPlayerOF@6ee1933
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:804)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (423, 256). Absolute: (846, 193)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Shashik'/293, l='MpServer', x=-29.50, y=71.62, z=201.50]]
	Chunk stats: MultiplayerChunkCache: 441, 450
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-33,64,204), Chunk: (at 15,4,12 in -3,12; contains blocks -48,0,192 to -33,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1072 game time, 1072 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 127 total; [EntityTrail['unknown'/1040, l='MpServer', x=-29.50, y=71.62, z=201.50], EntitySheep['Sheep'/37, l='MpServer', x=-98.53, y=68.00, z=159.47], EntityBat['Bat'/38, l='MpServer', x=-105.25, y=27.00, z=163.97], EntityBat['Bat'/39, l='MpServer', x=-99.44, y=28.00, z=168.97], EntityClientPlayerMP['Shashik'/293, l='MpServer', x=-29.50, y=71.62, z=201.50], EntitySheep['Sheep'/40, l='MpServer', x=-102.84, y=70.00, z=165.13], EntitySkeleton['Skeleton'/41, l='MpServer', x=-109.50, y=24.00, z=238.50], EntityWitch['Witch'/42, l='MpServer', x=-107.97, y=29.00, z=232.50], EntityBat['Bat'/43, l='MpServer', x=-100.78, y=35.00, z=231.75], EntityBat['Bat'/44, l='MpServer', x=-103.38, y=33.00, z=222.50], EntityEnderman['Enderman'/45, l='MpServer', x=-97.56, y=11.00, z=248.50], EntitySkeleton['Skeleton'/46, l='MpServer', x=-98.50, y=29.00, z=249.50], EntitySkeleton['Skeleton'/47, l='MpServer', x=-98.50, y=29.00, z=250.50], EntityWarg['Warg'/48, l='MpServer', x=-97.60, y=48.00, z=298.52], EntitySheep['Sheep'/50, l='MpServer', x=-93.50, y=67.00, z=159.50], EntityPig['Pig'/51, l='MpServer', x=-83.44, y=64.00, z=181.47], EntityPig['Pig'/52, l='MpServer', x=-80.19, y=64.00, z=175.50], EntitySheep['Sheep'/53, l='MpServer', x=-95.66, y=68.00, z=160.31], EntitySheep['Sheep'/54, l='MpServer', x=-79.31, y=63.00, z=156.75], EntitySheep['Sheep'/55, l='MpServer', x=-80.19, y=67.00, z=175.44], EntitySheep['Sheep'/56, l='MpServer', x=-84.53, y=65.00, z=183.53], EntitySheep['Sheep'/57, l='MpServer', x=-83.03, y=64.00, z=183.63], EntitySheep['Sheep'/58, l='MpServer', x=-84.53, y=64.00, z=182.25], EntityPig['Pig'/59, l='MpServer', x=-87.50, y=66.00, z=178.50], EntityPig['Pig'/60, l='MpServer', x=-87.06, y=68.00, z=167.06], EntityBat['Bat'/61, l='MpServer', x=-96.63, y=23.00, z=241.72], EntityBat['Bat'/62, l='MpServer', x=-77.25, y=43.00, z=250.06], EntityWitch['Witch'/63, l='MpServer', x=-85.50, y=43.00, z=245.50], EntityWitch['Witch'/64, l='MpServer', x=-84.50, y=43.00, z=245.50], EntitySkeleton['Skeleton'/65, l='MpServer', x=-75.56, y=43.00, z=252.06], EntitySkeleton['Skeleton'/66, l='MpServer', x=-87.88, y=45.00, z=255.50], EntitySkeleton['Skeleton'/67, l='MpServer', x=-92.22, y=47.00, z=261.53], EntitySkeleton['Skeleton'/68, l='MpServer', x=-93.50, y=15.00, z=273.50], EntityWitch['Witch'/69, l='MpServer', x=-85.50, y=18.00, z=277.50], EntityWitch['Witch'/70, l='MpServer', x=-83.50, y=18.00, z=277.50], EntityWarg['Warg'/72, l='MpServer', x=-95.52, y=48.00, z=298.48], EntitySheep['Sheep'/79, l='MpServer', x=-64.50, y=63.00, z=153.50], EntityChicken['Chicken'/80, l='MpServer', x=-78.50, y=63.00, z=176.50], EntitySkeleton['Skeleton'/81, l='MpServer', x=-73.50, y=29.00, z=247.50], EntitySkeleton['Skeleton'/82, l='MpServer', x=-83.91, y=46.00, z=253.53], EntitySkeleton['Skeleton'/83, l='MpServer', x=-76.66, y=44.00, z=254.69], EntityBat['Bat'/84, l='MpServer', x=-74.28, y=43.00, z=248.44], EntityBat['Bat'/85, l='MpServer', x=-68.34, y=43.00, z=252.75], EntityBat['Bat'/86, l='MpServer', x=-79.50, y=43.00, z=243.25], EntityBat['Bat'/87, l='MpServer', x=-75.06, y=43.00, z=245.47], EntityBat['Bat'/88, l='MpServer', x=-75.00, y=43.00, z=252.50], EntitySkeleton['Skeleton'/89, l='MpServer', x=-76.44, y=44.00, z=253.59], EntitySkeleton['Skeleton'/90, l='MpServer', x=-79.50, y=43.00, z=245.50], EntitySkeleton['Skeleton'/91, l='MpServer', x=-77.50, y=44.00, z=251.97], EntityItem['item.item.arrow'/93, l='MpServer', x=-75.53, y=44.13, z=253.81], EntityItem['item.item.bone'/94, l='MpServer', x=-75.69, y=44.13, z=254.31], EntityItem['item.item.arrow'/95, l='MpServer', x=-74.34, y=44.13, z=253.78], EntityItem['item.item.bone'/96, l='MpServer', x=-76.13, y=44.13, z=255.19], EntityBat['Bat'/97, l='MpServer', x=-77.72, y=25.00, z=272.63], EntitySkeleton['Skeleton'/98, l='MpServer', x=-73.50, y=26.00, z=262.94], EntityItem['item.item.bone'/99, l='MpServer', x=-76.34, y=46.13, z=257.78], EntitySheep['Sheep'/105, l='MpServer', x=-45.47, y=70.08, z=203.24], EntitySkeleton['Skeleton'/106, l='MpServer', x=-48.50, y=27.00, z=206.50], EntitySkeleton['Skeleton'/107, l='MpServer', x=-49.50, y=27.00, z=206.50], EntitySheep['Sheep'/108, l='MpServer', x=-55.44, y=63.00, z=251.41], EntitySheep['Sheep'/109, l='MpServer', x=-57.78, y=63.00, z=250.13], EntitySheep['Sheep'/110, l='MpServer', x=-58.25, y=63.00, z=251.28], EntitySheep['Sheep'/111, l='MpServer', x=-45.78, y=63.00, z=254.19], EntitySkeleton['Skeleton'/112, l='MpServer', x=-57.53, y=24.00, z=280.53], EntitySkeleton['Skeleton'/113, l='MpServer', x=-58.50, y=24.00, z=278.50], EntitySkeleton['Skeleton'/114, l='MpServer', x=-56.63, y=24.00, z=280.63], EntitySheep['Sheep'/119, l='MpServer', x=-47.41, y=75.00, z=189.47], EntitySheep['Sheep'/120, l='MpServer', x=-58.75, y=68.00, z=189.53], EntitySheep['Sheep'/121, l='MpServer', x=-42.50, y=69.00, z=191.50], EntitySheep['Sheep'/122, l='MpServer', x=-34.31, y=77.00, z=179.41], EntityBat['Bat'/123, l='MpServer', x=-22.75, y=21.05, z=211.56], EntitySheep['Sheep'/131, l='MpServer', x=-15.91, y=72.00, z=190.09], EntitySheep['Sheep'/132, l='MpServer', x=-38.91, y=69.00, z=190.06], EntitySheep['Sheep'/133, l='MpServer', x=-30.09, y=70.00, z=203.50], EntitySheep['Sheep'/134, l='MpServer', x=-28.81, y=70.00, z=203.50], EntitySheep['Sheep'/135, l='MpServer', x=-37.34, y=70.00, z=217.44], EntitySheep['Sheep'/136, l='MpServer', x=-25.50, y=68.00, z=213.50], EntitySkeleton['Skeleton'/137, l='MpServer', x=-16.50, y=22.00, z=233.50], EntityEnderman['Enderman'/138, l='MpServer', x=-18.41, y=21.00, z=237.53], EntitySkeleton['Skeleton'/140, l='MpServer', x=-1.50, y=55.00, z=154.50], EntitySkeleton['Skeleton'/141, l='MpServer', x=-0.50, y=55.00, z=154.50], EntitySkeleton['Skeleton'/142, l='MpServer', x=-1.50, y=55.00, z=155.50], EntitySheep['Sheep'/144, l='MpServer', x=-21.81, y=77.00, z=169.75], EntityWarg['Warg'/145, l='MpServer', x=-2.56, y=47.00, z=178.51], EntitySkeleton['Skeleton'/146, l='MpServer', x=-1.50, y=23.00, z=214.50], EntitySkeleton['Skeleton'/147, l='MpServer', x=-0.50, y=33.00, z=210.50], EntitySkeleton['Skeleton'/148, l='MpServer', x=-15.50, y=22.00, z=236.50], EntitySkeleton['Skeleton'/149, l='MpServer', x=-0.50, y=11.00, z=261.50], EntitySkeleton['Skeleton'/150, l='MpServer', x=-5.31, y=14.00, z=269.56], EntityCreeper['Creeper'/151, l='MpServer', x=8.50, y=36.00, z=125.41], EntitySheep['Sheep'/153, l='MpServer', x=2.22, y=67.00, z=144.78], EntitySheep['Sheep'/154, l='MpServer', x=5.91, y=66.00, z=147.53], EntitySheep['Sheep'/155, l='MpServer', x=4.50, y=66.00, z=149.50], EntitySheep['Sheep'/156, l='MpServer', x=-0.84, y=66.00, z=146.66], EntitySkeleton['Skeleton'/157, l='MpServer', x=1.50, y=33.00, z=202.50], EntitySkeleton['Skeleton'/158, l='MpServer', x=4.88, y=13.00, z=252.44], EntitySheep['Sheep'/159, l='MpServer', x=17.38, y=67.00, z=240.25], EntitySheep['Sheep'/160, l='MpServer', x=14.84, y=67.00, z=240.94], EntitySheep['Sheep'/161, l='MpServer', x=16.38, y=68.00, z=246.47], EntitySheep['Sheep'/162, l='MpServer', x=16.44, y=66.00, z=233.19], EntitySkeleton['Skeleton'/170, l='MpServer', x=29.78, y=29.00, z=156.84], EntityYale['Yale'/178, l='MpServer', x=45.12, y=89.00, z=78.34], EntityYale['Yale'/179, l='MpServer', x=42.57, y=91.00, z=82.41], EntityYale['Yale'/180, l='MpServer', x=43.93, y=91.00, z=83.52], EntityYale['Yale'/181, l='MpServer', x=44.54, y=90.00, z=81.44], EntitySheep['Sheep'/187, l='MpServer', x=40.84, y=62.00, z=278.50], EntitySheep['Sheep'/188, l='MpServer', x=43.16, y=62.00, z=278.50], EntityYale['Yale'/199, l='MpServer', x=63.87, y=76.00, z=122.46], EntityYale['Yale'/200, l='MpServer', x=59.46, y=75.00, z=120.53], EntitySkeleton['Skeleton'/206, l='MpServer', x=50.84, y=43.00, z=277.50], EntitySkeleton['Skeleton'/207, l='MpServer', x=50.00, y=43.00, z=277.50], EntitySilex['Silex'/1236, l='MpServer', x=-71.45, y=60.00, z=159.55], EntitySilex['Silex'/1237, l='MpServer', x=-74.58, y=60.00, z=183.42], EntityYale['Yale'/214, l='MpServer', x=78.49, y=138.00, z=168.24], EntityYale['Yale'/215, l='MpServer', x=77.67, y=137.00, z=169.64], EntityYale['Yale'/216, l='MpServer', x=77.31, y=130.00, z=174.12], EntityYale['Yale'/217, l='MpServer', x=76.01, y=137.00, z=169.47], EntityEnderman['Enderman'/1243, l='MpServer', x=48.50, y=20.00, z=276.44], EntityItem['item.tile.doublePlant.rose'/1245, l='MpServer', x=-61.09, y=63.13, z=254.06], EntityWarg['Warg'/224, l='MpServer', x=74.47, y=33.00, z=265.47], EntityYale['Yale'/226, l='MpServer', x=85.06, y=74.00, z=95.06], EntityYale['Yale'/227, l='MpServer', x=80.31, y=74.00, z=88.31], EntityYale['Light Yale'/228, l='MpServer', x=88.53, y=74.00, z=93.78], EntityYale['Yale'/229, l='MpServer', x=86.46, y=74.00, z=95.62], EntityYale['Yale'/234, l='MpServer', x=83.55, y=81.00, z=118.39], EntityYale['Light Yale'/235, l='MpServer', x=81.60, y=87.00, z=117.60], EntityWarg['Warg'/239, l='MpServer', x=86.42, y=36.00, z=228.42]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 367057728 bytes (350 MB) / 1027465216 bytes (979 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 9, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 Optifine OptiFine_1.7.10_HD_U_C1 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) 
	UCHIJAAAA	lotr{Beta v26.5 for Minecraft 1.7.10} [The Lord of the Rings Mod] ([1.7.10] The Lord of the Rings Mod B26.5.jar) 
	UCHIJAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-fairplay.jar) 
	UCHIJAAAA	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	moreplayermodels{1.7.10} [MorePlayerModels] (More-Player-Models-2-Mod-1.7.10.jar) 
	UCHIJAAAA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCHIJAAAA	neiLotr{Alpha 0.2.2} [NEI Addon for the "The Lord of the Rings" Minecraft Mod] (neiLotr-Alpha 0.2.2.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [music.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by iChun** [comment]
Could you send this stack trace over to Noppes?
