### ISSUE TITLE
morphs not working properly

### ISSUE THREAD

**Issue by zane49er2** [iChun/Morph#788]
If I use A morph other than what I was when I logged on, I just get those grey blobs but never morph. I can't fit in small spaces, or place/break blocks properly, and my eye height doesn't change until I morph twice, when it will change eye height to the first morph's. If I relog or change to my original form it fixes most of the issues, apart from the block thing.

**Comment by Tamaized** [comment]
Always post the Morph version and a mod list.

**Comment by zane49er2** [comment]
newest morph, very custom pack.
1.7.10-Pistronics2-v0.5.5
1.7.10_AM2-1.4.0.008
advancedgenetics-1.7.10-1.5.9
AnimationAPI-1.7.10-1.2.4
AppleCore-mc1.7.10-1.0.2
appliedenergistics2-rv2-stable-10
ArchimedesShips-1.7.1
Aroma1997Core-1.7.10-1.0.2.14
AttachableGrinder-4.0.0
BacteriaMod-1.7.10-2.3.2
BetterChests-1.7.10-1.1.1.9
BiblioCraft[v1.9.2][MC1.7.10]
BigReactors-0.4.2A2
BiomesOPlentyMod
BloodMagic-1.7.10-1.3.3-17
buildcraft-6.4.3
Carpenter's Blocks v3.3.4.2 - MC 1.7.10
ChickenChunks-1.7.10-1.3.4.19-universal
Chisel2-2.4.1.40
CodeChickenCore-1.7.10-1.0.7.47-universal
CoFHCore-[1.7.10]3.0.2-262
compactmachines-1.7.10-1.17
ComputerCraft1.65
CustomNPCs_1.7.10c
darkcore-0.25-35
DeadlyWorld-1.7.10-1.0.2
DragonAPI 1.7.10 V9b
Enchiridion-1.7.X-1.2b
EnderCore-1.7.10-0.2.0.31_beta
EnderIO-1.7.10-2.3.0.422_beta
EnderStorage-1.7.10-1.4.7.37-universal
Ex-Nihilo-1.38-45
ExpandedRedstone 1.7.10 V9a
ExtraCells-1.7.10-2.3.7b176
extrautilities-1.2.1
fastcraft-1.21
forestry_1.7.10-3.3.0.6
FPSPlus-1.7.10
funky-locomotion-1.7.10-beta-4
Galacticraft-Planets-1.7-3.0.7.254
GalacticraftCore-1.7-3.0.7.254
gases-1.5.2-1.7.10
gasesCore-1.5.2-1.7.10
gasesFramework-1.0.6-1.7.10
gasesFrameworkCore-1.0.6-1.7.10
geochests-1.7.10-v1.2.3
growthcraft-bamboo-1.7.10-2.1.0
growthcraft-bees-1.7.10-2.1.0
growthcraft-cellar-1.7.10-2.1.0a
growthcraft-core-1.7.10-2.1.0a
growthcraft-grapes-1.7.10-2.1.0
growthcraft-hops-1.7.10-2.1.0
growthcraft-rice-1.7.10-2.1.0a
Guide-API-1.7.10-1.0.1-20
HardcoreEnderExpansion  MC-1.7.10  v1.6.7
Hats-4.0.1
IC2NuclearControl-2.1.2a
iChunUtil-4.2.2
industrialcraft-2-2.2.658-experimental
InventoryTweaks-1.58-147
ironchest-1.7.10-6.0.62.742-universal
Jabba-1.2.1a_1.7.10
JourneyMap5.0.1_Unlimited_MC1.7.10
logisticspipes-0.8.3.123
LunatriusCore-1.7.10-1.1.2.21-universal
Mantle-1.7.10-0.3.2
Mariculture-1.7.10-1.2.3d
Mekanism-1.7.10-7.1.1.127
MicdoodleCore-1.7-3.0.7.254
Minechem-1.7.10-5.0.5.406
MineFactoryReloaded-[1.7.10]2.8.0-104
ModularPowersuits-0.11.0.296
Morph-Beta-0.9.2
mystcraft-1.7.10-0.11.0.00
natura-1.7.10-2.2.0.1
neiaddons-1.12.14.40-mc1.7.10
NEIIntegration-MC1.7.10-1.0.13
NotEnoughItems-1.7.10-1.0.5.118-universal
Numina-0.4.0.131
OpenBlocks-1.7.10-1.3
OpenComputers-MC1.7.10-1.5.14.30-universal
OpenModsLib-1.7.10-0.6
OpenPeripheral-1.7.10-AIO-1
Pam's HarvestCraft 1.7.10f
Peripherals++-1.2.7
Photoreal-4.0.0
PneumaticCraft-1.7.10-1.4.4-47-universal
PortalGun-4.0.0-beta-6
ProjectE-1.7.10-PE1.9.3h
ProjectRed-1.7.10-4.5.15.75-Base
ProjectRed-1.7.10-4.5.15.75-Compat
ProjectRed-1.7.10-4.5.15.75-Integration
ProjectRed-1.7.10-4.5.15.75-Lighting
ProjectRed-1.7.10-4.5.15.75-Mechanical_beta
qCraft1.2
Railcraft_1.7.10-9.8.0.0
RandomThings-2.2.2
ReactorCraft 1.7.10 V9b
RotaryCraft 1.7.10 V9b
Schematica-1.7.10-1.7.6.121-universal
secretroomsmod-1.7.10-4.7.1.413
SimplyJetpacks-MC1.7.10-1.3.2
slick-util
SpiceOfLife-mc1.7.10-1.2.3
StevesCarts2.0.0.b18
StevesFactoryManagerA92
supercraftingframe-1.7.10.3
Sync-4.0.0
tardismod-1.7.10-0.985-178
TConstruct-1.7.10-1.8.2a
Thaumcraft-1.7.10-4.2.3.0
ThaumicInfusion
ThaumicTinkerer-2.5-1.7.10-162
ThermalDynamics-[1.7.10]1.0.0-122
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-81
TMechworks_mc1.7.10_0.2.8
Translocator-1.7.10-1.1.2.15-universal
twilightforest-1.7.10-2.3.2
Waila-1.5.10_1.7.10
WailaHarvestability-mc1.7.x-1.1.0
WR-CBE-1.7.10-1.4.1.9-universal
Ztones-1.7.10-2.2.1
[1.7.10]WorldStateCheckpoints-client-1.7.10.r03

**Comment by zane49er2** [comment]
Oh, and I did disable AM2's shrink effect.

**Comment by zane49er2** [comment]
It seems dimention-related.

**Comment by Tamaized** [comment]
Could you try to pinpoint which mod is causing this? I don't have the time to figure it out and i'm sure iChun doesn't either. You could then bring it up to the offending mod's author. And if this happens with morph alone then we have a problem.

**Comment by iChun** [comment]
Heh yeah what Tamaized said.

**Comment by zane49er2** [comment]
I am not sure, but I think it's tardismod and it isnt really a big issue.
