### ISSUE TITLE
Morphed into player, and crash when login to server

### ISSUE THREAD

**Issue by Baifish** [iChun/Morph#789]
I was playing on my modded server, and I enabled player morphs. But, when I tried to morph into my friend I crashed myself, and everyone on the server. I don't know whether this has to do with that he changed his skin but that before that it seemed fine. Any help?

Crash Report: http://pastebin.com/37JFFL4V
Mod List: https://gyazo.com/fbd508ae8d18d8e94c9a676dc0ad5274

I have tried resetting my pack and re-installing the morph mod on both my client and server. No luck though.
Thanks!

**Comment by Tamaized** [comment]
Do you play in offline mode on the server? We had this issue on my server before, setting it to online mode fixed it.

**Comment by Baifish** [comment]
No, the server is in Online mode. I'm not sure why it's doing this. His skin was 1.8 but then converted it to 1.7 because it wasn't showing properly, does that have anything to do with it? @Tamaized

**Comment by Tamaized** [comment]
Doubt it, I would send this crash report to the Aether team though as it's their problem.

**Comment by Baifish** [comment]
Alright! Will do, thanks!

**Comment by Tamaized** [comment]
I just realized this is 1.6.4, I don't think anyone supports 1.6 anymore.

**Comment by Baifish** [comment]
Oh really? I'm not sure what to do. @Tamaized

**Comment by Tamaized** [comment]
Not much you can do other than move to 1.7 or not use morph and aether together in 1.6

**Comment by iChun** [comment]
What Tamaized said, basically, but it's best you alert the Aether team, if they even intend on updating to MC 1.8.9 at this point. Morph is no longer supported for MC 1.6 or 1.7
