### ISSUE TITLE
Block breaking glitch

### ISSUE THREAD

**Issue by Terminathan** [iChun/Morph#791]
When im an animal less then 1 block, i try to break a block and it breaks the one infront or above :S

**Comment by iChun** [comment]
A mod is messing up with your eye height. A couple mods have been known to cause this but off the top of my head it might be Tinker's Construct or Ars Magica 2 right now, which I have heard has fixed this issue, so it's possible your mods might be outdated as well.

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/796
