### ISSUE TITLE
Fly error

### ISSUE THREAD

**Issue by Hansoeaung** [iChun/Morph#792]
I can not fly with morph mod even when I set up the config file. I think its your mod that don't work with other mods as well try to fix it or show us a list of mods that don't work with morph. Thanks

**Comment by Tamaized** [comment]
Prob another mod is setting the players flight to always be false

**Comment by Hansoeaung** [comment]
I know but I do not know what mod it is

**Comment by Tamaized** [comment]
That's why you figure it out and report it to that Author, this isn't Morph's issue.

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/796
