### ISSUE TITLE
Blocks don't break properly?!?!?!

### ISSUE THREAD

**Issue by Vortalos** [iChun/Morph#793]
Hey, uh, I dunno if anyone ever told you...
but breaking blocks is broken.
Whenever I'm an animal less than one block high it always breaks the block above it.
Since it's not fixed, I guess noone really noticed this until now.
So please work on this asap.
Kthxbye

**Comment by Vortalos** [comment]
![1287666826226](https://cloud.githubusercontent.com/assets/5983139/12540187/ddc4ec76-c304-11e5-98c7-e75fa1de2030.png)

**Comment by Vortalos** [comment]
![trollface](https://cloud.githubusercontent.com/assets/5983139/12540719/55a693e0-c30d-11e5-8656-26eb3c40055f.jpg)

**Comment by heldplayer** [comment]
I'd slap you so hard for this if I could.

**Comment by Vortalos** [comment]
Please refrain from posting such unnecessary and unhelpful comments, heldplayer.
I'm only trying to do the mod author a favour by pointing out flaws in his mod.
If anything, he should be grateful for my help.

**Comment by Tamaized** [comment]
Seriously...?

#791, #774, #708, #705, and i'm pretty sure there's a lot more duplicated of this. I'm just way too lazy to go and find them all for you...

**Comment by iChun** [comment]
@Tamaized : Ignore Vortalos in anything he does online, he made this issue
cause I complained while streaming about duplicate issues. I won't mention
which specific one in particular, though...
