### ISSUE TITLE
Morph 1.7.10 Support FAQ

### ISSUE THREAD

**Issue by iChun** [iChun/Morph#796]
# General Issues

Any issue posted that is of significant relevance to the issues listed here will be closed without notice and linked to this issue. Issues that are not helpful/non-descriptive will also be closed. Be sure to use a clear and understandable issue name. Use of smileys, emoji, "plz", "thx", "halp", and the sort in the issue title will result in the issue being closed without response.

If your issue is not listed here, feel free to make a new issue and I will try to address it when I can, however I will not be updating/fixing any issues in Morph for MC1.7.10 anymore as I would like to focus on the new Morph for MC1.12.2 when I can.

Oh, also make sure that Forge is updated to the latest version for the version of Minecraft you are running.

Shoutouts to Tamaized for trying to resolve people's issues here when I am incapable of doing so. This post is to somehow make their life and mine (and to some extent, yours too) easier.
# 

**I get kicked from the server/the mod crashes**
Bear in mind that this version of the mod is no longer supported, you may be able to find some helpful information here: https://github.com/iChun/Morph/issues/941

**I can't fly.**
Please read through this topic first, if the mod is not listed there please find out what mod is causing the issue and add it to that list: https://github.com/iChun/Morph/issues/457

**iChunUtil doesn't work with Morph**
Uh, yes it does, it actually requires it. Make sure you're using the right version of iChunUtil. For MC 1.7.10 it'll be iChunUtil 4.X.X. MC1.8, 5.X.X. MC1.8.9, 6.X.X, and so on.

**Disabling early game flight doesn't work**
I'm aware of the issue, however I will not be fixing it in any of the MC 1.7.10 builds.

**I have too many morphs that I crash/disconnect when I try to connect to the server**
I'm aware of the issue, this has been resolved for the MC1.12.2 version as it required a massive restructure of how Morph stores morphs.

**I can't morph into mod mobs**
Generally Morph should support mod mobs. However there are some exceptions. The criteria for morphs are that they have to be an EntityLivingBase. The mod you just killed might not be one. This is known to be an issue with Custom NPCs.

**My health isn't the same as the health my morph is supposed to have**
This is an issue I've noticed with some mod mobs which health changes the older they get. This is probably resolved in Morph for 1.12.2.

**None of the mobs have abilities**
Make sure abilities are enabled in the config. If they are, there is a chance you are running an outdated version of Chance Cubes or (unconfirmed) Roulette Ores. Please update them or let them know. Finding out the mod that causes this and letting both mod authors know would be helpful for us and people having the same issue in the future. No, not having an internet connection wouldn't cause this as Morph would fall back to the local version of abilities.

**Mob from Mod X/Y/Z should have Ability A/B/C**
Morph uses community-contributed mappings to define what mod mob has what abilities. If you see a mod mob without abilities you can contribute to them. You can find the mappings here: https://github.com/iChun/Morph/blob/master/src/main/resources/assets/morph/mod/AbilitySupport.json

**I edited the AbilitySupport.json file but the changes aren't working for some reason**
Morph gets the latest version of this file from GitHub every time you launch the game. You need to tell Morph to use the local version of the file in the config.

**I have too many of the same morphs!**
With the way Morph detects how morphs are "different", occasionally (especially with mods), the mob would have some kind of data that doesn't make it seem any different from others visually but seems different enough to the mod. Morph for 1.12.2 or later will attempt to resolve this better with mappings contributed by the community called NBT modifiers. These modifiers are somewhat available in Morph for MC 1.7.10 but no one has ever contributed to them.

**When I kill stuff I can see the morph animation but I don't/can't morph into them**
You no longer instantly morph to mobs you kill (it is a config option) as it becomes really annoying after a while especially when you have a lot of mods.

If you're talking about not being able to morph because all you see is your own character in the morph selector, be sure you aren't hitting the Morph favourites key (which is the ` key). Try opening the Morph selector keys (by default they are [ and ] on QWERTY keyboards, they differ on other keyboard settings)

**I move around when I'm morphing to something of a different size**
Most likely a mod conflict, probably another mod trying to set the size of the player whilst morph is trying to do the same. If you could find the conflicting mod and inform said mod author and myself know, that would be great. Ideally they should only be setting the size of the player when they should be, not on every tick even when they shouldn't (Yes, I'm looking at you, Tinker's Construct)

**When I am something smaller than 2 blocks, I suffocate in a 1 block space/I break the block above me**
Also most likely a mod conflict, some culprits were Ars Magica 2 and Tinker's Construct (IIRC), they're messing around with the eye height of the player just as morph is doing so. If you could find the conflicting mod and inform said mod author and myself know, that would be great.

**Boss morphs show the boss health bar**
With mobs that use Minecraft's boss health bar, this will be fixed in the MC 1.12.2 version of Morph. However, if the boss health bar is custom, as with Twilight Forest, it is limited what I can do about this.

**I have trouble with Mo' Creatures' mobs, I crash/disconnect when I try to morph into them**
This is known and I'm not very sure what I can do about it. I constantly get alerts from OpenEye about it. All I can say is that it would be best you do not put Mo' Creatures and Morph in the same mod pack.
# 

Any issue not posted here, if prevalent enough, will be added to the list (eventually).

Once again, thanks Tamaized, hope this makes your life a little easier.

**Comment by Syndaryl** [comment]
Is there documentation on how the potion ability works?  I'm reading through the code, but I still can't tell if it applies the potion to the morph shape, or the morph shape somehow applies it to other things (and when, like on-hit or something), or what.

**Comment by iChun** [comment]
Morph shape applies it to other things when the player attacks a mob. I'm not writing proper documentation for the Abilities since I will be changing them to an easier (hopefully) system for MC 1.8.9.

**Comment by Syndaryl** [comment]
No problem and no worries. Didn't mean to sound like I wanted you to rush out and write it, I thought I'd just missed it somewhere.

Regardless, that's enough context for me to figure things out from here well enough with the help of the sourcecode and the examples in the AbilitySupport.json

**Comment by iChun** [comment]
No not at all, I didn't feel like you were rushing me or anything like that. I was merely explaining as to why I've not done any documentation on it. I realise it's a flawed system in many ways and I'm hoping a proper redo would fix that.

**Comment by Esbeckett** [comment]
I figure I should ask here but, how does Morph read locally? Like, if I check to read local files, is it checking for a set path? How would it read the custom path? I was getting confused about that.

**Comment by GalacticSpike** [comment]
i started playing on a new modpack for 1.710 that as morph and some other mods i can morph into every single mob except for hostile mobs like zombies creepers skeletons because when i kill them i dont get their morphs like other mobs

**Comment by iiDogeWave** [comment]
When i go into the mods in the main menu of MC, i click on the mod, but theres no config option, i cant click on it so i cant change the options.... I downloaded ichununtil and morph. they're the ones you need to open with, with java because its a jar. i put it in the mods folder, i swear i did everything right.

**Comment by iiDogeWave** [comment]
I installed winrar and dont know which config to edit... I also dont know what text or line i edit...
