### ISSUE TITLE
Grimoire of Gaia 3 Abilities issue

### ISSUE THREAD

**Issue by tetsune** [iChun/Morph#797]
They used to load just fine before Grimoire of Gaia updated. I attempted to edit the .json file, but for some reason, the edit does not effect in-game. I would have thought it was because Grimoire of Gaia updated it's filing/sorting or something (turned to entity.gaia or something).

**Comment by tetsune** [comment]
To clarify, I modified the AbilitySupport.json from "gaia.entity.EntityGaiaAnubis" to "gaia.entity.**monster**.EntityGaiaAnubis", since Grimoire of Gaia 3 has added an additional folder to the entities to separate passive mobs from hostile mobs.

However, changing them has not done anything, unless I have something else I must do other than modify the AbilitySupport.json. The file names have not changed, I checked. This is with the newest version of both mods.

**Comment by Tamaized** [comment]
Try checking their language file for the real unlocalized name, folder path doesn't mean much.

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/796

You need to tell the mod to use the local version of the mappings. Preferably I'd like a Pull request though.

**Comment by iChun** [comment]
@Tamaized folder structure does matter in the terms of java packages, actually.

**Comment by Tamaized** [comment]
Hmm, I was thinking it used the unlocalized names (where folder structure wouldn't really have an impact) for mapping but then again I haven't looked at how Morph does the mapping...

**Comment by iChun** [comment]
It actually uses the class name of the mob, including the class package, so, that's required.

**Comment by tetsune** [comment]
Actually, I realized that it was because the config automatically pulls from the online AbilitySupport, not the local one. c: The fixes I made actually worked.

**Comment by iChun** [comment]
Yeah that's what I said, that's why I would like if you submitted a pull
request to fix it.
