### ISSUE TITLE
How do I change the config file so that I can fly?

### ISSUE THREAD

**Issue by zooskater** [iChun/Morph#800]
I have a problem that a lot of other people have, which is not being able to fly.
I don't know how to change the config file correctly so that it will work.

In case it will help, the other mods that I have installed are:

AetherII
Damage Indicators
Rei's Minimap
Battlegear II
TreeCapitator
NotEnoughItems
Mo'Creatures
Tail's Mod
MorePlayerModels II

Any help is appreciated. Thanks!

**Comment by Yanniclord** [comment]
Could you explain further? Do you get kicked when trying to fly, or is it just impossible to fly at all, like jumping or trying to fly does nothing. Please explain.

**Comment by RedDisaster** [comment]
Hey, I know this post was done a while ago, but if you guys see this, i could really use some help too.  Im having the same problem, I can't seem to fly as a bat etc.  I have my config file all set correctly so it should let me fly, but I dont even see the Flight symbol next to the bat icon.  Or the Float icon next to the chicken etc etc.  Any help with how to enable the icons to I can use the mob abilites would be awesome!

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
