### ISSUE TITLE
[Major] Ticking Entity Zombie

### ISSUE THREAD

**Issue by LokeYourLord** [iChun/Morph#801]
So on my server, when someone morphs, and then gets attacked by Zombie, the server crashes (this happens randomly).

Here the log: http://pastebin.com/6Kses1np

**Comment by drinfernoo** [comment]
I will have to get a log later, but that log sounds eerily familiar to me. I just started a world, and my world crashes any time I open the GUI (either with ~ or [ ]) :(

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
