### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by Vypah7** [iChun/Morph#804]
I have noticed that trying to change the config for mob hostility that there are 6 options but it only allows options 0-4 to chosen, when i try to use option 5 it doesn't work and when i go back into config it has changed to 4? Option 5 is where hostile mobs only target you when you attack them, it's the only one I haven't been able to try and would like to see what it's like.

Thanks
Vypah

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
