### ISSUE TITLE
Reloading world while morph only renders small area.

### ISSUE THREAD

**Issue by Murdy007** [iChun/Morph#806]
For some reason when I am morphed into something and I close the world and load it up again, it only renders a small area around the player, although the world is perfectly fine. I have not tested this much but just wanted to report it.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
