### ISSUE TITLE
I'm getting this error whenever I try to use Morph

### ISSUE THREAD

**Issue by drinfernoo** [iChun/Morph#810]
This crash happens anytime I try to use Morph, either by ~ or [ ]. I found this stack on OpenEye, but it's very similar to mine (same stack, slightly differing mods, but mostly the same).

http://openeye.openmods.info/crashes/23b3a42c0512bd437e7b554c94964ab4

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
