### ISSUE TITLE
Morph error

### ISSUE THREAD

**Issue by nickpersaud14** [iChun/Morph#812]
Hi,I was excited to try turning into mobs and animals so i got this mod.

i loaded the mod by it self and when i try to go on a single player world i am getting an error like this

"A fatal error has occured, this connection is  terminated

a quick report please HELP!

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
