### ISSUE TITLE
Not acquiring morphs from Custom NPCs

### ISSUE THREAD

**Issue by Tster20XX** [iChun/Morph#814]
I can't absorb morphs from a custom NPCs.
The mod works fine with all other mobs, (Vanilla and Modded) but whenever I kill a CustomNpc, for example a Lamia I created with the mod, I don't absorb the morph.
I cannot force morph through commands either.
Any help would be appreciated.

**Comment by Tamaized** [comment]
#796

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
