### ISSUE TITLE
When I open a world with this mod it crashes.

### ISSUE THREAD

**Issue by tek101** [iChun/Morph#816]
Every time I use this mod it crashed when I open a world. I tried took all my other mods out and it still didn't work :(

**Comment by Tamaized** [comment]
Always show crash logs

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
