### ISSUE TITLE
morph kicks me

### ISSUE THREAD

**Issue by Assassin214365** [iChun/Morph#817]
when I play on 1 of my worlds with the morph mod a take me to a screen saying shutting down iternal servers... please help me

**Comment by Tamaized** [comment]
We can't help without logs. Also there's a few other issues with the same error here...

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
