### ISSUE TITLE
Hostile Ability Mode Issue

### ISSUE THREAD

**Issue by Keraven** [iChun/Morph#820]
When I try to set Hostile Ability Mode to 5, it marks the text as red rather than yellow and reverts to 4 when I open the mod options back up. This is even though in the config file, the max number is set to 5. Any solutions, or fixes anyone has found?

**Comment by iChun** [comment]
An incorrect cap/range on the option made it so Hostile Mode 5 never works,
sadly I won't be fixing this because I'll be favouring the morph rewrite
with a different range of abilities and modes :/ Look forward to that
whenever it gets released instead for the latest modable MC.

**Comment by Keraven** [comment]
Well I'll definitely be looking forward to that, Morph is by far one of my favorite mods. Cheers, and keep up the good work.
