### ISSUE TITLE
Why does this mod always think im on multiplayer even though its singleplayer

### ISSUE THREAD

**Issue by CrymsonCatalyst** [iChun/Morph#821]
Whenever i try to install the morph mod and play on singleplayer, it keep saying stuff like error and then it puts me on the multiplayer tab.

**Comment by iChun** [comment]
There's an error getting you into the world and because of the way the game
works it thinks you're on SMP. I need logs when this happens.

**Comment by CrymsonCatalyst** [comment]
Heres a link to my FML Log:

https://paste.ee/p/ITzWx

**Comment by iChun** [comment]
It's because you're using Mineshafter and not on Mojang's official
authentication servers. When Morph tries to look you (or any other
Mineshafter player) up on the Mojang's servers, it errors out.

**Comment by Tamaized** [comment]
Related and is still open #809

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
