### ISSUE TITLE
Requesting Features

### ISSUE THREAD

**Issue by MrPulchritudinous** [iChun/Morph#822]
Hi there, I am making a new modpack an i was wondering if i could request a few features that will be key to making the modpack, i have the idea set out i just need to tools to construct it.

Email
ethan.w.hull@gmail.com
Twitch 
https://www.twitch.tv/mr_pulchritudinous

**Comment by iChun** [comment]
Put them here, it allows for feedback from others as well.

On Tue, Aug 2, 2016 at 12:55 AM, MrPulchritudinous <notifications@github.com

**Comment by MrPulchritudinous** [comment]
So I though of the entire "one with nature" thing  and i came up with this, you start out with just a book,  a text of some kind giving you some Lore on what you're dong and why. the main goal is to morph into mobs to acquire certain achievements and items and fight certain mobs, but to morph you need certain requirement, Level, have at least killed the mob, and the thing that's not a reality yet, nature points.

Nature points would be acquired by Farming, breeding and killing Unnatural mobs
The points are used to to morph into different  creatures to acquire certain things ie// Squid to breath underwater for an item that's only found in underwater Ruins. And maybe Allow you to plant other crops
Of course tools and all the tech will be very limited so you don't get too over powered and you just negate the entire nature thing.

Another major feature would be magic, Mainly Thaumcraft, Botania and Magical Crops. and the you advance the more Nature points you can acquire 
ie//Every level for Magical crops With Essences  you progress, get an achievement and you are able to morph into more complex mobs (Blaze, Nether Skeletons, ...)

**Comment by MrPulchritudinous** [comment]
@iChun im trying to make a modpack an want to know if its possible

**Comment by MrPulchritudinous** [comment]
Feed Back anyone?

**Comment by iChun** [comment]
Sorry, I've had a look at these now and unfortunately I would have to say that it doesn't really align with the path that I'm hoping to send Morph through.

=========================================

This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
