### ISSUE TITLE
Mobs Still Attack When Morphed

### ISSUE THREAD

**Issue by lodi429** [iChun/Morph#823]
I just started playing and when I morphed into a zombie and went towards some zombies they attacked me, anyone know how to fix?

**Comment by MrPulchritudinous** [comment]
Go into the Config and change it.

**Comment by Tamaized** [comment]
@iChun It might be a good idea to include that this is off by default aswell as the hostile mode issue in #796

**Comment by lodi429** [comment]
Where is config?
I looked at the mod options and it wont let me config.

**Comment by MrPulchritudinous** [comment]
Config folder

**Comment by lodi429** [comment]
Kk

**Comment by Tamaized** [comment]
There's a file in your minecraft directory where you installed the mod (default for windows:  %appdata%/.minecraft/config) Make sure you go into the config folder

**Comment by MrPulchritudinous** [comment]
Are you useing curse?

**Comment by lodi429** [comment]
@Tamaized Im using a technic launcher, so is it the same?

**Comment by Tamaized** [comment]
I don't know where technic installs their stuff, might be something like /.technic you'd have to look around

**Comment by lodi429** [comment]
Kk

**Comment by lodi429** [comment]
The morph mod doesn't have a folder, only a .cfg thing

**Comment by Tamaized** [comment]
Thats the file, you edit that with notepad or something similar

**Comment by MrPulchritudinous** [comment]
Yeah open it as notepad or notpad++ or something simular

**Comment by lodi429** [comment]
kk Imma download it

**Comment by MrPulchritudinous** [comment]
@Tamazied >.>

**Comment by lodi429** [comment]
Also, is there another way to open it without downloading anything?

**Comment by Tamaized** [comment]
Drag it into an open notepad or whatever text editor you use

**Comment by MrPulchritudinous** [comment]
Open with > notepad

**Comment by lodi429** [comment]
Kk

**Comment by lodi429** [comment]
And do I just do save file and it saves into the .cfg thing?

**Comment by Tamaized** [comment]
yes

**Comment by lodi429** [comment]
Ok

**Comment by MrPulchritudinous** [comment]
@tamaized im using my phone lol

**Comment by lodi429** [comment]
Having no hostile mobs attack in caves is like taking mining to the next lvl XD

**Comment by Pierzaa** [comment]
Long long time
