### ISSUE TITLE
Hostile Ability Mode

### ISSUE THREAD

**Issue by Shin-Gojira** [iChun/Morph#826]
for what ever reason no matter what I do Hostile mobs continuously attack me even though I went through the config and set it so they wouldn't attack me can someone please help.

**Comment by Tamaized** [comment]
I'd say either you're trying to use mode 5 which doesn't work, your config isn't being loaded (could be the wrong file idk), or another mod is messing with AI

**Comment by Shin-Gojira** [comment]
I am using the first setting the 'Hostile mobs do not attack you if you are a hostile mob' setting and I don't have any mods that interfere with the AI.

**Comment by Tamaized** [comment]
Just tested myself using Mode 1
Forge 10.13.2.1291
iChunUtil 4.2.2
Morph 0.9.2
No other mods

Working fine, so it's either the config isn't getting loaded or another mod is causing a conflict with AI

**Comment by Shin-Gojira** [comment]
Yeah maybe i'll try to find out

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Comment by Betelgeusesupergiant** [comment]
I mostly say that i have optifine. And it doesn't mess with that mod! It only increases performance. And that means i am taking out my damn other mods

**Comment by Betelgeusesupergiant** [comment]
Now i have crap performance and i don't like it.

**Comment by Betelgeusesupergiant** [comment]
> Just tested myself using Mode 1
> Forge 10.13.2.1291
> iChunUtil 4.2.2
> Morph 0.9.2
> No other mods
> 
> Working fine, so it's either the config isn't getting loaded or another mod is causing a conflict with AI

That didn't fix it either for me
