### ISSUE TITLE
Internal server crashes on map load.

### ISSUE THREAD

**Issue by golyalpha** [iChun/Morph#827]
Title says it all. It happens in the 1.7.10 pack and the DNS Techpack, both downloaded through technic launcher.

[B#347]  [10:26:12] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel Morph
[B#347]  java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
[B#347]     at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService$GameProfileSerializer.deserialize(YggdrasilAuthenticationService.java:116) ~[YggdrasilAuthenticationService$GameProfileSerializer.class:?]
[B#347]     at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService$GameProfileSerializer.deserialize(YggdrasilAuthenticationService.java:1) ~[YggdrasilAuthenticationService$GameProfileSerializer.class:?]
[B#347]     at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
[B#347]     at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[Gson$1.class:?]
[B#347]     at com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse$Serializer.deserialize(ProfileSearchResultsResponse.java:44) ~[ProfileSearchResultsResponse$Serializer.class:?]
[B#347]     at com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse$Serializer.deserialize(ProfileSearchResultsResponse.java:1) ~[ProfileSearchResultsResponse$Serializer.class:?]
[B#347]     at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:717) ~[Gson.class:?]
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:689) ~[Gson.class:?]
[B#347]     at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:75) ~[YggdrasilAuthenticationService.class:?]
[B#347]     at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:53) ~[YggdrasilGameProfileRepository.class:?]
[B#347]     at ichun.common.core.EntityHelperBase.getPartialGameProfileFromName(EntityHelperBase.java:151) ~[EntityHelperBase.class:?]
[B#347]     at ichun.common.core.EntityHelperBase.getFullGameProfileFromName(EntityHelperBase.java:101) ~[EntityHelperBase.class:?]
[B#347]     at morph.common.morph.MorphState.createPlayer(MorphState.java:173) ~[MorphState.class:?]
[B#347]     at morph.common.morph.MorphState.readTag(MorphState.java:123) ~[MorphState.class:?]
[B#347]     at morph.common.packet.PacketMorphStates.handleClient(PacketMorphStates.java:83) ~[PacketMorphStates.class:?]
[B#347]     at morph.common.packet.PacketMorphStates.execute(PacketMorphStates.java:62) ~[PacketMorphStates.class:?]
[B#347]     at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
[B#347]     at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
[B#347]     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
[B#347]     at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#347]     at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#347]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
[B#347]     at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[B#347]     at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#347]     at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#347]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
[B#347]     at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
[B#347]     at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#347]     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#347]     at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[B#347]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
[B#347]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
[B#347]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[B#347]     at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#347]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[B#347]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
[B#347]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
[B#347]     at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
[B#347]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

If I check the technic launcher console, that is what I get. I suspect that full logs are going to be quite big, because of the over 230 mods thing.

**Comment by iChun** [comment]
Can you post the full log anyways? I'd like to take a look at it.
