### ISSUE TITLE
when i open a world it says:a fatal error has occured this connection is terminated

### ISSUE THREAD

**Issue by tfrrft** [iChun/Morph#828]

**Comment by tfrrft** [comment]
plz help

**Comment by Tamaized** [comment]
Post logs, specifically the fml-client-latest.log (or something similar) or we can't help

**Comment by tfrrft** [comment]
what?

**Comment by Tamaized** [comment]
In your Minecraft directory there's a folder called "logs" in there is a fml-client-latest.log file, we need to see the contents of that after this error occurred, if you reboot minecraft then the file will get wiped so get it right as the error happens. Use gist or pastebin, don't copy and paste its contents directly here.

**Comment by tfrrft** [comment]
[22:56:32] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.

**Comment by Tamaized** [comment]
I mean, we need the entire log

**Comment by tfrrft** [comment]
i cant it is says that it is too big and i cant send it

**Comment by Tamaized** [comment]
you've tried both pastebin and gist?

**Comment by tfrrft** [comment]
i just copy the log paste it in pastebin,submit then copy and paste here

**Comment by tfrrft** [comment]
did i need to paste the RAW paste data?

**Comment by Tamaized** [comment]
We need the link to the pastebin

**Comment by tfrrft** [comment]
ooooooo now i see

**Comment by tfrrft** [comment]
http://pastebin.com/SBWNpNZw

**Comment by Tamaized** [comment]
Can you try this with Morph 0.9.2 and iChunUtil 4.2.2, you're using outdated versions.

**Comment by tfrrft** [comment]
just a second...

**Comment by tfrrft** [comment]
it crash

**Comment by Tamaized** [comment]
need the new log

**Comment by tfrrft** [comment]
http://pastebin.com/tWp85Q2A

**Comment by Tamaized** [comment]
Morph doesn't work with Mineshafter, see #821

**Comment by tfrrft** [comment]
ok thenk you a lot

**Comment by tfrrft** [comment]
i finaly fix it thaks you a loooooot

**Comment by tfrrft** [comment]
i am having another problem with a pixelmon crash but you are for morph mod and i cant find enywhere how to submit my issue can you help me?

**Comment by Tamaized** [comment]
1.7.10 is longer supported as iChun is moving onto 1.10.2+
There's a New Issue button if you go back to the issue list of this repo.

But I'll bet you the crash is on pixelmon's end but I would need the log to be sure.

**Comment by tfrrft** [comment]
so i give you the pasterbin log here?

**Comment by tfrrft** [comment]
it is 1.7.10

**Comment by Tamaized** [comment]
There's nothing that'll be fixed on Morph's end and the log will most likely just guarantee that it's on pixelmon's end. You can show it anyway though.

**Comment by tfrrft** [comment]
ok wait a little

**Comment by tfrrft** [comment]
i just want to know what is wrong with pixelmon and it is crashing

**Comment by Tamaized** [comment]
You would have to send the issue over to them. I can't point you to where exactly as I have no idea.

**Comment by tfrrft** [comment]
ok wait

**Comment by tfrrft** [comment]
http://pastebin.com/tCTQTLsn

**Comment by tfrrft** [comment]
hear it is

**Comment by tfrrft** [comment]
here*

**Comment by Tamaized** [comment]
`java.lang.IllegalArgumentException: Could not get provider type for dimension -30, does not exist`
it's neither a Morph issue or Pixelmon (Unless Pixelmon adds a dimension with ID -30) I can't really help you any further

**Comment by tfrrft** [comment]
ok

**Comment by tfrrft** [comment]
can you help me with this?
http://pastebin.com/Kq4GFeFc

**Comment by Tamaized** [comment]
`uristqwerty.CraftGuide.client.fml.CraftGuideClient_FML.checkKeybind(CraftGuideClient_FML.java:37)`

This is not a Morph issue, you don't even have the mod in your instance. Use this tracker for Morph issues.

**Comment by tfrrft** [comment]
sorry
