### ISSUE TITLE
Game seems to crash when i kill certain mobs.

### ISSUE THREAD

**Issue by Nevik9191** [iChun/Morph#829]
Hey! usually i'm pretty good at figuring these errors out but i have had no luck as of yet.  Any help would be greatly appreciated.

My crash report: 

My log file: 

I removed custom recipes mod spam from the .log it has nothing to do with this crash anyway.

Thanks in advance!

**Comment by Tamaized** [comment]
`com.Mod_Ores.EventHandlers.ForgeHookEventHelper.entityAttacked(ForgeHookEventHelper.java:50)`
Nothing to do with Morph

**Comment by Nevik9191** [comment]
oh! Haha. My bad sorry! i saw this and i got confused:  morph.client.entity.EntityMorphAcquisition cannot be cast to net.minecraft.entity.EntityLiving. Thanks anyway! Feel free to close this issue!

**Comment by Tamaized** [comment]
Only either you or iChun can close it.

But yea, the issue is that mod is trying to cast a class from Morph to EntityLiving that isn't possible so a crash occurs.

**Comment by Nevik9191** [comment]
Ok! Thank you again for your quick reply. There are others who don't work so quickly so late.
