### ISSUE TITLE
Cant Morph

### ISSUE THREAD

**Issue by HybridGamer2006** [iChun/Morph#831]
I Got The Newest Version Of Morph Mod 0.93 But When I Tried It I Can't Morph!

**Comment by Tamaized** [comment]
I know this is a very late reply but I figured we should point you here #796 and if you're positive you're doing the correct steps to actually morph (Should really specify how you're trying to Morph) then I would say it's a mod conflict.

It should also be noted that iChun dropped support for 1.7 as stated here #830

**Comment by HampDoesThings** [comment]
Whenever I try to Morph my entire game crashes. Do I need to get rid of the Hats mod?

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
