### ISSUE TITLE
Can't respawn When morphed

### ISSUE THREAD

**Issue by amurity** [iChun/Morph#835]
I have this mod on my server, and whenever I'm morphed and die, I can't respawn. I die isntantly when I click respawn. Once I die as a morphed creature, I have to delete my player info and reset my character. I downloaded the mod via Curse for v 1.7.10.

**Comment by Tamaized** [comment]
Possible it's a weird interaction with another mod. If you could track down which mod together with Morph causes this issue you could report back here and to the other mod's issue tracker. Should be noted though in case this really is on Morph's end that iChun has dropped support for 1.7.10 and there most likely wont be a fix for the issue.

**Comment by iChun** [comment]
Seen your message on IRC, unfortunately what @Tamaized said is true, I've dropped support for now and the mod works fine on it's own so it's potentially a mod conflict. You have to find out what mod is causing it.

**Comment by amurity** [comment]
I found out that the conflicting mod was Danger RPG. I've cantacted the
creator of that mod for further support, than you for your reply.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
