### ISSUE TITLE
steve skin

### ISSUE THREAD

**Issue by JoshDaDirt** [iChun/Morph#837]
I am using the 1.7.10 version of the mod and whenever i switch to another form and back im switched to the default steve skin the glitch is fixed by dying and respawning but is repeated whenever i change and change back its not a huge game breaking glitch but it is annoying my plan to work around it is to download and install (if i can find it for 1.7.10) the custom npcs mod make a custom npc using my own skin and use it as a backup

**Comment by Tamaized** [comment]
Should be noted that CustomNPCs doesn't work with Morph.

**Comment by JoshDaDirt** [comment]
Thank you for telling me that saves about an our of my time
