### ISSUE TITLE
flying problem

### ISSUE THREAD

**Issue by flicka106** [iChun/Morph#841]
Hey, i have been able to fly but the animal i am wont do the flying animation when i morph into it. I really like the flying animation but every time i morph into the animal the animation doesn't work on me.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
