### ISSUE TITLE
Can't fly in morph on lan server

### ISSUE THREAD

**Issue by DeamLupus** [iChun/Morph#842]
I know there's a way to turn it on and off but we haven't touched that(don't know how), do we have to turn it on before it'll work? If so how do we even do that? If not how do we do it anyway and whats the actual problem?

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
