### ISSUE TITLE
Morph Crashes after using the morph menu...

### ISSUE THREAD

**Issue by Alexde23** [iChun/Morph#843]
Hi,i installed a 1.7.10 version of forge.I installed Morph Mod with other 3-5 mods
First time i morphed,it worked perfectly.Second time when i morphed it  crashes.I tried on another world to see if the world is the issue.When i tried to open morph tab still crashes.
Sorry for language romanian in the crash report...I can send another crash report if you don't understand...
---- Minecraft Crash Report ----
// Sorry :(

Time: 4/28/17 8:28 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at morph.common.core.EventHandler.onKeyBindEvent(EventHandler.java:1020)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_EventHandler_onKeyBindEvent_KeyEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at ichun.client.keybind.KeyBind.triggerEvent(KeyBind.java:97)
	at ichun.client.keybind.KeyBind.tick(KeyBind.java:63)
	at ichun.client.core.TickHandlerClient.worldTick(TickHandlerClient.java:95)
	at ichun.client.core.TickHandlerClient.clientTick(TickHandlerClient.java:85)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_9_TickHandlerClient_clientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at morph.common.core.EventHandler.onKeyBindEvent(EventHandler.java:1020)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_EventHandler_onKeyBindEvent_KeyEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at ichun.client.keybind.KeyBind.triggerEvent(KeyBind.java:97)
	at ichun.client.keybind.KeyBind.tick(KeyBind.java:63)
	at ichun.client.core.TickHandlerClient.worldTick(TickHandlerClient.java:95)
	at ichun.client.core.TickHandlerClient.clientTick(TickHandlerClient.java:85)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_9_TickHandlerClient_clientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['minecraft22'/2526, l='MpServer', x=18.61, y=70.62, z=334.22]]
	Chunk stats: MultiplayerChunkCache: 284, 284
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-44,64,256), Chunk: (at 4,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5442 game time, 5442 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: true. Cheats: false
	Forced entities: 82 total; [EntityCreeper['Creeper'/19465, l='MpServer', x=96.50, y=37.00, z=258.50], EntityBat['Liliac'/15889, l='MpServer', x=-21.47, y=37.10, z=283.66], EntityBat['Liliac'/17430, l='MpServer', x=64.07, y=19.09, z=269.64], EntityZombie['Zombie'/19741, l='MpServer', x=87.50, y=17.00, z=277.50], EntitySkeleton['Schelet'/19742, l='MpServer', x=84.50, y=17.00, z=275.50], EntitySkeleton['Schelet'/18975, l='MpServer', x=98.50, y=37.00, z=259.50], EntityZombie['Zombie'/19743, l='MpServer', x=86.50, y=17.00, z=278.50], EntityZombie['Zombie'/19744, l='MpServer', x=89.50, y=17.00, z=278.50], EntityZombie['Zombie'/19745, l='MpServer', x=88.50, y=17.00, z=277.50], EntityCreeper['Creeper'/10791, l='MpServer', x=-37.00, y=16.00, z=300.34], EntityCreeper['Creeper'/10792, l='MpServer', x=-29.50, y=18.00, z=307.50], EntitySpider['P?ianjen'/10793, l='MpServer', x=-31.28, y=15.00, z=300.41], EntitySpider['P?ianjen'/19241, l='MpServer', x=-50.50, y=23.00, z=268.16], EntitySkeleton['Schelet'/18990, l='MpServer', x=44.53, y=18.00, z=283.00], EntityBat['Liliac'/19505, l='MpServer', x=96.75, y=44.00, z=261.75], EntityBat['Liliac'/14901, l='MpServer', x=37.58, y=25.76, z=292.69], EntityZombie['Zombie'/20037, l='MpServer', x=-30.63, y=30.00, z=286.46], EntitySkeleton['Schelet'/20039, l='MpServer', x=-32.50, y=30.00, z=286.50], EntityBat['Liliac'/16972, l='MpServer', x=86.84, y=18.10, z=277.41], EntityCreeper['Creeper'/18766, l='MpServer', x=55.94, y=23.00, z=272.53], EntityCreeper['Creeper'/18767, l='MpServer', x=55.38, y=24.00, z=267.00], EntityChicken['G?in?'/11605, l='MpServer', x=18.34, y=69.00, z=336.59], EntityClientPlayerMP['minecraft22'/2526, l='MpServer', x=18.61, y=70.62, z=334.22], EntitySkeleton['Schelet'/15962, l='MpServer', x=-24.50, y=21.00, z=292.50], EntityPig['Porc'/2405, l='MpServer', x=-38.78, y=70.00, z=381.50], EntityPig['Porc'/2406, l='MpServer', x=-37.19, y=70.00, z=381.50], EntityPig['Porc'/2407, l='MpServer', x=-30.91, y=72.00, z=377.09], EntityPig['Porc'/2408, l='MpServer', x=-35.50, y=71.00, z=376.50], EntityCreeper['Creeper'/19568, l='MpServer', x=94.50, y=18.00, z=267.50], EntityCreeper['Creeper'/19569, l='MpServer', x=94.50, y=18.00, z=266.50], EntityChicken['G?in?'/2421, l='MpServer', x=-5.47, y=70.00, z=343.47], EntityChicken['G?in?'/2422, l='MpServer', x=-18.53, y=72.00, z=333.53], EntityChicken['G?in?'/2431, l='MpServer', x=21.47, y=74.00, z=384.56], EntityChicken['G?in?'/2432, l='MpServer', x=-15.56, y=71.00, z=335.44], EntityChicken['G?in?'/2433, l='MpServer', x=30.56, y=67.00, z=329.56], EntityPig['Porc'/2434, l='MpServer', x=23.91, y=68.00, z=334.28], EntityPig['Porc'/2435, l='MpServer', x=11.97, y=72.00, z=357.06], EntityPig['Porc'/2436, l='MpServer', x=21.84, y=68.00, z=364.97], EntityChicken['G?in?'/2437, l='MpServer', x=20.63, y=69.00, z=335.63], EntityChicken['G?in?'/2438, l='MpServer', x=19.38, y=69.00, z=336.56], EntityChicken['G?in?'/2439, l='MpServer', x=-1.56, y=71.00, z=351.56], EntityPig['Porc'/2440, l='MpServer', x=-3.13, y=71.00, z=352.13], EntitySkeleton['Schelet'/16524, l='MpServer', x=-33.50, y=16.00, z=292.50], EntityChicken['G?in?'/2445, l='MpServer', x=25.50, y=64.00, z=277.50], EntityChicken['G?in?'/2446, l='MpServer', x=27.50, y=64.00, z=276.50], EntityCreeper['Creeper'/18830, l='MpServer', x=99.03, y=43.00, z=268.56], EntityChicken['G?in?'/2447, l='MpServer', x=39.44, y=64.00, z=282.38], EntityChicken['G?in?'/2448, l='MpServer', x=18.81, y=69.00, z=336.63], EntityChicken['G?in?'/2449, l='MpServer', x=17.63, y=69.00, z=332.19], EntityChicken['G?in?'/2451, l='MpServer', x=15.59, y=71.00, z=357.59], EntityItem['item.tile.dirt.default'/7059, l='MpServer', x=24.69, y=64.13, z=316.41], EntityChicken['G?in?'/2452, l='MpServer', x=17.94, y=69.00, z=335.09], EntityCreeper['Creeper'/19092, l='MpServer', x=-54.50, y=20.00, z=282.50], EntityChicken['G?in?'/2453, l='MpServer', x=19.19, y=69.00, z=335.91], EntityChicken['G?in?'/2454, l='MpServer', x=46.56, y=68.00, z=355.44], EntityChicken['G?in?'/2463, l='MpServer', x=35.41, y=64.00, z=269.59], EntityChicken['G?in?'/2464, l='MpServer', x=19.94, y=69.00, z=336.31], EntitySheep['Oaie'/2465, l='MpServer', x=46.56, y=69.00, z=412.88], EntitySheep['Oaie'/2466, l='MpServer', x=43.22, y=70.00, z=417.19], EntitySkeleton['Schelet'/16041, l='MpServer', x=43.34, y=18.00, z=282.34], EntitySkeleton['Schelet'/16042, l='MpServer', x=47.50, y=18.00, z=282.50], EntitySheep['Oaie'/2474, l='MpServer', x=48.84, y=69.00, z=411.50], EntitySheep['Oaie'/2475, l='MpServer', x=48.38, y=69.00, z=415.81], EntitySkeleton['Schelet'/16044, l='MpServer', x=51.50, y=18.00, z=282.50], EntityChicken['G?in?'/2485, l='MpServer', x=73.47, y=64.00, z=319.47], EntityChicken['G?in?'/2486, l='MpServer', x=66.50, y=64.00, z=321.50], EntityChicken['G?in?'/2487, l='MpServer', x=64.50, y=64.00, z=324.50], EntityChicken['G?in?'/2488, l='MpServer', x=64.50, y=64.00, z=326.50], EntityChicken['G?in?'/2489, l='MpServer', x=74.56, y=65.00, z=325.56], EntityChicken['G?in?'/2490, l='MpServer', x=91.56, y=67.00, z=332.63], EntityChicken['G?in?'/2491, l='MpServer', x=85.50, y=66.00, z=333.50], EntityChicken['G?in?'/2492, l='MpServer', x=85.50, y=66.00, z=333.50], EntityZombie['Zombie'/17347, l='MpServer', x=33.50, y=25.00, z=293.50], EntityBat['Liliac'/18895, l='MpServer', x=-26.09, y=52.05, z=271.22], EntityBat['Liliac'/18898, l='MpServer', x=-23.91, y=51.00, z=265.88], EntityZombie['Zombie'/19155, l='MpServer', x=94.50, y=39.00, z=261.50], EntityBat['Liliac'/18900, l='MpServer', x=-25.94, y=52.27, z=269.63], EntityZombie['Zombie'/19426, l='MpServer', x=-21.50, y=24.00, z=298.50], EntitySkeleton['Schelet'/19427, l='MpServer', x=-23.50, y=24.00, z=297.50], EntityTrail['necunoscut'/4838, l='MpServer', x=18.61, y=70.62, z=334.22], EntityChicken['G?in?'/18928, l='MpServer', x=17.81, y=69.00, z=333.63], EntityCreeper['Creeper'/18937, l='MpServer', x=-35.50, y=16.00, z=293.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 138796664 bytes (132 MB) / 389287936 bytes (371 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 103
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) 
	UCHIJAAAAAAAAA	emeraldobsidianmod{1.3.1} [Emerald & Obsidian tools/armor mod] (emeraldobsidianmod-1.7.10-1.3.1.jar) 
	UCHIJAAAAAAAAA	iChunUtil{4.2.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	Morph{0.9.3} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	com.lament.terraria{Beta} [2D Craft : Reborn] (twod_craft-1.7.10-0.2.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4300' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.4.0 - Build 20.19.15.4300, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Român? (România)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by iChun** [comment]
Dang. A legit Morph issue.

I wonder if this carried over to the 1.12.2 version... I hope not.

Anyways.

This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
