### ISSUE TITLE
morph crashes world after morphing

### ISSUE THREAD

**Issue by Uni99** [iChun/Morph#846]
it just crashes my world after I morphed to a creeper
I don't mean whole Minecraft crashed so theres no crash report, it just won't let me play on my world

**Comment by Tamaized** [comment]
Show your fml-client-latest.log file after the issue happens. Don't send it after restarting Minecraft it the file gets wiped. Use pastebin or gist.

**Comment by Uni99** [comment]
tbh I'm only 11

**Comment by Uni99** [comment]
do you mean this thing? https://pastebin.com/7eyj19QM

**Comment by Tamaized** [comment]
Could you try removing optifine? For some reason the log isnt showing everything like it should but I see you've got optifine installed which is known to have issues with Morph.

**Comment by Uni99** [comment]
optifine? the one thing keeping me away from like 17 fps?

**Comment by Uni99** [comment]
its out

**Comment by Tamaized** [comment]
does the issue still occur without optifine?

**Comment by Uni99** [comment]
nope

**Comment by border999** [comment]
Same issue here. But I'm not willing to remove optifine seeing as Ichun has said that he's working on the issue to some degree.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
