### ISSUE TITLE
Morph abilities disappeared?

### ISSUE THREAD

**Issue by Lamsgirl** [iChun/Morph#847]
When I look next to the morphs all the abilities are gone. My bat and blaze cant fly now like before.  Fire resistance and other abilities too, not just flight. I even changed what I could in the config file. I also updated to the newest version. So, I tried everything I am aware of to try to fix it.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
