### ISSUE TITLE
Optifine crashing Morph Mod.

### ISSUE THREAD

**Issue by Sypticle** [iChun/Morph#848]
everytime i kill a new mob or if i morph into the mob it crashes my world and i have 0 idea why but this is a common bug
log file
https://pastebin.com/81PYyaCP

**Comment by Gabrielcoolguy** [comment]
same thing happend to me :C

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Comment by Cristelknight999** [comment]
morph mod and Optifine don't work together

**Comment by SKILGAMING** [comment]
They do work together if you use optifine 1.7.10 version D6

**Comment by withdime** [comment]
> They do work together if you use optifine 1.7.10 version D6

but you cant even use shaders then
