### ISSUE TITLE
My world exits (log out) when i Morphed.

### ISSUE THREAD

**Issue by islender** [iChun/Morph#852]
I morphed into a chicken (this was my first morph so i don't know if it is a problem with all morphs)
Basically, i had normal difficulty and was standing near a zombie spawner. I had Rogelike dungeons and battle towers installed. I doubt any of my other mods have caused the problem as they always worked fine. So when i morphed it said shutting down internal server. Then it said a fatal error has occurred. When i tried to enter the world again, in Peaceful it said the same things. It is really annoying as it was my best world survival DAMN. Please help me. Link to fml-client-latest.log: https://goo.gl/AGKRTS
By the way, I do have optifine but it never caused problems for me.

**Comment by Tamaized** [comment]
This is a conflict between optifine and morph

**Comment by islender** [comment]
Thats wierd because I used to use Optifine with Morph and it worked even with modded morphs.

**Comment by islender** [comment]
WELL at least my world is still alive.
