### ISSUE TITLE
can't skip ad and download

### ISSUE THREAD

**Issue by mr2meows** [iChun/Morph#853]
i spam skip and and restart PC and still doesent work

**Comment by theishiopian** [comment]
Questions about relevancy aside, why did you expect that restarting the PC would help with this?

**Comment by iChun** [comment]
Just get the mod from CurseForge.

This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
