### ISSUE TITLE
AM2 Issue with the Morph mod

### ISSUE THREAD

**Issue by Zer0Cool0** [iChun/Morph#854]
If a player is a 1x1 mob and they touch a ceiling they will start dying. I have searched for the issue and it appears to be AM2's newer versions. However Chun has stated he will not be supporting 1.7.10 anymore, so rip

**Comment by iChun** [comment]
Hahahaha yeah sorry :/

=============

This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
