### ISSUE TITLE
Crazy craft morph mode crashing

### ISSUE THREAD

**Issue by FozexD** [iChun/Morph#855]
as soon as i use any morph like a pig or something it says shutting serve or something while playing single player https://pastebin.com/CdJPViyz

**Comment by Tamaized** [comment]
Morph is known to have issues with Optifine, try again without it.

**Comment by FozexD** [comment]
yeh it worked without it there is no way to ever play morph with optifine ?

**Comment by Tamaized** [comment]
AFAIK that is correct

**Comment by FozexD** [comment]
well thats sad :l

**Comment by FozexD** [comment]
oh just downloaded other version of optifine now its working nice

**Comment by Tamaized** [comment]
Post the version here so others know about it, if it's an older version than latest that is.

**Comment by FozexD** [comment]
the versions of optifine that have shaders is not woking but the ones without it works normally

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
