### ISSUE TITLE
Suddenly unable to fit in 1 block tall spaces

### ISSUE THREAD

**Issue by Shin-Gojira** [iChun/Morph#856]
um I cannot fit in 1 block tall spaces as mobs that are one block tall anymore and I have the morph mod version 0.9.3. and iChunUtil version 4.2.3.

**Comment by Tamaized** [comment]
Usually a mod conflict, see #796

**Comment by Shin-Gojira** [comment]
nothing has changed since I was last able to squeeze into a 1*1 space, i just stopped being able to I didn't add, remove or update any mods.

**Comment by Shin-Gojira** [comment]
when i am a mod that is taller than two blocks i am unable to go through two blocks like i am supposed to, but i am unable to fit in 1 block tall spaces as mobs such as bats, I NEED this to be sorted out because I am a bit of a perfectionist

**Comment by Shin-Gojira** [comment]
Nevermind it turned out it was because of my armor my bad
