### ISSUE TITLE
a Fatal Error has Occured

### ISSUE THREAD

**Issue by darkdrakan199** [iChun/Morph#858]
i am running in 1.7.10 and i created a cauldron server and I played on my server a little bit and then it said a Fatal error has occured I think its Morph

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
