### ISSUE TITLE
Cant use abilities after move to an new Server

### ISSUE THREAD

**Issue by CalvinVail** [iChun/Morph#865]
Hy we moved our server and copy paste all configs to the new one but after that we cant even use abilities for all mobs. Even if we change the config. We tryed to change some other settings (like instant morph) and restart the server. And it worked. We deleted ALL morphes out of our "UI" with backspace and killed the mob again, still no abilities.

How to solve this kinda issue ? any idea ? I deleted also the whole config folder and the mod from the server. restarted it without morph and after that we insatlled it again (same for the client, we started without morph and after that insatlled it new) still no abilities.

Iam confused, pls help

**Comment by CalvinVail** [comment]
MC Server: 1.7.10

**Comment by CalvinVail** [comment]
Befor that anything worked fine

**Comment by kkaracho** [comment]
"co-admin" from that server here
also we have disabled the need for nether or wither kill
like he said, exactly the same config was on another server and it worked perfectly

trying to fix that for about 1 hour now and we are out of ideas

**Comment by CalvinVail** [comment]
solved the Problem, Mod ist compatible with MoCreatures
