### ISSUE TITLE
Bioms o planty not compatible

### ISSUE THREAD

**Issue by akosHUN001** [iChun/Morph#866]
I installed bioms o planty for forge 1.7.10 and it took away all mobs ability,  so watch for it if you play in 1.7.10 and want that mod, i don't say fix it just saying for another gamers who run in the same issue.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
