### ISSUE TITLE
World Closes When I Kill Something

### ISSUE THREAD

**Issue by Apin2017** [iChun/Morph#867]
I always play modded Minecraft and today wasn't anything different. I was playing 1.7.10 forge with a few mods including Morph mod beta 0.9.3 with iChuntUtil 4.2.3. Everything runs fine until I kill something. I get the error "A fatal error has occurred, this connection is terminated" and the world closes. It was the first thing I ever killed (a butterfly) when this happened. It happens with vanilla entities as well. I think it may be another mod interfering with it. Please let me know. Thanks. -Apin

**Comment by Josh74000** [comment]
The mod that interferes with the morph mod has to be optifine.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
