### ISSUE TITLE
Minecraft crashing when I look at a cave spider mob spawner

### ISSUE THREAD

**Issue by Skiter01** [iChun/Morph#869]
Every time that I enter the game and look to the cave spider mob spawner the game show them essage: shutting down internal server and shows fatal error ocurred... Plz help me!

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
