### ISSUE TITLE
Cant play on 1.12

### ISSUE THREAD

**Issue by victorurios** [iChun/Morph#879]
1.12 - 14.21.1.2443 doesnt work

**Comment by iChun** [comment]
Please keep to your own issue you opened earlier, thanks

**Comment by iChun** [comment]
The file for Morph on CurseForge no longer permits 1.12 or 1.12.1.

**Comment by victorurios** [comment]
Sorry ! 1 time on git hub xD , and ok , i`ll update my modpack so  :) thanks
