### ISSUE TITLE
Abilities not working for MC version 1.12.2

### ISSUE THREAD

**Issue by TimelessLore** [iChun/Morph#883]
Chicken Morph won't slowly fall, Squid Morph won't breathe underwater, Zombie won't burn in sunlight and is attacked by hostiles, Bat morph won't fly. Everything else seems to work smoothly.

Installed the newly updated mods: from iChun Util, Forge, and Morph
Checked in game and the config file (didn't touch it) if they are true
No other mods besides the necessary ones.
Reinstalled them.
I am unsure of what's going on or if I am missing something.

**Comment by iChun** [comment]
Sorry, should have made an issue about this because I knew people'd be wondering. 

https://github.com/iChun/Morph/issues/884
