### ISSUE TITLE
Crash through Null Pointer Exception 

### ISSUE THREAD

**Issue by FridgeBoy** [iChun/Morph#886]
Just standing around causes this
we have no clue what else might be happening other than your mod ticking
https://pastebin.com/0Kt34tHE
this happened using version 7.0.1, in the All the Mods 3 Pack

**Comment by kulflame** [comment]
Same with everyone on my ATM3 v.5 server.

https://pastebin.com/9EjDpHL5

**Comment by iChun** [comment]
It's crashing when someone was morphing. I'll toss out a fix in 7.0.2 which should be out by the weekend.

**Comment by PapiDimmi** [comment]
Same issue here. I could morph just fine yesterday.

Crash log: https://pastebin.com/raw/VX5S0sd8

What happened: I was playing multiplayer, and another player morphed into a mob. Then I crashed.

**Minecraft version**: 1.12.2
**Morph version**: 7.0.1

**Comment by iChun** [comment]
I mean, I did comment saying I'll be throwing out a fix by the weekend.

**Comment by PapiDimmi** [comment]
I just wanted to share my crash log too. ¯\_(ツ)_/¯

**Comment by PapiDimmi** [comment]
I just wanted to share my crash log too. ¯\\\_(ツ)_/¯

**Comment by PapiDimmi** [comment]
I just wanted to share my experience too. ¯\\\_(ツ)_/¯
