### ISSUE TITLE
Jumping into a block as a chicken damages you

### ISSUE THREAD

**Issue by PapiDimmi** [iChun/Morph#888]
If you’re in a one-block-high space as a chicken, and you jump, you slightly jump through the block and get damaged by it, for some reason.

I haven’t updated to 7.1.0 yet, so I’m not sure if this has been fixed, but the changelog doesn’t mention anything about block damage.

**Minecraft version**: 1.12.2
**Morph version**: 7.0.1
**iChunUtil version**: 7.0.3

**Comment by iChun** [comment]
Yeah don't do that.

**Comment by PapiDimmi** [comment]
OK. But what if I want to? I like being a chicken.

**Comment by PapiDimmi** [comment]
OK, but what if I want to? I like being a chicken.

**Comment by iChun** [comment]
I don't think anything can be done with this really. The game unfortunately thinks you're in the block above you when you're that small, from the way they check to see if you're in a block. Some other mobs have no problem.

**Comment by PapiDimmi** [comment]
From what I’ve experienced, only the chicken has this problem. Poor chicken.
