### ISSUE TITLE
Some mobs don’t fit through doors

### ISSUE THREAD

**Issue by PapiDimmi** [iChun/Morph#890]
When I’m morphed as a cow, sheep, pig, or another small mob, I don’t fit through any doors.

****

**Minecraft version**: 1.12.2
**Morph version**: 7.1.0
**iChunUtil version**: 7.1.2

**Comment by iChun** [comment]
That's cause you're too fat. Not an issue.

**Comment by PapiDimmi** [comment]
:(

**Comment by iChun** [comment]
Wait hang on, which small mob are you talking about. You can't fit through doors for any mob that's larger than 0.8125 of a block.

**Comment by iChun** [comment]
(Cow Sheep and Pig are 0.9)
