### ISSUE TITLE
Rabbits never stand still

### ISSUE THREAD

**Issue by PapiDimmi** [iChun/Morph#891]
When you’re morphed as a rabbit, your legs constantly move, even whilst standing still, to other players in multiplayer.

****

**Minecraft version**: 1.12.2
**Morph version**: 7.1.0
**iChunUtil version**: 7.1.2

**Comment by iChun** [comment]
I had it the other way around. Rabbit legs never moved. I tried fixing this for the next update. Let me know if it's still a problem.
