### ISSUE TITLE
Crashes with Primitive Mobs

### ISSUE THREAD

**Issue by PapiDimmi** [iChun/Morph#895]
I killed a haunted tool mob from the [Primitive Mobs](https://minecraft.curseforge.com/projects/primitive-mobs) mod, and I instantly crashed.

Crash log: https://pastebin.com/raw/xmKvjpm3

From what I can tell, there’s a compatibility issue with the Morph mod. It might be because of the morph acquired effect upon killing a mob.

I reported this to @Vazkii, and he told me that it looks like this is an issue with Morph, not Primitive Mobs.
Daveyx0/PrimitiveMobs/issues/1

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**Primitive Mobs version**: 1.1beta
**iChunUtil version**: 7.1.2
**Morph version**: 7.1.0

**Comment by iChun** [comment]
Self note: getEntityTexture is @Nullable. Bear that in mind.

**Comment by PapiDimmi** [comment]
I also crashed upon trying to morph into a treasure slime from Primitive Mobs.

Crash log: https://pastebin.com/raw/803XRN2p

I’m not sure if this issue is related.

**Comment by iChun** [comment]
This is a different crash.

**Comment by ashly138** [comment]
allso had this and with the firefly from twilight forest mods here the log https://gist.github.com/ashly138/f80af5d68ff51980ef226c5f020d29f0

**Comment by iChun** [comment]
@ashly138 that's a separate crash, same with #889. Make a new issue if you're not sure if the crashes are the same. I won't be able to fix this anytime soon though.

**Comment by ashly138** [comment]
Made a new post. And gues till its fix i will just not go into twilight forest or restart every time haha

**Comment by iChun** [comment]
Fixed for next update.

**Comment by PapiDimmi** [comment]
Thanks!
