### ISSUE TITLE
Crash with Twilight Forest ( Posted As Own Issue Post :P )

### ISSUE THREAD

**Issue by ashly138** [iChun/Morph#897]
allso had this and with the firefly from twilight forest mods here the log https://gist.github.com/ashly138/f80af5d68ff51980ef226c5f020d29f0

**Comment by iChun** [comment]
Same as #889

**Comment by ashly138** [comment]
i want to block firefly in the blacklist of morph but dont know the name thing to block the firefly

**Comment by iChun** [comment]
Fixed for next update.
