### ISSUE TITLE
Disable 'Morph' Graphics on Kill

### ISSUE THREAD

**Issue by Avnior** [iChun/Morph#898]
So I have the automatic morphing turned off. But I was wondering if there was a way to turn off the graphics that happen when you kill a new mob.

It makes since if you automatically morph into it, but since I have it disabled, I don't really like it.

**Comment by iChun** [comment]
That animation is to indicate that you have a new Morph, not to indicate
that you're immediate morphing into it.

**Comment by iChun** [comment]
Config will be in the next update.
