### ISSUE TITLE
Problem with primitive mobs.

### ISSUE THREAD

**Issue by 63502** [iChun/Morph#902]
In the primitive mobs mod, there is a critter called the filch lizard. It steals valuable items from players and runs away with them. A small problem occurs when morphed into them. When valuable items are picked up by a player morphed into a filch lizard, a small amount of them prioritize the lizard's inventory instead of the player's, making them appear to vanish when picked up. it also appears that filch lizard morphed players inventories will randomly loose existing valuables every now and again. I remember from a previous issue I opened about hostile morphs attacking the player that AI/behavior is supposed to be disabled when mobs are morphs. Is it possible to stop a filch lizard(or any) morph from messing with dropped items and/or the players inventory?

**Comment by iChun** [comment]
Should be fixed in the next update.

**Comment by 63502** [comment]
Ok, cool. I'll keep an eye out for anymore weirdness as I get further into my survival world.
