### ISSUE TITLE
Crash with IntegratedTunnels

### ISSUE THREAD

**Issue by SirFlip** [iChun/Morph#907]
You crash when you or a mob gets killed by a Player Simulator from IntegratedTunnels.

#### Short description: 
Crash when killed by Player Simulator
Also happens when mobs are killed

#### Expected behaviour: 
Player/mob dies no crash

#### Actual behaviour: 
Game crashes

#### Steps to reproduce the problem:

1. Get killed by Player Simulator

____
#### Versions:
- Morph: 1.12.2-7.1.1
- iChunUtil: 7.1.3
- Minecraft: 1.12.2
- Forge: 14.23.1.2555
- IntegratedTunnels: 1.3.5
- CyclopsCore: 0.10.23

https://gist.github.com/SirFlip/8ad0e572ebb81f24d1b7c31305962b08

Because I don't know where the bug is I also post it on IntegratedTunnels Issue Tracker and link it here.
CyclopsMC/IntegratedTunnels#92

**Comment by iChun** [comment]
It's morph's end but I'm out of the country right now. I'll only be able to
work on this in January.

**Comment by iChun** [comment]
Fixed for the next update whenever it's out.
