### ISSUE TITLE
Infinite spawning MeeCreep Cubes with Morph mod interaction

### ISSUE THREAD

**Issue by SystemCollapse** [iChun/Morph#908]
Little hard to explain so I can just show you my video.

https://youtu.be/XzF1xugEGTw?t=51s

McJty said he could not do anything on his end so figured I would throw this here.

-Systemcollapse

**Comment by iChun** [comment]
Heh that looks like fun. Use the latest version of Morph (7.1.1). This should already be fixed on that version via this commit https://github.com/iChun/Morph/commit/265db9d7c050cfdfc376efde3dd17a6857d2b9b1

Also @McJty https://github.com/iChun/Morph/blob/1.12.2/src/main/resources/assets/morph/mod/nbt_modifiers.json
