### ISSUE TITLE
MorphMod Crash (Fatal internal server error)

### ISSUE THREAD

**Issue by VadimeFR** [iChun/Morph#910]
Hi I have a problem for a long time and I know it's due to a conflict between morph and another mod but I can not find it in the logs ... :(
When I play, I kill a mob and here I crash directly
Can you help me pls and im not english sry ^^
I play in 1.7.10 with a modpack

Logs:   http://pasted.co/0c65d4cf

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
