### ISSUE TITLE
Crash when unlocking advancements or crafting recipes

### ISSUE THREAD

**Issue by Natetheman7740** [iChun/Morph#913]
Hi, I noticed that whenever I unlock an advancement or crafting recipe, the game crashes, but luckily I found a workaround by giving myself all advancements. Here are the crash reports, and I only had Morph and IchunUtil. It doesn't happen in vanilla minecraft. Do you know what's going on?
[crash-2017-11-14_15.49.01-server.txt](https://github.com/iChun/Morph/files/1580457/crash-2017-11-14_15.49.01-server.txt)
[crash-2017-11-14_15.42.18-server.txt](https://github.com/iChun/Morph/files/1580458/crash-2017-11-14_15.42.18-server.txt)
[crash-2017-11-14_15.45.48-server.txt](https://github.com/iChun/Morph/files/1580459/crash-2017-11-14_15.45.48-server.txt)

**Comment by MissPotato** [comment]
This appears to be caused by RecipeBooks, why are you reporting it here?
