### ISSUE TITLE
Legacy repo missing code

### ISSUE THREAD

**Issue by KIPdeKIP** [iChun/Morph#915]
Hi, I cloned the repo to build a copy that doesn't crash with the latest version of OptiFine.

I've got everything working and building successfully but it looks like the Morph-Beta-0.9.3 changes were never published in this repo.

The `master` branch appears to be version 0.9.1 with updated mob lists and the `legacy1710` branch appears to be version 0.9.2.

Any chance the missing code could be added to this repo?

I realize it's technically no longer supported but I feel there is a difference in "Help me thing broke" and git history missing.

**Comment by iChun** [comment]
Uhhhhhhhh I don't think I even have the code for that anymore. It might be
lost in one of the hard drives backups I have.

The changelog for it was:
Morph – 0.9.3
– Fix hostileMode capping at 4, making option 5 unselectable
– Add /morph morph [player name] <entity name> command

Nothing too major. Hopefully that's alright? The important bits in previous
updates were to redirect the URL for the abilities and that's been done.

**Comment by KIPdeKIP** [comment]
While the changes are nothing essential they're still nice things to have. Even just to have the git history match the release versions.

If you don't mind me decompiling the mod I'll go and figure out how reasonable it even is to decompile Minecraft mods. Comparing 0.9.2 and 0.9.3 *should* get me the changes which can then be applied to the current code.

If you ever bump into the code again please do add it to the repo.

With that said. I'll leave it up to you if you want to leave this issue open or not.

**Comment by iChun** [comment]
Should be fine. All you gotta do is poke through the config class (or maybe
the morph class) and the command class and that should be it.
