### ISSUE TITLE
[1.12.2] Morph doesn't work in LAN games

### ISSUE THREAD

**Issue by Snuggle** [iChun/Morph#918]
After using morph in a LAN game with my little brother, I've noticed it really doesn't work at all.

Skeletons turned upside down and inside out, morphing seemed to affect both of us in a way that caused both player models to glitch out into some scary mess and after about ten or so times of morphing, the game just crashed.

`crash-2017-12-26_11.06.47-server.txt` - https://pastebin.com/GQk3Br0Y

**Comment by iChun** [comment]
The mod works fine on LAN as far as I have tested but it has been known
that the mod is not compatible with Optifine, which you have installed.

**Comment by Snuggle** [comment]
Hmm... Good point. I wouldn't have thought that Optifine would cause my morph to affect another player's morph, though. I'll try to reproduce without Optifine. :heart:
