### ISSUE TITLE
Crash when hitting mobs with ExUtils2 mechanical user

### ISSUE THREAD

**Issue by dartzmaster** [iChun/Morph#921]
I'm playing version 1.4.0 of the Direwolf20 1.12 pack and had this crash: https://gist.github.com/anonymous/5c2cf3cc77d8ee6968e305be4862fa61 someone on the DW20 told me it might be a problem between ExUtils2 and Morph so i wanted to post this here.

**Comment by iChun** [comment]
Update morph.
