### ISSUE TITLE
[Suggestion] Have health proportionally scale down and up while morphing

### ISSUE THREAD

**Issue by WeaselOnaStick** [iChun/Morph#922]
And make this feature configurable if you can.

**Comment by iChun** [comment]
Scale how?

**Comment by SHIuSH** [comment]
for example:
you had 5/5 hearts(100%), you morph back to Player and you get 10/10 hearts(same 100%).
you had 2/5 hearts(40%), you morph back to Player to only get 4/10 hearts(same 40%)
and so on...

**Comment by iChun** [comment]
That's what I thought you meant. The last time I did that I accidentally
gave the player insane regeneration when they're morphing. I'll see how I
can do this next time round.

**Comment by SHIuSH** [comment]
I mean you don't have to do regen. just set players health to Max_HP*percentage

**Comment by iChun** [comment]
I know, that's what I did. I meant a side effect/bug of the way I did it
back then made players just really hard to kill when morphing

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.

If it helps any, I think I handled this properly in the 1.16.5 version, so health is scaled proportionately on that version! Couple years late of a response, but ehhhh what can you do
