### ISSUE TITLE
Gameover screen while morphing, left me in a alive\dead state

### ISSUE THREAD

**Issue by Dutchs** [iChun/Morph#923]
Somehow died while morphing even with more then 0 health
Got a gameover screen but clicking respawn just closed the gameover screen and i was still at the same location.
Character preview in inventory showed me skewed as if i was dead but i was able to eat and regen health.
Version: 1.12.2-7.1.2
Steps to reproduce:
morph into silverfish and duck.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
