### ISSUE TITLE
Problem with playing crazy craft A fetal error has occured, this connection is terminated.

### ISSUE THREAD

**Issue by iicNDx** [iChun/Morph#927]
A problem in crazy craft. when I kill any monster it gives me a problem says: A fetal error has occured, this connection is terminated.
I need help. I think the problem is from morph because it gives me the same problem when I try to trasform and that's the log:

**Comment by iChun** [comment]
... Log?

**Comment by iChun** [comment]
Isn't crazy craft like, MC 1.7.10?
