### ISSUE TITLE
Disable Kill Animation?

### ISSUE THREAD

**Issue by JasonBourne007** [iChun/Morph#929]
Hello. I am using the Replay Mod, as well as Morph Mod in 1.12.2. Everything works fine until I kill something in game, and then replay mod crashes when watching the recording due to an issue it has with Morph Mod's kill/morph animation. Is there ANY way that I can disable the Morph/New Kill animation for Morph Mod? It only causes an issue when I kill a new mob.
Any help with this would be great. I will include the crash report below.
Thank you.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.4.jar)
  LoadingPlugin (replaymod-1.12.2-2.0.1-b1.jar)
  FCFMLCorePlugin (FinderCompass-1.12.1.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 1/18/18 7:24 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at me.ichun.mods.morph.client.core.EventHandlerClient.onClientTick(EventHandlerClient.java:827)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_392_EventHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:347)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1909)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.ichun.mods.morph.client.core.EventHandlerClient.onClientTick(EventHandlerClient.java:827)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_392_EventHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:347)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [CameraEntity['Player'/-1789435, l='MpServer', x=-576.21, y=87.97, z=1738.69], EntityOtherPlayerMP['ZWOGs'/179026, l='MpServer', x=-578.97, y=83.00, z=1730.94]]
	Chunk stats: MultiplayerChunkCache: 841, 841
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options:
	Level spawn location: World: (-962,64,933), Chunk: (at 14,4,5 in -61,58; contains blocks -976,0,928 to -961,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 355355 game time, 363466 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 136 total; [CameraEntity['Player'/-1789435, l='MpServer', x=-576.21, y=87.97, z=1738.69], EntitySkeleton['Skeleton'/187138, l='MpServer', x=-529.50, y=20.00, z=1757.50], EntityLatchedRenderer['unknown'/1, l='MpServer', x=-576.21, y=87.97, z=1738.69], EntityZombie['Zombie'/188160, l='MpServer', x=-499.50, y=27.00, z=1708.50], EntityLatchedRenderer['unknown'/3, l='MpServer', x=-578.93, y=83.00, z=1731.01], EntitySkeleton['Skeleton'/187142, l='MpServer', x=-526.71, y=21.00, z=1761.50], EntityChicken['Chicken'/179460, l='MpServer', x=-570.03, y=65.00, z=1695.49], EntitySkeleton['Skeleton'/187140, l='MpServer', x=-529.50, y=20.00, z=1759.50], EntityCreeper['Creeper'/186120, l='MpServer', x=-550.50, y=41.00, z=1731.50], EntitySkeleton['Skeleton'/185865, l='MpServer', x=-616.50, y=24.00, z=1736.50], EntityChicken['Chicken'/179215, l='MpServer', x=-653.43, y=66.00, z=1677.81], EntityChicken['Chicken'/187405, l='MpServer', x=-582.34, y=83.00, z=1731.89], EntitySheep['Sheep'/179219, l='MpServer', x=-522.20, y=74.00, z=1805.38], EntityBat['Bat'/186902, l='MpServer', x=-629.50, y=23.37, z=1730.12], EntitySkeleton['Skeleton'/187160, l='MpServer', x=-507.50, y=32.00, z=1704.50], EntityChicken['Chicken'/179234, l='MpServer', x=-624.81, y=69.00, z=1691.42], EntityBat['Bat'/186914, l='MpServer', x=-524.48, y=37.63, z=1786.17], EntityZombie['Zombie'/187427, l='MpServer', x=-516.50, y=32.00, z=1664.50], EntitySkeleton['Skeleton'/184353, l='MpServer', x=-545.50, y=48.00, z=1740.50], EntityZombie['Zombie'/187430, l='MpServer', x=-513.81, y=31.00, z=1664.39], EntityZombie['Zombie'/187428, l='MpServer', x=-514.56, y=31.00, z=1670.21], EntitySkeleton['Skeleton'/181289, l='MpServer', x=-533.50, y=31.00, z=1717.50], EntityItem['item.item.rottenFlesh'/181551, l='MpServer', x=-586.32, y=74.00, z=1750.18], EntityCreeper['Creeper'/185135, l='MpServer', x=-529.51, y=20.00, z=1756.22], EntityBat['Bat'/186671, l='MpServer', x=-621.78, y=31.42, z=1749.07], EntityZombie['Zombie'/185655, l='MpServer', x=-652.50, y=16.00, z=1740.50], EntityCreeper['Creeper'/185909, l='MpServer', x=-531.50, y=41.00, z=1775.50], EntityBat['Bat'/186427, l='MpServer', x=-634.90, y=18.35, z=1727.46], EntitySkeleton['Skeleton'/185657, l='MpServer', x=-527.50, y=48.00, z=1755.50], EntityChicken['Chicken'/179263, l='MpServer', x=-542.43, y=67.00, z=1730.87], EntityCreeper['Creeper'/185663, l='MpServer', x=-573.50, y=42.00, z=1665.50], EntityZombie['Zombie'/186434, l='MpServer', x=-522.50, y=17.00, z=1714.50], EntityItem['item.item.arrow'/181315, l='MpServer', x=-542.29, y=68.00, z=1737.88], EntityCow['Cow'/179264, l='MpServer', x=-535.78, y=67.00, z=1737.86], EntityCow['Cow'/179520, l='MpServer', x=-556.22, y=65.00, z=1704.46], EntityCreeper['Creeper'/187200, l='MpServer', x=-614.50, y=37.00, z=1771.50], EntityItem['item.item.bone'/181316, l='MpServer', x=-542.42, y=68.00, z=1737.82], EntityVillager['Villager'/179018, l='MpServer', x=-514.30, y=66.00, z=1755.70], EntityVillager['Villager'/179019, l='MpServer', x=-515.10, y=66.00, z=1755.19], EntitySkeleton['Skeleton'/188232, l='MpServer', x=-527.89, y=35.00, z=1785.48], EntityVillager['Villager'/179022, l='MpServer', x=-507.48, y=64.00, z=1759.92], EntityVillager['Villager'/179023, l='MpServer', x=-506.20, y=64.00, z=1753.56], EntityVillager['Villager'/179020, l='MpServer', x=-507.30, y=65.00, z=1767.30], EntityVillager['Villager'/179021, l='MpServer', x=-503.50, y=64.00, z=1753.64], EntityOtherPlayerMP['ZWOGs'/179026, l='MpServer', x=-578.97, y=83.00, z=1730.94], EntityZombie['Zombie'/185682, l='MpServer', x=-525.51, y=17.00, z=1707.94], EntityVillager['Villager'/179024, l='MpServer', x=-506.85, y=64.00, z=1753.17], EntityBat['Bat'/184145, l='MpServer', x=-618.49, y=35.97, z=1750.75], EntityCreeper['Creeper'/187217, l='MpServer', x=-647.50, y=17.00, z=1734.50], EntityBat['Bat'/187473, l='MpServer', x=-621.24, y=39.81, z=1755.84], EntityBat['Bat'/185430, l='MpServer', x=-627.27, y=16.02, z=1745.93], EntityZombie['Zombie'/188244, l='MpServer', x=-529.50, y=20.00, z=1755.50], EntityZombie['Zombie'/188250, l='MpServer', x=-617.50, y=35.00, z=1762.50], EntitySkeleton['Skeleton'/182616, l='MpServer', x=-528.51, y=20.00, z=1752.29], EntityChicken['Chicken'/187484, l='MpServer', x=-581.62, y=83.00, z=1731.98], EntityCreeper['Creeper'/187996, l='MpServer', x=-624.50, y=31.00, z=1750.50], EntityMorphAcquisition['unknown'/612, l='MpServer', x=-579.87, y=83.00, z=1729.46], EntityCreeper['Creeper'/186983, l='MpServer', x=-527.50, y=35.00, z=1753.50], EntityItem['item.item.egg'/188263, l='MpServer', x=-580.78, y=83.00, z=1730.05], EntityChicken['Chicken'/187492, l='MpServer', x=-582.52, y=83.00, z=1729.66], EntitySkeleton['Skeleton'/185961, l='MpServer', x=-648.50, y=25.00, z=1741.50], EntityCreeper['Creeper'/187511, l='MpServer', x=-656.50, y=43.00, z=1730.50], EntityChicken['Chicken'/179060, l='MpServer', x=-505.13, y=66.00, z=1781.88], EntityBat['Bat'/187765, l='MpServer', x=-618.25, y=31.00, z=1754.75], EntityChicken['Chicken'/185979, l='MpServer', x=-631.50, y=64.00, z=1749.50], EntityCreeper['Creeper'/186491, l='MpServer', x=-529.50, y=57.00, z=1750.50], EntitySquid['Squid'/187515, l='MpServer', x=-536.80, y=60.30, z=1680.79], EntityWitch['Witch'/186495, l='MpServer', x=-536.50, y=57.00, z=1740.50], EntityCreeper['Creeper'/185980, l='MpServer', x=-630.50, y=64.00, z=1748.50], EntityBat['Bat'/188034, l='MpServer', x=-527.83, y=21.99, z=1755.77], EntityItem['item.item.egg'/179334, l='MpServer', x=-580.65, y=65.00, z=1684.74], EntityItem['item.item.bone'/181382, l='MpServer', x=-620.88, y=65.00, z=1760.24], EntityCow['Cow'/179335, l='MpServer', x=-575.50, y=71.00, z=1704.20], EntityChicken['Chicken'/179333, l='MpServer', x=-580.89, y=65.00, z=1684.39], EntityItem['item.item.arrow'/181381, l='MpServer', x=-620.22, y=65.00, z=1758.88], EntityChicken['Chicken'/179338, l='MpServer', x=-582.20, y=83.00, z=1733.42], EntityChicken['Chicken'/179594, l='MpServer', x=-512.16, y=65.00, z=1711.49], EntityChicken['Chicken'/179339, l='MpServer', x=-581.96, y=83.00, z=1730.90], EntityChicken['Chicken'/179595, l='MpServer', x=-511.81, y=67.00, z=1725.51], EntityChicken['Chicken'/179336, l='MpServer', x=-581.47, y=83.00, z=1731.33], EntityZombie['Zombie'/184969, l='MpServer', x=-514.50, y=31.00, z=1666.50], EntitySkeleton['Skeleton'/187017, l='MpServer', x=-633.29, y=22.00, z=1733.50], EntityChicken['Chicken'/179340, l='MpServer', x=-582.38, y=83.00, z=1728.16], EntityChicken['Chicken'/179341, l='MpServer', x=-582.49, y=83.00, z=1727.45], EntityBat['Bat'/188306, l='MpServer', x=-521.62, y=31.48, z=1714.53], EntityItem['item.item.arrow'/181399, l='MpServer', x=-553.62, y=70.00, z=1726.94], EntityEnderman['Enderman'/187802, l='MpServer', x=-523.50, y=17.00, z=1712.50], EntityItem['item.item.bone'/181400, l='MpServer', x=-555.39, y=70.00, z=1726.82], EntityEnderman['Enderman'/187801, l='MpServer', x=-521.50, y=17.00, z=1712.50], EntityChicken['Chicken'/179616, l='MpServer', x=-499.88, y=67.00, z=1650.74], EntityItem['item.item.tconstruct.edible.slimeball_blue'/187304, l='MpServer', x=-578.35, y=68.00, z=1786.78], EntityZombie['Zombie'/188328, l='MpServer', x=-622.50, y=20.00, z=1755.50], EntityZombie['Zombie'/188329, l='MpServer', x=-622.50, y=20.00, z=1753.50], EntitySquid['Squid'/187566, l='MpServer', x=-515.60, y=62.59, z=1689.80], EntitySkeleton['Skeleton'/188078, l='MpServer', x=-536.50, y=20.00, z=1757.50], EntityZombie['Zombie'/185519, l='MpServer', x=-621.50, y=26.00, z=1741.50], EntitySquid['Squid'/187567, l='MpServer', x=-520.95, y=59.79, z=1686.83], EntityItem['item.item.feather'/188332, l='MpServer', x=-579.93, y=83.16, z=1729.41], EntityItem['item.item.chickenRaw'/188333, l='MpServer', x=-579.90, y=83.16, z=1729.36], EntitySquid['Squid'/187570, l='MpServer', x=-536.08, y=62.49, z=1668.59], EntityBat['Bat'/187315, l='MpServer', x=-524.68, y=13.17, z=1732.82], EntitySquid['Squid'/187571, l='MpServer', x=-537.68, y=60.92, z=1668.18], EntitySkeleton['Skeleton'/183729, l='MpServer', x=-625.49, y=66.00, z=1737.71], EntitySquid['Squid'/187569, l='MpServer', x=-515.91, y=62.54, z=1700.73], EntityBat['Bat'/184502, l='MpServer', x=-605.08, y=68.28, z=1794.08], EntitySheep['Sheep'/179383, l='MpServer', x=-504.81, y=69.00, z=1797.49], EntitySquid['Squid'/187572, l='MpServer', x=-529.16, y=61.17, z=1670.34], EntitySpider['Spider'/186805, l='MpServer', x=-619.46, y=37.00, z=1754.70], EntityCreeper['Creeper'/186554, l='MpServer', x=-626.50, y=32.00, z=1760.50], EntityCreeper['Creeper'/185019, l='MpServer', x=-632.50, y=19.19, z=1758.10], EntityEnderman['Enderman'/186808, l='MpServer', x=-621.53, y=38.00, z=1754.64], EntityBat['Bat'/187071, l='MpServer', x=-618.52, y=32.10, z=1759.75], EntityCreeper['Creeper'/182722, l='MpServer', x=-531.50, y=19.00, z=1756.50], EntityItem['item.item.egg'/185030, l='MpServer', x=-531.85, y=66.00, z=1791.13], EntitySkeleton['Skeleton'/186315, l='MpServer', x=-522.50, y=35.00, z=1777.50], EntityChicken['Chicken'/179150, l='MpServer', x=-531.18, y=65.00, z=1769.72], EntityCreeper['Creeper'/181198, l='MpServer', x=-546.50, y=20.00, z=1729.50], EntityChicken['Chicken'/179151, l='MpServer', x=-532.09, y=66.00, z=1791.73], EntityZombie['Zombie'/186061, l='MpServer', x=-620.77, y=26.00, z=1745.49], EntitySkeleton['Skeleton'/187090, l='MpServer', x=-512.50, y=32.00, z=1665.50], EntityChicken['Chicken'/179152, l='MpServer', x=-526.33, y=67.00, z=1785.00], EntityBat['Bat'/187856, l='MpServer', x=-524.44, y=26.96, z=1784.01], EntityItem['item.item.egg'/187355, l='MpServer', x=-584.69, y=68.00, z=1790.21], EntitySkeleton['Skeleton'/187352, l='MpServer', x=-520.50, y=33.00, z=1653.50], EntityCreeper['Creeper'/183261, l='MpServer', x=-524.50, y=17.00, z=1704.50], EntityChicken['Chicken'/179433, l='MpServer', x=-585.23, y=68.00, z=1790.52], EntityChicken['Chicken'/179439, l='MpServer', x=-583.48, y=69.00, z=1794.84], EntitySkeleton['Skeleton'/187119, l='MpServer', x=-628.21, y=64.00, z=1747.49], EntitySkeleton['Skeleton'/184557, l='MpServer', x=-632.50, y=29.00, z=1760.50], EntityChicken['Chicken'/179440, l='MpServer', x=-580.40, y=69.00, z=1794.17], EntitySkeleton['Skeleton'/187120, l='MpServer', x=-625.50, y=66.00, z=1740.50], EntityChicken['Chicken'/179194, l='MpServer', x=-596.67, y=68.00, z=1785.86], EntityBat['Bat'/185592, l='MpServer', x=-643.39, y=40.10, z=1729.72], EntityCreeper['Creeper'/180217, l='MpServer', x=-564.16, y=74.00, z=1718.73], EntitySkeleton['Skeleton'/184313, l='MpServer', x=-537.49, y=57.00, z=1738.69], EntityCreeper['Creeper'/187389, l='MpServer', x=-602.50, y=26.00, z=1740.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:527)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2133302696 bytes (2034 MB) / 4211081216 bytes (4016 MB) up to 4211081216 bytes (4016 MB)
	JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -Xmn800m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.1.2582 Optifine OptiFine_1.12.2_HD_U_C5 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version         | Source                                        | Signature                                |
	|:------ |:----------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft               | 1.12.2          | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                     | 9.42            | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                     | 8.0.99.99       | forge-1.12.2-14.23.1.2582.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                   | 14.23.1.2582    | forge-1.12.2-14.23.1.2582.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | openmodscore            | 0.11.4          | minecraft.jar                                 | None                                     |
	| UCHIJA | mercurius_updater       | 1.0             | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJA | replaymod-compat        | 1.12.2-2.0.1-b1 | replaymod-1.12.2-2.0.1-b1.jar                 | None                                     |
	| UCHIJA | replaymod-replay        | 1.12.2-2.0.1-b1 | replaymod-1.12.2-2.0.1-b1.jar                 | None                                     |
	| UCHIJA | replaymod               | 1.12.2-2.0.1-b1 | replaymod-1.12.2-2.0.1-b1.jar                 | None                                     |
	| UCHIJA | replaymod-render        | 1.12.2-2.0.1-b1 | replaymod-1.12.2-2.0.1-b1.jar                 | None                                     |
	| UCHIJA | replaymod-editor        | 1.12.2-2.0.1-b1 | replaymod-1.12.2-2.0.1-b1.jar                 | None                                     |
	| UCHIJA | replaymod-extras        | 1.12.2-2.0.1-b1 | replaymod-1.12.2-2.0.1-b1.jar                 | None                                     |
	| UCHIJA | replaymod-online        | 1.12.2-2.0.1-b1 | replaymod-1.12.2-2.0.1-b1.jar                 | None                                     |
	| UCHIJA | replaymod-recording     | 1.12.2-2.0.1-b1 | replaymod-1.12.2-2.0.1-b1.jar                 | None                                     |
	| UCHIJA | replaymod-simplepathing | 1.12.2-2.0.1-b1 | replaymod-1.12.2-2.0.1-b1.jar                 | None                                     |
	| UCHIJA | appliedenergistics2     | rv5-alpha-8     | Applied-Energistics-2-Mod-1.12.2.jar          | None                                     |
	| UCHIJA | bibliocraft             | 2.4.3           | BiblioCraft-Mod-1.12.jar                      | None                                     |
	| UCHIJA | biomesoplenty           | 7.0.1.2297      | BiomesOPlenty-1.12.2-7.0.1.2297-universal.jar | None                                     |
	| UCHIJA | buildcraftlib           | 7.99.12         | BuildCraft-Mod-1.12.2(1).jar                  | None                                     |
	| UCHIJA | buildcraftcore          | 7.99.12         | BuildCraft-Mod-1.12.2(1).jar                  | None                                     |
	| UCHIJA | buildcraftbuilders      | 7.99.12         | BuildCraft-Mod-1.12.2(1).jar                  | None                                     |
	| UCHIJA | buildcraftenergy        | 7.99.12         | BuildCraft-Mod-1.12.2(1).jar                  | None                                     |
	| UCHIJA | buildcraftfactory       | 7.99.12         | BuildCraft-Mod-1.12.2(1).jar                  | None                                     |
	| UCHIJA | buildcraftrobotics      | 7.99.12         | BuildCraft-Mod-1.12.2(1).jar                  | None                                     |
	| UCHIJA | buildcraftsilicon       | 7.99.12         | BuildCraft-Mod-1.12.2(1).jar                  | None                                     |
	| UCHIJA | buildcrafttransport     | 7.99.12         | BuildCraft-Mod-1.12.2(1).jar                  | None                                     |
	| UCHIJA | codechickenlib          | 3.1.5.331       | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | chickenchunks           | 2.4.0.70        | ChickenChunks-1.12-2.4.0.70-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | redstoneflux            | 2.0.1           | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJA | cofhcore                | 4.3.9           | CoFHCore-1.12.2-4.3.9.2-universal.jar         | None                                     |
	| UCHIJA | cofhworld               | 1.1.1           | CoFHWorld-1.12.2-1.1.1.12-universal.jar       | None                                     |
	| UCHIJA | enderstorage            | 2.4.0.122       | EnderStorage-1.12-2.4.0.122-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | jei                     | 4.8.0.114       | Just-Enough-Items-Mod-1.12.2.jar              | None                                     |
	| UCHIJA | mantle                  | 1.12-1.3.1.18   | Mantle-1.12-1.3.1.18.jar                      | None                                     |
	| UCHIJA | tconstruct              | 1.12-2.7.4.34   | TConstruct-1.12-2.7.4.34.jar                  | None                                     |
	| UCHIJA | extrautils2             | 1.0             | Extra-Utils-1.12.jar                          | None                                     |
	| UCHIJA | findercompass           | 1.12            | FinderCompass-1.12.1.jar                      | None                                     |
	| UCHIJA | waila                   | 1.8.20          | Hwyla-Mod-1.12.1.jar                          | None                                     |
	| UCHIJA | ichunutil               | 7.1.0           | iChunUtil-1.12.2-7.1.0.jar                    | None                                     |
	| UCHIJA | ic2                     | 2.8.37-ex112    | industrialcraft-2-2.8.37-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJA | moreoverlays            | 1.12            | More-Oerlays-1.12.jar                         | None                                     |
	| UCHIJA | morph                   | 7.1.0           | Morphing-Mod-1.12.2.jar                       | None                                     |
	| UCHIJA | nei                     | 2.4.1           | Not-Enough-Items-1.12.2-Recommended.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | openmods                | 0.11.4          | OpenModsLib-1.12.2-0.11.4.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJA | openblocks              | 1.7.4           | OpenBlocks-1.12.2-1.7.4.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJA | portalgun               | 7.0.0           | Portal-Gun-Mod-1.12.2(1).jar                  | None                                     |
	| UCHIJA | redstonearsenal         | 2.3.8           | RedstoneArsenal-1.12.2-2.3.8.21-universal.jar | None                                     |
	| UCHIJA | subcommonlib            | 1.2.0.1         | subcommonlib-sublib-1.12-1.2.0.1.jar          | None                                     |
	| UCHIJA | telepads                | 1.11.2-1.0.2.1  | TelePads-Mod-1.12.2.jar                       | None                                     |
	| UCHIJA | thermalfoundation       | 2.3.8           | Thermal-Foundation-Mod-1.12.2.jar             | None                                     |
	| UCHIJA | bspkrscore              | at_0.9          | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UCHIJA | treecapitator           | at_0.9          | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UCHIJA | twilightforest          | 3.0.0           | Twilight-Forest-Mod-1.12.2.jar                | None                                     |
	| UCHIJA | wailaharvestability     | 1.1.11          | WailaHarvestability-1.12.jar                  | None                                     |
	| UCHIJA | xaerominimap            | 1.14.5          | Xaeros_Minimap_1.14.5_Forge_1.12_OLD.jar      | None                                     |

	Loaded coremods (and transformers):
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.4.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (replaymod-1.12.2-2.0.1-b1.jar)

FCFMLCorePlugin (FinderCompass-1.12.1.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.65' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: alpha rv5-alpha-8 for Forge 14.23.0.2491
	Pulsar/tconstruct loaded Pulses:
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2582
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: revival.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C5
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Continuum-§91.3-§f§2Low§f-§4Ultra§f.zip
	OpenGlVersion: 4.6.0 NVIDIA 390.65
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by iChun** [comment]
I think I added a config for this in 7.1.1. Do correct me if I'm wrong.
