### ISSUE TITLE
Can't break blocks when morphed

### ISSUE THREAD

**Issue by RoyalCube** [iChun/Morph#932]
I am not able to break blocks when morphed, placing blocks is fine, it's just breaking them that doesn't work. I'm playing on a server and my friend doesn't have this problem so it shouldn't be server sided

**Comment by iChun** [comment]
I would need your Minecraft IGN/UUID if I want to try and replicate this I reckon, since it seems specific to users rather than reproducible.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
