### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Staudi14** [iChun/Morph#934]
I'm a playing the Direwolf20 1.12.2 Version 1.7.1 and while I was playing the game suddenly crashed. After disabling your mods the game started again.
[2018-02-04-6.log](https://github.com/iChun/Morph/files/1693261/2018-02-04-6.log)
I hope i have interpreted the log right and didn't bother you without unnecesery.

Kind regards Staud14 😄

**Comment by Staud14** [comment]
I disabled IChun Morph and Portal Gun

**Comment by iChun** [comment]
Looks like your keybinds were a little borked btw. Might want to try deleting the iChunUtil-keybinds.cfg to reset them and see if it sorts things out.
