### ISSUE TITLE
Morphs Pushing Me North-West

### ISSUE THREAD

**Issue by ZombieSlayermod** [iChun/Morph#936]
When ever I morph into any morph, It pushes me North-West at varying speeds depending what morph I am. Could a guy get some help with this one??? Please...

**Comment by Chick3nBomber** [comment]
This happens to me too. No idea why

**Comment by ash39503** [comment]
Same for me, but i drift south-east

**Comment by iChun** [comment]
What version of Morph?

**Comment by ZombieSlayermod** [comment]
1.7.10, unless you want the file version

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
