### ISSUE TITLE
Whitelist / Blacklist config does not work in latest version

### ISSUE THREAD

**Issue by Colorfold** [iChun/Morph#938]
I simply tried everything, I just want the player to only be able to morph into a Skeleton.

Am I missing something, am I doing something wrong?

Here are my configs:

gameplay {
    # A blacklist or whitelist of mobs disallowed/allowed to be acquired.
    S:blackwhiteListedMobs <
        net.minecraft.entity.monster.EntitySkeleton
     >

    # A blacklist or whitelist of players disallowed/allowed to be morph.
    S:blackwhiteListedPlayers <
     >

    # Can you acquire boss morphs?This is disabled by default due to morphing issues with mobs like the EnderDragon, Twilight Forest's Hydra and Naga, etc.
    I:bossMorphs=0

    # Can you sleep while morphed?
    I:canSleepMorphed=0

    # Can you acquire child mob morphs?
    # Disabled by default due to improper morph transitions
    I:childMorphs=0

    # Enable Classic Mode for Morph?
    # Classic Mode aka Morph 0.9.2 style morph.
    I:classicMode=0

    # Redirect the mod to a different JSON patch location rather then the default patch hosted on GitHub.
    # If you would like to use the default, leave this blank.
    # This also affects nbt_modifiers.json.
    # If the link to your file is "https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/ability_support.json", put "https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/", you cannot change the file name (eg: ability_support.json) part of the link.
    S:customPatchLink=

    # Will you insta-morph into a new morph acquired?
    I:instaMorph=0

    # Is the list a blacklist or whitelist? (Yes = Blacklist, No = Whitelist)
    I:listIsBlacklistMobs=1

    # Is the list a blacklist or whitelist? (Yes = Blacklist, No = Whitelist)
    I:listIsBlacklistPlayers=1

    # Will you lose your morphs on death?
    # 0 = No
    # 1 = Yes, all morphs
    # 2 = Yes, the morph you're currently using
    I:loseMorphsOnDeath=0

    # Maximum health when in Morph.
    I:maxMorphHealth=20

    # Can morphing affect your health?
    I:morphHealthBalancing=1

    # Time to complete a morph (in ticks)
    I:morphTime=80

    # Can you acquire player morphs?
    I:playerMorphs=1

    # Show the player label of a morphed player?
    I:showPlayerLabel=0

    # Force the mod to use the local copy of resources in the config folder?
    # This is meant for debugging purposes and for modified local mod mob abilities mappings/NBT stripper.
    # Do take note that mappings server and clientside are not synched so both ends will require the same mappings.
    I:useLocalResources=1

**Comment by iChun** [comment]
It's not possible to make the player only morph into a skeleton via the configs.
