### ISSUE TITLE
crashing when i kill a mob or use morph

### ISSUE THREAD

**Issue by Nekomancer120** [iChun/Morph#940]
nvm this is 1.7.10 close it but here's the issue

![screen shot 2018-03-04 at 19 33 50](https://user-images.githubusercontent.com/25490349/36956498-9179c6d2-1fe3-11e8-9db4-e84df0fea2cc.png)

**Comment by Nekomancer120** [comment]
i didnt see the post about 1.7.10 sorry

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
