### ISSUE TITLE
Potential fix for 1.7.10 crashing/kicking issues

### ISSUE THREAD

**Issue by ArtelGG** [iChun/Morph#941]
I did some extensive testing, due to me getting kicked from the game every time I would kill a mob I decided to go through my mods one-by-one until it stopped happening, and I ended up finding the cause.

If you are experiencing crashing/kicking issues with your 1.7.10 modpack, try downgrading your OptiFine version to anything [Ultra D6](https://optifine.net/adloadx?f=OptiFine_1.7.10_HD_U_D6.jar) and under.

@iChun If this helps people please mark it as important, or make a Wiki. As this might solve peoples issues and you won't have tickets opened anymore regarding this version.

**Comment by xJon** [comment]
Thanks :)

**Comment by T-Grave** [comment]
This fixworks but do note you won't be able to run any shaders on 1.7.10 with that OptiFine version (it was introduced the version after that). And the original GLSL Shaders Mod that was used back then has a lot of issues with the shaderpacks that are available today.

**Comment by DruidDobby** [comment]
> I did some extensive testing, due to me getting kicked from the game every time I would kill a mob I decided to go through my mods one-by-one until it stopped happening, and I ended up finding the cause.
> 
> If you are experiencing crashing/kicking issues with your 1.7.10 modpack, try downgrading your OptiFine version to anything [Ultra D6](https://optifine.net/adloadx?f=OptiFine_1.7.10_HD_U_D6.jar) and under.
> 
> @iChun If this helps people please mark it as important, or make a Wiki. As this might solve peoples issues and you won't have tickets opened anymore regarding this version.

OMFG TYSM. This is exactly what I was looking for!!

**Comment by ISAK-SWE05** [comment]
Thanks a lot that fixed it
