### ISSUE TITLE
"A fatal error occured, this connection is terminated" when killing mob

### ISSUE THREAD

**Issue by HungieSpoon** [iChun/Morph#943]
The message is seen when i kill a mob, i suppose its because of morph because its does it when i kill a new mob.
Here is the log: http://pasted.co/ddb97e87

**Comment by iYT242** [comment]
me too

**Comment by Chick3nBomber** [comment]
This happens when you use OptiFine. Delete OptiFine and your be good to go

**Comment by ArtelGG** [comment]
See #941

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
