### ISSUE TITLE
Killing A Mod And I Crash

### ISSUE THREAD

**Issue by iYT242** [iChun/Morph#946]
Hello I Have This Problem.

Whenever i kill any mob i crash and i don't know why please help me and it just says:

Shutting down internal server... 

Please Help

**Comment by Chick3nBomber** [comment]
As a lot of these other issues say... **DELETE OPTIFINE!**

**Comment by Raoul1808** [comment]
Me too but if I delete Optifine, Minecraft lags to death :/

**Comment by iYT242** [comment]
yeah but look first do this delete Optifine and Run Minecraft with morph
mod and once that quit install once again Optifine and have fun :D

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878

**Comment by SKILGAMING** [comment]
Use optifine version D6 for 1.7.10 it worked for me
