### ISSUE TITLE
No keys work

### ISSUE THREAD

**Issue by Zakke** [iChun/Morph#949]
I have eu keyboard and i don't have the little thing i need to press to switch between mobs and i want to know if there's anyway to change the controls

**Comment by iChun** [comment]
Bit late on this, but have you tried hitting the last few keys near the enter key? the keys where [ and ] would be on a QWERTY keyboard.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
