### ISSUE TITLE
Direwolf20 1.12: Crash trying to load Nether -> Overworld

### ISSUE THREAD

**Issue by Dekutanoth** [iChun/Morph#952]
I've been playing Direwolf20 with my girlfriend for a couple weeks now. I had been making several trips to and from the nether with no issue. On one of the trips back, Minecraft hangs for a good minute, and then crashes with the following error:

https://pastebin.com/rQdg2KXw

I have made several trips since, so I don't know what caused the crash, but I wanted to post it here in case the author/developer(s) saw something important.

**Comment by Dekutanoth** [comment]
Addendum: before the crash, the other player listed, Coffeefox, reported that she could not see me at all, I was invisible no matter what I tried. After I loaded back in from the crash, she was able to see me.

**Comment by iChun** [comment]
If this one was a one off, I'd like to just close the issue for the time being.
