### ISSUE TITLE
Morph Mod - Bat moves by itself

### ISSUE THREAD

**Issue by DreamExtinct** [iChun/Morph#954]
When I morph into any flying mob, it always moves by itself. Here are the mods i have, im not sure if one of these mods is causing the issue.
https://user-images.githubusercontent.com/39245952/39970940-7f84246c-56c1-11e8-8986-ade7425f3b13.PNG

**Comment by nosknut** [comment]
I am having this issue too! Running 1.12.2-7.1.2

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
