### ISSUE TITLE
Sheep sheep sheep

### ISSUE THREAD

**Issue by generrosity** [iChun/Morph#955]
Love your mods iChun!

Watching and helping test FoolCraft3, noticing that killing identical freshly spawned 1.12 sheep gives unique morphs. I shudder to think the overhead it is causing.

The sheep have a cooldown to drop dye (part of another mod) - its possible that this NBT data is being detected as a unique property?  I suspect "Dye it yourself" might be doing that too?

**Comment by iChun** [comment]
It's probably the NBT data that other mods are adding like you said, and Morph for 1.12 already has a system to manage that. Just gotta find out what NBT tag it is and add it to the nbt modifiers for Morph via a pull request.

The file for it is here: https://github.com/iChun/Morph/blob/1.12.2/src/main/resources/assets/morph/mod/nbt_modifiers.json

**Comment by Poke1650** [comment]
Is there any way I could fix this on my end?

**Comment by generrosity** [comment]
Ah! If you are the author of DyeItYourself, you could easily confirm what NBT tags you use? We suspect you have one for timing, but any others that would differentiate two sheep spawned within seconds of eachother?

**Comment by generrosity** [comment]
From the linked page - "You can also add compatibility for your own mod via the IMC system. Look in the Morph main class for documentation."

**Comment by generrosity** [comment]
Drop a note here if you find it - I'm starting to look at the code (scary) and put my hand in where I can

**Comment by Poke1650** [comment]
Fixed in latest build, will upload to curse now!

**Comment by Poke1650** [comment]
Alright should be fixed now! Uploaded on [CurseForge](https://minecraft.curseforge.com/projects/dye-it-yourself/files/2567788)
