### ISSUE TITLE
kick me from the word when i kill a mob

### ISSUE THREAD

**Issue by MohammadHDPro** [iChun/Morph#959]
when i kill any mob in morph mod kick me from the word and say (a fatal error has occured, this connection is terminated)

Minecraft: 1.7.10
Morph: 0.9.3
iChunUtil: 4.2.3

**Comment by CaptainGame17** [comment]
same 😕

**Comment by YaibaToKen** [comment]
If possible, post your log files, using a service like pastebin, gist or hastebin, so that iChun can see what exactly went wrong and hopefully fix it :)

**Comment by ArtelGG** [comment]
See #941

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
