### ISSUE TITLE
Mob Abilities

### ISSUE THREAD

**Issue by Preminenc3** [iChun/Morph#965]
Will you be adding back abilities to the mobs you transform into, I really need that for my pack.

- Thanks and You are the best mod dev keep up the great work.

**Comment by SinZ163** [comment]
Based on the last commit, abilities are coming back (and he kept the ability stuff in config for future proofing), next version released will have them and a good amount of vanilla mobs have their abilities back already

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/884
