### ISSUE TITLE
crashing wehn i morph

### ISSUE THREAD

**Issue by ZEROX7** [iChun/Morph#966]
hey i am crashing wehn i am mohrping in or load a map wehre i am morphed
[latest.log](https://github.com/iChun/Morph/files/2151974/latest.log)

**Comment by generrosity** [comment]
Error: me.ichun.mods.morph.client.render.RenderPlayerHand.func_177138_b(RenderPlayerHand.java:103)



Do you recall what you would have had in your hand?

**Comment by ZEROX7** [comment]
It was empty

generrosity <notifications@github.com> schrieb am Mo., 9. Juli 2018, 12:13:

**Comment by iChun** [comment]
Should be fixed in Morph 7.1.3 (when released)
