### ISSUE TITLE
Compilation issue: Your access transformers be broke

### ISSUE THREAD

**Issue by loper12** [iChun/Morph#968]
AT.cfg files from [IChunUtil](https://github.com/iChun/iChunUtil/tree/master/src/main/resources/META-INF)
I can't even compile iChunUtil!

**Comment by iChun** [comment]
What branch are you using on what version of Minecraft?

**Comment by loper12** [comment]
i am using the 1.12.2 branch

**Comment by iChun** [comment]
Are you using the access transformers from iChunUtil? Morph itself doesn't
have any ATs since it depends on iChunUtil.

**Comment by loper12** [comment]
Yes

**Comment by loper12** [comment]
update: I tried it again, and i got the error, bad class file for the line
`NetworkPlayerInfo info = new NetworkPlayerInfo(((EntityOtherPlayerMP)ent).getGameProfile());
` right on the N of new.

**Comment by iChun** [comment]
Are you sure you're using the right Access Transformers from iChunUtil?
That class should have been set to public.

**Comment by loper12** [comment]
Yes. Do I have to rename the Access transformers? Because currently they are named iChunUtil-at.cfg and iChunUtil-deobf_at.cfg

**Comment by iChun** [comment]
Don't use the deobf ones.

**Comment by loper12** [comment]
oh ok.

**Comment by loper12** [comment]
It's still not working

**Comment by iChun** [comment]
I'll look into it when I can. You can try and manually make that class
public in the meantime. I'm wondering if there's a commit I didn't push or
something missing somewhere.

**Comment by loper12** [comment]
Thank you! I hope this issue is resolved! Is there any public ci servers
that I can visit to get the mod in the mean time?

**Comment by loper12** [comment]
or do you have a precompiled jar so I can test it?

**Comment by iChun** [comment]
A precompiled jar? There's nothing really new with this vs the public
version.
