### ISSUE TITLE
Suggestion - NBT Size Check / Warning 

### ISSUE THREAD

**Issue by generrosity** [iChun/Morph#970]
Hello!

With NBT Bloat being a thing, could I suggest that you give active feedback?

Would any combination of this be possible?
- when a player logs in/ each time they morph/ each time their NBT data is saved
- all OPS are notified via whisper/ server warning is logged/ player is warned/ server config of 'maxMorphs: X' and drops adding new morphs after a certain point with user feedback.

If possible, I personally would prefer when a player logs in for an op whisper and server log to be mode to say "Heya - player with large Morph NBT data - might cause issues - help out the community on ( this link to the attribute list )" and "heya player, oops youve hit your server limit, see (link to faq if you have too much identical waffle)"

Side note -  I've also logged a note with FTBUtilities where NBTEdit crashes the client when payload is more than 32k. I'll be working through https://pastebin.com/ZvWQ9W5f to see if I can help NetherEx, Chickens, etc. No idea if you have a "/morph purge player" either.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.

If it helps any: Morph's data is saved to the world folder now, and your morph info is sent on login. No more player save bloating!

I also just strip everything except tags that affect entity appearance, too. Later versions of Morph (when default mode is available) will require players to unlock higher morph capacities.
