### ISSUE TITLE
Wierd Visual bug

### ISSUE THREAD

**Issue by Gogasb156** [iChun/Morph#973]
https://gyazo.com/7d7cc400ce5f5ca525ddd82806505119
Only happens when morphed and in third person

**Comment by iChun** [comment]
Bit late on this one but do you know if there was anything spitting out in the console when this was happening?

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
