### ISSUE TITLE
Can't Fly

### ISSUE THREAD

**Issue by spongeblast** [iChun/Morph#975]
Hi I have a private server that i run with my friends and it is a really small modpack with just tinkers, thermal and morph mod for some reason I can't fly with a morph that can even after going to the nether. Can anyone help with this?

**Comment by loper12** [comment]
Abilities haven't been implemented in the 1.12.2 versions

**Comment by spongeblast** [comment]
Ok, thank you very much, is there an estimate

**Comment by iChun** [comment]
No. When it's done.
