### ISSUE TITLE
Custom Models "Too Big"?

### ISSUE THREAD

**Issue by Danthy** [iChun/Morph#976]
I'm having an issue where I created a custom model, I say custom but it's the exact ocelot model, and the camera barely goes down when I morph into it and I am unable to go through 1 high openings like the ocelot can. I've tested it on even smaller models and it has the same problem. Is it an issue with the model and if so how may it be fixed?

**Comment by iChun** [comment]
This is an issue with your code. Your entity's bounding box and eye heights aren't set properly.
