### ISSUE TITLE
"A fatal error as ocurred" in Modded Network 2.4 (Technic)

### ISSUE THREAD

**Issue by loutei02** [iChun/Morph#978]
So i created a server in modded network today and i dont know why sometimes i get forced out of the server and the message is "A fatal error as ocurred, this connection is terminated". Please help!

**Comment by AmDoctor** [comment]
What MC version.
If 1.7.10 then any optifine version D7 and up will not work with morph. However D6 and below should.
In short, if shaders is integrated with optifine it will not work.

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
