### ISSUE TITLE
Crash after killing mob (morph mentioned as cause)

### ISSUE THREAD

**Issue by Lazarix** [iChun/Morph#983]
https://paste.dimdev.org/ejusewazov.mccrash

using FoolCraft 3 pack, Morph 1.12.2-7.1.2

**Comment by Lazarix** [comment]
no good, crashed again.

**Comment by EvilCh33z** [comment]
So I just came here to add to this issue. I have had it happen a few times. Causes a client crash and then everything is fine after relogging (including then posessing said morph). Heres a few crash logs.
https://paste.dimdev.org/odomawipey.mccrash
https://paste.dimdev.org/ayoxavipah.rb
https://paste.dimdev.org/quhepoduye.mccrash
It looks like iChun doesn’t check if a value is null?
Im not an expert just thought I'd try to help.
Thanks for an awesome, fun mod!

**Comment by iChun** [comment]
I have a mild suspicion what might be causing this, please try v 7.1.3 when it is released and get back to me on if this issue is resolved, thanks! Marking as closed for now.
