### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by SkiperSk** [iChun/Morph#990]
When i kill a mob it will die like normaly it would.But when i try to change into it my world will crash. Not minecraft just world. It will disconnect me from the world a when i try reconnect i cant becouse i transformd into a mob im using MorphBeta 0.9.2 and ichuntil 4.2.2 i also tried it on Ichuntil 4.2.3 and it still wont work. I sended a video too
[Minecraft 1.7.10 23.11.2018 17_36_20.zip](https://github.com/iChun/Morph/files/2611317/Minecraft.1.7.10.23.11.2018.17_36_20.zip)

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
