### ISSUE TITLE
NullPointerException on 1.12.2

### ISSUE THREAD

**Issue by GGG-KILLER** [iChun/Morph#991]
Hello, I've encountered a `NullPointerException` crash while playing with Morph 7.1.2.
Unfortunately as I did not have the tab focused at the time of the initial crash I'm unable to provide with reproduction steps, and every time I tried to load the world the crash occurred in, it crashed a few seconds after the player spawning.
The crash log: https://pastebin.com/8pgHHR66

**Comment by iChun** [comment]
Is anyone morphed as a GenericNPC mob? That's what's causing the crash.
Avoid using them as morph's for now until I can investigate further.

**Comment by GGG-KILLER** [comment]
I was morphed as Techgun's Cyberdemon as I cycled through all available morphs iirc

**Comment by GGG-KILLER** [comment]
Ok, this seems to be a problem on Techguns 2's side: https://github.com/pWn3d1337/Techguns2/pull/76
