### ISSUE TITLE
1 Block tall mobs drifting

### ISSUE THREAD

**Issue by ash39503** [iChun/Morph#993]
For some reason, anytime i morph into anything that us not player sized, like a bat or chicken etc, they drift south east non-stop and will get pulled through blocks and cause me to suffocate. Is this fixable or?

**Comment by iChun** [comment]
What version of the mod?

**Comment by ash39503** [comment]
Never mind! I believe at the time though it was 1.7. Sorry!

**Comment by reubenr11** [comment]
what did you do to fix this?

**Comment by AntoanBG** [comment]
same issue

**Comment by AntoanBG** [comment]
how to fix

**Comment by Red-S2** [comment]
same issue

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.

**Comment by iChun** [comment]
Also if anyone's coming across this, This is usually due to a mod conflict, two mods are trying to set the player's size at the same time, every tick
