### ISSUE TITLE
Client Crash on Server

### ISSUE THREAD

**Issue by 77wisher77** [iChun/Morph#995]
I'm frequently receiving this crash when i press the `[` key on a server (the morph key to search through morphs)
The crash usually occurs when im moving as well as pressing the button but also happens sometimes when standing still

This has happened multiple times with the same crash report
[crash-2019-01-04_19.57.55-client.txt](https://github.com/iChun/Morph/files/2726562/crash-2019-01-04_19.57.55-client.txt)

Im playing on `Onion Sage Adventures` `Version`:`B-0.6.0`
Links:
[CurseForge](https://minecraft.curseforge.com/projects/onion-sage-adventures/files/2653428)
[GitLab](https://gitlab.com/Wisher/onion-sage-adventures/tree/Beta_0.6.0)

**Comment by iChun** [comment]
This should be fixed on the next update. 7.1.3.
