### ISSUE TITLE
I CAN'T STOP

### ISSUE THREAD

**Issue by Lukaz-835** [iChun/Morph#999]
Is Morph compatible with Custom NPCs in 1.12? Beacuse when I transform into a custom NPC and start to move... I JUST CAN'T STOP

I mean... I actually can stop, but only by hitting a wall :P
 
It's something that I need to set in the NPC or it's just incompatibility?

Edit: I just tested, and it only happen with Pixelmons. Other Custom NPCs don't cause this glitch

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
